### ISSUE TITLE
Item 25962 not animated

### ISSUE THREAD

**Issue by jerryb1988** [malucooo/Otxserver-New#101]
blade of carving - 25962 - doesn't have equipped animation

Also, properties are wrong/missing on most of the (overcharged) weapons.

**Comment by jerryb1988** [comment]
It's also missing 

<attribute key="decayTo" value="25919" />

**Comment by jlcvp** [comment]
a new item.otb is needed in order to animate the sword. Also a lot of items need to be fixed.

**Comment by jerryb1988** [comment]
I fixed a bunch of the newer items with my last 2 PR, but I don't have an items.otb editor. All the ones i try to download are broken.
