### ISSUE TITLE
Bug criação de novos items

### ISSUE THREAD

**Issue by Zebutops** [malucooo/otxserver-new#106]
Ao utilizar os comandos /i Rod of Destruction; /i wand of destruction ocorre o debug window (o client fecha) e não é mais possivel logar na conta.

**Comment by favasconcelos** [comment]
Qual cliente/versão você está usando?

**Comment by Zebutops** [comment]
O cliente 10.0 e o 11.49.5884

**Comment by Zebutops** [comment]
@favasconcelos com o cliente 11.44.5516 também ocorre o mesmo problema, os itens novos são criados mas não aparecem a sprite dele.
![gnome itens](https://user-images.githubusercontent.com/46094882/50646664-c865ca00-0f5d-11e9-9608-83a680b4cb23.png)

**Comment by favasconcelos** [comment]
Esse problema está relacionado com o #89 onde as sprites estão inconsistentes entre o cliente e o servidor. Enquanto isso existir um padrão entre os dois não creio que há uma solução definitiva.
