### ISSUE TITLE
Trap door vengoth castle

### ISSUE THREAD

**Issue by newacc12** [malucooo/Otxserver-New#107]
The highlighted SQM is supposed to have a trap door under the carpet.

![image](https://cloud.githubusercontent.com/assets/20234557/25882395/d858f436-3508-11e7-90b7-e04eb05a9f94.png)

Reference: http://tibia.wikia.com/wiki/Blood_Brothers_Quest/Spoiler (Mission 06: A Black History).

You can also see how it works here: https://www.youtube.com/watch?v=DKb2wKOQ_XU (2:25)

Basically when you use the southern part of the carpet it shows the trap door. Then you open the trap door and go down and then it resets to the initial state.

Right now when you walk over you just go down no matter what.

**Comment by malucooo** [comment]
send me the coordenates... plz!

**Comment by Rockerszzz** [comment]
![trap](https://user-images.githubusercontent.com/25540139/29532260-9cbed23a-8682-11e7-9f6a-66c435881591.png)

There are.
