### ISSUE TITLE
Question: Docker images

### ISSUE THREAD

**Issue by lucascebertin** [malucooo/otxserver-new#108]
What you guys think about to include a docker image here (even a docker-compose.yml on other repo or something like that)?

I'm just saying that because I really love docker, almost all softwares on my machine are dockerized. Not only because the isolation level, makes simple to build and ship the otserv.

I already have a dockerfile for the server, just need to finish the compose to getting all the stuff up together (already working on this for me).

**Comment by favasconcelos** [comment]
Indeed it's a great idea! For running this repo in my environment I do also use Docker containers, you can find the start of the development process in my fork: https://github.com/favasconcelos/otxserver-new/tree/feature/docker

**Comment by lucascebertin** [comment]
Thank God...
I will look on it soon, probably will *steal* some stuff there. :)

Thanks again!

**Comment by lucascebertin** [comment]
Just another question... 
Will you add gesior frontend in your compose yml?

**Comment by favasconcelos** [comment]
Actually, no.
IMO we should stick to the project settings, and if we want to support other "integrated systems" we may add a comment on a wiki page or even in the README, because not everyone want to use gesior (myself included).
