### ISSUE TITLE
Client crash when enter on depot

### ISSUE THREAD

**Issue by lucascebertin** [malucooo/otxserver-new#109]
Can someone help me?

Versions: 
otx - master version
client - Tibia 11.44.5516 - pointing to 127.0.0.1 (link found in the readme.md here)
 
This is the only thing that I got from minidump: 0xE06D7363
When I get close to depot from thais, the client just crashes and close.

Did I screw something up?
Thanks!

**Comment by lucascebertin** [comment]
Nevermind, changed the client version and the crash is gone.

Now I'm using 11.43.5504

**Comment by MajestyOTBR** [comment]
Download link?

**Comment by favasconcelos** [comment]
Aonde tu conseguiu @lucascebertin ? Add o link ai pra quem tiver o problema usar :)

**Comment by lucascebertin** [comment]
https://tibiaking.com/forums/topic/85241-download-clients-11-ip-127001/

Precisa ter cadastro.

**Comment by MajestyOTBR** [comment]
Cliente 10: https://gitlab.com/guilhermesidney/cliente10/tree/master/tibia
Cliente 11 (sem debug): https://gitlab.com/guilhermesidney/cliente10/tree/9e9554613304ccad63e558328ac587e7cef3b95c/Tibia%2011.44.5516
