### ISSUE TITLE
login.lua (furygate)

### ISSUE THREAD

**Issue by QuebradaZN** [malucooo/otxserver-new#112]
**Adicionar no Login.lua**
-- fury gates
    local messageType = nil
    if (player:getClient().os == 3 or
    	player:getClient().os == 5) then
    	messageType = MESSAGE_EVENT_ADVANCE
    end

    if Game.getStorageValue(GlobalStorage.FuryGates, (9710)) == 1 then -- for venore
		player:sendTextMessage(MESSAGE_STATUS_CONSOLE_BLUE, 'Fury Gate is on Venore Today.')
	elseif Game.getStorageValue(GlobalStorage.FuryGates, (9711)) == 2 then -- for ab...
		player:sendTextMessage(MESSAGE_STATUS_CONSOLE_BLUE, 'Fury Gate is on Abdendriel Today.')
	elseif Game.getStorageValue(GlobalStorage.FuryGates, (9712)) == 3 then -- for ab...
		player:sendTextMessage(MESSAGE_STATUS_CONSOLE_BLUE, 'Fury Gate is on Thais Today.')
	elseif Game.getStorageValue(GlobalStorage.FuryGates, (9713)) == 4 then -- for ab...
		player:sendTextMessage(MESSAGE_STATUS_CONSOLE_BLUE, 'Fury Gate is on Carlin Today.')
	elseif Game.getStorageValue(GlobalStorage.FuryGates, (9714)) == 5 then -- for ab...
		player:sendTextMessage(MESSAGE_STATUS_CONSOLE_BLUE, 'Fury Gate is on Edron Today.')
	elseif Game.getStorageValue(GlobalStorage.FuryGates, (9716)) == 6 then -- for ab...
		player:sendTextMessage(MESSAGE_STATUS_CONSOLE_BLUE, 'Fury Gate is on Kazordoon Today.')
	end

**Comment by Raphaellb** [comment]
fury gates were fixed under pull request #42
