### ISSUE TITLE
MEU CHAR NAO ENTRA NA VERSÃO 11, preciso de ajuda

### ISSUE THREAD

**Issue by guinhoxm** [malucooo/otxserver-new#114]
### Subject of the issue
Describe your issue here.

### Tibia Version
- [ ] 10.00
- [x] 11.00
- [ ] Other

### Steps to reproduce
How to reproduce this issue.

### Expected behaviour
What should happen.

### Actual behaviour
What happens instead.

**Comment by guinhoxm** [comment]
TENHO 2 char na conta, mas 1 deles não loga na versão 11.

estava caçando em oramond, quando deu um bug, agora fui teleportado para o templo, mesmo sem morrer e não consigo entrar nesse char na versão 11.

MEU nick é Guinho

AGUARDO UMA AJUDA

**Comment by guinhoxm** [comment]
Quando abro na versão 10. ele entra normal, mas é muito lixo essa versão.

será que tem como concertar isso?

**Comment by MajestyOTBR** [comment]
Cliente 10: https://gitlab.com/guilhermesidney/cliente10/tree/master/tibia
Cliente 11 (sem debug): https://gitlab.com/guilhermesidney/cliente10/tree/9e9554613304ccad63e558328ac587e7cef3b95c/Tibia%2011.44.5516
