### ISSUE TITLE
Fix Creatures

### ISSUE THREAD

**Issue by GabrielMancio** [malucooo/otxserver-new#118]
### Subject of the issue
Describe your issue here.

### Tibia Version
- [x ] 10.00
- [ ] 11.00
- [ ] Other

### Steps to reproduce
How to reproduce this issue.

### Expected behaviour
Falcons dealing massive damage.
Skeletons(ankrahmun, new)are giving the wrong loot.

### Actual behaviour
What happens instead.

**Comment by EnzzoCaaue** [comment]
im working on it in my free time

**Comment by gutogirardon** [comment]
will be the next major update!
