### ISSUE TITLE
Realm of Dreams quest

### ISSUE THREAD

**Issue by newacc12** [malucooo/Otxserver-New#118]
According to http://tibia.wikia.com/wiki/Realm_of_Dreams_Quest , the level door should be 40 not 240

![image](https://cloud.githubusercontent.com/assets/20234557/26028434/e89edfe2-37e5-11e7-948f-8cb3e9151646.png)

**Comment by GoularPink** [comment]
Alguém poderia dar uma solução pro abuso de uso da chayenne key

**Comment by malucooo** [comment]
fixed!
