### ISSUE TITLE
Asassins outfit quest

### ISSUE THREAD

**Issue by newacc12** [malucooo/Otxserver-New#119]
According to http://tibia.wikia.com/wiki/Assassin_Outfits_Quest , you should only be able to enter the door on the screen to see the NPC Erayo if you are invisible.

![image](https://cloud.githubusercontent.com/assets/20234557/26028453/493d4280-37e6-11e7-92d2-81fbb7c4e89f.png)

Behavior can be seen here: https://www.youtube.com/watch?v=EK39ZFL56RA at 6:40

**Comment by marsoncschneider** [comment]
I will try.

**Comment by joseluis2g** [comment]
```lua
local failPosition = Position(x, y, z)

function onStepIn(creature, item, position, fromPosition)
	local player = creature:getPlayer()
	if not player then
		return true
	end

	if player:getCondition(CONDITION_INVISIBLE) then
		return true
	end

	failPosition:sendMagicEffect(CONST_ME_MAGIC_BLUE)
	player:teleportTo(failPosition)
	return true
end
```

**Comment by malucooo** [comment]
make pull request!
