### ISSUE TITLE
Serious failure of stability

### ISSUE THREAD

**Issue by Zainox** [malucooo/Otxserver-New#12]
@malucooo Malucoo I followed your work of serca and is very good, I would like to report that in this datapack, you still have the swimming bug, as the char does not go swimming and stands, in the console marks the error of the movement and the compat . Another error I want to report is the serious instability that the server has, whether in Linux or Windows the server crashes only in different periods of time, **_I have been monitoring the behavior of the server and crashes every 3 hours, and every 15 hours._** On both platforms, such as windows or linux, so I ask you with all my heart to check the globalevents or any file that is causing this instability.

Contact: Skype and email: zainox@live.it
Facebook: www.facebook.com/zainox1

**Comment by newacc12** [comment]
@Zainox Have you tried the latest commits? Swimming is working fine for me. I also had the server running for like a week with no problems but I didn't have a lot of players. The only time I got crashes was during the pirate invasion on Thais before @malucooo modified the raids. After I disabled that raid the crashes stopped.

**Comment by Zainox** [comment]
Hey @newacc12 Well I tell you ... I downloaded the datapack about 3 or 4 days ago, and compile on the 28th of this month, and then I still had the problem of swimming, because only the problem of bones in Roshamull had been fixed. So I'll try again, but what really worries me a lot and has me without sleep **_is stability, the server crashes, and I've already changed the globalevents, and the raids, and it's still happening._** **We have to do, you do not have some method for me to contact you so we can talk about the datapack and improve it? What operating system do you use?**

**Comment by Rockerszzz** [comment]
I've been opened the latest commits and worked very fine on windows 7 x64, no crashes, no errors on console.

**Comment by Zainox** [comment]
@Rockerszzz yeah, it`s tru, but, you try to open at server 1 week, and you see the server is down in hours.

**Comment by newacc12** [comment]
@Zainox I had a crash today lol, that's weird :< the only message that I have for the logs is: Segmentation fault. Do you have any ideas what be causing the crashes?

I'm currently running on linux ubuntu 16.04

**Comment by Zainox** [comment]
@newacc12 I told you, I'm also running Ubuntu 16.04, I've made several fixes and I've had 24 hours of stability, I'm going by 48. Please give me a contact method to contact and do the tests. I would also like the script to be shared in order to see the console logs

My skype: zainox@live.it
My Facebook: https://www.facebook.com/Zainox1

**Comment by Zainox** [comment]
@malucooo, you have to check the scripts, libraries or global events, modified the server scripts save and put the originals of the git hub Mattyx14 but still the server falls, with your source also falls, please Check the Data, and if there are libraries that find that the officers of mattyx14 are changed, I do not understand why they fall so much. No matter the operating system, the server is in a global event. Because on my server (Ubuntu 16.04) had a stability of 26 hours (no players) and fell. Please check that, this problem makes the datapack, not used well.

Im do not alone in this bug, @newacc12 have the same crash bug.

**Comment by malucooo** [comment]
i cant reproduce, because my pc isn't run the server =/~

**Comment by Zainox** [comment]
So, i gift you 1 month of VPS? is possible you test in linux? @malucooo

**Comment by malucooo** [comment]
i need more info to find the error =/

**Comment by Zainox** [comment]
@malucooo no have info because, the server is crash and is impossible to see, is necessary, look the console 24/7. @newacc12 have`s a one error in the log, and this say : Segmentation fault

**Comment by Blingx** [comment]
We need to work together to figure out these problems, Post your globalevents @Zainox

**Comment by Zainox** [comment]
@Blingx the Globalevents is same of have disponible in this github, this is:

**Comment by Zainox** [comment]
I think, the error is in Raids... and no, no is the pirate thais, this is a another, the problem is, what is the raid?... The server is stable but, when one player go to hunting, the server is crash... (no, the monsters and the player scripts no have a error)

**Comment by malucooo** [comment]
more infos?

**Comment by Rockerszzz** [comment]
Then i believe we are facing a new problem, i've used this datapack about 1 month without any crash with 10 players online per day. @malucooo , i will start the server again, and i'll let open for some days to test this new version. I'll back with more informations if there a real problem with the server. best regards.
