### ISSUE TITLE
BUG PUSH

### ISSUE THREAD

**Issue by ZeroSkywalker** [malucooo/otxserver-new#121]
### Subject of the issue
The attack is exhausting the push, if it is attacking, it can not be pushed.

### Tibia Version
- [OK] 10.00
- [OK] 11.00
- [ ] Other

### Steps to reproduce
The attack is exhausting the push, if it is attacking, it can not be pushed.

**Comment by EnzzoCaaue** [comment]
couldnt reproduce here.
