### ISSUE TITLE
Damaged Steel Helmet has wrong sprite

### ISSUE THREAD

**Issue by newacc12** [malucooo/Otxserver-New#123]
http://tibia.wikia.com/wiki/Damaged_Steel_Helmet

![image](https://cloud.githubusercontent.com/assets/20234557/26029829/94c77eaa-3804-11e7-9612-4b86508e3969.png)

![image](https://cloud.githubusercontent.com/assets/20234557/26029835/a29a57f0-3804-11e7-97a3-51dd7888f09b.png)

**Comment by Eternal-Scripts** [comment]
`<item id="11422" article="a" name="damaged steel helmet">`
