### ISSUE TITLE
Taming.lua

### ISSUE THREAD

**Issue by johnnybarroso** [malucooo/Otxserver-New#13]
Hello Malucoo,
Morning.

I'm added in taming.lua the configuration of walker mount because don't worked using control unit.
See the code bellow for implementation.

```
[23557]	= {
		name = 'walker',
		id = 43,
		type = TYPE_MONSTER,
		chance = 30,
		fail = {
			{run = true, text = 'The Walker disappeared.'},
			{sound = '*pling*', text = 'The walker seems incompatible with this control unit.'}
		},
		success = {sound = '*brzzz*', text = 'You tamed the walker.'}
	},
```

I creating according of Tibia global.
I hope I've helped you and community.

Thanks for atention,
GOD Bon xD

**Comment by johnnybarroso** [comment]
I added in taming.lua the configuration of noble lion see the code bellow.

`[23810]	= {
		name = 'noble lion',
		id = 40,
		type = TYPE_MONSTER,
		chance = 30,
		fail = {
			{run = true, text = 'The noble lion fled.'},
			{sound = 'GRRRRRRRRR', text = 'The noble lion majestically rejects your amulet.'}
		},
		success = {sound = 'Grrr', text = 'The noble lion will now accompany you as friend and ally.'}
	}`

In the action.xml i added this tag
`<action itemid="23810" script="other/taming.lua" />`

**Comment by malucooo** [comment]
make a pull request!
