### ISSUE TITLE
Menu de Outfit e Montaria dando Debug

### ISSUE THREAD

**Issue by neykos** [malucooo/Otxserver-New#131]
Eu estava com uma versão menos atualizada de uns 10 dias atrás, fui resolver atualizar agora
Quando crio um personagem ao logar já dá debug, quando logo com o ADM, ou o char Erick Nunes
ao tentar entrar na janela que troca Oufit e Montaria simplesmente da debug no cliente.

Obs: não é o cliente que está com problema, pois eu entrei em outros servidores e funcionou perfeitamente e antes de atualizar para a versão mais atualizada do github começou esse problema.

**Comment by newacc12** [comment]
It's working perfect here. You need to use the client that's on the read-me on the first page: 
http://www.mediafire.com/file/571cbbt9cy2y30t/tibia1000.rar

**Comment by neykos** [comment]
I'm using this first page client

**Comment by newacc12** [comment]
That's weird I'm logged in right now using the latest version from this repository :/
