### ISSUE TITLE
Dreamer's Challenge Quest

### ISSUE THREAD

**Issue by neykos** [malucooo/Otxserver-New#132]
A parte onde precisa usar o Fire bug

"Haverá um lugar com Poison Gas (cuidado, ele causa dano assim como um Poison Field). Depois dos poison gas você encontrará um espaço chamuscado por onde gás está passando. Use o Fire Bug nele."

Essa parte está bugada, precisa ser corrigida, pois não aparece o teleporte.

**Comment by newacc12** [comment]
It has been fixed already on https://github.com/malucooo/Otxserver-New/commit/66c12cc6cc4caeb2c6a12b98d6bc9c06c0fcd4de 

Update your version
