### ISSUE TITLE
Not possible to use insectoid cell in the Hive

### ISSUE THREAD

**Issue by newacc12** [malucooo/Otxserver-New#134]
According to http://tibia.wikia.com/wiki/Gooey_Mass, when using insectoid cells we should have a chance to get some items including gooey mass to tame the lady bug. However if you try to use the insectoid cell it just opens a container so I guess it's not working:

![image](https://cloud.githubusercontent.com/assets/20234557/26182876/b7dbd7d0-3b40-11e7-909f-63bab5afa7d1.png)

After looking into actions.xml I can see we have all the actions and lua scripts in place:
![image](https://cloud.githubusercontent.com/assets/20234557/26182915/038aa44a-3b41-11e7-87ca-2bf1c6a96b9d.png)

My guess is that we are missing the ActionIDs on the insectoid cells on the map (http://www.tibiawiki.com.br/wiki/Insectoid_Cell). I was going to try to fix it but RME does work on my computer for some bizarre reason. Can someone take a look at this? Or help me to fix RME for my environment.

**Comment by darkjav** [comment]
@newacc12 Please check if this fix the problem:
https://github.com/malucooo/Otxserver-New/commit/07c8b886b81ba485f954775bf2c54fbbb8b844e8

And tell us. Thanks.

**Comment by newacc12** [comment]
@darkjav It seems to be working now! Thanks
