### ISSUE TITLE
Can't get any client work with this server

### ISSUE THREAD

**Issue by janpaweldrugijebal** [malucooo/otxserver-new#140]
### Subject of the issue
Tibia 10 included in package runs OK, but when I wan't to run version 11.44 also included, client is getting crashed in random moments. There aren't any errors in console, so I bet this is just a matter of using proper client.

### Tibia Version
- [ ] 10.00
- [x] 11.00
- [ ] Other

### Steps to reproduce
Just run any Tibia client ver 11 and walk near paladin's guild in thais (offline training)

### Expected behaviour
Game should work properly.

### Actual behaviour
Client crashes without any error.

**Comment by EnzzoCaaue** [comment]
are you using the client that is attached to readme.md?

**Comment by EnzzoCaaue** [comment]
are you using the client provided by the project?

**Comment by gutogirardon** [comment]
In this package has a client v10 and an v11.  
source ->  https://gitlab.com/guilhermesidney/cliente10
sdk full -> https://gitlab.com/guilhermesidney/cliente10/-/archive/master/cliente10-master.zip
both have been tested, I am closing this issue, next time try to be specific about any issue.
