### ISSUE TITLE
map issue

### ISSUE THREAD

**Issue by pitis91** [malucooo/otxserver-new#143]
i have a question, why johncore distro have more and best map than our map? why noone updates it? :(

**Comment by Raphaellb** [comment]
feel free to update it, everyone can contribute.

**Comment by pitis91** [comment]
> 
> 
> feel free to update it, everyone can contribute.

i'm not sure to do it better than another one 1. the map editor maybe is different and maybe i could bug the current map 2. the itemids i'm not sure if all the id's are the same and 3. just now i'm out of contribuing cuz i have too much work right now on rl life :'(

**Comment by Raphaellb** [comment]
no problem man. we all contribute when we can.
