### ISSUE TITLE
[Discussion] - Loot statistics

### ISSUE THREAD

**Issue by newacc12** [malucooo/Otxserver-New#143]
I was working on a simple parser to read the loot statistics from TibiaWikia to update all the monsters with current loot and drop chance. However it seems that information is different depending on the page that you are, for example:

http://tibia.wikia.com/wiki/Behemoth
http://tibia.wikia.com/wiki/Loot_Statistics:Behemoth

On the first link, the Gold amount is 0-199. On the second it is 1-346. Loot chance for these are the same tho.
Meat on the first page is 0-6. On the second page it has no value which is clearly wrong.

What do you guys think? Is there any other source of information out there?

**Comment by sn4tch0vsk** [comment]
newacc12
I updated loots of monsters based on first link, not in statistics
The OT has just a few monsters to update, specially the bosses, cause it's too much loot and that's take a lot of time from me, but I'll get there. if you have a better and fast way to fix this, let me know.

**Comment by newacc12** [comment]
@sn4tch0vsk I see. I will try to make a quick and dirty parser to try to automatically update the monsters. The problem with that page is that we need a click to load the percentages AFAIK. Anyway if you have updated the majority of the monsters already I would suggest keep going that way. If I come up with something I'll let you know.

Thanks

**Comment by darkjav** [comment]
I think that the amount more lower is good, because almost all OT's use loot rate x4 or more. So when the lower amount is multiplied, you get more.

**Comment by Eternal-Scripts** [comment]
@newacc12 if you need help with looktypes tell me, i can list to you.
