### ISSUE TITLE
Missing sprites in client 11.44

### ISSUE THREAD

**Issue by janpaweldrugijebal** [malucooo/otxserver-new#144]
### Subject of the issue
You deleted my last issue, where I tried to explain my problem. Best support ever.
There is a problem with missing sprites (outfits, mounts etc.). Client crashes when I want to change outfit and also crashes in some areas like trainers room.
Yes, I am using client version 11.44 downloaded from this repo (cliente10).
"everything is tested and working" - don't bullshit me like that, this isn't working, even if I will redownload this 1000 times, it's the same bug.

### Tibia Version
- [ ] 10.00
- [x] 11.00
- [ ] Other

### Steps to reproduce
Just try to change outfit...

### Expected behaviour
IT SHOULD WORK

### Actual behaviour
CLIENT CRASH

**Comment by cys9211** [comment]
On Thais depot crash =p

**Comment by Tazer89** [comment]
Its the client not the server. So you could close this.
