### ISSUE TITLE
Cant enter the server.

### ISSUE THREAD

**Issue by Merran2k** [malucooo/Otxserver-New#145]
Hey there..

I downloaded this server today & installed it completely. but when im trying to login the server dont let me in. The character list is coming up but when im trying to enter it just loading... I do have a linux ubuntu 16.04 LTS..

Regards,
Merran

**Comment by westwol** [comment]
- What client are you using to log in?
- Did you change the ip in _config.lua_?

**Comment by Merran2k** [comment]
I´m using a client you had on descriptions. "http://www.mediafire.com/file/571cbbt9cy2y30t/tibia1000.rar"

Config has been changed & all ports on my dedicated server machine is opened. I can login on other server i do have on my machine but not this one.

Regards,
Merran

**Comment by westwol** [comment]
Any console print?
