### ISSUE TITLE
There is some wrong with connection

### ISSUE THREAD

**Issue by Merran2k** [malucooo/Otxserver-New#148]
Hey there.

I've been trying to login into the server for a while now without any result because it is something wrong with connection. I've downloaded official TFS 1.3 and tried it & got connected directly into the server.

So take a look on the sources because it is really something wrong!

Regards,
Merran

**Comment by westwol** [comment]
Are you having any console print?

**Comment by Merran2k** [comment]
There is not showing anything wrong in console but just cant acces to the server. 

I'll show you picture of it ofcourse.

Server Console:
http://1.1m.yt/zUHKVU0.png

Tibia:
http://1.1m.yt/CpxOWbE.png

**Comment by westwol** [comment]
The console doesn't even print when the character logs in.

**Comment by Merran2k** [comment]
Nope it doesnt.
 
There most be a problem with the server or something because when im trying to login into my other server it works well with same database etc. I've also tried to using your database that you have uploaded here but it dosnt work on this server. What can the problem be?

**Comment by westwol** [comment]
I will do a couple of tests when I get home cloning the whole datapack and will let you know.

**Comment by Merran2k** [comment]
Awesome.

Will it take time ?

Tell me if you find anything or something wrong, I'll redownload the server and try to start it once again!

Thanks for fast response!

**Comment by helli3** [comment]
You have to check your ports, ip adress, and all applications turned on. I tested this sources and it works for me.

**Comment by Merran2k** [comment]
How can ports not be open if i can acces on TFS 1.3..

I've tried alot of other servers to, All works fine just this one is complicated

**Comment by malucooo** [comment]
check ip on config.lua...

**Comment by jlcvp** [comment]
@Merran2k, additionally, do the player have a blade of carving equiped or in the backpack?

**Comment by helli3** [comment]
malucooo have rights check ip in config lua if you have problems you can msg to me on skype hellsoul_helli and i can try help you ;) try to kill all tfs

**Comment by Merran2k** [comment]
IP in config is right now. Have been looking around in sources if i could find something related to this..

I'm going to reinstall the server machine to see if it was something wrong with it, But can still start my other servers which make it more no sense for me

**Comment by helli3** [comment]
Im using this sources and it works. Im sure about this.

**Comment by Merran2k** [comment]
I'll try once again tomorrow.

Thanks once again for fast response! :)

**Comment by helli3** [comment]
I will try to help. :+1:

**Comment by Merran2k** [comment]
There is something wrong. I just bought another server machine to just test the sources & still not connecting ingame. There is something wrong with it!

I dont have skype, if you discord then you can add me, LuckyM#8741

**Comment by Eternal-Scripts** [comment]
You need to check ports, configure your ip and connection configs in config.lua correctly and now we are using new connection for 11.20.
