### ISSUE TITLE
Reward chest /  Countmax does not work

### ISSUE THREAD

**Issue by Nicholasz23** [malucooo/Otxserver-New#149]
The loot countmax of monsters that are on the reward chest, does not work. It clones items that are with countmax = '1' delivering the same items to all players that attacks the creature.

**Comment by lamonato29** [comment]
Bro, it works. You have to add a unique="1" on the loot. Countmax will only limit the COUNT MAX not the exclusivity of the item.

**Comment by Nicholasz23** [comment]
I'm not talking about exclusivity, but about quantity. The unique = "1" is used to not clone and also to give the item to those who take more life from the creature, but the ones that do not have this unique? He is cloning the items that are not with that tag in the loot, so I talked about quantity and about the countmax tag.

**Comment by lamonato29** [comment]
I understand! Yes, it happens bro.. The reward system need to be reviewed.. Srry for my bad english..

**Comment by Eternal-Scripts** [comment]
This is an old bug of OTX Reward System and i can confirm this.
