### ISSUE TITLE
Message: Unknown column 'instantrewardtokens' in 'field list'

### ISSUE THREAD

**Issue by FlexLewis** [malucooo/otxserver-new#152]
**Erro na distro ao logar**
Ao criar uma conta com qualquer uma das opções de site disponibilizadas no próprio repositório, gera o erro a seguir na distro do otx: 

1º: Aqui segue a distro sem nenhum erro
![image](https://user-images.githubusercontent.com/28009621/64981123-c6485f00-d891-11e9-9449-453a50aeeb3b.png)

2º: Aqui segue o erro que o corre após criar o char em qualquer uma das opções de site, usando o schema.sql do repositório como database.
![image](https://user-images.githubusercontent.com/28009621/64981333-3c4cc600-d892-11e9-81dc-f630bf4ec610.png)

**### Tibia Version**
- [x] 10.00
- [ ] 11.00
- [ ] Other

**### Steps to reproduce**
1. Configurar xampp
2. Configurar database
3. Criar um char com qualquer um dos sites do repositório
4. Realizar login com Tibia 10 e receber a mensagem:

![image](https://user-images.githubusercontent.com/28009621/64981629-da409080-d892-11e9-91f7-e046393007d6.png)

**### Expected behaviour**
Deveria logar normalmente.

**### Actual behaviour**
Gera erro na distro / Mensagem no tibia informando que não é possível logar.

**Comment by malucooo** [comment]
fixed
