### ISSUE TITLE
Error when looking at giant sword

### ISSUE THREAD

**Issue by newacc12** [malucooo/Otxserver-New#152]
When trying to look at giant sword the console throws this error and it does not show anything on the client:

Lua Script Error: [Event Interface]
data/events/scripts/player.lua:Player@onLook
data/events/scripts/player.lua:27: attempt to call method 'getSpecialAttribute' (a nil value)
stack traceback:
        [C]: in function 'getSpecialAttribute'
        data/events/scripts/player.lua:27: in function <data/events/scripts/player.lua:12>

I guess it's related to the WIP from the imbue/prey/inspect system, right? Maybe we should stop committing WIP to the master branch and create like a development branch. This way we just commit code to the master branch that's been tested and we know it's working.

**Comment by Eternal-Scripts** [comment]
Please update your OTX, here is working 100%.
![image](https://cloud.githubusercontent.com/assets/20959344/26433983/491279f2-40dc-11e7-8815-9a1ef20d4b53.png)

**Comment by newacc12** [comment]
Of course, you have added the missing libraries on this commit https://github.com/malucooo/Otxserver-New/commit/434ecc8a0ddaf2958accafb117d7e313288e57b6

At the time of the previous post, when I downloaded the latest version, it was bugged. I will update to the latest version and will let you know. 

Thanks!

**Comment by newacc12** [comment]
@Eternal-Scripts Thanks! I confirmed it's working now.
