### ISSUE TITLE
Warning when starting up the server

### ISSUE THREAD

**Issue by newacc12** [malucooo/Otxserver-New#153]
[Spawn::addMonster] Can not find Orclops Doomhauler
[Spawn::addMonster] Can not find Cave Parrot
[Spawn::addMonster] Can not find Orclops Ravager
[Spawn::addMonster] Can not find Orclops Doomhauler
[Spawn::addMonster] Can not find Orclops Doomhauler
[Spawn::addMonster] Can not find Orclops Ravager
[Spawn::addMonster] Can not find Orclops Ravager
[Spawn::addMonster] Can not find Orclops Ravager
[Spawn::addMonster] Can not find Orclops Doomhauler
[Spawn::addMonster] Can not find Orclops Doomhauler
[Spawn::addMonster] Can not find Twisted Shaper
[Spawn::addMonster] Can not find Broken Shaper
[Spawn::addMonster] Can not find Twisted Shaper
[Spawn::addMonster] Can not find Twisted Shaper
[Spawn::addMonster] Can not find Twisted Shaper
[Spawn::addMonster] Can not find Broken Shaper
[Spawn::addMonster] Can not find Broken Shaper
[Spawn::addMonster] Can not find Shaper Matriarch
[Spawn::addMonster] Can not find Broken Shaper
[Spawn::addMonster] Can not find Twisted Shaper
[Spawn::addMonster] Can not find Twisted Shaper
[Spawn::addMonster] Can not find Broken Shaper
[Spawn::addMonster] Can not find Shaper Matriarch
[Spawn::addMonster] Can not find Twisted Shaper
[Spawn::addMonster] Can not find Broken Shaper
[Spawn::addMonster] Can not find Broken Shaper
[Spawn::addMonster] Can not find Shaper Matriarch
[Spawn::addMonster] Can not find Twisted Shaper
[Spawn::addMonster] Can not find Shaper Matriarch
[Spawn::addMonster] Can not find Shaper Matriarch
[Spawn::addMonster] Can not find Broken Shaper
[Spawn::addMonster] Can not find Shaper Matriarch
[Spawn::addMonster] Can not find Broken Shaper
[Spawn::addMonster] Can not find Twisted Shaper
[Spawn::addMonster] Can not find Broken Shaper
[Spawn::addMonster] Can not find Twisted Shaper
[Spawn::addMonster] Can not find Twisted Shaper
[Spawn::addMonster] Can not find Shaper Matriarch
[Spawn::addMonster] Can not find Shaper Matriarch
[Spawn::addMonster] Can not find Shaper Matriarch
[Spawn::addMonster] Can not find Twisted Shaper
[Spawn::addMonster] Can not find Twisted Shaper
[Spawn::addMonster] Can not find Twisted Shaper
[Spawn::addMonster] Can not find Shaper Matriarch
[Spawn::addMonster] Can not find Twisted Shaper
[Spawn::addMonster] Can not find Twisted Shaper
[Spawn::addMonster] Can not find Shaper Matriarch
[Spawn::addMonster] Can not find Shaper Matriarch
[Spawn::addMonster] Can not find Broken Shaper
[Spawn::addMonster] Can not find Twisted Shaper
[Spawn::addMonster] Can not find Broken Shaper
[Spawn::addMonster] Can not find Twisted Shaper
[Spawn::addMonster] Can not find Broken Shaper
[Spawn::addMonster] Can not find Shaper Matriarch
[Spawn::addMonster] Can not find Shaper Matriarch
[Spawn::addMonster] Can not find Orclops Ravager
[Spawn::addMonster] Can not find Orclops Doomhauler
[Spawn::addMonster] Can not find Orclops Ravager
[Spawn::addMonster] Can not find Orclops Ravager
[Spawn::addMonster] Can not find Orclops Doomhauler
[Spawn::addMonster] Can not find Orclops Doomhauler
[Spawn::addMonster] Can not find Orclops Ravager
[Spawn::addMonster] Can not find Orclops Doomhauler
[Spawn::addMonster] Can not find Orclops Doomhauler
[Spawn::addMonster] Can not find Orclops Ravager
[Spawn::addMonster] Can not find Orclops Doomhauler
[Spawn::addMonster] Can not find Orclops Doomhauler
[Spawn::addMonster] Can not find Orclops Ravager
[Spawn::addMonster] Can not find Orclops Doomhauler
[Spawn::addMonster] Can not find Orclops Ravager
[Spawn::addMonster] Can not find Orclops Ravager
[Spawn::addMonster] Can not find Orclops Doomhauler
[Spawn::addMonster] Can not find Orclops Doomhauler
[Spawn::addMonster] Can not find Orclops Doomhauler
[Spawn::addMonster] Can not find Orclops Ravager
[Spawn::addMonster] Can not find Orclops Doomhauler
[Spawn::addMonster] Can not find Orclops Ravager
[Spawn::addMonster] Can not find Orclops Ravager
[Spawn::addMonster] Can not find Orclops Ravager
[Spawn::addMonster] Can not find Orclops Doomhauler
[Spawn::addMonster] Can not find Twisted Shaper
[Spawn::addMonster] Can not find Broken Shaper
[Spawn::addMonster] Can not find Broken Shaper
[Spawn::addMonster] Can not find Twisted Shaper
[Spawn::addMonster] Can not find Broken Shaper
[Spawn::addMonster] Can not find Twisted Shaper
[Spawn::addMonster] Can not find Twisted Shaper
[Spawn::addMonster] Can not find Twisted Shaper
[Spawn::addMonster] Can not find Twisted Shaper
[Spawn::addMonster] Can not find Broken Shaper
[Spawn::addMonster] Can not find Broken Shaper
[Spawn::addMonster] Can not find Broken Shaper
[Spawn::addMonster] Can not find Broken Shaper
[Spawn::addMonster] Can not find Twisted Shaper
[Spawn::addMonster] Can not find Broken Shaper
[Spawn::addMonster] Can not find Broken Shaper
[Spawn::addMonster] Can not find Twisted Shaper
[Spawn::addMonster] Can not find Twisted Shaper
[Spawn::addMonster] Can not find Broken Shaper
[Spawn::addMonster] Can not find Broken Shaper
[Spawn::addMonster] Can not find Twisted Shaper
[Spawn::addMonster] Can not find Broken Shaper
[Spawn::addMonster] Can not find Broken Shaper
[Spawn::addMonster] Can not find Broken Shaper
[Spawn::addMonster] Can not find Twisted Shaper
[Spawn::addMonster] Can not find Twisted Shaper
[Spawn::addMonster] Can not find Twisted Shaper
[Spawn::addMonster] Can not find Twisted Shaper
[Spawn::addMonster] Can not find Twisted Shaper
[Spawn::addMonster] Can not find Broken Shaper
[Spawn::addMonster] Can not find Twisted Shaper
[Spawn::addMonster] Can not find Broken Shaper
[Spawn::addMonster] Can not find Broken Shaper
[Spawn::addMonster] Can not find Twisted Shaper
[Spawn::addMonster] Can not find Broken Shaper
[Spawn::addMonster] Can not find Broken Shaper
[Spawn::addMonster] Can not find Twisted Shaper
[Spawn::addMonster] Can not find Twisted Shaper
[Spawn::addMonster] Can not find Twisted Shaper
[Spawn::addMonster] Can not find Broken Shaper
[Spawn::addMonster] Can not find Twisted Shaper
[Spawn::addMonster] Can not find Broken Shaper
[Spawn::addMonster] Can not find Twisted Shaper
[Spawn::addMonster] Can not find Twisted Shaper
[Spawn::addMonster] Can not find Broken Shaper
[Spawn::addMonster] Can not find Broken Shaper
[Spawn::addMonster] Can not find Broken Shaper
[Spawn::addMonster] Can not find Broken Shaper
[Spawn::addMonster] Can not find Twisted Shaper
[Spawn::addMonster] Can not find Broken Shaper
[Spawn::addMonster] Can not find Broken Shaper
[Spawn::addMonster] Can not find Broken Shaper
[Spawn::addMonster] Can not find Twisted Shaper
[Spawn::addMonster] Can not find Broken Shaper

**Comment by jerryb1988** [comment]
I also am having these errors.

**Comment by darkjav** [comment]
You need make the new monsters and shared with us.

**Comment by newacc12** [comment]
@darkjav My point is, we shouldn't commit code that is not working to the main branch as a general rule. This can generate errors that can even stop it from running and it's frustrating, specially for new people that are starting to contribute. Also I'm not sure how to make monsters otherwise I would've fixed it.
