### ISSUE TITLE
Imbuing Shrine.

### ISSUE THREAD

**Issue by Tekadon58** [malucooo/Otxserver-New#154]
Não está funcionando fica aparecendo This item is not imbuable.

Antes nem isso aparecia eu tive de mudar a tag do Actions.xml que estava com corpos de monstros ai coloquei : <action fromid="27716" toid="27717" script="other/imbuement.lua" />  ai começou aparecer a notificação que eu falei no começo.

**Comment by Schiffers** [comment]
você marcou a tag no item que vc quer imbuir no items.xml ?

**Comment by Tekadon58** [comment]
Como faço isso amigo pode me dizer pf

**Comment by Eternal-Scripts** [comment]
No items.xml atribua esse valor.
**`<attribute key="imbuingSlots" value="3" />`**
3 é o número de Slots que terá na arma.
