### ISSUE TITLE
Your character could not be loaded.

### ISSUE THREAD

**Issue by Eyalon** [malucooo/otxserver-new#154]
I have that error on client and this spam on server console. Screen down:

https://imgur.com/a/1DMJo1W

**Comment by Kairi85** [comment]
i think that's because u are using you old database and there are missing rows from this new version, i had to add all those rows and change preperties exactly like the new one manually via phpmyadmin to make it work it took me like 2 hours, still theres so many debug errors

**Comment by FlexLewis** [comment]
Same error here. I am using all files available inside otxserver-new.
I didn't changed any of the files.

Do you know what it is?

**Comment by malucooo** [comment]
fixed
