### ISSUE TITLE
crash when buy list reroll in prey system

### ISSUE THREAD

**Issue by Schiffers** [malucooo/Otxserver-New#155]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. have some money in the bank
2. try buy reroll lists in the prey window (some times you will buy without crash)
3. then crash

### Expected behaviour
well, not crash when you buy lists

### Actual behaviour
crash when you try buy the lists to find a monster expecific for exemple: demon

### Environment
no error in console, just crash
edit:
also when you have the 3 slots available for the character when you buy a list for a slot the all slots with monsters list will be changed
edit 2: another issue D:
the same monster can appear in different slots at same time
edit 3: more one issue, some times when you buy the list can came just one monster
http://imgur.com/0lEOPHp
then I close the prey window and open it again then
http://imgur.com/9dRLLZr
and sometimes when you buy a list and select any monster can appear another monster

**Comment by darkjav** [comment]
You need compile with debug mode and show us the "bt full".

**Comment by Schiffers** [comment]
is not necessary, the crash is from module script, we need debug the script and not the source I guess

**Comment by westwol** [comment]
I couldn't reproduce the crash while buying reroll lists.

**Comment by Eternal-Scripts** [comment]
1. Tested many times (with the last otx datapack) and is working.
2. Impossible, look at this line.
`if (not tableContains(monstersGenerated[player:getGuid()], randomName)) then`
3. Can't reproduce too.

If have other people where can confirm that, i will put label 'bug' in this issue.

**Comment by Schiffers** [comment]
![image](https://cloud.githubusercontent.com/assets/10325310/26463670/760dd83c-415b-11e7-8776-15c7fc70ada6.png) here when try, I'm using the code from here too D:

maybe my pack don't have **tableContains** I use isInArray

**Comment by westwol** [comment]
Regarding this issue, can you record a video showing how to reproduce it? I could not crash it.

**Comment by Schiffers** [comment]
sure, I'll try and later upload it

**Comment by Schiffers** [comment]
hey @Eternal-Scripts and @westwol, I have noticed that I have another issue, when I use the stamina of a prey monster when I logout and login again the stamina is full, exemple:
I have prey in medusa, kill some medusas for 15 mins
then I logout, and
login again then open the prey window and the stamina is 2h, it should be an issue of some db.query
what you think guys?

**Comment by Schiffers** [comment]
sorry, was my bad, miss some declaration on iologindata.cpp.... the crash was resolved, but still have the same monster in different lists

**Comment by darkjav** [comment]
The next time, you need compile on Linux, windows not is good for OT server production.
