### ISSUE TITLE
Erro ao usar o imbuement system

### ISSUE THREAD

**Issue by Tekadon58** [malucooo/Otxserver-New#157]
Lua Script Error: [Action Interface]
data/actions/scripts/other/imbuement.lua:onUse
data/modules/scripts/imbuement/imbuement.lua:436: attempt to call method 'getSpecialAttribute' (a nil value)
stack traceback:
        [C]: in function 'getSpecialAttribute'
        data/modules/scripts/imbuement/imbuement.lua:436: in function 'isActiveImbuement'
        data/modules/scripts/imbuement/imbuement.lua:364: in function 'openImbuementWindow'
        data/actions/scripts/other/imbuement.lua:9: in function <data/actions/scripts/other/imbuement.lua:3>

**Comment by Tekadon58** [comment]
data/events/scripts/player.lua:Player@onLook
data/events/scripts/player.lua:29: attempt to call method 'getSpecialAttribute' (a nil value)
stack traceback:
        [C]: in function 'getSpecialAttribute'
        data/events/scripts/player.lua:29: in function <data/events/scripts/player.lua:13>

**Comment by Eternal-Scripts** [comment]
434ecc8a0ddaf2958accafb117d7e313288e57b6
Tente esse commit e me avise.

**Comment by Tekadon58** [comment]
Esse sistema esta funcionando 100% mesmo ? ou estou fazendo algo errado Eternal ?

**Comment by Eternal-Scripts** [comment]
Não estou fazendo errado amigo, quem adicionou o protótipo do sistema esqueceu de adicionar muitas coisas, principalmente essas libs que são cruciais para o funcionamento.

**Comment by Tekadon58** [comment]
Parceiro 
 
a janela abriu mais na hora de fazer a magica da erro kkkk 

http://prntscr.com/fbst57

**Comment by Tekadon58** [comment]
Ai como voce poder ver a janela abre normal 

http://prntscr.com/fbsu3k

mais ai vem esse erro na hora de por para funcionar : http://prntscr.com/fbst57

**Comment by Eternal-Scripts** [comment]
Ele removeu o seu dinheiro após essa mensagem? se gastou algo em itens/dinheiro?

**Comment by Tekadon58** [comment]
Gastou não amigo.
Ele não removeu nada manteve tudo e me deu essa mensagem ai

**Comment by Eternal-Scripts** [comment]
Faça o seguinte, reinicie o servidor, crie um novo item com slots e tente fazer o mesmo processo.

**Comment by newacc12** [comment]
Where is that imbuing shrine? I tried the one in halls of hope north of thais but it's giving me the message You cannot use this object:

![image](https://cloud.githubusercontent.com/assets/20234557/26434817/8a52117c-40d0-11e7-8923-a06441d34a6e.png)

22:30 You see a giant sword (Atk:46, Def:22).
It can only be wielded properly by knights of level 55 or higher.
Imbuements: (Empty Slot, Empty Slot, Empty Slot).
It weighs 180.00 oz.
This sword has been forged by ancient giants.
Item ID: 2393

**Comment by Eternal-Scripts** [comment]
@newacc12 please tell me the ID of imbuing shrine

**Comment by newacc12** [comment]
@Eternal-Scripts 22:33 You see imbuing shrine.
Item ID: 27716
Position: 32324, 32093, 7

**Comment by Tekadon58** [comment]
Tem que mudar a tag la no actions.xml que ta errada para pode usar o imbuing

**Comment by Eternal-Scripts** [comment]
@newacc12 fixed 01e28f312cefe04846e9e728890156207eaabd6d

**Comment by Tekadon58** [comment]
eu mudei a tag para essa 

<action fromid="27716" toid="27717" script="other/imbuement.lua" />

**Comment by Tekadon58** [comment]
<action fromid="27716" toid="27717" script="other/imbuement.lua" />

**Comment by Tekadon58** [comment]
mudei de item e continua a mesma mensagem

**Comment by Eternal-Scripts** [comment]
Fez o que eu lhe pedi lá em cima? reiniciar o servidor...

**Comment by Tekadon58** [comment]
sim man e continua a mesma coisa

**Comment by Tekadon58** [comment]
man eu fiz a mudança la no  data/modules/scripts/imbuement/imbuement.lua

local imbuingShrineIds = {
 -    27728, 27729, 27850, 27851
 +    27716, 27717, 27728, 27729, 27850, 27851
  }
  

e agora ele gasta os recursos mais o item nn melhora

**Comment by Eternal-Scripts** [comment]
Você está fazendo algo de errado, ao você criar um novo Item ele já estará com todos os atributos limpos e pelo que eu entendi o problema que está passando é sobre ter o slot da arma já ocupado.

Eu testei novamente para confirmar e está funcionando corretamente, verifique se tem erros na Distro.
Outra coisa que pode ser é o imbuing shrine que está tentando usar pode não estar cadastrado no modules e sim somente no Actions.

**Comment by Tekadon58** [comment]
Vou fazer o seguinte ... Vou baixar o pack dnv e tentar para ver se resolve

**Comment by Schiffers** [comment]
estou com o mesmo problema, eu segui todos os passos do eternal, e fica dando o mesmo problema do tekadon...

**Comment by Tekadon58** [comment]
Eu baixei a pack de novo e mudei o item para fazer testa adicionando a tag <attribute key="imbuingSlots" value="3" /> porem o que aconteceu ? Ele gastou os itens mais não fez nenhuma mudança.

2º Fiz o mesmo procedimento porem usei a chance de 100% ... Bom de 100% não tem nada porem só nesta opção apareceu que o processo falhou como se a chance fosse de 12% Ex ...

**Comment by Eternal-Scripts** [comment]
Não vou poder olhar agora, espera mais tarde o @westwol entrar ele vai ajudar. Deve ser alguma parte faltando ainda.

**Comment by newacc12** [comment]
I'm using a translator to see what you guys are talking about and I think I'm having the same problems as @Tekadon58 and @Schiffers. I tried to imbue a brand new giant sword with Life Leech > Powerful Vampirism. I also selected the Protection Charm. It consumed all the items and the money but it did not improve the item. We are probably missing some other part.

Anyway thanks everyone for helping.

**Comment by joseluis2g** [comment]
@newacc12 
do something like 
```lua
if (not (self:isPremium() and (self:getMoney() + self:getBankBalance()) or self:getMoney())) >= imbuingPrice then
        sendImbuementError(self, "You don't have enough money " ..imbuingPrice.. " gps.", ErrorMessages.MESSAGEDIALOG_IMBUEMENT_ROLL_FAILED)
        return false
    end
	self:removeMoneyNpc(imbuingPrice)
```
instead and test

**Comment by Tekadon58** [comment]
jose adiciona isso aonde man ?

**Comment by joseluis2g** [comment]
well just edited the line cus I guess that imbuiment is only for premium ppl? Idk well change 
```lua
if (not self:removeMoneyNpc(imbuingPrice)) then
        sendImbuementError(self, "You don't have enough money " ..imbuingPrice.. " gps.", ErrorMessages.MESSAGEDIALOG_IMBUEMENT_ROLL_FAILED)
        return false
    end
```
to 
```lua
if (not (self:getMoney() + self:getBankBalance())) >= imbuingPrice then
        sendImbuementError(self, "You don't have enough money " ..imbuingPrice.. " gps.", ErrorMessages.MESSAGEDIALOG_IMBUEMENT_ROLL_FAILED)
        return false
    end
	self:removeMoneyNpc(imbuingPrice)
```

**Comment by Tekadon58** [comment]
Deu erro

Lua Script Error: [Modules Interface]
data/modules/scripts/imbuement/imbuement.lua:onRecvbyte
data/modules/scripts/imbuement/imbuement.lua:268: attempt to compare number with boolean
stack traceback:
        [C]: in function '__le'
        data/modules/scripts/imbuement/imbuement.lua:268: in function 'applyImbuement'
        data/modules/scripts/imbuement/imbuement.lua:111: in function <data/modules/scripts/imbuement/imbuement.lua:108>

Lua Script Error: [Modules Interface]
data/modules/scripts/imbuement/imbuement.lua:onRecvbyte
data/modules/scripts/imbuement/imbuement.lua:268: attempt to compare number with boolean
stack traceback:
        [C]: in function '__le'
        data/modules/scripts/imbuement/imbuement.lua:268: in function 'applyImbuement'
        data/modules/scripts/imbuement/imbuement.lua:111: in function <data/modules/scripts/imbuement/imbuement.lua:108>

**Comment by joseluis2g** [comment]
ups my bad
```lua
if not (self:getMoney() + self:getBankBalance() >= imbuingPrice) then
        sendImbuementError(self, "You don't have enough money " ..imbuingPrice.. " gps.", ErrorMessages.MESSAGEDIALOG_IMBUEMENT_ROLL_FAILED)
        return false
    end
self:removeMoneyNpc(imbuingPrice)
```

**Comment by Tekadon58** [comment]
Continua a mesma coisa.
Gasta o dinheiro os itens mais não melhora o item principal

**Comment by joseluis2g** [comment]
you added all the things? here is working as intented.

**Comment by Tekadon58** [comment]
Manda o seu ai man

**Comment by Tekadon58** [comment]
Manda o seu ai man o seu imbuement.lua pf

**Comment by joseluis2g** [comment]
https://hastebin.com/enewumujoc.lua
btw I removed the shrines part cus im not working with rl map I dont know how it works so that...

**Comment by Tekadon58** [comment]
Ele diz que funciona mais na hora o slot continua mostrando que está vazio

**Comment by Eternal-Scripts** [comment]
Creio eu que o BUG esteja nas funções setSpecialAttribute & getSpecialAttribute, estarei verificando.

**Comment by Tekadon58** [comment]
Agora o sistema funciona porem na hora de dar look no item aparece um erro 

Lua Script Error: [Event Interface]
data/events/scripts/player.lua:Player@onLook
data/events/scripts/player.lua:32: attempt to call global 'getTime' (a nil value)
stack traceback:
        [C]: in function 'getTime'
        data/events/scripts/player.lua:32: in function <data/events/scripts/player.lua:13>

**Comment by Schiffers** [comment]
aqui o código que o joseluis2g mandou funciona, porém, não aplica no item, ele diz que aplicou, mas no look não aparece o imbuement

**Comment by joseluis2g** [comment]
you guys must edit player event too, show that file

**Comment by Schiffers** [comment]
**************************
               local itemType = thing:getType()
 			if (itemType and itemType:getImbuingSlots() > 0) then
 				local imbuingSlots = "Imbuements: ("
 				for i = 1, itemType:getImbuingSlots() do
 					local specialAttr = thing:getSpecialAttribute(i)
 					local time = 0
 					if (thing:getSpecialAttribute(i+3)) then
 						time = getTime(thing:getSpecialAttribute(i+3))
 					end
 					
 					if (specialAttr and specialAttr ~= 0) then
 						if (i ~= itemType:getImbuingSlots()) then
 							imbuingSlots = imbuingSlots.. "" ..specialAttr.." " ..time..", "
 						else
 							imbuingSlots = imbuingSlots.. "" ..specialAttr.." " ..time..")."
 						end
 					else
 						if (i ~= itemType:getImbuingSlots()) then
 							imbuingSlots = imbuingSlots.. "Empty Slot, "
 						else
 							imbuingSlots = imbuingSlots.. "Empty Slot)."
 						end
 					end
 				end
 				description = string.gsub(description, "It weighs", imbuingSlots.. "\nIt weighs")
 			end
*****************************

**Comment by Tekadon58** [comment]
Conseguiram resolver ?

**Comment by Schiffers** [comment]
nada ainda, amigo, vamos usar o inglês como linguagem principal assim outras pessoas poderão entender o que nós conversamos/resolvemos e também mantemos um padrão de linguagem...
english version:
nothing yet, friend, lets go use the english as main language, another people will understand what we talk/resolve and we will have a standard language

**Comment by joseluis2g** [comment]
Ok was taking a shower and thinking on it and this is my solution, to create a new decay type that checks if item got imbuing slots and if got time left, with that we can easily add attributes to the imbuiment items that will only work when you got it equipped and will stop working when time is over or when you deequip it.
