### ISSUE TITLE
CRYSTAL WAND QUEST

### ISSUE THREAD

**Issue by sn4tch0vsk** [malucooo/Otxserver-New#159]
CURRENT: 3 warlocks and 4 dragons in the final room
                 Reward: 1 chest (ID 9144) Crystal Wand
                               2 chest (ID 9143) 6 sudden death runes

FIX: 4 warlocks and 5 dragons in the final room
       Reward: 1 chest (ID 9144) Crystal Wand
                     2 chest (ID 9143) A bag with Silver Rune emblem and a Parchment

Position: 32480, 31613, 15

Source: http://tibia.wikia.com/wiki/Crystal_Wand_Quest

**Comment by malucooo** [comment]
fixed!
