### ISSUE TITLE
Cliente 11

### ISSUE THREAD

**Issue by Tekadon58** [malucooo/Otxserver-New#160]
Eu acabei de notar que ouve uma mudança na versão do cliente.

Esse cliente 11 que está mostrando agora no config.lua é um cliente especifico ou posso baixar o direto da Cipsoft ?

**Comment by Eternal-Scripts** [comment]
Eu mudei o protocolo por que 1200 não é existente, portanto o Servidor só é compatível com a primeira versão do Cliente 11 (11.00).

O atual tibia rl está na versão 11.30.

**Comment by Tekadon58** [comment]
Sabe como poderia eu poderia encontrar o tibia na versão 11.00 ? Estou procurando no google neste momento e não encontro ele na primeira versão do 11

**Comment by Tekadon58** [comment]
Todos mandam atualizar ou mandam baixar pelo servidor da Cip e acaba que não funciona

**Comment by Tekadon58** [comment]
http://prntscr.com/fbxex5

**Comment by Eternal-Scripts** [comment]
O jeito é esperar alguém que tenha.
Talvez @malucooo possa ter.

**Comment by Tekadon58** [comment]
Achei o cliente porem o ipcharge não pega nele
Ja compilei o ipcharge 11.00 mais nn funcionou

**Comment by Tekadon58** [comment]
http://www.tibiaking.com/forum/uploads/monthly_2017_05/Screenshot_18.thumb.png.8fbfc9f2fe5602b32002e5a9e52a9760.png

**Comment by Tekadon58** [comment]
o Cliente 11 que estou usando é o 11.01

https://mega.nz/#!oE4E0TgZ!UvVsG2G8ZgaXilrQJO0XHyL8rCXHS_Wt61qjftuM-Bc

ai

**Comment by Tekadon58** [comment]
@Eternal-Scripts
