### ISSUE TITLE
Prey System - Structure & probably need remake

### ISSUE THREAD

**Issue by Eternal-Scripts** [malucooo/Otxserver-New#161]
Only creating this issue to remember, the prey system is missing bytes to make a functional system.

State Types
STATE_LOCKED = 0
STATE_INACTIVE = 1
STATE_ACTIVE = 2
STATE_SELECTION = 3
STATE_SELECTION_CHANGE_MONSTER = 4

Unlock Types
UNLOCK_PREMIUM_OR_STORE = 0
UNLOCK_STORE = 1
UNLOCK_NONE = 2

PreyData structure (server to client)
byte (232) -> head byte (sendPreyData)
byte (column)
byte (StateTypes)

Conditions
StateLocked => changeStateToLocked(column, UNLOCKTYPE)

StateInactive => changeStateToInactive(column)

StateActive \/
string (monsterName)
ReadOutfit (all info)
byte (bonusType)
short (bonusValue)
byte (bonusGrade)
changeStateToActive(column,bonusType,bonusValue,bonusGrade, monsterInfo(monsterName, outfit))

StateSelection \/
byte (columnLength)
for i = 0, columnLength-1 do (-1 because start from 0) ej. length = 9 (9 elements) -1 => 0 ~ 8
   string (mName)
   ReadOutfit (all info)
end

changeStateToSelection(column, forLoopMonsterVector (all monsters index bla))
StateSelectionChangeMonster
byte (bonusType)
short (bonusValue)
byte (bonusGrade)
byte (columnLength) (maybe?)
for i = 0, columnLength-1 do (same here -1)
    string (monsterName)
    ReadOutfit (all info)
end
changeStateToSelectionChangeMonster(column,bonusType,bonusValue,bonusGrade,forLoopMonsterVector)

after all conditions he send the timeUntilFreeListReroll, anyway, all this conditions (if / elseif / else) are inside of a loop from 0, to 2 (column numbers) or 1, to 3 xD

setTimeUntilFreeListReroll(column,shortValue (time free reroll))

I create this issue because i think is missing these conditions (idk) anyway, if anyone can make that is become helpful

**Comment by joseluis2g** [comment]
nice information, this also got it detailed if someone do not know
```
      protected function readSPREYDATA(param1:ByteArray) : void
      {
         var _loc2_:PreyManager = null;
         var _loc3_:uint = 0;
         var _loc4_:uint = 0;
         var _loc5_:String = null;
         var _loc6_:AppearanceInstance = null;
         var _loc7_:uint = 0;
         var _loc8_:uint = 0;
         var _loc9_:uint = 0;
         var _loc10_:uint = 0;
         var _loc11_:Vector.<PreyMonsterInformation> = null;
         var _loc12_:uint = 0;
         _loc2_ = PreyManager.getInstance();
         _loc3_ = param1.readUnsignedByte();
         _loc4_ = param1.readUnsignedByte();
         if(_loc4_ == PreyData.STATE_LOCKED)
         {
            _loc2_.changeStateToLocked(_loc3_,param1.readUnsignedByte());
         }
         else if(_loc4_ == PreyData.STATE_INACTIVE)
         {
            _loc2_.changeStateToInactive(_loc3_);
         }
         else if(_loc4_ == PreyData.STATE_ACTIVE)
         {
            _loc5_ = StringHelper.s_ReadLongStringFromByteArray(param1);
            _loc6_ = this.readCreatureOutfit(param1,null);
            _loc7_ = param1.readUnsignedByte();
            _loc8_ = param1.readUnsignedShort();
            _loc9_ = param1.readUnsignedByte();
            _loc2_.changeStateToActive(_loc3_,_loc7_,_loc8_,_loc9_,new PreyMonsterInformation(_loc5_,_loc6_));
            _loc2_.setPreyTimeLeft(_loc3_,param1.readUnsignedShort());
         }
         else if(_loc4_ == PreyData.STATE_SELECTION)
         {
            _loc10_ = param1.readUnsignedByte();
            _loc11_ = new Vector.<PreyMonsterInformation>();
            _loc12_ = 0;
            while(_loc12_ < _loc10_)
            {
               _loc5_ = StringHelper.s_ReadLongStringFromByteArray(param1);
               _loc6_ = this.readCreatureOutfit(param1,null);
               _loc11_.push(new PreyMonsterInformation(_loc5_,_loc6_));
               _loc12_++;
            }
            _loc2_.changeStateToSelection(_loc3_,_loc11_);
         }
         else if(_loc4_ == PreyData.STATE_SELECTION_CHANGE_MONSTER)
         {
            _loc7_ = param1.readUnsignedByte();
            _loc8_ = param1.readUnsignedShort();
            _loc9_ = param1.readUnsignedByte();
            _loc10_ = param1.readUnsignedByte();
            _loc11_ = new Vector.<PreyMonsterInformation>();
            _loc12_ = 0;
            while(_loc12_ < _loc10_)
            {
               _loc5_ = StringHelper.s_ReadLongStringFromByteArray(param1);
               _loc6_ = this.readCreatureOutfit(param1,null);
               _loc11_.push(new PreyMonsterInformation(_loc5_,_loc6_));
               _loc12_++;
            }
            _loc2_.changeStateToSelectionChangeMonster(_loc3_,_loc7_,_loc8_,_loc9_,_loc11_);
         }
         _loc2_.setTimeUntilFreeListReroll(_loc3_,param1.readUnsignedShort());
}
```

**Comment by Eternal-Scripts** [comment]
yes, i forgot add this code from flash client, in my issue i detailed the variables and functions xd
