### ISSUE TITLE
DEMONA RING QUEST

### ISSUE THREAD

**Issue by sn4tch0vsk** [malucooo/Otxserver-New#163]
Missing both rings in the quest. (Energy ring and stealth ring)

Chests are there, but no actionID

Position: 32509, 31595, 14

**Comment by GoularPink** [comment]
onde tem essa quest no tibia wiki?

**Comment by sn4tch0vsk** [comment]
http://tibia.wikia.com/wiki/Demona_Ring_Quest

**Comment by malucooo** [comment]
fixed!
