### ISSUE TITLE
[BUG]Searing fire

### ISSUE THREAD

**Issue by helli3** [malucooo/Otxserver-New#165]
> You see a searing fire.
> Item ID: 7466
> Position: 32830, 32337, 11
> 

PPL can push this fire from gates poi :)

**Comment by Eternal-Scripts** [comment]
@malucooo Qual a versão do cliente que usa no items.otb? preciso saber para poder gerencia-lo.

**Comment by flaviiojr** [comment]
É a última versão do tibia

**Comment by darkjav** [comment]
I think that the solution is with a action id, that should not allowed move the fire to another position.

**Comment by helli3** [comment]
@darkjav You are wrong. You dont need action ad. When you are using item field type it should be instantly unmovable :)

**Comment by GoularPink** [comment]
nos **events>player.lua**

function Player:onMoveItem(item, count, fromPosition, toPosition, fromCylinder, toCylinder)

if item:getId() == 7466 then 
            self:sendCancelMessage('Sorry, not possible.')
			self:getPosition():sendMagicEffect(CONST_ME_POFF)
            return false
        end

**Comment by malucooo** [comment]
make a pull request...
