### ISSUE TITLE
Erro ao se conectar com o cliente 11

### ISSUE THREAD

**Issue by Tekadon58** [malucooo/Otxserver-New#166]
Eu to tentando me conectar usando o cliente 11 porem ele só abre ate a lista de personagens mais não consegue entrar no mundo.

Suspeito eu que seja algo ou no login.php ou no próprio servidor 

Login.php

`<?php
	if($_SERVER['HTTP_USER_AGENT'] == "Mozilla/5.0") {
		@error_reporting(0);
		@ini_set('display_errors', 'Off');
		header("Content-Type: application/json");

		$loginInfo = json_decode(file_get_contents("php://input"));
		$accountName = $loginInfo->{"accountname"};
		$password = $loginInfo->{"password"};

		if($accountName == "" || $password == "") {
			die('{"errorCode":3,"errorMessage":"Account name or password is incorrect."}');
		}

		$MySQL_Host = "127.0.0.1";
		$MySQL_User = "root";
		$MySQL_Password = "123456";
		$MySQL_DB = "global";

		$SQL = new mysqli($MySQL_Host, $MySQL_User, $MySQL_Password, $MySQL_DB);

		if(mysqli_connect_error()) {
			die('{"errorCode":3,"errorMessage":"Internal error. Please try again later or contact customer support if the problem persists."}');
		}

		$AccountQuery = $SQL->query("SELECT * FROM `accounts` WHERE `name` = '".$SQL->real_escape_string($accountName)."' AND `password` = '".SHA1($SQL->real_escape_string($password))."'")->fetch_array(MYSQLI_ASSOC);
		if($AccountQuery["name"] != $accountName) {
			die('{"errorCode":3,"errorMessage":"Account name or password is incorrect."}');
		}

		$AccountID = $AccountQuery["id"];
		$Secret = $AccountQuery["secret"];
		$Premdays = $AccountQuery["premdays"];

		$CharacterQuery = $SQL->query("SELECT `name` FROM `players` WHERE `account_id` = '".$AccountID."'")->fetch_all(MYSQLI_ASSOC);

		$worldID = 0;
		$worldName = "Tibia11 Server";
		$serverAddress = $_SERVER["127.0.0.1"];
		$serverPort = 7172;
		$freePremium = false;

		echo '{"session":{"sessionkey":"'.$accountName.'\n'.$password.'\n'.$secret.'\n'.(floor(time() / 30)).'","lastlogintime":0,"ispremium":'.($Premdays > 0 || $freePremium ? "true" : "false").',"premiumuntil":'.($freePremium ? "0" : time() + ($Premdays * 86400)).',"status":"active"},"playdata":{"worlds":[{"id":'.$worldID.',"name":"'.$worldName.'","externaladdress":"'.$serverAddress.'","externalport":'.$serverPort.',"previewstate":0}],"characters":[';
		foreach($CharacterQuery as $Character) {
			if($Character != $CharacterQuery[0]) {
				echo ',';
			}
			echo '{"worldid":'.$worldID.',"name":"'.$Character["name"].'"}';
		}
		echo ']}}';
	return;
	}
?>`

**Comment by Schiffers** [comment]
bro, could you provide the full code of login.php ? I guess that have something related with connection.cpp

**Comment by Tekadon58** [comment]
okay

@Schiffers https://pastebin.com/0muVxFin

**Comment by Tekadon58** [comment]
Esse é o erro que não conecta:

http://prntscr.com/fcif1i


Desculpa postar em português é que não sei inglês e quando faço a tradução perde o sentido

**Comment by Tekadon58** [comment]
http://prntscr.com/fcijyn

**Comment by Schiffers** [comment]
calma cara, esse seu login.php é do gesior. eu estou usando znote usa o znote acc que te garanto acesso até o cliente 11.02

**Comment by Tekadon58** [comment]
Nossa amigo não sabia que ainda tem isso kkkkk.
To calmo kkkk.

Manda ai esse Znote Acc e esse login.php 

por favor maninho @Schiffers

**Comment by Schiffers** [comment]
https://github.com/Znote/ZnoteAAC
só arrumar o config.php pra o diretório do config do server e os dados pra ele pegar o banco de dados e sucesso

**Comment by Tekadon58** [comment]
@Schiffers Ta dizendo que o protocolo não é compatível com o servidor.

Já mudei no config.lua do servidor e continua a mesma coisa

**Comment by Schiffers** [comment]
cara, então provavelmente vai ter que mexer na source, veja se sua source tem as coisas do authenticator, veja no default TFS
https://github.com/otland/forgottenserver/pull/1603/commits/fc848f09ea992559780f54c3287c7165f0b32829
tinha um post no otland que o znote mesmo ajudou a conseguir logar no client 11
https://otland.net/threads/tibia-client-11-x.247592/

**Comment by Tekadon58** [comment]
Eu vou desistir vei negocio complicado de se fazer to me acabando fazendo essas configurações e corre de um lado e vai para outro já tem 3 dias nessa e ainda não consigo logar no cliente 11.00 e toda hora um bug diferente.

**Comment by Eternal-Scripts** [comment]
O problema está no seu login.php e tem que ver o que o Cliente 11.0 seu manda (output e input em json).

**Comment by Schiffers** [comment]
@Tekadon58 como eu falei, znote acc funciona perfeitamente o login.php
http://imgur.com/eM1UKKB
o problema agora é que o client crasha quando loga, imagino que seja um byte a mais, não sei se essa versão de cliente que você mandou tem os novos bytes, prey e tal ...
gostaria de adicionar vocês no skype, a gente pode resolver coisas em conjunto e mesmo dar algum suporte de vez em quando, o que acham ?
@Eternal-Scripts @Tekadon58 @jlcvp

**Comment by Tekadon58** [comment]
pode ser man.
To ansioso para que venha a versão 11.00, muitos lá fora já tem. Eu dei uma olhada no otserv list e vi uns 15 servidores já com o cliente 11 funcionando perfeitamente 
posta ai o seu skype

**Comment by Tekadon58** [comment]
https://join.skype.com/qpX7Jo4n1YaQ
