### ISSUE TITLE
RME Unsupported Client Version

### ISSUE THREAD

**Issue by jerryb1988** [malucooo/Otxserver-New#167]
RME was included in the previous version of this repo, but now it is not. Where can I get RME that supports the current map?

**Comment by sn4tch0vsk** [comment]
I have the same problem. Can't fix map issues cause of this.

**Comment by jerryb1988** [comment]
RME has client version 10.100 and others on the repo but I can't compile the project without errors

**Comment by Eternal-Scripts** [comment]
Use 10.00 version is stable.
