### ISSUE TITLE
Mecheram no item.otb do  imbuing shrine

### ISSUE THREAD

**Issue by Tekadon58** [malucooo/Otxserver-New#168]
Modificaram a imagem do  imbuing shrine e editaram ela agora está como diferente 
http://prntscr.com/fcjuvk

**Comment by darkjav** [comment]
@Eternal-Scripts @granoob @malucooo I hink that problem is the last edit of item.otb, so not is good idea edit directly the otb, this cause errors.

**Comment by Eternal-Scripts** [comment]
@darkjav yes, its my error sorry. i will revert commit.
