### ISSUE TITLE
Player:onLook(thing, position, distance)

### ISSUE THREAD

**Issue by helli3** [malucooo/Otxserver-New#169]
Player:onLook(thing, position, distance) doesn't work? 

I see all extra informations just on look on battle, like marry status :octopus:  

I deleted it even script from
function Player:onLookInBattleList(creature, distance)
and still the same problem :o:

**Comment by joseluis2g** [comment]
onlook and onlookinbattlelist are different things bro...

**Comment by darkjav** [comment]
@helli3 What you need?

**Comment by helli3** [comment]
Im fighting with marry status on look. On battle it works on normal look nope

**Comment by zexn** [comment]
@darkjav Necesitamos saber porqué solo en el battle podemos ver que está casado, ejemplo: 
` He is married to Zexn.`
Pero en la función OnLook no sale,

**Comment by helli3** [comment]
@joseluis2g  Ye i know that, i have script for 2 of them and all scripts works just on battle :> That the problem ^^

**Comment by darkjav** [comment]
Ok you mean that only work the function Look on the Battle window, so let me check.

**Comment by helli3** [comment]
Ok, i changed something and on look it works but still not that what i want :) im near haha

**Comment by darkjav** [comment]
Not close it, because the bug still there.
