### ISSUE TITLE
ITEMS OTB FAIL

### ISSUE THREAD

**Issue by zexn** [malucooo/Otxserver-New#171]
This is my problem with items otb, i have a new map and new items.otb from malucoo.
http://imgur.com/a/lEzEr

**Comment by Schiffers** [comment]
why do you open threads in otland, tibiaking and here? when everyone tell you what is wrong
??????
the problem is that you edited the map with a different otb, do you can expect that it works with a new otb, so you need to edit your map with the same otb that you're using in the server
