### ISSUE TITLE
Wrong items .otb

### ISSUE THREAD

**Issue by darkjav** [malucooo/Otxserver-New#175]
With the last update to .otb items, that cause errors.
Check image:
![2](https://cloud.githubusercontent.com/assets/9681018/26535464/5d82b356-43f3-11e7-938e-5b2a54fdcd1a.png)

**Comment by flaviiojr** [comment]
The otb has been updated, so the ids have changed, causing this conflict, just modify the ids through the RME

**Comment by darkjav** [comment]
@flaviiojr You can shared the RME.
