### ISSUE TITLE
Alavancas Farmine

### ISSUE THREAD

**Issue by RickSanchez19** [malucooo/otxserver-new#18]
As alavancas para a saída de Farmine não estão funcionando.
Tem que mudar os ActionId com o RME
A alavanca na posição x=33061, y=31527, z=14, tem q colocar o ActionId 9123
A alavanca na posição x=33061, y=31527, z=12, tem q colocar o ActionId 9122
Assim elas vão funcionar e vai ser possivel continuar com a The New Frontier Quest

**Comment by gordonbay** [comment]
A sugestão acima funciona

**Comment by Raphaellb** [comment]
Tem como posta no github o mapa com esses updates feitos? nao tenho access a RME, e gostaria muito se vc pudesse fazer o upload dessa fix.

Obrigado

**Comment by guifagotti** [comment]
ARRUMADO COM O PULL REQUEST #65
