### ISSUE TITLE
Another imbuement error

### ISSUE THREAD

**Issue by darkjav** [malucooo/Otxserver-New#182]
Second error is that after of imbuement item, not is possible Look on the item, error:

Lua Script Error: [Event Interface]
data/events/scripts/player.lua:Player@onLook
data/events/scripts/player.lua:32: attempt to call global 'getTime' (a nil value)
stack traceback:
[C]: in function 'getTime'
data/events/scripts/player.lua:32: in function <data/events/scripts/player.lua:13>

**Comment by joseluis2g** [comment]
@Schiffers hey bro, did you get it working? I mean with my changes and files about the imbuiment equip :)

**Comment by darkjav** [comment]
@Schiffers I use the last version of project, so i test with giant sword, becaus is the only one in items.xml and actions.xml

@joseluis2g WHere ypu put the changes, because i use the last version and not work. Thanks.

**Comment by Schiffers** [comment]
@joseluis2g I resolve the crash from my source, so now I get the chance to test it with calm, lemme try

**Comment by joseluis2g** [comment]
btw what was that?

**Comment by zexn** [comment]
You must check Onlook in player.lua and add attributes with imbuement system.
