### ISSUE TITLE
New items.otb

### ISSUE THREAD

**Issue by helli3** [malucooo/Otxserver-New#186]
22:10 You see large glowing amethyst (Vol:8).
Item ID: 27724.

And it looks like dead body.

Today i will sit down on your items.otb maluco and i will try to fix this  otb with xml version cuz this need to be finished :+1:

**Comment by malucooo** [comment]
thank you for help!

**Comment by helli3** [comment]
@malucooo how can i contact with you because i have question about this items.otb and this old one, cuz before update you had a ~27525 items and now you are using old one without 500 items

**Comment by GoularPink** [comment]
https://mega.nz/#!GNUGDIaK!lYctmSRHrw9s_HmT_83yWMwUPoeF5e8Q_1JC0ErziKw

**Comment by malucooo** [comment]
we gonna fix the items.xml
