### ISSUE TITLE
Movements issue Roshamul

### ISSUE THREAD

**Issue by MxSoft** [malucooo/Otxserver-New#188]
/master/data/movements/scripts/lowerRoshamuul.lua
This scripts lets you go directly to the boss of roshamul by entering a lader in 33552,32546,7

**Comment by luanluciano93** [comment]
Can anyone properly explain what is wrong with this script?

**Comment by darkjav** [comment]
@MxSoft I think that script is fine, because this telelport to random place, same that Rl.
