### ISSUE TITLE
new client?

### ISSUE THREAD

**Issue by newacc12** [malucooo/Otxserver-New#191]
After updating to the latest version and re-downloading the client on the main page I get debug'ed when trying to log in.

Do we have a new client or what?

Thanks

**Comment by darkjav** [comment]
Yes, confirmed.

What client version you use?

**Comment by flaviiojr** [comment]
New client is 10.00d and 11.10

**Comment by darkjav** [comment]
@flaviiojr Where i can download client 11.10?

**Comment by Tazer89** [comment]
Where to get the 10.00d version :)

**Comment by GoularPink** [comment]
where?

**Comment by darkjav** [comment]
Here download:
http://www.mediafire.com/file/571cbbt9cy2y30t/tibia1000.rar
