### ISSUE TITLE
Problems with protocol 11.10

### ISSUE THREAD

**Issue by darkjav** [malucooo/Otxserver-New#192]
I try login with protocol 11.01.4078 and not work, the client crash, days ago was posible.

The fix: https://github.com/malucooo/Otxserver-New/commit/09ea153b391a1bddcaf27d411f699fd1193c364c, not work, i use the last version of project.

And with client 11.21.4812 i get in console the error:
[Network error - Connection::parseHeader] Invalid Client Login

**EDIT:**

@malucooo I get debug when login with client 11.10

The char appear in console, but the client crash.

[DEV] Legendz has logged in.
[DEV] Legendz has logged out.

I use the last version of project.
And i use the client 11 that you upload, also i test with anothers 11.10.xxxx and happen the same.

**Comment by flaviiojr** [comment]
This new protocol is 11.10, and everybody done connect!

**Comment by darkjav** [comment]
@flaviiojr Where i can download client 11.10?

**Comment by darkjav** [comment]
I download client 11.10.4445, with the changes for login.php, and i get:
![whatsapp image 2017-06-11 at 2 06 27 pm](https://user-images.githubusercontent.com/9681018/27013782-625187be-4eb0-11e7-9249-8c264e98c3d6.jpeg)
![whatsapp image 2017-06-11 at 2 08 16 pm](https://user-images.githubusercontent.com/9681018/27013781-6250a3a8-4eb0-11e7-99d0-f026fbafa753.jpeg)

**Comment by newacc12** [comment]
after the last update by @malucooo the client 10 is working again, but client 11 does not.

I can see the character list but as soon as I hit enter on one of the characters the client just closes.

**Comment by mattyx14** [comment]
the problems on connection require rewrite this system

**Comment by extailer** [comment]
[https://www.youtube.com/watch?v=_ok93rqcDQQ&t=50s](url)

mano ae tem tutorial pra pegar serv maluco full

**Comment by mattyx14** [comment]
https://github.com/malucooo/Otxserver-New/commit/55c0031a50296d7584121cccb4aafd74414f8aeb
