### ISSUE TITLE
Casting System is not working as inteed

### ISSUE THREAD

**Issue by westwol** [malucooo/Otxserver-New#198]
The current casting system has a bug that won't allow spectators to see the casting in real time, once the spectator log in the cast, it freezes. This bug can be reproduced using master.

There's a problem with the sync between the caster movements and protocolspectator.

Thanks in advance.

**Comment by darkjav** [comment]
Confirmed.

**Comment by extailer** [comment]
https://youtu.be/nnGf4fspKeo  FIX compiling here tutorial

**Comment by westwol** [comment]
@extailer This issue is not related.

**Comment by Crixpx** [comment]
some solution ?

**Comment by joseluis2g** [comment]
to use a new cast system.

**Comment by darkjav** [comment]
@joseluis2g I think is complicated, because this protocolgamebase have alot custom functions, and TFS not have. 

The other option is fix the current cast system.
Or what you think?

**Comment by westwol** [comment]
I have already fixed this, as soon as I get home I'll try to commit that would address this issue.

Regards,
westwol

**Comment by darkjav** [comment]
@westwol 
Ok bro, thanks.

**Comment by darkjav** [comment]
@westwol 
Hi bro, any news?
I try fix but i not get results :/

**Comment by igorlabanca** [comment]
Has anyone been able to solve the problem?

**Comment by igorlabanca** [comment]
https://github.com/otland/forgottenserver/pull/2230/files/27c85712b0c93a5b6c87e5db9ddb7531e7bb2235
