### ISSUE TITLE
Bug client 11

### ISSUE THREAD

**Issue by GoularPink** [malucooo/Otxserver-New#200]
Oi, estou utilizando um item.otb diferente do de vocês..

Ai sempre em certos sqms como esse em edron na imagem abaixo o client fecha (lá no local não possui **nenhum item novo**).
http://prntscr.com/fkkld5

Error:
http://prntscr.com/fkkkbp

Por que será que o client crasha ? estou utilizando o login.php de voces e o client também!

Client otb atualizado que eu uso:
https://mega.nz/#!GNUGDIaK!lYctmSRHrw9s_HmT_83yWMwUPoeF5e8Q_1JC0ErziKw

-- Se alguém souber e não quiser fazer de graça podemos negociar, preciso fixar isso, amo o client 11!!!

**Comment by mattyx14** [comment]
use items.otb from this Repo

**Comment by Schiffers** [comment]
@GoularPink what acc you're using? gesior or znote?

**Comment by GoularPink** [comment]
@Schiffers  acc gesior, why? you have this issue too?

@mattyx14 if I use items.otb from this repo my map dont load.

**Comment by Schiffers** [comment]
@GoularPink could you share the acc? Well, I ask because I'm using znote, I was thinking that was the acc, but I need to test the gesior to be sure about it

**Comment by darkjav** [comment]
@mattyx14 @GoularPink
I tested and with the items.otb of this project, also happened. And the problem only is with the client 11.10, if you use the client 10 not should have problems. So i think that is necessary update the .otb

**Comment by mattyx14** [comment]
I no tested with client 11 ... I no use gesior acc for. Use login.php

**Comment by GoularPink** [comment]
@mattyx14 I tested with login.php
maybe is the cliente or missing bytes? I think not is the item.otb

**Comment by GoularPink** [comment]
@darkjav  I tested with another item.otb (updated by me) and happened too, dont is otb

**Comment by flaviiojr** [comment]
@GoularPink, manda mensagem pra mim no whatsapp
+5581999982880
te dou um suporte

**Comment by darkjav** [comment]
@flaviiojr Why you not support us here? Because the problem not is only for one. So you can said the ideas or you solution here.

**Comment by malucooo** [comment]
use the client 10 for fully compatibility!
