### ISSUE TITLE
killed after loading map

### ISSUE THREAD

**Issue by adii1111** [malucooo/Otxserver-New#202]
tfs killed after loading map and map size 
`The OTX Server Global - Version: (3.9 . DEV) - Codename: ( OpenTibia )
Compiled with: GNU C++ version 4.9.2
Compiled on Jun 17 2017 15:27:12 for platform x64

A server developed by Matt Gomez, Leandro Brewster, Erick Nunes, João Leonardo Pereira, OTX Contributors and The Forgotten Server Developers.
Visit our forum for updates, support, and resources: https://github.com/mattyx14/otxserver/tree/otxserv3/.

>> Loading config
>> Establishing database connection... MySQL 5.5.55
>> Running database manager
> Optimizing table account_ban_history... [success]
> Optimizing table account_bans... [success]
> Optimizing table account_viplist... [success]
> Optimizing table accounts... [success]
> Optimizing table guild_invites... [success]
> Optimizing table guild_membership... [success]
> Optimizing table guild_ranks... [success]
> Optimizing table guild_wars... [success]
> Optimizing table guilds... [success]
> Optimizing table guildwar_kills... [success]
> Optimizing table house_lists... [success]
> Optimizing table houses... [success]
> Optimizing table ip_bans... [success]
> Optimizing table live_casts... [success]
> Optimizing table market_history... [success]
> Optimizing table market_offers... [success]
> Optimizing table player_deaths... [success]
> Optimizing table player_depotitems... [success]
> Optimizing table player_inboxitems... [success]
> Optimizing table player_items... [success]
> Optimizing table player_kills... [success]
> Optimizing table player_namelocks... [success]
> Optimizing table player_prey... [success]
> Optimizing table player_preytimes... [success]
> Optimizing table player_rewards... [success]
> Optimizing table player_spells... [success]
> Optimizing table player_storage... [success]
> Optimizing table players... [success]
> Optimizing table server_config... [success]
> Optimizing table store_history... [success]
> Optimizing table tile_store... [success]
> Optimizing table znote... [success]
> Optimizing table znote_accounts... [success]
> Optimizing table znote_changelog... [success]
> Optimizing table znote_deleted_characters... [success]
> Optimizing table znote_forum... [success]
> Optimizing table znote_forum_posts... [success]
> Optimizing table znote_forum_threads... [success]
> Optimizing table znote_global_storage... [success]
> Optimizing table znote_guild_wars... [success]
> Optimizing table znote_images... [success]
> Optimizing table znote_news... [success]
> Optimizing table znote_paygol... [success]
> Optimizing table znote_paypal... [success]
> Optimizing table znote_player_reports... [success]
> Optimizing table znote_players... [success]
> Optimizing table znote_shop... [success]
> Optimizing table znote_shop_logs... [success]
> Optimizing table znote_shop_orders... [success]
> Optimizing table znote_tickets... [success]
> Optimizing table znote_tickets_replies... [success]
> Optimizing table znote_visitors... [success]
> Optimizing table znote_visitors_details... [success]
>> Loading vocations
>> Loading items
>> Loading script systems
>> Loading monsters
>> Loading outfits
>> Checking world type... PVP
>> Loading map
> Map size: 34143x33812.
Killed
`
any idea why?

**Comment by Schiffers** [comment]
probably an item that couldn't be created! check your otb and map

**Comment by adii1111** [comment]
solved vps problem

**Comment by Schiffers** [comment]
are you sure that the character is GOD... god != gamemaster or tutor

**Comment by adii1111** [comment]
group_id on 1 char set to 5 - got next char have id set to 4 -gm and cant use only /i and /m

**Comment by adii1111** [comment]
nvm im drunk sorry
