### ISSUE TITLE
Ferumbras' Ascension Quest missing map

### ISSUE THREAD

**Issue by darkjav** [malucooo/Otxserver-New#203]
The area of Ferumbras' Ascension Quest not exist, and in old projects of @malucooo was there.

![asc](https://user-images.githubusercontent.com/9681018/27255302-2938ebce-5361-11e7-9294-8f1ce1758f92.png)

In this position: 33278, 32392, 8. must have a teleport that take you to position: 33292, 31453, 12.

But not exist nothing there.

**Comment by Andreeyyy** [comment]
Will Verify ;) Ty
