### ISSUE TITLE
Znote AAC Client 11 loginWebService compatibility

### ISSUE THREAD

**Issue by Znote** [malucooo/Otxserver-New#208]
Znote AAC should support Client 11 loginWebService if you configure it directly to the domain home url, index.php or login.php (either should work). 

It will load this piece of code:
https://github.com/Znote/ZnoteAAC/blob/master/login.php#L5-L88

I tested this on an early beta version of client 11, not 100% sure if it works properly on this version. Would be great if any of you who has gotten it to work through other means try it out with Znote AAC.

**Comment by mattyx14** [comment]
for the actual version no work @Znote :(

**Comment by Znote** [comment]
What json message does the client send to the server, and what json message does it expect in return?

**Comment by malucooo** [comment]
use gesior or make ur login compatible...

**Comment by Znote** [comment]
This is a sample of how it currently works (with the client in download):

Client 11 sends:
```json
{
	"accountname": "testing",
	"password": "testing",
	"stayloggedin": true,
	"type": "login"
}
```

Znote AAC responds:
```json
{
	"session": {
		"sessionkey": "testing\ntesting\n\n49933322",
		"lastlogintime": 0,
		"ispremium": false,
		"premiumuntil": 1497999670,
		"status": "active"
	},
	"playdata": {
		"worlds": [{
			"id": 0,
			"name": "OTserv",
			"externaladdress": "192.168.0.100",
			"externalport": 7172,
			"previewstate": 0
		}],
		"characters": [{
			"worldid": 0,
			"name": "Testing"
		}]
	}
}
```

Is there something missing from this response?

**Comment by mattyx14** [comment]
Are on main readme 
http ://www.mediafire.com/file/2jbauphk3eksm14/login.php

**Comment by gonsandia** [comment]
im using Znote with last login patch and the recomended tibia 11 client and i cant login

**Comment by Znote** [comment]
@gonsandia Remember to not open up regular tibia file, but the client.exe file in tibia/packages/Tibia/bin/ folder.

**Comment by gonsandia** [comment]
Only allowed http://127.0.0.1/login.php ?? I changed client to my ip and done all the other steps. I can connect with client 10.
With client 11 I can enter and see my character login box but when i presh ok, i see the message conecting to the game world but it never finish to login.

**Comment by Znote** [comment]
@gonsandia Ahh yeah sorry. 
You also need to modify this:
```php
	$config['gameserver'] = array(
		'ip' => $_SERVER["SERVER_ADDR"], // Can be an ip string like '123.123.123.123'
		'port' => 7172,
		'name' => 'OTserv'
	);
```
The name must be identical to OT server config.lua (name = OTXServer-Global by default )

**Comment by gonsandia** [comment]
The name must be identical to OT server config.lua (name = OTXServer-Global by default ) it was the key.
Ty for ur help :)
