### ISSUE TITLE
Problema ACC GOD

### ISSUE THREAD

**Issue by gusbossini** [malucooo/Otxserver-New#209]
Eu tinha uma database do TFS 1.3 com o site Znote AAC, fiz o build do server, tudo perfeito, servidor rodando perfeitamente, porém a conta do GOD que antes funcionava não funciona mais.
Querys SQL:
UPDATE accounts SET type = 6 WHERE id =1;
UPDATE players SET group_id = 3 WHERE id =1;

![image](https://user-images.githubusercontent.com/12719902/27310582-b313c590-5531-11e7-9b73-82c7f7092260.png)

**Comment by Schiffers** [comment]
vei, cê tem que fazer isso com o char logado, aqui funciona quando eu troco direto no phpmyadmin...

**Comment by westwol** [comment]
Try setting account type = 5

**Comment by gusbossini** [comment]
@westwol already tried but nothing changed.

**Comment by Eternal-Scripts** [comment]
(Accounts) type = 5
(Players) group_id = 5

Efetue isso com o Char offline, após aplicado as mudanças tente logar e veja se mudou.
`Funcional com o repositório oficial sem nenhuma mudança`
