### ISSUE TITLE
Atributos armas distance

### ISSUE THREAD

**Issue by GoularPink** [malucooo/Otxserver-New#211]
não ta aparecendo o atributo +3 de distance, mas ele está dando os 3 de distance normalmente, só n aparece.

21:26 You see a umbral master crossbow (Range:5, Atk+9, Hit%+4).
It can only be wielded properly by players of level 250 or higher.
It weighs 120.00 oz.
Item ID: 22421.

**Comment by Dyablots** [comment]
This issue is only with you, change your item id 22421 in items.xml:

```
<item id="22421" article="a" name="umbral master crossbow">
		<attribute key="weight" value="12000" />
		<attribute key="slotType" value="two-handed" />
		<attribute key="weaponType" value="distance" />
		<attribute key="ammoType" value="bolt" />
		<attribute key="range" value="5" />
		<attribute key="hitChance" value="4" />
		<attribute key="skillDist" value="3" />
		<attribute key="attack" value="9" />
		
	</item>
```

**Comment by Eternal-Scripts** [comment]
`<attribute key="showattributes" value="1" />`

**Comment by GoularPink** [comment]
<attribute key="showattributes" value="1" />

não adianta isso ai nao.. :1234:

**Comment by malucooo** [comment]
working fine here!
