### ISSUE TITLE
bug coal basin

### ISSUE THREAD

**Issue by GoularPink** [malucooo/Otxserver-New#212]
https://github.com/malucooo/Otxserver-New/blob/master/data/movements/scripts/others/tombCoalBasin.lua

ta errado, o certo é jogar no coal e o player entrar, se jogar e o player nao estiver em cima o scarab coin ta sumindo

**Comment by flaviiojr** [comment]
Fique a vontade pra corrigir pra nós :D
Só vejo você pedindo e pedindo ¬¬
