### ISSUE TITLE
bug Trap

### ISSUE THREAD

**Issue by GoularPink** [malucooo/Otxserver-New#213]
não ta dando hit nos players:

http://tibiawiki.com.br/wiki/Trap

**Comment by gantit** [comment]
check this line in ur code [trap.lua](https://github.com/malucooo/Otxserver-New/blob/master/data/movements/scripts/trap.lua#L4) you must have it disabled. If I do not recommend you change it or update your code.

**Comment by luanluciano93** [comment]
Como esta seu script trap.lua?

**Comment by GoularPink** [comment]
Ta assim mesmo igual o cara ai disse, eu fui e deixei true

https://github.com/malucooo/Otxserver-New/blob/master/data/movements/scripts/trap.lua#L4

tem problema?
