### ISSUE TITLE
Bug itens trade client 11

### ISSUE THREAD

**Issue by GoularPink** [malucooo/Otxserver-New#217]
Valores altamente absurdos quando abre trade com alguns npcs (npc da imagem é o yasir):

http://prntscr.com/fmnwof

obs. somente com o cliente 11.

**Comment by Eternal-Scripts** [comment]
Essa referência não tem relação nenhuma com o cap, o que falta mesmo é um byte importante tanto pro prey quanto pro trade do NPC.

**Comment by joseluis2g** [comment]
@Eternal-Scripts could you enlight me? maybe some links? :)

**Comment by GoularPink** [comment]
@Eternal-Scripts  blz, poderia ajudar com os bytes?
