### ISSUE TITLE
Bug cap client 11

### ISSUE THREAD

**Issue by GoularPink** [malucooo/Otxserver-New#218]
Olha a cap que aparece no client 11, testando com o char GOD:

http://prntscr.com/fmnx8u

obs. não deu pra eu testar com char normal, pois o client 11 está aparecendo somente 1 char na account, tenho 7 char na account e só aparece UM dos god.

**Comment by Schiffers** [comment]
velho, para de reportar coisa que é normal, é óbvio que vai estar essa cap pra um player god, porque ele tem a cap máxima, o numero que aparece ai é o numero maximo....

**Comment by GoularPink** [comment]
Tem razão, não havia testado com player normal, porém o valor dos itens estão errados mesmo: 
https://github.com/malucooo/Otxserver-New/issues/217
