### ISSUE TITLE
Client 11 buga com novas mounts

### ISSUE THREAD

**Issue by GoularPink** [malucooo/Otxserver-New#219]
Client 11 Compativel (http://www.mediafire.com/file/x0q6exqko4y7gvn/Tibia_11.10.rar)

esse cliente ai não aceita as novas montarias, lagoon~ eu baixe um cliente do gunzot e consigo entrar na lista de personagens e dali não passa, alguém fixa pela mor <3 

deve ta faltando bytes, ou poderia haver um jeito de colocar somente os sprits dos novos items, mounts, etc

**Comment by joseluis2g** [comment]
Gunzino and me already linked to the missing bytes, we are not doing the job for you.

**Comment by GoularPink** [comment]
Amigo, acho que faltou interpretação.
Eu disse que o cliente disponível aqui no repositório que é o 11.10 não aceita as montarias novas que também tem aqui no repositório.
Os bytes que voce disse:

 if (version >= 1110) {
 		msg.addByte(0x00);
 	}

Só serve pra cliente 11.10, não os atualizados.
Ninguém ta pedindo serviço particular aqui, só estou citando os bugs que o repositório aqui contém.

**Comment by joseluis2g** [comment]
thats not what I said

**Comment by Eternal-Scripts** [comment]
Se só serve para Cliente 11.10 obviamente não vai funcionar outra versão maior, portanto isso não é um issue. Apenas aguarde alguém atualizar ou faça você mesmo.
