### ISSUE TITLE
Reward chest

### ISSUE THREAD

**Issue by gonsandia** [malucooo/Otxserver-New#220]
Im trying the reward chest system:
- If the monster dont have the reward flag give normal loot
- If have the flag give always nothing as a reward and create a empty reward bag. (sometimes it gave me 20 gold)

**Comment by gonsandia** [comment]
I found the bug is because this commit https://github.com/malucooo/Otxserver-New/commit/797d04b68c8c8baa487d010e342b7e58e540df0a

**Comment by Schiffers** [comment]
so, make the pr that revert these change, and close this issue, also OFCOURSE that the monster will give normal loot without the flag in the monsters.xml

**Comment by jlcvp** [comment]
fixed in [20cb202](https://github.com/malucooo/Otxserver-New/commit/20cb202d45d6654b8880716c1261301e200a9ca5)
