### ISSUE TITLE
Battlefield outfit

### ISSUE THREAD

**Issue by GoularPink** [malucooo/Otxserver-New#221]
um bugzinho... quando sai do battlefield o outfit não é removido.

https://github.com/malucooo/Otxserver-New/blob/master/data/lib/events/battlefield.lua

tinha que remover igual ao capture the flag

**Comment by joseluis2g** [comment]
just add a condition also you can use the same function, then check on change outfit event if he could change his outfit while hes on  the event and done.

**Comment by luanluciano93** [comment]
Depois que sai do evento você não consegue mudar o outfit?
