### ISSUE TITLE
Skill fishing 

### ISSUE THREAD

**Issue by GoularPink** [malucooo/Otxserver-New#225]
O skill se passar de 25, quando o char loga volta pro 10

bug estranho, tentei achar e nao consegui ver o error

**Comment by GoularPink** [comment]
@mattyx14

**Comment by GoularPink** [comment]
@Eternal-Scripts

**Comment by darkjav** [comment]
Confirmed

**Comment by GoularPink** [comment]
@Eternal-Scripts

**Comment by Eternal-Scripts** [comment]
Inválido, acabei de testar.
![screenshot_9](https://user-images.githubusercontent.com/20959344/28397189-6cad5f00-6cd6-11e7-8050-2d4829d560ef.png)
