### ISSUE TITLE
NPC Eremo when buy bless Solitude

### ISSUE THREAD

**Issue by Andreeyyy** [malucooo/Otxserver-New#226]
Lua Script Error: [Npc interface]
data/npc/scripts/Eremo.lua:onCreatureSay
data/npc/lib/npcsystem/customModules.lua:219: attempt to compare number with string
stack traceback:
        [C]: in function '__lt'
        data/npc/lib/npcsystem/customModules.lua:219: in function 'removeMoneyNpc'
        data/npc/lib/npcsystem/modules.lua:168: in function 'callback'
        data/npc/lib/npcsystem/keywordhandler.lua:31: in function 'processMessage'
        data/npc/lib/npcsystem/keywordhandler.lua:186: in function 'processNodeMessage'
        data/npc/lib/npcsystem/keywordhandler.lua:154: in function 'processMessage'
        data/npc/lib/npcsystem/npchandler.lua:428: in function 'onCreatureSay'
        data/npc/scripts/Eremo.lua:7: in function <data/npc/scripts/Eremo.lua:7>

**Comment by malucooo** [comment]
Fixed in last commit
