### ISSUE TITLE
Boss Terofar (Prison silver key)

### ISSUE THREAD

**Issue by christxx** [malucooo/Otxserver-New#228]
Hi,
Today I've tested roshamuul spawns, bosses, gaz'haragoth etc and I found that boss Terofar is bugged (wrong creature spawning) against [Terofar](http://tibia.wikia.com/wiki/Terofar) there is spawning rabbit xD (screen above)
http://imgur.com/a/FRpf6
Which file should I update/change to fix this issue?
Cheers

**Comment by joseluis2g** [comment]
updating the monsters?

**Comment by christxx** [comment]
Can you precise what files? There is a lot files called "monsters" with different file extensions like .cpp .h .lua etc (I'm newbie)

**Comment by gantit** [comment]
I leave a proposal for improvement but it is necessary to add the items

**Comment by christxx** [comment]
Thanks @gantit :)
I have added code to loot
[terofar.xml](https://pastebin.com/1P0pYsxU)
