### ISSUE TITLE
Twist of Fate bug with NPCs

### ISSUE THREAD

**Issue by christxx** [malucooo/Otxserver-New#231]
Hi there,
When I am trying to buy Twist of Fate blessing in temple with NPCs there is a some errors (just like at screenshot)
![image](https://user-images.githubusercontent.com/29754758/27686681-25277998-5cd4-11e7-89d5-47434d849f68.png)
Tried to buy twist of fate with NPCs like Lorietta, Amanda, Quentin, Alia.
Any ideas how to fix this?
Cheers

**Comment by christxx** [comment]
I checked the code Otxserver-New-master\data\npc\lib\npcsystem\customModules.lua
line 219
` if amount > (moneyCount + bankCount) then`
variables moneyCount and bankCount are local, but I am thinking about variable amount, any ideas how to describe this var?

**Comment by malucooo** [comment]
Fixed in last commit
