### ISSUE TITLE
XP Gain Rate cosmic Value (60000%)

### ISSUE THREAD

**Issue by christxx** [malucooo/Otxserver-New#234]
Hey, 
There is an issue with XP Gain Rate - above 40 hours of stamina (green stamina) XP Gain Rate should be increased to 150%, by default there is 100% like at the screenshot below. 
http://imgur.com/a/TOSF4

**Comment by christxx** [comment]
There is another issue with XP Gain rate - value is too big, look at this
http://imgur.com/PXKHYn8

**Comment by christxx** [comment]
I found solution to fix XP Gain rate with stamina above 40 hours, solution is to change code in file \Otxserver-New-master\src\player.h
> uint16_t staminaXpBoost = 100;
> uint16_t staminaXpBoost = 150;
[img]http://imgur.com/a/flvaE[/img]

But there is still issue, when player get level then XP Gain rate at green stamina is changing to big value, just like screenshot above changed from 150% (normal rate green stamina) to 60000% 
[img]http://imgur.com/a/gxHg9[/img]

**Comment by darkjav** [comment]
Confirmed.

**Comment by christxx** [comment]
I think this issue is coming by stages.xml because exp stage from 8 to 50 level gain rate is x400, by calculating happy hour (150%) x 400 sum equal 60000%.

**Comment by malucooo** [comment]
isn't a bug... is based in your xp stages

**Comment by christxx** [comment]
ok then can you tell @malucooo  how to disabble this? This shouldn't show 60000%, its look so bad

**Comment by jlcvp** [comment]
@christxx this may look bad for you but it's the ACTUAL VALUE. 

60 000% means you have a 600x multiplier active in your current exp stage.

**Comment by christxx** [comment]
@jlcvp okey I got it, thanks :)
