### ISSUE TITLE
Erro compilation

### ISSUE THREAD

**Issue by zarkank** [malucooo/Otxserver-New#236]
Hello
Could you help me with this error?
I checked all the paths and everything is correct: /
Help please

1>------ Compilação iniciada: Projeto: theforgottenserver, Configuração: Release x64 ------
1>otpch.cpp
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.10.25017\include\crtdefs.h(10): fatal error C1083: Não é possível abrir arquivo incluir: 'corecrt.h': No such file or directory
1>Projeto de compilação pronto "theforgottenserver.vcxproj" -- FALHA.
========== Compilar: 0 com êxito, 1 com falha, 0 atualizados, 0 ignorados ==========

**Comment by christxx** [comment]
Compile with MS Visual Studio 2015 bro, it helped me

**Comment by zarkank** [comment]
Solved 
s2
