### ISSUE TITLE
Missing item from box [roshamuul]

### ISSUE THREAD

**Issue by christxx** [malucooo/Otxserver-New#238]
Hey,
There is missing item after clicking box on rosha, after click player should get a mouthpiece for a horn.
http://imgur.com/a/n2s88

ID of box: 1738
Pos(X,Y,Z): 33501,32545,7
ID of missing item: 22391
At real Tibia this works that, every player can take from box mouthpiece for a horn once per 24 hours. I couldn't find any tutorial how to make this, so I am posting it here.

**Comment by joseluis2g** [comment]
use forum to this kind of things
```lua
function onUse(player, item, fromPosition, itemEx, toPosition, isHotkey)
	local exhaustion = player:getStorageValue(1231231)
	if os.time() <= exhaustion then
		player:sendCancelMessage("Nothing seems to happen....")
		return true
	end
	
	player:addItem(mouth piece, 1)
	
	player:setStorageValue(1231231, os.time() + (24 * 60 * 60))
	return true
end
```

**Comment by christxx** [comment]
thank you so much, sorry for offtop here I was thinking that is right place to post this kind of things :P
