### ISSUE TITLE
Ankrahmun Cave ERRO

### ISSUE THREAD

**Issue by rogerfernando** [malucooo/otxserver-new#24]
Existe um erro no mapa no deserto de ankrahmun.

Na entrada do buraco a shovel funciona mas o personagem não consegue descer.
Position: 33236, 32577, 7

**Comment by EnzzoCaaue** [comment]
Aqui funcionou, pode fechar.

**Comment by Raphaellb** [comment]
esse issue ja foi arrumado, e pode fechar.
