### ISSUE TITLE
Warning and Crash with gamestore

### ISSUE THREAD

**Issue by darkjav** [malucooo/Otxserver-New#241]
With the last changes in gamestore.xml, the server show the next issue:

>> Initializing gamestate
[Error - GameStore::loadFromXml] Failed to load data/XML/gamestore.xml: Err
ment tag
Line 12:
<offer name="Prey Bonus Reroll", state="new", count="1", type="5", icons="Product_UsefulThings_PreyBonusReroll.png" />
                                               ^

And server crash when you click on the button for open the Store.

**Comment by jlcvp** [comment]
The gamestore xml subsystem is documented in this page: [In Game Store XML configuration](https://github.com/mattyx14/otxserver/wiki/In-Game-Store-XML-configuration)

Note that type="5" doesn't exist in the store definition.

This system was implemented by me and at the moment it doesn't have the ability to show custom-typed offers. 
I'm currently planing to extend the subsystem to support custom lua scripts to sell ANYTHING we want in the game.
