### ISSUE TITLE
GAMESTORE Error

### ISSUE THREAD

**Issue by Andreeyyy** [malucooo/Otxserver-New#242]
[Error parsing XML invalid offer type - GameStore::loadFromXml] Failed to load data/XML/gamestore.xml: No error
Line 1:
<?xml version="1.0" encoding="UTF-8"?>
^

expboost
preybonus

Don't exist in source

**Comment by darkjav** [comment]
Same that https://github.com/malucooo/Otxserver-New/issues/241

**Comment by jlcvp** [comment]
duplicate - see #241 for further information
