### ISSUE TITLE
How to enabled gamestore.lua ?

### ISSUE THREAD

**Issue by darkjav** [malucooo/Otxserver-New#247]
What is necessary do for enable gamestore.lua, and disable gamestore.xml ?

Because i try make it, but i get crash when press button Store:

> terminate called after throwing an instance of 'std::out_of_range'
>   what():  vector::_M_range_check
> 
> Program received signal SIGABRT, Aborted.
> [Switching to Thread 0x697049486700 (LWP 23427)]
> 0x000069704a1f4c37 in __GI_raise (sig=sig@entry=6)
>     at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
> 56      ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.

Or not is possible??

**Comment by jlcvp** [comment]
on [protocolgame.cpp Lines 583~585](https://github.com/malucooo/Otxserver-New/blob/master/src/protocolgame.cpp#L583) comment/delete the lines relative to store, those are the lines that are responsible to parse store packets in the source. Additionally, go to modules.lua and enable the gamestore.lua packet parsing.

**Comment by darkjav** [comment]
@jlcvp 
Thanks alot!

And you recommended enable: C_TransferCoins = 0xEF, -- 239  ??

And for what is C_StoreEvent = 0xE9, -- 233  ??

**Comment by Andreeyyy** [comment]
@jlcvp Esta no gropo do whats? Poderia explicar melhor como fazer isso?

**Comment by jlcvp** [comment]
@darkjav don't enable the transfer via .lua, use only the 0xFA~0xFC. StoreEvent (0xE9) is not implemented on the backend srcs, so keep it enabled on the lua Sources.


@Andreeyyy Eu saí do grupo, tinha muita conversa, muita pergunta e pouca interação e troca de conhecimento que realmente importava. Mas sinta-se à vontade de perguntar diretamente por aqui.
