### ISSUE TITLE
Bonus rerrol still error

### ISSUE THREAD

**Issue by christxx** [malucooo/Otxserver-New#248]
Hey, 
I've udpated and recompiled today source including new commits with prey, then I tried to add bonusreroll to gamestore (updating file gamestore.xml) but there is still problem
http://imgur.com/a/yP6DQ

How we can add bonus reroll to gamestore? I tried add to **gamestore.xml** new item

` <offer name="bonus reroll" type="BonusReroll" price="250" icons="sexchange.png" />`

Tried with these types:
```
bonusreroll
BonusReroll
bonusReroll
preyreroll
preyReroll
PreyReroll
preyRerollToken
preyrerolltoken
PreyRerollToken
bonusrerolltoken
bonusRerollToken
BonusRerollToken

```
None of them working.

**Comment by Eternal-Scripts** [comment]
Please, can you read the comment in my commit?

Thanks.

**Comment by christxx** [comment]
Oh my bad, sorry :D
