### ISSUE TITLE
Walkthrough players lower than protection level

### ISSUE THREAD

**Issue by darkjav** [malucooo/Otxserver-New#249]
Im facing a problem on my server, in my config protectionLevel = 50.
A player under lvl 50 cant be attacked.
But its impossible to walk through this under lvl 50 players.
Sadly, my players are creating alot of underlevel'd accs to trap another players in combat, its possible to make walk through the underlevel'd (non-pvp) players ?

I check this fix, but not work:
https://github.com/otland/forgottenserver/pull/1083/commits/ee7823256996bd6b835d7cbac82c3d4af8483d83

Any idea?

**Comment by christxx** [comment]
Confirmed, tried to add some code to player.cpp, recompiled checked - 0 results

**Comment by gantit** [comment]
@christxx  only need add this? 

``` c

	if (playerTile && (playerTile->hasFlag(TILESTATE_PROTECTIONZONE) || player->getLevel() < static_cast<uint32_t>(g_config.getNumber(ConfigManager::PROTECTION_LEVEL)))) {
		Item* playerTileGround = playerTile->ground;
		if (playerTileGround && playerTileGround->hasWalkStack()) {
			Player* thisPlayer = const_cast<Player*>(this);
			if ((OTSYS_TIME() - lastWalkthroughAttempt) > 2000) {
				thisPlayer->setLastWalkthroughAttempt(OTSYS_TIME());
				return false;
			}

			if (creature->getPosition() != lastWalkthroughPosition) {
				thisPlayer->setLastWalkthroughPosition(creature->getPosition());
				return false;
			}

			thisPlayer->setLastWalkthroughPosition(creature->getPosition());
			return true;
		}
	}
```

**Comment by christxx** [comment]
@gantit I checked this code what you pasted, it works only for Protection zones like Temples, depots, boats etc but for normal zones like cities, spawns etc doesn't work so this is bad solution. Right now I am trying to make it on my way, If I found something usefull then I will share it here

**Comment by christxx** [comment]
I found a solution, there is needed code isAttackable to solve this walking through players with level below protection level.

Find in your file **player.cpp** these bools and replace with this.

`bool Player::canWalkthrough(const Creature* creature) const
{
    if (group->access || creature->isInGhostMode()) {
        return true;
    }
 
    const Player* player = creature->getPlayer();
    if (!player) {
        return false;
    }
 
    if ((player->isAttackable() &&
    (player->getLevel() < (uint32_t)g_config.getNumber(ConfigManager::PROTECTION_LEVEL))))
    return true;
 
    const Tile* playerTile = player->getTile();
    if (!playerTile || !playerTile->hasFlag(TILESTATE_PROTECTIONZONE)) {
        return false;
    }
 
    const Item* playerTileGround = playerTile->getGround();
    if (!playerTileGround || !playerTileGround->hasWalkStack()) {
        return false;
    }
 
    Player* thisPlayer = const_cast<Player*>(this);
    if ((OTSYS_TIME() - lastWalkthroughAttempt) > 2000) {
        thisPlayer->setLastWalkthroughAttempt(OTSYS_TIME());
        return false;
    }
 
    if (creature->getPosition() != lastWalkthroughPosition) {
        thisPlayer->setLastWalkthroughPosition(creature->getPosition());
        return false;
    }
 
    thisPlayer->setLastWalkthroughPosition(creature->getPosition());
    return true;
}
 
bool Player::canWalkthroughEx(const Creature* creature) const
{
    if (group->access) {
        return true;
    }
 
    const Player* player = creature->getPlayer();
    if (!player) {
        return false;
    }
 
    const Tile* playerTile = player->getTile();
    if ((!player->isAttackable() &&
        (player->getLevel() > (uint32_t)g_config.getNumber(ConfigManager::PROTECTION_LEVEL))))
        return true;
    return playerTile && playerTile->hasFlag(TILESTATE_NONE);
}`

**Comment by darkjav** [comment]
@gantit Yo can check my question please?
https://github.com/gantit/Otxserver-New/commit/b892fd28f4deff98c344a4296c7c952bf300faaa#commitcomment-22962841

**Comment by gantit** [comment]
@darkjav Replayed

**Comment by darkjav** [comment]
@christxx @gantit 
I found a bug, if player is high level, that protected character in tile of depot or any other special tile, so the high player can walk through the player with protected level. Example:
![example1](https://user-images.githubusercontent.com/9681018/28005411-0ae7fe4c-6510-11e7-9969-e50748f81a82.png)

And:
![example2](https://user-images.githubusercontent.com/9681018/28005416-134a536e-6510-11e7-857c-d7c1a1f3fe8c.png)

**Comment by darkjav** [comment]
@christxx @gantit Any idea?

**Comment by christxx** [comment]
I tried to fix this issue with NOPVPZONE but I can't make it workable. No idea how to fix this, sorry

**Comment by jlcvp** [comment]
@christxx @Eternal-Scripts checking on this protection level source if it's a depot tile should resolve, shouldn't it?

**Comment by mattyx14** [comment]
tfs 0.4 use the flags "isprotect"

**Comment by mattyx14** [comment]
https://github.com/malucooo/Otxserver-New/issues/286
