### ISSUE TITLE
Imbuement No Detect Items

### ISSUE THREAD

**Issue by Crixpx** [malucooo/Otxserver-New#250]
Hi, I have a timestamp testing the imbuement but it is giving me the following error which does not detect the items when doing the imbue I am using the same one that is here in the repository so that's why I put the issue

http://i.imgur.com/p1w6BB5.png

http://i.imgur.com/OhtFloG.png

http://i.imgur.com/EiUu3fj.png

**Comment by darkjav** [comment]
Confirmed.

**Comment by luminera** [comment]
Confirmed, Any solution to this?

**Comment by christxx** [comment]
Imbuement is not full implemented yet, we can try to do this by ourselves or wait for someone who is gonna write this

**Comment by Andreeyyy** [comment]
It works perfectly here, you need to check all the conditions of the item in the moon and xml

**Comment by luminera** [comment]
@Andreeyyy  Can we teach you how to do this?

**Comment by Eternal-Scripts** [comment]
Fix in last commit.
