### ISSUE TITLE
Crash later of buy slot in Prey System

### ISSUE THREAD

**Issue by darkjav** [malucooo/Otxserver-New#251]
When you buy aPrey Slot number 3, and later do logout, when login the server Crash.

Also when buy reroll bonus, this not add the bonus to the player.

**Comment by christxx** [comment]
Hey, bonus reroll is missing yet, @Eternal-Scripts wrote that in last commit ;p

**Comment by darkjav** [comment]
@christxx 
Yes, @Eternal-Scripts wrote, but exist error. I use the last commit.

**Comment by Eternal-Scripts** [comment]
Clean your database and set prey column to default in players.

**Comment by darkjav** [comment]
Yes i cleaned for not get more crash, but so i think not yet is completed the system, true?

**Comment by Eternal-Scripts** [comment]
in luascript.cpp is missing lines of code, @malucooo commit but still wrong.

**Comment by darkjav** [comment]
I use now the last commit and issue still there.
