### ISSUE TITLE
Crash tibia 10.99

### ISSUE THREAD

**Issue by sonolusa** [malucooo/Otxserver-New#252]
Baixei agora o server, compilei para windows e quando vou tentar logar ele da Crash, aconteceu com alguem tambem? alguem sabe como resolver?
Ou se alguem puder me ajudar a entrar com v11.10, pq quando tento, ele da Connection Refused
___

I downloaded the server now, I compiled it to Windows and when you are trying to log in it crashes, happened to someone as well? Does anyone know how to solve it?
Or if anyone can help me to get with v11.10, because when I try, it's Connection Refused

**Comment by sonolusa** [comment]
Ow se alguem puder me ajudar a entrar com v11.10, pq quando tento, ele da Connection Refused

**Comment by darkjav** [comment]
You need use client verion 10.0, because 10.99 not have more support here.

**Comment by sonolusa** [comment]
and for the version 11.10 or 11x?

**Comment by darkjav** [comment]
Client 11 Compativel (http://www.mediafire.com/file/x0q6exqko4y7gvn/Tibia_11.10.rar)

Se você estiver usando o Gesior:
Login.php (http://www.mediafire.com/file/2jbauphk3eksm14/login.php)

**Comment by sonolusa** [comment]
Eu tentei esse, exatamente com esse login.php, mas esta dando connection refused
___

I tried this, exactly with this login.php, but its giving connection refused when I try to connect

**Comment by darkjav** [comment]
You config the client 11.10 fine?

**Comment by jlcvp** [comment]
You need to configure config.lua with your credentials for database, etc. Additionally, use [my **login.php**](https://gist.github.com/jlcvp/2f1772cbbcdfc966ee982985326d964a) but you'll need a up to date version of the gesior. 

You can use mine: https://github.com/jlcvp/GesiorMonteiro

**Comment by sonolusa** [comment]
I download the client 11.10 from here and need to change the ip for I access local?
I used your site and login.php, but continues the same error on 11.10 connection refused
My config.lua is this, I think I had configured all
 `-- Combat settings
-- NOTE: valid values for worldType are: "pvp", "no-pvp" and "pvp-enforced"
worldType = "pvp"
hotkeyAimbotEnabled = true
protectionLevel = 7
pzLocked = 60 * 1000
removeChargesFromRunes = true
timeToDecreaseFrags = 24 * 60 * 60 * 1000
whiteSkullTime = 15 * 60 * 1000
stairJumpExhaustion = 2 * 1000
experienceByKillingPlayers = false
expFromPlayersLevelRange = 75
dayKillsToRedSkull = 3
weekKillsToRedSkull = 5
monthKillsToRedSkull = 10
redSkullDuration = 30
blackSkullDuration = 45
orangeSkullDuration = 7

-- Connection Config
-- NOTE: maxPlayers set to 0 means no limit
ip = "myIP"
bindOnlyGlobalAddress = false
loginProtocolPort = 7171
gameProtocolPort = 7172
statusProtocolPort = 7171
maxPlayers = 30
motd = "Welcome to The OTXServer Global!"
onePlayerOnlinePerAccount = true
allowClones = false
serverName = "OTXServer-Global"
statusTimeout = 5 * 1000
replaceKickOnLogin = true
maxPacketsPerSecond = 25

-- Version Manual
clientVersionMin = 1000
clientVersionMax = 1110
clientVersionStr = "Only clients with protocol 10.00 or 11.00 is allowed!"

-- Depot Limit
freeDepotLimit = 2000
premiumDepotLimit = 10000
depotBoxes = 17

-- Casting System 
enableLiveCasting = true
liveCastPort = 7173

-- Deaths
-- NOTE: Leave deathLosePercent as -1 if you want to use the default
-- death penalty formula. For the old formula, set it to 10. For
-- no skill/experience loss, set it to 0.
deathLosePercent = -1

-- Houses
-- NOTE: set housePriceEachSQM to -1 to disable the ingame buy house functionality
housePriceEachSQM = 1000
houseRentPeriod = "weekly"

-- Item Usage
timeBetweenActions = 200
timeBetweenExActions = 1000

-- Map
-- NOTE: set mapName WITHOUT .otbm at the end
mapName = "global"
mapAuthor = "Cipsoft"

-- Market
marketOfferDuration = 30 * 24 * 60 * 60
premiumToCreateMarketOffer = true
checkExpiredMarketOffersEachMinutes = 60
maxMarketOffersAtATimePerPlayer = 100

-- MySQL
mysqlHost = "localhost"
mysqlUser = "root"
mysqlPass = ""
mysqlDatabase = "mydb"
mysqlPort = 3306
mysqlSock = ""
passwordType = "sha1"

-- Misc.
allowChangeOutfit = true
freePremium = false
kickIdlePlayerAfterMinutes = 15
maxMessageBuffer = 4
emoteSpells = false
classicEquipmentSlots = false
allowWalkthrough = true
coinPacketSize = 25
coinImagesURL = "http://some.url/images/store/"
classicAttackSpeed = false

-- Rates
-- NOTE: rateExp is not used if you have enabled stages in data/XML/stages.xml
rateExp = 900
rateSkill = 15
rateLoot = 6
rateMagic = 6
rateSpawn = 1

-- Monster rates
rateMonsterHealth = 1.0
rateMonsterAttack = 1.0
rateMonsterDefense = 1.0

-- Monsters
deSpawnRange = 2
deSpawnRadius = 50

-- Stamina
staminaSystem = true

-- Scripts
warnUnsafeScripts = true
convertUnsafeScripts = true

-- Startup
-- NOTE: defaultPriority only works on Windows and sets process
-- priority, valid values are: "normal", "above-normal", "high"
defaultPriority = "high"
startupDatabaseOptimization = true

-- Status server information
ownerName = "Malucooo"
ownerEmail = "e_nunes@live.com"
url = "http://www.facebook.com/erick.nunes.75"
location = "Brazil"
`

**Comment by jlcvp** [comment]
@sonolusa You need to configure you database credentials in config.lua. 
And you need to change the login page inside of the 11.10's client.exe

**Comment by jlcvp** [comment]
@sonolusa Have you ever ran a otserver before?

**Comment by sonolusa** [comment]
@jlcvp Yes, i was using a old malucooo, but had a lot of bugs, so I search and I found here. I can login in version 10, but this version 11 is new and I am learning how to configure, if you can explain how to configure this client version

**Comment by sonolusa** [comment]
@jlcvp I am trying to use your website, but the label password does not appears, how can I activate this label?

**Comment by sonolusa** [comment]
I have deleted some characters and works tibia 11, thanks
