### ISSUE TITLE
Not is possible unwrap items that was buy in Shop

### ISSUE THREAD

**Issue by darkjav** [malucooo/Otxserver-New#254]
When you buy a item in the Shop that have attribute wrapableTo, not is possible unwrap it.

**Comment by flaviiojr** [comment]
set a action on a item

**Comment by darkjav** [comment]
@flaviiojr 
How do it? Because in the .iit file exist the code, but not work, check:
https://github.com/malucooo/Otxserver-New/blob/master/data/modules/scripts/gamestore/init.lua#L286-#L299

**Comment by jlcvp** [comment]
@darkjav 
which version of store are you using? Lua or xml?

**Comment by darkjav** [comment]
@jlcvp 
I use .lua because have more features, but i see that days ago was update the version .xml,
so what version you recommended?
