### ISSUE TITLE
Potion kegs

### ISSUE THREAD

**Issue by GoularPink** [malucooo/Otxserver-New#255]
O script foi feito com amor, porém o sistema de keg não é assim...

Ele funciona da seguinte forma, o player compra através do store e o keg **não é possível mover ou dar trade**, somente o player que comprou irá poder usar.

Não se usa o potion no keg, **o correto é clicar no keg e ele refilará as potions**, podendo assim refillar potions em hunts ou seja lá onde estiver. (**os kegs podem ser usados fora da house**)

Frases: 
You cannot refill any more flasks. (quando nao tem potion pra refillar)
Your potion container has been depleted. (quando acaba o keg)
Quando o potion é refilado não aparece msg nenhuma

Obs. os potions refillados vão pro store inbox, porém pode ficar na backpack mesmo sem problemas né.

A ideia do cask está certa

**## English:**

It works as follows: the player buys through the store shop, the keg can not move from store inbox and not is tradeable, only the player you bought will be able to use it.

The correctly is: USE keg and it will refill all empty flasks. 
Wrong: use empty flask on keg.

(**Kegs can be used outside the house**)

Phrases:
You can not refill any more flasks. (When there is no potion to refill)
Your potion container has been depleted. (When the keg ends)
When the potion is refiled, no msg appears

The idea of ​​cask is right

**Comment by GoularPink** [comment]
Um error no console, testando com GOD e não sou owner da house


Lua Script Error: [Action Interface]
data/actions/scripts/other/caskkegs.lua:onUse
data/actions/scripts/other/caskkegs.lua:8: attempt to call method 'canEditAccessList' (a nil value)
stack traceback:
        [C]: in function 'canEditAccessList'
        data/actions/scripts/other/caskkegs.lua:8: in function <data/actions/scripts/other/caskkegs.lua:1>

**Comment by westwol** [comment]
You should keep the language in English so most of the people understand.

**Comment by darkjav** [comment]
@GoularPink You can put in english please?

**Comment by GoularPink** [comment]
@darkjav  @westwol  

I edited above

I'm using Viking Client
https://www.vikingtibia.com.br/?subtopic=downloads
