### ISSUE TITLE
Error with attack spells, players without war

### ISSUE THREAD

**Issue by darkjav** [malucooo/Otxserver-New#256]
When players without war use the spells: exevo gran mas flam, exevo gran mas frigo, exevo gran mas tera, exevo gran mas vis, get error in console:

> Lua Script Error: [Spell Interface]
> data/spells/scripts/attack/hells core.lua:onCastSpell
> data/spells/lib/spells.lua:352: attempt to call global 'getPlayerWarType' (a nil value)
> stack traceback:
>         [C]: in function 'getPlayerWarType'
>         data/spells/lib/spells.lua:352: in function 'isSpellBlocked'
>         data/spells/scripts/attack/hells core.lua:15: in function <data/spells/scripts/attack/hells core.lua:14>
> 

I use the last commit, i think is error of new war anti entrosa.

**Comment by gantit** [comment]
This function is removed on commit [Added retro outfits, Albinius npc and bla bla bla!](https://github.com/malucooo/Otxserver-New/commit/6514bdf8ce3b7f3b30fc072998746d7876afda25#diff-e48f380da2d4a71fa7398be673c8a435L351) by @malucooo

**Comment by darkjav** [comment]
@gantit Yes i know, but not is the solution, because players in war anti entrosa, can use spells if they choice the option for disable it.

@malucoo You think is possible block the spells in the war or not?
