### ISSUE TITLE
Error console Kegs

### ISSUE THREAD

**Issue by GoularPink** [malucooo/Otxserver-New#260]
Lua Script Error: [Action Interface]
data/actions/scripts/other/caskkegs.lua:onUse
data/actions/scripts/other/caskkegs.lua:5: attempt to call method 'getActionId' (a nil value)
stack traceback:
        [C]: in function 'getActionId'
        data/actions/scripts/other/caskkegs.lua:5: in function <data/actions/scripts/other/caskkegs.lua:1>

**Comment by marsoncschneider** [comment]
Fixed all cask kegs system

**Comment by marsoncschneider** [comment]
Just will update phrases.
