### ISSUE TITLE
Items wrap in gamestore

### ISSUE THREAD

**Issue by zarkank** [malucooo/Otxserver-New#261]
How to put these items in the store?

**Comment by jlcvp** [comment]
I'm implementing this feature just now

mattyx14/otxserver#262

**Comment by zarkank** [comment]
GOD s2
But how would I put to receive 2 different items in the same purchase?

**Comment by jlcvp** [comment]
Unfortunately, not. I've put to receive only 1 type of item per purchase, You can sell a 4x pack of chairs, for example, but you can't sell the **chairs and table set**, if it's necessary I can implement it in a future update.

**Comment by zarkank** [comment]
I would be very grateful.
I'm setting up the store according to the global, I'll just need that.

Thanks for everything s2
