### ISSUE TITLE
Gaz Spells

### ISSUE THREAD

**Issue by GoularPink** [malucooo/Otxserver-New#264]
Lua Script Error: [Spell Interface]
data/spells/scripts/monster/gaz'haragoth death.lua:onCastSpell
luaAddEvent(). Argument #3 is unsafe
stack traceback:
        [C]: in function 'addEvent'
        data/spells/scripts/monster/gaz'haragoth death.lua:68: in function <data/spells/scripts/monster/gaz'haragoth death.lua:66>

**Comment by MichelFigueira** [comment]
How can I simulate this error? 

Thanks

**Comment by darkjav** [comment]
@MichelFigueira 
Happen when Gaz'haragoth do the ultimate explosion, when had red life.

**Comment by GoularPink** [comment]
@Eternal-Scripts  open this issue please, this are bugged yet, the same thing..

http://prntscr.com/fx05j5

**Comment by Eternal-Scripts** [comment]
Fix: https://github.com/malucooo/Otxserver-New/commit/a21d49a29fbb33ed1fe82450afd0aa84bbeea17a
