### ISSUE TITLE
No monsters in Monters.xml

### ISSUE THREAD

**Issue by Zainox** [malucooo/Otxserver-New#27]
I have been observing the moustro and I have taken with a not very pleasant surprise, as the moustros of the update 10.7 is not, something that is inconsubble since it is a very old update of the Hero Rantlheton Quest. Not a single boss is. So please add among the highlights that are not registered are:

Strong glooth horror
Weakened Glooth Horror
Tentacle of the Deep Terror

Among others, so I'm assuming that the Hero Ranthleton Quest is incomplete or disabled: /

**Comment by malucooo** [comment]
go work man... make the monsters and take for we!
