### ISSUE TITLE
In Service of Yalahar: Missão do bueiro faltando actions

### ISSUE THREAD

**Issue by renangranatto** [malucooo/otxserver-new#27]
http://prntscr.com/kylrt8
http://prntscr.com/kyls4c

Nessas duas partes, não tem as actions pra usar a Crowbar e completar a quest, as outras duas estão funcionando.

**Comment by lamonato29** [comment]
Amigo, o problema é o seguinte: Está faltando o UniqueID nas pedras, nesse print q vc mandou https://prnt.sc/kyls4c a UniqueID está no item pendurado na parede, por algum erro... é só arrumar

**Comment by EnzzoCaaue** [comment]
Já foi arrumado, pode fechar.
