### ISSUE TITLE
Coins in store sys!

### ISSUE THREAD

**Issue by gutogirardon** [malucooo/Otxserver-New#28]
My account have coins, can see here
![image](https://cloud.githubusercontent.com/assets/5953211/24991078/c5b1b090-1fee-11e7-8ada-84bc0a6861f6.png)

But store can't recognize them
![image](https://cloud.githubusercontent.com/assets/5953211/24991108/ecf84b14-1fee-11e7-8c85-513aeef5d1e9.png)

I am using the latest otx version of git!

**Comment by Zainox** [comment]
The premium poitns is a diferent of Coins almost you need is a same... Look in you sql in Account, the table coins, it is a coins table... And man please you share your store images with me? and change i help you what do you need!!!

Facebook: www.facebook.com/zainox1
skype: zainox@live.it

**Comment by malucooo** [comment]
your site... your problem... i dont have nothing with this!
