### ISSUE TITLE
How enabled Bless Equipment Border??

### ISSUE THREAD

**Issue by darkjav** [malucooo/Otxserver-New#282]
I dont know if exist the feature in the code.

![28b39b2c-b44c-11e6-9713-74688db35665](https://user-images.githubusercontent.com/9681018/28192269-9a797030-67fa-11e7-8054-b1c7161d865a.png)

http://tibia.wikia.com/wiki/Adventurer%27s_Blessing

**Comment by westwol** [comment]
```
function Player.sendAdventurerBlessing(self)
    local msg = NetworkMessage()
    msg:addByte(0x9C)
    msg:addU16(self:hasBlessing(7) and 0x01 or 0x00) -- 0x01 for the golden frame
    msg:sendToPlayer(self)
    msg:delete()
end
```
To trigger the function player:sendAdventurerBlessing(), it should be onLogin

**Comment by darkjav** [comment]
Ok i try, and this work with client 10,
but not is compatible with client 11, i get debug there.

You know how fix? Thanks.
