### ISSUE TITLE
Poison Field

### ISSUE THREAD

**Issue by Pimentelsz** [malucooo/Otxserver-New#284]
Estava testando umas coisas e acabei achando esse bug, teria alguma solução? Quando é jogado a poison com o "**AntiPUSH**" ligado, ele buga.

Apenas as poisons estão bugadas, já tentei mexer na configuração dela nos items e não resolveu, procurei na source e aparentemente não tem nada que modifique ela, está igual as outras.
Testei a  `ITEM_POISONFIELD_PERSISTENT = 1496`, e funcionou perfeitamente, porem essa é usada em quests, e não teria como trocar.

![gif](https://user-images.githubusercontent.com/29966489/28211806-e64ee894-6874-11e7-9a39-ca2cb0938b49.gif)

**Comment by Eternal-Scripts** [comment]
Isso é BUG do bot e não do Servidor.
