### ISSUE TITLE
WELCOME TO THE CJAKER PLACE

### ISSUE THREAD

**Issue by Eternal-Scripts** [malucooo/Otxserver-New#286]
I am fixing all systems and all missing bytes now, JUST WAIT FOR ME NIGGAAAAAA OH YEAH!
@jlcvp @darkjav @westwol
- [x] Prey System **fix** 9e235990af1325d4926dbdbac3ae4ec8b3d3a17c
- [x] Login 11.32 (debug) **fix** 188e0efd0ae3844757f6b74a8e8e7b54be98ffb2
- [x] Depot Global (missing features and have bugs) **fix** bebcd1910beefef30bf4fe796367f1574554bbe4
- [x] Game News (packets MY FRIEND) **fix** 188e0efd0ae3844757f6b74a8e8e7b54be98ffb2
- [x] Blessings Dialog (new packet) **fix** 188e0efd0ae3844757f6b74a8e8e7b54be98ffb2 **and** 568371913c8b2e5255f3ff052eda164a0acf3aad
- [x] Client Check (new packet) **fix** bccad305b3f54fd2753c0931fbd99103fbc7e7f0 **and** f5a8f3693cc429600dd0507e54cbd44b8b40aa40
- [x] Resource Shop NPC (get money from bank & player 11.0+) **fix** 43da4f2ab880ddc70a64ae84ab441d119b8e87ee
- [x] Store Button Highlight **fix** 4fb46c41230c96c0893fe70c13573a51764327cc
- [x] Premium Features **fix** 2bbd9c742198496ac450e1c3f8f1e0d97ee1fda7 -> by @comedinha 
- [x] Imbuement System **fix** last commits
- [x] Protocol status (otservlist or any other) **fix** https://github.com/malucooo/Otxserver-New/commit/ae08d172ebb31f4f7ad9313ee6ffcd09b4c240f3 Thanks @jlcvp!
- [x] Summons Debug 10 **fix** c601604992875df3b55f327566ff3405bca4b149
- [x] Cast System (freezes mai frêndi)
- [x] Reward System (fix or remake)
- [ ] No logout on death **need fix with player pointer**
- [ ] Inspect System
- [ ] Report System (yeah, fuck off botters).
- [ ] Walkthrough players
- [ ] PvP Expert
- [ ] Look NPC on Battle List (Client 11)

**Link [Client 11.49_5884](https://github.com/malucooo/Otxserver-New/raw/master/Tibia_11_49.5884.rar)

If you have other system please comment in this issue, i will PRAISE THE SUN to make all work.

**Comment by christxx** [comment]
Hey,
Maybe you could look at this https://github.com/malucooo/Otxserver-New/issues/249 ? I tried to make it on my way, but not enough knowledge of C++ to solve this walking through players under protection levels at Depot Tiles.

**Comment by Eternal-Scripts** [comment]
@christxx Added in list, just wait may frendi

**Comment by joseluis2g** [comment]
I would love to help when I can, also in this post https://github.com/malucooo/Otxserver-New/issues/162 you edited some things to your prey system, maybe this weekend after my exams I could do something.

**Comment by westwol** [comment]
I'm down to helping in anything I can to address the issues.

**Comment by FourMozart** [comment]
Could fix the reward system, it clones rewards.

**Comment by mattyx14** [comment]
good TODO :D

**Comment by mattyx14** [comment]
add pvp expert - retro is more work

**Comment by Eternal-Scripts** [comment]
![screenshot_2](https://user-images.githubusercontent.com/20959344/28233719-2feba118-68cf-11e7-920a-27fc609c0e26.png)
Blessings

**Comment by joseluis2g** [comment]
whats the missing feature on the global depot?

**Comment by westwol** [comment]
Log in with 10.32 is not working atm. Tested using master.

**Comment by darkjav** [comment]
@Eternal-Scripts 
With last commit, player can only login with client 11.32,
because with the client 10.00 get debug on Login.

You know?

**Comment by Eternal-Scripts** [comment]
@darkjav versions where don't have the new blessings will debug, but the 11.32 and 11.32 (old) works fine.
I send a commit where can fix your problem, please test. d4efdd23f4ce468287b03da69aedefeeb122d640

**Comment by mattyx14** [comment]
Store Button
![store](https://user-images.githubusercontent.com/2807739/28239183-7f2257f2-692b-11e7-83da-99c87b4360e5.png)

**Comment by Eternal-Scripts** [comment]
@mattyx14 Added my friend, and i done now Prey System (bonus reroll)

**Comment by mattyx14** [comment]
and other is:
![premium](https://user-images.githubusercontent.com/2807739/28239225-9a4dc5ec-692c-11e7-9a3b-af1c8fa81885.png)

**Comment by mattyx14** [comment]
ooo it a good check if npc work for you "sell/buy"

**Comment by Eternal-Scripts** [comment]
@mattyx14 its fixed i add a missing byte in saleItemList (c++)

**Comment by mattyx14** [comment]
ok now are fix :D

**Comment by mattyx14** [comment]
To my comment previous
NPC work on trade windows fine
08:14 Dakito [160]: buy antidote potion
08:14 Eryn: Do you want to buy 1 antidote potion for 50 gold coins?
08:14 Dakito [160]: yes
```
Lua Script Error: [Npc interface]
data/npc/scripts/runes.lua:onCreatureSay
data/npc/lib/npcsystem/modules.lua:1174: attempt to index global 'player' (a nil value)
stack traceback:
        [C]: in function '__index'
        data/npc/lib/npcsystem/modules.lua:1174: in function 'callback'
        data/npc/lib/npcsystem/keywordhandler.lua:30: in function 'processMessage'
        data/npc/lib/npcsystem/keywordhandler.lua:185: in function 'processNodeMessage'
        data/npc/lib/npcsystem/keywordhandler.lua:153: in function 'processMessage'
        data/npc/lib/npcsystem/npchandler.lua:428: in function 'onCreatureSay'
        data/npc/scripts/runes.lua:7: in function <data/npc/scripts/runes.lua:7>
```

**Comment by Eternal-Scripts** [comment]
Fix blessings in old client d5d48e3e847712960f5de05a0e3afc96e207aa4f

**Comment by joseluis2g** [comment]
actually those premium features are really easy to add

**Comment by MichelFigueira** [comment]
For me display only the first character in login. Does anyone know what I'm doing wrong?

**Comment by adrianofiuza** [comment]
@MichelFigueira , you need to make a little change on change login.php.

On this line
`$dbResource = $SQL->query("SELECT `name`,`sex`,`lastlogin` FROM `players` WHERE `account_id` = $accId LIMIT 1");`

Change 1 by the number of characters you want to display.

**Comment by MichelFigueira** [comment]
Thanks man

**Comment by Eternal-Scripts** [comment]
@christxx how walkthrough works, can u explain me?

**Comment by christxx** [comment]
@Eternal-Scripts You know, for this moment players with level higher than protection level (setted in config) can walkthrough players with level under protection level, for example Protection level=20, so player with 21 level can walkthrough player with level under 20 like 10, 15, 8 etc but there is a problem that players with level higher than protection can also walkthrough players at Depot Tiles (link to screenshots)
https://github.com/malucooo/Otxserver-New/issues/249#issuecomment-314017926

**Comment by mattyx14** [comment]
Other missing here : https://github.com/mattyx14/otxserver/issues/252

**Comment by tfornalewicz** [comment]
How did you remove Battleeye from 11.32 client? I'd like to do the same with 11.46 but when I compare your 11.32 to normal one I can't see the difference.

**Comment by bennydz** [comment]
i need same client but for 11.46

**Comment by nycholassousa** [comment]
Imbuement is not working properly. The slots are added, however, when the equipment is equipped, the status do not change.

**Comment by Eternal-Scripts** [comment]
@nycholassousa fix for us! the version in this repository is the incomplete version, so if you know how to fix welcome xD

**Comment by nycholassousa** [comment]
I'm accustomed to TFS 0.4, I'm still trying to adapt to this new version ... If I can, of course I'll help :)

**Comment by nycholassousa** [comment]
@Eternal-Scripts Além de adicionar os movements pra um "imbuements.lua" no lugar do onEquipeItem/onDeEquipItem que chame onEquipWeaponImbuement(player, item)/onDeEquipWeaponImbuement(player, item) o que mais é necessário?

**Comment by nycholassousa** [comment]
Comecei a ter um norte em relação ao equipar. Uma das coisas é: o module ainda está realmente incompleto e com alguns bugs, mas estou tentando ajustar. Outra coisa é: falta adicionar os items no movements.xml e as skills simples (magic, sword, etc) está mudando corretamente (prova: https://imgur.com/a/g86DL), porém, skills do tipo leech e afins não mudou aqui. Posso ter errado algo, claro, mas ainda vou testar melhor.

Qualquer coisa, como quero ajudar a colocar esse bendito sistema completamente funcionando (tentando ajudar no que posso), vou adicionando os movements.

@Eternal-Scripts sabe me dizer se além disso que notei, deixei passar algo?

**Comment by nycholassousa** [comment]
Além do mais, notei que quando você equipa, ele adiciona os status normalmente, mas quando desequipa, ele retira os status até de outros equipamentos. Exemplo: Equipei helmet com axe e uma wand com magic, fico com axe + 1 e magic + 1. Removo apenas o helmet, tudo fica zerado.

**Comment by mattyx14** [comment]
Update first: Look NPC on Battle List (Client 11)

**Comment by Eternal-Scripts** [comment]
I am not updating more the list, so please do it in my place. thanks.

**Comment by Tekadon58** [comment]
Estou tentando me conectar e dar erro de senha errada porem a senha está certa


![image](https://user-images.githubusercontent.com/23642470/33226571-ff89801c-d16f-11e7-8dd1-b48785b01dee.png)

**Comment by JavEver** [comment]
In it has the bug fill the (player_inboxitems) and re-log the char with the inbox crowded, and the server crash?
