### ISSUE TITLE
Last commit debug with client 10.00

### ISSUE THREAD

**Issue by darkjav** [malucooo/Otxserver-New#288]
@Eternal-Scripts 
With last commit, player can only login with client 11.32,
because with the client 10.00 get debug on Login.

I think is the new blessings system,
any idea?

**Comment by Andreeyyy** [comment]
Same problem here

**Comment by Eternal-Scripts** [comment]
Test the 10.0 from my issue.

**Comment by Eternal-Scripts** [comment]
Please test this commit d4efdd23f4ce468287b03da69aedefeeb122d640
