### ISSUE TITLE
New bless system possible missing byte

### ISSUE THREAD

**Issue by darkjav** [malucooo/Otxserver-New#290]
@Eternal-Scripts 
When player get all blessings, there are missing the first bless Twist of Fate:
![bless_test](https://user-images.githubusercontent.com/9681018/28236809-ac12953c-68f5-11e7-88a9-b067128a6958.png)

but in the database are there:
![bless_test2](https://user-images.githubusercontent.com/9681018/28236812-b4c81936-68f5-11e7-9773-2dfa856d7309.png)

I use client 11.32
Any idea?

**Comment by westwol** [comment]
Tested and it works.
![works](https://user-images.githubusercontent.com/17607894/28237556-c229f7a4-6907-11e7-9406-722b53422d3b.png)

**Comment by darkjav** [comment]
@westwol 
What value you have in the database, for Twist of Fate?

**Comment by Eternal-Scripts** [comment]
Tested here and nothing happens, all is fine check again @darkjav .
