### ISSUE TITLE
House cleaning bug

### ISSUE THREAD

**Issue by christxx** [malucooo/Otxserver-New#291]
Hey,
Today I noticed that there is a issue with cleaning house. Week ago I bought house for test, had no money in bank to pay for rent and today house were cleaned. Everything would be okay but there are 2 issues -
1. At house were a lot of items, none of them were not sent to character's depot.
2. Tiles where were items located, were cleaned but there disappear some rubbish "items of type 1094 with id 1094" on the ground (there shouldn't be these items)
IMG: http://imgur.com/a/8dbP8

**Comment by Schiffers** [comment]
confirmed! this items 1094 appear from nothing lol
