### ISSUE TITLE
Error for update and count players- Otservlist

### ISSUE THREAD

**Issue by darkjav** [malucooo/Otxserver-New#293]
@malucooo @Eternal-Scripts @mattyx14 @jlcvp 
I have a issue, today i open new OT for test with real players,
and in otservlist appear:
0 ( 0 ) / 0
and as offline.

I reported to xinn (owner of otservlist), and he respond me:
"This is an error on your side. It has nothing to do with our list."

Also i try apply this new rule:
https://otland.net/threads/very-important-rules-change-on-otservlist-org.247531/page-3#post-2407794
but i get the same result.

Any idea?

**Comment by darkjav** [comment]
@Andreeyyy You have the same bug, you can explain?

**Comment by mattyx14** [comment]
He post the required code?

**Comment by darkjav** [comment]
@malucooo The commit: https://github.com/malucooo/Otxserver-New/commit/10ba22540dfee63e95d4309579aeb90072ab5320 not work for fix this issue.

**Comment by darkjav** [comment]
@mattyx14 Andrey said me in whatsapp that he have the same error, her server is onyxdream.com, is online, but in the otservlist appear offline always (https://otservlist.org/ots/1598619), the same problem that i have in my OT.

**Comment by jlcvp** [comment]
[This line](https://github.com/malucooo/Otxserver-New/commit/beda91b51f9bb2dfeef576f598f6dd73e2a33fd7#commitcomment-23143472)

breaks the protocolstatus. It's not checksummed, assuming true makes a corrupt packet header to otservlist-like clients, I guess. 

We need to find a way to differentiate between a protocol 11.11+ connection from a protocoStatus "client"

**Comment by methemia** [comment]
I have the same problem

**Comment by Olimpotibia** [comment]
How we can help to fix this problem?

**Comment by Crixpx** [comment]
:S my erver are down for this bug :S :venezuela:
