### ISSUE TITLE
Bless 

### ISSUE THREAD

**Issue by flaviiojr** [malucooo/Otxserver-New#294]
Ao morrer sem bless, o char ganha 127 charges de cada bless.

Ao comprar uma unica bless, o icone da Bless deveria acender e indicar que ele possue uma bless. Ele só acende depois que todas a bless estão no char, e pra acender o icone é preciso deslogar!

A janela de dialogo da Bless não está abrindo no cliente 11.32, retorna um falso indicando que o dialogo só deve ser aberto no flash client ou cliente 11, porém eu estou usando o cliente 11...

**Comment by zarkank** [comment]
Só pra não criar outro vou colocar isso aqui também
O sistema do char ter bless ate certo level não está direito também.
Exemplo: Se colocar a bless pra char até level 50, ele terá a bless até morrer, acredito que isso não seja o certo, pois coloquei o level maximo pra 50, e ele fica até a primeira morte.
Desculpe caso eu esteja falando bobeira, mas sei lá né

**Comment by Andreeyyy** [comment]
@zarkank Sim essa é a ideia.

**Comment by zarkank** [comment]
Mas não seria para a bless sumir depois do 50?

**Comment by Eternal-Scripts** [comment]
127 Charges confirmado.
Agora sobre comprar Blessing é inválido, testei com o repositório clean e funcionou utilizando player:addBlessing
