### ISSUE TITLE
Loot dos servants

### ISSUE THREAD

**Issue by GoularPink** [malucooo/Otxserver-New#296]
quando tem um fungus em baixo do corpo o loot nao abre..

You see a slime fungus.
Item ID: 13589.

ai tenta abrir um corpo em cima desse slime fungus, nao da

**Comment by Schiffers** [comment]
ainda está com aquele erro quando abre 2 corpos no mesmo stack abre o de baixo e não o de cima ?
se sim, provavelmente é isso, verifique.

**Comment by GoularPink** [comment]
to nao, tem como tu testar ai no seu pra confirmar o bug? @Schiffers

**Comment by GoularPink** [comment]
@Schiffers  onde que tem esse commit ? @darkjav

**Comment by darkjav** [comment]
@GoularPink You use the last commit?

**Comment by GoularPink** [comment]
yes, check yourself please @darkjav

**Comment by Schiffers** [comment]
"check yourself please"?????????????????????????????
 que tal conferir se ainda tem o bug que eu comentei antes ? vc nem se dá o trabalho ai fica tenso

**Comment by darkjav** [comment]
Confirmed.
I think is missing attribute in items.otb for the id: 13589,
because if you put anything that have "containersize" as a corpse or backpack,
appear the next: "You cannot use this object."

**Comment by darkjav** [comment]
@GoularPink The issue was fixed with latest commit?
