### ISSUE TITLE
Latest client 10 debug

### ISSUE THREAD

**Issue by darkjav** [malucooo/Otxserver-New#298]
In the latest client 10 of Tibia (outdated), when player do a summon with command: /summon
or with spell: utevo res, the master and all players around get debug.

And later of the debug, if they login again, the summon appear there, with green and red icon, without problems.

**Comment by Andreeyyy** [comment]
Deactivate utevo res spells or use only client 11

**Comment by sn4tch0vsk** [comment]
I'm having the same issue. Can't use /summon ou utevo res without debug.

**Comment by darkjav** [comment]
@Andreeyyy Yes i already desactivated, but not is the solution,
im trying make the correct code.

**Comment by sn4tch0vsk** [comment]
@darkjav I'm running the 11.32
It works fine.
if you use localhost, you can download de client already changed here
http://www.mediafire.com/file/lgi0nuztlao1t4w/Tibia1132localhost.rar

**Comment by darkjav** [comment]
@sn4tch0vsk 
Yes i know the bug, is because not yet is completed the code for summons, is necessary desactivate the spell "utevo res "and "convince rune", also the command "/summon".

**Comment by mattyx14** [comment]
updateCreatureType have the problem

**Comment by darkjav** [comment]
@mattyx14 Yes, we need check here: https://github.com/malucooo/Otxserver-New/commit/fc166cac1ae5a1faebe850ec39fd1182f976e55b

**Comment by 11229900** [comment]
a few weeks ago my server went well with the client 10 and worked well the magic utevo res without bugs and now only this bug I do not know what to do I'm lost
