### ISSUE TITLE
Swimming on fallen tree

### ISSUE THREAD

**Issue by newacc12** [malucooo/Otxserver-New#3]
The character is supposed to walk on the tree not swim:

![image](https://cloud.githubusercontent.com/assets/20234557/24333313/4731c524-121b-11e7-9052-ba1365cbefb8.png)

**Comment by malucooo** [comment]
send me id of tile!

**Comment by newacc12** [comment]
I'm not sure what to send, so I'm sending all of them:

![error1](https://cloud.githubusercontent.com/assets/20234557/24339015/0d67e7e8-126f-11e7-9f1a-e638a59962e9.png)
![error2](https://cloud.githubusercontent.com/assets/20234557/24339018/0f1de97a-126f-11e7-9496-e466d86b924d.png)
![error3](https://cloud.githubusercontent.com/assets/20234557/24339020/11422bf8-126f-11e7-8650-43783142374e.png)
![error4](https://cloud.githubusercontent.com/assets/20234557/24339025/12e3770a-126f-11e7-942b-d6116b5a2a6f.png)
![error5](https://cloud.githubusercontent.com/assets/20234557/24339027/1535a2c6-126f-11e7-8bf7-24b56f45c632.png)

The first and the last one I wrote "WORKS" which means they are working, the character does not swim on those 2 tiles. Are those IDs that you need?

**Comment by newacc12** [comment]
@malucooo After downloading the latest version now the character does not swim on any water and it gives console errors:

Lua Script Error: [MoveEvents Interface]
data/movements/scripts/swimming.lua:onStepIn
data/lib/compat/compat.lua:1022: attempt to index global 'itemType' (a nil value)
stack traceback:
        [C]: in function '__index'
        data/lib/compat/compat.lua:1022: in function 'doSetCreatureOutfit'
        data/movements/scripts/swimming.lua:9: in function <data/movements/scripts/swimming.lua:3>

![image](https://cloud.githubusercontent.com/assets/20234557/24387603/a2334620-133b-11e7-963b-173bef69709f.png)
