### ISSUE TITLE
CRASH CLIENT 11.32 PREYSLOT

### ISSUE THREAD

**Issue by treeckoo** [malucooo/Otxserver-New#301]
When Player buy from store prey slot 3 permanently all work fine..

But when player disconect or relog the theforgottenserver.exe crash without error in console.

**Comment by Andreeyyy** [comment]
Correct report, the same thing happened here as well

**Comment by christxx** [comment]
Confirmed, on client 10.00 there is a problem when trying to login at character that has bought prey slot pernamently
http://imgur.com/a/loGB3

**Comment by granoob** [comment]
The bug is in the database (player) then goes in prey-column, where the value was for this at maximum 2, some accounts this 10, change to 2 or 1 and then download the scripts preysystem.lua from the last correction of the eternal

**Comment by Eternal-Scripts** [comment]
![image](https://user-images.githubusercontent.com/20959344/28370065-bee55a3c-6c6f-11e7-8528-d9d094e9bc4a.png)
Are you fucking kidding me madafacka?

**Comment by Eternal-Scripts** [comment]
Reopenned by request of andreyyy.

**Comment by darkjav** [comment]
Same bug that https://github.com/malucooo/Otxserver-New/issues/251

**Comment by Andreeyyy** [comment]
Corrected. Download Last Commit
