### ISSUE TITLE
Items.otb editor

### ISSUE THREAD

**Issue by kito2** [malucooo/Otxserver-New#305]
Could you please post the otb editor you are using in order to modify items.otb? I have found a few  things that should be changed as a few tiles blocking missile for example.

**Comment by jlcvp** [comment]
@kito2 Coul you please list the ids of these things you said?

**Comment by kito2** [comment]
2231, 21937, 22158, 21936 need to remove block missiles.
23523 need to define stack order at top.
1718 to 1723 need to be defines as block pathfinder and block misslers and stack order at top.

Also for my own, I use 8753 as magic wall, so the bots doesn't show the timer over the walls (this is optional).
