### ISSUE TITLE
Error on running server

### ISSUE THREAD

**Issue by Echenique** [malucooo/Otxserver-New#314]
when i try run server on linus 
command: ./tsf

after load some modules i have an error

`>>Loading config: config.lua
>>Establishing database connection... MySQL 5.7.19
>>Running database manager
> No tables were optimized
>>Loading vocations
>>Loading items
>>Loading script systems
>>Loading monsters
>>Loading outfits
>>Checking world type... PVP
>>Loading map
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<std::ios_base::failure[abi:cxx11]> >' what(): failed opening file: No such file or directory: iostream error
Aborted`

please help me (=

**Comment by flaviiojr** [comment]
Extract the map in the world folder '-'
