### ISSUE TITLE
Enable travis-ci build

### ISSUE THREAD

**Issue by jlcvp** [malucooo/Otxserver-New#32]
despite of having a .travis.yml file, this project is inactive on [travis-ci.org](https://travis-ci.org).

Enable it there and set the badge on README.md so we can check the current status of the sources before clonning it.

**Comment by malucooo** [comment]
Enabled! Show me more info plz
Thank you!

**Comment by jlcvp** [comment]
@malucooo , o travis serve pra compilar e, opcionalmente, testar o código sempre que há um novo commit. E automaticamente colocar uma badge no README.md do projeto dizendo se os sources atuais tão compilando ou se há algum erro. Como é um ambiente controlado e configurado, qualquer erro de compilação será culpa dos códigos incorretos, e não falta de biblioteca de um ambiente específico, por exemplo. É possível também ativar a build para pull requests, e assim garantir que qualquer código feito por terceiros ainda deixará as sources compiláveis.

Lá no [travis do projeto](https://travis-ci.org/malucooo/Otxserver-New)  em `more options -> settings`, deixa **OFF** apenas o **`Limit concurrent jobs`**, os outros 3 da parte GENERAL pode deixar ON. 

Qualquer dúvida pode falar.

--- 
@malucooo , the travis ci aims to aid the proccess of compiling and, optionally, test the code every time a new commit occurs. It automatically puts a badge in the README.md of the project signalizing if the current sources are compilable or if any error is occuring. As long as it is a controlled environment, any compilation error would be a fault source, not a misconfiguration or lost dependence on a specific environment. It's also possible to enable builds of the pull requests, and as a consequence we can assure that any third party code will still be compilable when the merge occurs.

Feel free to ask me anything about the process.
