### ISSUE TITLE
Why free bless ??

### ISSUE THREAD

**Issue by sn4tch0vsk** [malucooo/Otxserver-New#320]
Não há apenas os NPCS, mas também uma loja pra comprar blessings através de tibia coins, então qual o sentido de mudar o arquivo e colocar free bless ?

Mudar um arquivo que vai de conflito com outro sistema dentro do jogo, acho perda de tempo, afinal acho que o projeto tem q ser puxado mais para o lado real, e ai depois cada 1 personaliza do jeito que quiser. 

Apenas minha opinião

**Comment by darkjav** [comment]
You can have blessings up to a certain level and then later buy them with NPC and store.

**Comment by Andreeyyy** [comment]
-.-' Você entendeu oque o sistema faz?
