### ISSUE TITLE
imbuenment not working on some items

### ISSUE THREAD

**Issue by sonolusa** [malucooo/Otxserver-New#323]
Item imbuenment not working on some items like magic sword, emerald sword(Vampirism) - it says that i dont have the items required(similar to issue #250).
When equiped the weapons that work, on the skill tab, it does not show the percentage of the imbuement that is applyed, Mana Leech consuming 8 mana instead of regenerating 8%(For lvl 3 imbuement, didnt test  lvl 1 and 2). Not Working on spells(Critical, Vampirism Mana Leech).

**Comment by luminera** [comment]
The imbue is not 100%

**Comment by malucooo** [comment]
make for me plz!

**Comment by Eternal-Scripts** [comment]
Equip skills isn't done yet, you can done if you want or just wait.
About required items please tell us how you reproduce that.

**Comment by darkjav** [comment]
@sonolusa You can check this: https://github.com/malucooo/Otxserver-New/commit/65887322bea990f7c705dde5e00b49a55ee1ca4d

**Comment by sonolusa** [comment]
http://imgur.com/a/rG4yP

**Comment by darkjav** [comment]
@sonolusa The issue exist with the latest commit?
