### ISSUE TITLE
Store

### ISSUE THREAD

**Issue by meffon1** [malucooo/Otxserver-New#324]
Como eu coloco para que a pessoa compre a outfit com as 2 addons?
Quando eu coloco addon=3 ele não vende pq o char não tem a outfit :s

**Comment by darkjav** [comment]
Confirmed. This happen with Retro Outfits, because not exist addons.

**Comment by meffon1** [comment]
Sim
mas nesse caso é só mudar de addon pra outfit. 
GameStore.OfferTypes.OFFER_TYPE_OUTFIT_ADDON
GameStore.OfferTypes.OFFER_TYPE_OUTFIT


Mas não sei como colocar os dois

**Comment by meffon1** [comment]
Só deixar a linha assim
Consegui
{name = "Full Trophy Hunter Outfit", thingId = {male=957,female=958}, **addon = 3**, type = **GameStore.OfferTypes.OFFER_TYPE_OUTFIT**, price = 870, icons = {"f957.png", "f958.png"}},

**Comment by Eternal-Scripts** [comment]
GameStore.OfferTypes.OFFER_TYPE_OUTFIT...
