### ISSUE TITLE
Debug Client 10

### ISSUE THREAD

**Issue by Ondrake** [malucooo/Otxserver-New#329]
ao entrar no ot o cliente da debug, somente na versao 10.

**Comment by guilhermesidney** [comment]
oque aparece no debug?

**Comment by mattyx14** [comment]
wait to team adapt changes to lasted protocol

**Comment by Ondrake** [comment]
okey

**Comment by Ondrake** [comment]
![image](https://user-images.githubusercontent.com/9012031/28589449-99be57f6-7154-11e7-87e0-122c784340f4.png)

**Comment by darkjav** [comment]
@Ondrake 
You use the last commit and the latest client official of Tibia?

**Comment by Ondrake** [comment]
@darkjav yeah outdate client.

**Comment by darkjav** [comment]
Fixed in https://github.com/malucooo/Otxserver-New/commit/1c4c6b3189cf9bbb2bd32f155274904d1e4f1cf1
Thanks @Eternal-Scripts
