### ISSUE TITLE
Equip and DeEquip with imbuement

### ISSUE THREAD

**Issue by darkjav** [malucooo/Otxserver-New#334]
When players Equip or DeEquip items with the attribute ` script="imbuement.lua"` in movements.xml,
not work the attribute for add skills or others. But if you delete the code `script="imbuement.lua"` in the line, so work fine.

Example Elite Draken Helmet:
```
	<movevent event="Equip" itemid="12645" slot="head" level="100" function="onEquipItem" script="imbuement.lua">
		<vocation name="Paladin" />
		<vocation name="Royal Paladin" showInDescription="0" />
	</movevent>
	<movevent event="DeEquip" itemid="12645" slot="head" function="onDeEquipItem" script="imbuement.lua" />
```

EDIT:

Also i test imbuing system, example Rift Bow with 3 slots, but not work:

20:54 You see a rift bow (Range: 7, Atk +5, Hit% +3).
It can only be wielded properly by paladins of level 120 or higher.
Imbuements: (Powerful Strike 20:00h, Powerful Vampirism 20:00h, Powerful Void 20:00h).
It weighs 130.00 oz.
![window_test](https://user-images.githubusercontent.com/9681018/28651000-db53cdcc-7244-11e7-8062-115b94edada5.png)

Only work the Powerful Strike in this example.

I use the latest commit.

**Comment by Eternal-Scripts** [comment]
The imbuement system is 100%, only missing the conditions in lib at movements, you can wait any add the conditions or help us with this.

**Comment by jhonnyrs** [comment]
@Eternal-Scripts @darkjav I use the script below in the lib, but I have bug with items that already have attributes, example: shiny blade loses +1 sword when used imbue.

local condition = Condition(CONDITION_ATTRIBUTES, 10)
local condition1 = Condition(CONDITION_ATTRIBUTES, 20)
local condition2 = Condition(CONDITION_ATTRIBUTES, 30)
local condition3 = Condition(CONDITION_ATTRIBUTES, 40)
local condition4 = Condition(CONDITION_ATTRIBUTES, 50)
local condition5 = Condition(CONDITION_ATTRIBUTES, 60)
local condition6 = Condition(CONDITION_ATTRIBUTES, 70)
local condition7 = Condition(CONDITION_ATTRIBUTES, 80)
local condition8 = Condition(CONDITION_ATTRIBUTES, 90)


function onEquipWeaponImbuement(player, item)
	local weaponType = item:getType()
    for i = 1, weaponType:getImbuingSlots() do
    	local slotEnchant = item:getSpecialAttribute(i)
        if (slotEnchant ~= nil and slotEnchant ~= 0) then
        	local skillValue = item:getImbuementPercent(slotEnchant)
        	local typeEnchant = item:getImbuementType(i) or ""

	    				if (typeEnchant == "hitpointsleech") then
						condition:setParameter(CONDITION_PARAM_TICKS, -1)
						condition:setParameter(CONDITION_PARAM_SKILL_LIFE_LEECH_AMOUNT, skillValue)
						condition:setParameter(CONDITION_PARAM_SKILL_LIFE_LEECH_CHANCE, 100)
						player:addCondition(condition)
					end
					if (typeEnchant == "manapointsleech") then
						condition1:setParameter(CONDITION_PARAM_TICKS, -1)
						condition1:setParameter(CONDITION_PARAM_SKILL_MANA_LEECH_AMOUNT, skillValue)
						condition1:setParameter(CONDITION_PARAM_SKILL_MANA_LEECH_CHANCE, 100)
						player:addCondition(condition1)
					end
					if (typeEnchant == "criticaldamage") then
						condition2:setParameter(CONDITION_PARAM_TICKS, -1)
						condition2:setParameter(CONDITION_PARAM_SKILL_CRITICAL_HIT_DAMAGE, skillValue)
						condition2:setParameter(CONDITION_PARAM_SKILL_CRITICAL_HIT_CHANCE, 10)
						player:addCondition(condition2)
					end
					if (typeEnchant == "skillAxe") then
						condition3:setParameter(CONDITION_PARAM_TICKS, -1)
						condition3:setParameter(CONDITION_PARAM_SKILL_AXE, skillValue)
						player:addCondition(condition3)
					end
					if (typeEnchant == "skillClub") then
						condition4:setParameter(CONDITION_PARAM_TICKS, -1)
						condition4:setParameter(CONDITION_PARAM_SKILL_CLUB, skillValue)
						player:addCondition(condition4)
					end
					if (typeEnchant == "skillSword") then
						condition5:setParameter(CONDITION_PARAM_TICKS, -1)
						condition5:setParameter(CONDITION_PARAM_SKILL_SWORD, skillValue)
						player:addCondition(condition5)
					end
					if (typeEnchant == "skillDist") then
						condition6:setParameter(CONDITION_PARAM_TICKS, -1)
						condition6:setParameter(CONDITION_PARAM_SKILL_DISTANCE, skillValue)
						player:addCondition(condition6)
					end
					if (typeEnchant == "magiclevelpoints") then
						condition7:setParameter(CONDITION_PARAM_TICKS, -1)
						condition7:setParameter(CONDITION_PARAM_STAT_MAGICPOINTS, skillValue)
						player:addCondition(condition7)
					end
					if (typeEnchant == "skillShield") then
						condition8:setParameter(CONDITION_PARAM_TICKS, -1)
						condition8:setParameter(CONDITION_PARAM_SKILL_SHIELD, skillValue)
						player:addCondition(condition8)
					end



       				 end
			
    			end
	return true
end

function onDeEquipWeaponImbuement(player, item)
	local weaponType = item:getType()
    for i = 1, weaponType:getImbuingSlots() do
    	local slotEnchant = item:getSpecialAttribute(i)
        if (slotEnchant) then
        	local skillValue = item:getImbuementPercent(slotEnchant)
        	local typeEnchant = item:getImbuementType(i) or ""

		    			if (typeEnchant == "hitpointsleech") then
					
						player:removeCondition(CONDITION_ATTRIBUTES, 10)
					end
					if (typeEnchant == "manapointsleech") then
					
						player:removeCondition(CONDITION_ATTRIBUTES, 20)
					end
					if (typeEnchant == "criticaldamage") then
					
						player:removeCondition(CONDITION_ATTRIBUTES, 30)
					end
					if (typeEnchant == "skillAxe") then
				
						player:removeCondition(CONDITION_ATTRIBUTES, 40)
					end
					if (typeEnchant == "skillClub") then
			
						player:removeCondition(CONDITION_ATTRIBUTES, 50)
					end
					if (typeEnchant == "skillSword") then
				
						player:removeCondition(CONDITION_ATTRIBUTES, 60)
					end
					if (typeEnchant == "skillDist") then
					
						player:removeCondition(CONDITION_ATTRIBUTES, 70)
					end
					if (typeEnchant == "magiclevelpoints") then
						
						player:removeCondition(CONDITION_ATTRIBUTES, 80)
					end
					if (typeEnchant == "skillShield") then
					
						player:removeCondition(CONDITION_ATTRIBUTES, 90)
					end
				end
			end
	return true
end

**Comment by granoob** [comment]
Really the conditions of the friend jhonnyrs works perfectly but we have another problem the items that this with the function onEquipItem that in case it is fundamental to the attributes of the does not work example: Hat of te mad - receives ML +1, this bonus +1 has stopped To function

**Comment by jhonnyrs** [comment]
então, pra mim só falta isso para deixar 100%. cade os universitários? hehe

**Comment by granoob** [comment]
jhonnyrs, verdade o problema fica no moviment quando adicionamos o script="imbuement.lua"
ele anula o a função function="onEquipItem"

to tentando tambem uma forma pra fazer isso funcionar, eu vou tentar muda isso para action para ver como fica e caso de certo posto aqui

**Comment by jhonnyrs** [comment]
pensei em adicionar um if no moviments da lib para todos os items que tem atributos fixos, mas isso seria bem trabalhoso ;/

**Comment by granoob** [comment]
talvez uma solução, tentei pela action funcionou porem propicio a bug

**Comment by jhonnyrs** [comment]
@granoob tentei compilar aqui assim como falou e deu o seguinte erro.
[http://imgur.com/Q6LVOLU](url)

**Comment by granoob** [comment]
sim, eu esqueci de coloca o baseeent.ccp, o de cima tambem parece que nao resolver
o que cheguei mais aproximado foi deixa a explicação de cima de lado e indo por esse caminho

vai em baseevents.cpp
procure por 

bool sucess;

e troque por esse

bool success = true;

		pugi::xml_attribute scriptAttribute = node.attribute("script");
		pugi::xml_attribute function = node.attribute("function");
		if (scriptAttribute) {
			std::string scriptFile = "scripts/" + std::string(scriptAttribute.as_string());
			success = event->checkScript(basePath, scriptsName, scriptFile) && event->loadScript(basePath + scriptFile);
		}

		if (success && function) {
			success = event->loadFunction(function);
		}

		if (!success || !registerEvent(event, node)) {
			delete event;
		}
	}
	return true;
}

**Comment by granoob** [comment]
de outra forma não achei solução, para que consiga usa isso pelo moviments vai precisa modificar muito a source e não tenho muito conhecimento em C

**Comment by Olimpotibia** [comment]
i tried to add new condition to movements but all errors appear .. fk

**Comment by jlcvp** [comment]
We could call a kind of "super.OnEquipItem()" on the onEquipImbuement

**Comment by jlcvp** [comment]
I'm currently addressing this issue, expect an update soon

**Comment by jlcvp** [comment]
can anyone test my last commit?
[HERE](https://github.com/malucooo/Otxserver-New/commit/b46be75542c8c334a07d78f198f8cc1bfaeec362)
@Olimpotibia @darkjav @Eternal-Scripts @granoob @jhonnyrs

**Comment by jhonnyrs** [comment]
@jlcvp testei aqui e deu crash no server :/ mas acho que é por ai a solução... vou alterar umas coisas aqui e qualquer coisa aviso.

**Comment by Olimpotibia** [comment]
some news?

**Comment by Olimpotibia** [comment]
#thexamx you have solution you can help us? 💃
