### ISSUE TITLE
BIG BUG in Dawnport

### ISSUE THREAD

**Issue by MichelFigueira** [malucooo/Otxserver-New#337]
At the time of going to Main he is keeping the Skills.
Example: I played in Dawnport as Mage and advanced the magic level to 30. I chose knight to go to Main. 
I now have a Knight ML 30 :(

**Comment by darkjav** [comment]
Confirmed.

**Comment by Rockerszzz** [comment]
When the player passes through the portals of vocations, the skills must pass to the respective vocation's ability, right?

**Comment by MichelFigueira** [comment]
Yes @Rockerszzz.

I do not know the calculation that it does, but it follows exactly the change that the global is doing:
Ps: He starts the character no vocation with skill already

[http://imgur.com/a/7IlEN](http://imgur.com/a/7IlEN)

**Comment by marsoncschneider** [comment]
Lets work.

**Comment by marsoncschneider** [comment]
First part of dawnport add

**Comment by darkjav** [comment]
@MichelFigueira With latest commit, the skills are reset? For i closed this issue.
