### ISSUE TITLE
[11.40+] Impact Analyser

### ISSUE THREAD

**Issue by westwol** [malucooo/Otxserver-New#343]
Regarding the missing 11.4+ features, I started writing **impact analyser**. The system is not completed at all but this might help a bit. Everyone is welcome to collaborate though. First of all I am not an expert of the topic so **constructive criticism** is welcome.

**Impact Analyser** which provides you with information on healing and damage output within the last hour, as well as a healing and damage per second value
Source: [Tibia](http://tibia.com)

As impact analyser is client sided, server must push values called bytes to the client using **NetworkMessage()** in order to update tibia interface.

Taking a look to the Tibia 11.40 decompiled client:
```
      protected static const SIMPACTTRACKING:int = 204;

      protected function readSIMPACTTRACKING(param1:ByteArray) : void
      {
         var _loc2_:Boolean = param1.readBoolean();
         var _loc3_:uint = param1.readUnsignedInt();
      }
```
Source: [GitHub - Comendinha/Flash-News](https://github.com/comedinha/Flash-News/blob/c986ca7096b1ba7e8d4141167e3690e05801fccb/scripts/tibia/network/Communication.as#L2852)

Here we can notice that **IMPACTTRACKING** has two arguments: a _boolean_ and an _unsigned int_ . 

So we create a function in global.lua to handle that, it could be handled by sources though.
```
--[ Impact Analyser ]--
	-- Healing
	healthImpact = {} -- global table to insert data
	function Player.sendHealingImpact(self, damage)
		local msg = NetworkMessage()
 		msg:addByte(0xCC) -- DEC: 204
 		msg:addByte(0) -- 0 = healing / 1 = damage (boolean)
 		msg:addU32(damage) -- unsigned int
 		msg:sendToPlayer(self) 
 	end
 	-- Damage (not coded yet)
 	damageImpact = {} -- global table to insert data
	function Player.sendDamageImpact(self, damage)
		local msg = NetworkMessage()
 		msg:addByte(0xCC) -- DEC: 204
 		msg:addByte(1) -- 0 = healing / 1 = damage (boolean)
 		msg:addU32(damage) -- unsigned int
 		msg:sendToPlayer(self) 
 	end
 --[]--
```
**Parameters:** 
- self = userdata
- damage = damage dealed

Next step is to get values or data from the server, to calculate healing per second, I opted to insert values in a table for 2 seconds and then push them to the client using the function written before. Here's the script. As I stated before this could have been written better.
```
local function sendImpactToClient(self)
    local player = Player(self)
    if player ~= nil then
    	if healthImpact[self][1] > 0 then 
    		player:sendHealingImpact(healthImpact[self][1]) 
    		healthImpact[self] = nil 
    	end
    end
end

function onHealthChange(creature, attacker, primaryDamage, primaryType, secondaryDamage, secondaryType, origin)
	
	local player, modifier = creature:getPlayer(), attacker:getPlayer()
	local k, secondsToGetHealing, currentTime = player:getId(), 2, os.time()

	if player and modifier then
		-- if time table is null then insert current time
		if healthImpact[k] == nil then
			healthImpact[k] = healthImpact[k] or {0, currentTime}
		end
		if currentTime - healthImpact[k][2] < secondsToGetHealing then
			if primaryType == COMBAT_HEALING then
        		healthImpact[k][1] = healthImpact[k][1] + primaryDamage -- damage row
        	end
        else
        	sendImpactToClient(player:getId()) -- sending to client as secondToGetHealing passed
        end
	end
	return primaryDamage, primaryType, secondaryDamage, secondaryType
end
```
**Results:**

![hpdps](https://user-images.githubusercontent.com/17607894/28740569-efea6178-73cb-11e7-8b10-5199518ee855.png)

Regards,
westwol

**Comment by joseluis2g** [comment]
Awesome job you did here.

**Comment by malucooo** [comment]
very nice!

**Comment by Andreeyyy** [comment]
@Eternal-Scripts , @jlcvp , @malucooo

**Comment by jlcvp** [comment]
I can port it to C++ to avoid LuaScript environment allocation overhead for EVERY DAMAGE and HEALING on the server.

**Comment by jlcvp** [comment]
Correcting, the luaScript environment is already allocated anyway, I'll do it in Lua then.
