### ISSUE TITLE
Double Doubt

### ISSUE THREAD

**Issue by MichelFigueira** [malucooo/Otxserver-New#344]
In some cases when the character dies the error occurs:
```
[Error - mysql_real_query] Query: UPDATE `players` SET `level` = 69,`group_id` = 1,`vocation` = 0,`health` = 490,`healthmax` = 490,`experience` = 5109732,`lookbody` = 124,`lookfeet` = 0,`lookhead` = 78,`looklegs` = 124,`looktype` = 962,`lookaddons` = 0,`maglevel` = 27,`mana` = 2070,`manama
Message: Out of range value for column 'manaspent' at row 1
```

This error occurs only when the character dies and he is relog in the last place of the server salve.
What is the real function of the column "manaspent"? In some cases it has a big value and so the error occurs. My resolution was to change from INT for BIGINT.

Along with this problem some characters also run out of vocation when they die.
This second bug has a connection with the manaspent?
Anyone have an idea of what's going on to run out of vocations?

Thanks

**Comment by jlcvp** [comment]
The manaspent is used to calculate the next magic level percentage.

the vocation loss when dying was fixed.
