### ISSUE TITLE
Change to Rook

### ISSUE THREAD

**Issue by robsongabriel** [malucooo/Otxserver-New#345]
A question, I did not find a way to change to rook.
Someone help me? thks

**Comment by darkjav** [comment]
In RME map editor you need create a new Town with the name of Rookgaard, later in config.php of you website, put the number in setTown of the Town of Rookgaard.

**Comment by robsongabriel** [comment]
The map of malucooo project have rookguard lol and my gesior have rookguard configured but start in Dawnport
