### ISSUE TITLE
bug venda de itens

### ISSUE THREAD

**Issue by GoularPink** [malucooo/Otxserver-New#347]
ta mostrando itens que nem tem pra vender, e os preços tb...

http://prntscr.com/g1zuk8

**Comment by Eternal-Scripts** [comment]
Inválido... confirme direito... não atrapalhe-nos...

**Comment by GoularPink** [comment]
@Eternal-Scripts  eu fico caçando bug mano, testa ai po, vai no npc de yalahar de pot e veja

**Comment by Eternal-Scripts** [comment]
1. Você fica caçando BUG que tem no seu Servidor e espera que descobrirmos qual é.
2. ANTES de abrir um issue confirme com o último commit atualizado, sem nada alterado.
3. A próxima vez você será banido desse repositório e do OTX oficial.

Aviso foi dado, nós fazemos de tudo para trazer um datapack atualizado e você nem se da o trabalho de ajudar direito.
