### ISSUE TITLE
Missing items in Dawnport

### ISSUE THREAD

**Issue by RichardMuller** [malucooo/Otxserver-New#355]
Quando um novo personagem é criado, ele passa por aquele tutorial onde tem que clicar para abrir as coisas, usar as setas para andar, etc, mas tem uma parte onde se o personagem morrer, ele volta para o mesmo lugar e sem a corda e também não há os itens fixos no chão, sendo assim o personagem fica preso. Ele não consegue subir pois está sem corda e se descer, morre para os bixos e acaba voltando pro mesmo lugar.

![capturar](https://user-images.githubusercontent.com/7664609/28843727-9fac2862-76d8-11e7-8bf6-11825c05ee70.JPG)

**Comment by Andreeyyy** [comment]
O tutorial tem que ser retirado no login.php

**Comment by darkjav** [comment]
@RichardMuller You need only add a Stairs in the map or add rope in firstitems.lua
