### ISSUE TITLE
Tibia 10 and 11.4x Login problem

### ISSUE THREAD

**Issue by ledther0n** [malucooo/Otxserver-New#356]
I'm getting a debug when I try to enter in Tibia 10 : "unknown packet type during login"

**Comment by darkjav** [comment]
Sometimes happen, you need restart the OT.

**Comment by ledther0n** [comment]
Still happening, I have restarted at least 10 times

**Comment by darkjav** [comment]
You use latest commit? Or only you adapted the code in you own project?

**Comment by ledther0n** [comment]
I used a 7 days old version, now I tried with the latest and still the same problem

**Comment by darkjav** [comment]
Confirmed.
Sometimes happen, the unique solution is restart the hosting.

Any idea?
