### ISSUE TITLE
Error in tile - Dawnport

### ISSUE THREAD

**Issue by darkjav** [malucooo/Otxserver-New#357]
@marsoncschneider 
1.- When player walk for get vocation, appear this error:

> Lua Script Error: [MoveEvents Interface]
> data/movements/scripts/vocationtrial.lua:onStepIn
> data/movements/scripts/vocationtrial.lua:150: bad argument #1 to 'pairs' (table expected, got nil)
> stack traceback:
>         [C]: in ?
>         [C]: in function 'pairs'
>         data/movements/scripts/vocationtrial.lua:150: in function 'changeVocation'
>         data/movements/scripts/vocationtrial.lua:247: in function <data/movements/scripts/vocationtrial.lua:240>

**Comment by marsoncschneider** [comment]
I think because player have no bp... Will fix fast.

**Comment by darkjav** [comment]
The fix https://github.com/malucooo/Otxserver-New/commit/af7bb325f3cc37f223de1218a87d702205e9c55f not work, still hapen the same.

> Lua Script Error: [MoveEvents Interface]
> data/movements/scripts/vocationtrial.lua:onStepIn
> data/movements/scripts/vocationtrial.lua:150: bad argument #1 to 'pairs' (table expected, got nil)
> stack traceback:
>         [C]: in ?
>         [C]: in function 'pairs'
>         data/movements/scripts/vocationtrial.lua:150: in function 'changeVocation'
>         data/movements/scripts/vocationtrial.lua:248: in function <data/movements/scripts/vocationtrial.lua:240>

**Comment by marsoncschneider** [comment]
I could not get the same error. Are you using which client version?

**Comment by marsoncschneider** [comment]
I'm using client 11.40

**Comment by marsoncschneider** [comment]
![image](https://user-images.githubusercontent.com/30011438/28880057-3d52bb66-777a-11e7-8c53-d27b531a4536.png)
fiz um char do level 1 ao 8 mudando de vocaçao varias vezes, inclusive no npc do barco. sem errors.

**Comment by marsoncschneider** [comment]
![image](https://user-images.githubusercontent.com/30011438/28880156-8ac3c1b0-777a-11e7-80d0-d260f28fef41.png)


I made a char from level 1 to 8 changing vocation several times, with and without backpack, including in the npc of the boat. Without errors.

**Comment by marsoncschneider** [comment]
However I found a small bug that was fixed, and I already took advantage to reduce the code. Test again because I believe that now there will be no console error

**Comment by darkjav** [comment]
@marsoncschneider 
Bro, i use the client 11.40.5409,
in console appear the same error:

> Lua Script Error: [MoveEvents Interface]
> data/movements/scripts/vocationtrial.lua:onStepIn
> data/movements/scripts/vocationtrial.lua:134: bad argument #1 to 'pairs' (table expected, got nil)
> stack traceback:
>         [C]: in ?
>         [C]: in function 'pairs'
>         data/movements/scripts/vocationtrial.lua:134: in function 'changeVocation'
>         data/movements/scripts/vocationtrial.lua:232: in function <data/movements/scripts/vocationtrial.lua:224>

In your config.lua, how you have this?
warnUnsafeScripts = true
convertUnsafeScripts = false

Because with that values, you can see the error in console, also i use Ubuntu 14.04, not windows.

**Comment by marsoncschneider** [comment]
-- Scripts
warnUnsafeScripts = true
convertUnsafeScripts = true

**Comment by marsoncschneider** [comment]
try with this

**Comment by marsoncschneider** [comment]
![image](https://user-images.githubusercontent.com/30011438/28902559-1029f6f2-77d6-11e7-96d3-8b0ebdb544a1.png)
in ubunty 16.04 dont show console error too. use all new datapack

**Comment by darkjav** [comment]
@marsoncschneider 
Solved.
Thanks for you attention and you time.
