### ISSUE TITLE
Bug List

### ISSUE THREAD

**Issue by robsongabriel** [malucooo/Otxserver-New#358]
I found bugs. I'll send you a list below with as many details as possible. Unfortunately I do not have enough knowledge to correct it, but the information stays for everyone. Thanks!

- [ ] POI Quest does not working as Global.
        - The stone to get out of the DT City it's not there. Allows going to the second part, without pulling the levers.

- [ ] Mounts Itens for Quests are breaking.
        - The Lion's Heart and Golem Wrench breaking.

- [ ] BattleField Event no have return teleport.
        - If the player enters teleport he can not return.

- [ ] Boss The Welter not working as Global.
        - Do not make eggs and do not summon hydras. Ps: I believe Shlorg it's also this way.

- [ ] Monster Glooth Bandit have Incorrect Attack values
        - His attack is very low

- [ ] Error in Create Group VIP List.
        - When I try to create the group, the error occurs: You have already reached the maximum of groups you can create yourself. Ps: Not have 1 Group created.

- [ ] NPC Tarun does not exist.
        - Is a NPC Merchant of The Lost Brother Quest.

- [ ] NPC Yasir does not working as Global.
        - Are in 3 locations at the same time. Not switching like the global.

- [ ] NPC Rashid does not working as Global.
        - It has the random spawn, without following the pattern of days

Console errors:

- [ ] Problem with NPC.

> Lua Script Error: [Npc interface]
> data/npc/scripts/Captain Breezelda.lua:onCreatureSay
> data/npc/lib/npcsystem/customModules.lua:41: bad argument #1 to 'random' (interval is empty)
> stack traceback:
> [C]: in ?
> [C]: in function 'random'
> data/npc/lib/npcsystem/customModules.lua:41: in function 'callback'
> data/npc/lib/npcsystem/keywordhandler.lua:31: in function 'processMessage'
> data/npc/lib/npcsystem/keywordhandler.lua:186: in function 'processNodeMessage'
> data/npc/lib/npcsystem/keywordhandler.lua:161: in function 'processMessage'
> data/npc/lib/npcsystem/npchandler.lua:429: in function 'onCreatureSay'
> data/npc/scripts/Captain Breezelda.lua:7: in function <data/npc/scripts/Captain Breezelda.lua:7>

- [ ] Problem with Werewolf Helmet, not is possible echanted with moonlight crytal:

> Lua Script Error: [Action Interface]
> data/actions/scripts/other/enchanting.lua:onUse
> data/actions/scripts/other/enchanting.lua:171: attempt to index a nil value
> stack traceback:
>         [C]: in function '__index'
>         data/actions/scripts/other/enchanting.lua:171: in function <data/actions/scripts/other/enchanting.lua:116>

I'm just passing some bugs I found. Only to help the community.
No are required type messages . "Solve the bug then". It was the way I found it to help.
Sorry my English. Thanks!

- I have all updated github files and unmodified.

Images:

![untitled](https://user-images.githubusercontent.com/30556179/28880403-ecfc468e-7772-11e7-9355-e69034cd13da.png)
![untitled3](https://user-images.githubusercontent.com/30556179/28880400-ece99afc-7772-11e7-8799-f672fe5b866b.png)

**Comment by marsoncschneider** [comment]
The bug of no vocation was fixed

**Comment by joseluis2g** [comment]
the vip list stuff is cus there is not yet implemented...

**Comment by robsongabriel** [comment]
Ok I go test now! thanks

**Comment by robsongabriel** [comment]
Lost Vocation after dead solved. Thanks Marson

**Comment by flaviiojr** [comment]
pqp, os caras fazem uma lista, até entendendo que tenha bugs criticos, mas porra! Pequenos detalhes?! Nada que um pouco de leitura e esforço não resolva, sinceramente... Povo folgado

**Comment by luanluciano93** [comment]
projeto é open para isso mesmo, poste tudo que ver de errado. Final de semana estou em cada e fixo todos eles. valeu

**Comment by Andreeyyy** [comment]
@robsongabriel 

Event hall entry has information from another server.

another server = server test of oficial project
I'm mapper and Its my server and i use from test map from release. :) 

No problem, if you don't like you can remove this.

**Comment by Andreeyyy** [comment]
Exura ico is correct
exhaustion="1000"

**Comment by Andreeyyy** [comment]
Small problem in Reward Quest.

This not problem, if don't like this, choose the value of this item.

**Comment by MichelFigueira** [comment]
@Andreeyyy Is it no problem to drop two f-hat from a single ferrumbras? Explain it to me lol

**Comment by Andreeyyy** [comment]
@MichelFigueira  o seu merdinha, primeiro você ve com quem você ta falando pra depois falar eu tentar ajudar mais. 
Entre no forum que la tem e a explicação sobre o Drop Loot do Reward do Ferumbras Hat.
Não tem a ver com .xml do Monstro e sim com o Reward System Drop Chance. Fica Dica.

Em vez de colocar os erros aqui pra gente arrumar, e querer pagar de foda, comece a dar commit corrigindo os erros e ajudando de verdade. Apontar os erros temos 5000 fazendo isso, ajudando e montando as coisas da pra contar nos dedos quantos são.

**Comment by joseluis2g** [comment]
You guys want it all free, you can't even handle a simple error code by yourselves and then you scream for help and blame all others if they do not help you, f*ck you off.

**Comment by Andreeyyy** [comment]
@MichelFigueira  Editei seu "Issue" e deixei os problemas reais e que realmente ainda estão com Problema.

**Comment by joseluis2g** [comment]
and yes, lemme show you this feru hat pic.
![only one hat](https://user-images.githubusercontent.com/7506164/28997601-95608252-79e6-11e7-9aac-bddb5e5ed6f0.jpg)

**Comment by MichelFigueira** [comment]
> @MichelFigueira Editei seu "Issue" e deixei os problemas reais e que realmente ainda estão com Problema.

@Andreeyyy Acabou de comprovar que não sabe o que fala... O Issue nao é meu filhao

**Comment by MichelFigueira** [comment]
Me retiro da conversa mas deixo aqui a imagem do seu profile que só confirma que voce fala mais do que ajuda...
http://imgur.com/a/mVviR

vlw flw

**Comment by robsongabriel** [comment]
Meu deus infelizmente nao vou nem comentar mais
Tentei ajudar da minha forma, nao tenho intensao de criar servidor nem nada, apenas ajudar da minha forma. Mas o pessoal ai nao respeita e querem ser maiores que os outros. O que ganham com isso?
Deletaram e editaram todo meu post, deixando uma desorganizacao para quem realmente quer ajudar....

@joseluis2g Test with two players, giving good amounts damage. You will see the two win f-hat. One for each player, not two for one player

@malucooo Se poder deletar o Issues, ja que nao vai levar a lugar algum isso aqui. Obrigado!

**Comment by joseluis2g** [comment]
You have to edit the system, no one will do that for you, that system was created by someone called NonSequitur like 2 years ago and you just want to someone do this for you.

**Comment by robsongabriel** [comment]
@joseluis2g What is the purpose of the project? What is the meaning of open source?

> 
projeto é open para isso mesmo, poste tudo que ver de errado. Final de semana estou em cada e fixo todos eles. valeu
--

Gracias!
