### ISSUE TITLE
Items with charge and duration

### ISSUE THREAD

**Issue by GoularPink** [malucooo/Otxserver-New#359]
Example item:

`<item id="2393" article="a" name="giant sword">
		<attribute key="description" value="This sword has been forged by ancient giants." />
		<attribute key="weight" value="18000" />
		<attribute key="defense" value="22" />
		<attribute key="attack" value="46" />
		<attribute key="weaponType" value="sword" />
		<attribute key="slotType" value="two-handed" />
                <attribute key="charges" value="250" />
		<attribute key="showcharges" value="1" />
		<attribute key="duration" value="900" />
		<attribute key="showduration" value="1" />
		<attribute key="decayTo" value="0" />
	</item>`

When charges is gone it will be 1 until the time end.

**Comment by granoob** [comment]
qual a finalidade, é sobre a imbuement, se pode trocar a <attribute key="decayTo" value="0" />
para <attribute key="decayTo" value="2393" />

assim toda vez que acabar a duração sera trocado por ela novamente, porem o enchated sera vazio

**Comment by GoularPink** [comment]
The problem is: The item dont disappear when the charges is gone, its to disappear. 
attribute key="charges" value="250"

If the item have duration like my example, the item dont disappear, only will disappear when the time end not disappear if the charge end, cuz charge will be 1 forever

**Comment by jlcvp** [comment]
The charges in weapons is consumed on every hit, right? We can solve this using the same type of event that is handled on Ice Rapier.

**Comment by GoularPink** [comment]
@jlcvp  right, but if the item have duration too (duration and charge on item), when we got 1 charge this dont disappear, stay with 1 charge ever or until duration is gone

**Comment by GoularPink** [comment]
@jlcvp  where we verify this? in the weapons.xml we have: melee id="2396" action="removecharge" />
but this is not enough.
try yourself to put one duration on ice rapier for decayTo 0

**Comment by jlcvp** [comment]
looking at the sources, I've found that it really has to do with the charge behavior. It'd never destroy an item with the decayTo=0 property, commited a fix to change this. Can you test this for me? I'm at work now and opening a tibia window would be pretty shortcut to be fired.

**Comment by jlcvp** [comment]
@GoularPink this commit should fix the ice rapier as well

**Comment by GoularPink** [comment]
@jlcvp 
testei aqui e o item não está decaindo mais, quando acaba as charges ele some, mas não funciona a duração agora kk

e outro bugzin também, não da pra por duração nas munições, se por a contagem para e também não da pra reagrupar as bolts, tem que ter essa função pq lançou as novas bolts com duração

**Comment by Olimpotibia** [comment]
and it can use to wand of darkness?

**Comment by joseluis2g** [comment]
whats the bug?
