### ISSUE TITLE
The Welter Raid with wrong monster on spawn

### ISSUE THREAD

**Issue by Rockerszzz** [malucooo/Otxserver-New#36]
data/raids/scripts/the welter.lua Change:

function onRaid()
 local monster = Game.createMonster("**weakened shlorg**", Position(33026, 32660, 5))
 monster:setReward(true)
end

for:

function onRaid()
 local monster = Game.createMonster("**The welter**", Position(33026, 32660, 5))
 monster:setReward(true)
end

**Comment by lamonato29** [comment]
The solution is proposed on Pull Requests.. Thank you !!
