### ISSUE TITLE
Coals Shlorg

### ISSUE THREAD

**Issue by GoularPink** [malucooo/Otxserver-New#360]
Os coal basin não existem na cave pra matar o Shlorg, presumo que esteja errada a raid, pois o boss vem na forma imortal, só depois que acender os basins que nao existem o boss fica na forma mortal

posição da cave: 33171, 31728, 9

**Comment by flaviiojr** [comment]
Faz mano! Isso são pequenos detalhes, se tu quer algo bom e bem feito, paga pra ser feito!
Ora porra

**Comment by luanluciano93** [comment]
projeto é open para isso mesmo, poste tudo que ver de errado. Final de semana estou em cada e fixo todos eles. valeu

**Comment by GoularPink** [comment]
@luanluciano93  parabéns pela resposta mano, admiro pessoas assim, e pro @flaviiojr  ali em cima, se eu soubesse não postaria ajuda e sim a solução meu amigo, passar bem.

**Comment by biaggio12** [comment]
Can you guys please use english while reporting an issue ? Cuz i can't understand anything tho i can't help you with issue

**Comment by GoularPink** [comment]
@biaggio12  The coal basings doenst exists on this cave33171, 31728, 9 , we want to put fire there so we can kill the boss, the boss before was imunity. after used the basings we can kill the boss..
