### ISSUE TITLE
Missing database tables

### ISSUE THREAD

**Issue by biaggio12** [malucooo/Otxserver-New#361]
There is a lack of DB tables in DATABASE.sql

> [Error - mysql_real_query] Query: ALTER TABLE `players` ADD COLUMN `prey_stamina_1` int(11) DEFAULT NULL
Message: Duplicate column name 'prey_stamina_1'
[Error - mysql_real_query] Query: ALTER TABLE `players` ADD COLUMN `prey_stamina_2` int(11) DEFAULT NULL
Message: Duplicate column name 'prey_stamina_2'
[Error - mysql_real_query] Query: ALTER TABLE `players` ADD COLUMN `prey_stamina_3` int(11) DEFAULT NULL
Message: Duplicate column name 'prey_stamina_3'
[Error - mysql_real_query] Query: ALTER TABLE `players` ADD COLUMN `prey_column` smallint(6) NOT NULL DEFAULT 1
Message: Duplicate column name 'prey_column'
[Error - mysql_real_query] Query: ALTER TABLE `players` ADD COLUMN `bonus_reroll` int(11) DEFAULT NULL
Message: Duplicate column name 'bonus_reroll'
[Error - mysql_real_query] Query: ALTER TABLE `players` ADD COLUMN `xpboost_stamina` smallint(5) DEFAULT NULL
Message: Duplicate column name 'xpboost_stamina'
[Error - mysql_real_query] Query: ALTER TABLE `players` ADD COLUMN `xpboost_value` tinyint(4) DEFAULT NULL
Message: Duplicate column name 'xpboost_value'
> Database has been updated to version 26.
> Updating database to version 26 (Blessings Dialog System)
[Error - mysql_real_query] Query: CREATE TABLE `blessings_history` (`id` int(11) NOT NULL, `player_id` int(11) NOT NULL, `blessing` tinyint(4) NOT NULL, `loss` tinyint(1) NOT NULL, `timestamp` int(11) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=latin1;
Message: Table 'blessings_history' already exists
[Error - mysql_real_query] Query: ALTER TABLE `players` ADD COLUMN `blessings1` tinyint(4) NOT NULL DEFAULT '0' AFTER `blessings`
Message: Duplicate column name 'blessings1'
[Error - mysql_real_query] Query: ALTER TABLE `players` ADD COLUMN `blessings2` tinyint(4) NOT NULL DEFAULT '0' AFTER `blessings1`
Message: Duplicate column name 'blessings2'
[Error - mysql_real_query] Query: ALTER TABLE `players` ADD COLUMN `blessings3` tinyint(4) NOT NULL DEFAULT '0' AFTER `blessings2`
Message: Duplicate column name 'blessings3'
[Error - mysql_real_query] Query: ALTER TABLE `players` ADD COLUMN `blessings4` tinyint(4) NOT NULL DEFAULT '0' AFTER `blessings3`
Message: Duplicate column name 'blessings4'
[Error - mysql_real_query] Query: ALTER TABLE `players` ADD COLUMN `blessings5` tinyint(4) NOT NULL DEFAULT '0' AFTER `blessings4`
Message: Duplicate column name 'blessings5'
[Error - mysql_real_query] Query: ALTER TABLE `players` ADD COLUMN `blessings6` tinyint(4) NOT NULL DEFAULT '0' AFTER `blessings5`
Message: Duplicate column name 'blessings6'
[Error - mysql_real_query] Query: ALTER TABLE `players` ADD COLUMN `blessings7` tinyint(4) NOT NULL DEFAULT '0' AFTER `blessings6`
Message: Duplicate column name 'blessings7'
[Error - mysql_real_query] Query: ALTER TABLE `players` ADD COLUMN `blessings8` tinyint(4) NOT NULL DEFAULT '0' AFTER `blessings7`
Message: Duplicate column name 'blessings8'
> Database has been updated to version 27.
> Updating database to version 27 (Fix bonus reroll and wrap/unwrap casks)
[Error - mysql_real_query] Query: ALTER TABLE `store_history` ADD COLUMN `timestamp` int(11) NOT NULL DEFAULT 0 AFTER `time`
Message: Duplicate column name 'timestamp'

Can someone fix it i have absolutely 0 knowledge of SQL

**Comment by jlcvp** [comment]
This is not an error, it's just telling you that your database version already has the columns we need to run the server. Just run again e it'll work.
