### ISSUE TITLE
CRASH ON VOCATIONS.XML

### ISSUE THREAD

**Issue by treeckoo** [malucooo/Otxserver-New#363]
The exe send an error when is running I cant see it i need to record screen so this have on line 10 on vocations,xml

--- double << so its error i cant put o this editor <<vocation name
I think is that. 

I have a question too, How can do a command !bless on this new system?

Sorry my bad english.

**Comment by darkjav** [comment]
Fixed in: https://github.com/malucooo/Otxserver-New/commit/b5241894510987ffc625176ba54fdf41a5975484
