### ISSUE TITLE
Ghostlands and Banshee quest paths deleted

### ISSUE THREAD

**Issue by sn4tch0vsk** [malucooo/Otxserver-New#365]
![bug](https://user-images.githubusercontent.com/27328490/28999461-7a7dbbba-79fc-11e7-99c3-42297efb8588.jpg)
![bug 2](https://user-images.githubusercontent.com/27328490/28999519-021a8fc0-79fe-11e7-801c-cf046f0d47ff.jpg)

Someone screwed big part of the ghostlands and banshee quest paths, south of carlin. The positions are in the pics.

PS: There're a lot more deleted parts, not just these ones in the pics.

**Comment by Andreeyyy** [comment]
Corrected
