### ISSUE TITLE
wrap furniture items not working

### ISSUE THREAD

**Issue by Rockerszzz** [malucooo/Otxserver-New#37]
maybe you can find the solution here: https://github.com/otland/forgottenserver/pull/2033

**Comment by flaviohulk** [comment]
Create a pull request with the modifications in source, and add here in github :+1:

**Comment by Rockerszzz** [comment]
I don't have any experience editing source files, im just reporting the issue for those who can solve him.

**Comment by darkjav** [comment]
@Rockerszzz 
I compile with that code, and not work, so we need wait that somebody completed the code.

**Comment by Rockerszzz** [comment]
Wrap system added, close this issue @malucooo

**Comment by evalio** [comment]
[Warning - Events::load] Unknown player method: onWrapItem

Does this system works for sure? Because for me not... (using newest master release).

**Comment by Rockerszzz** [comment]
ok, thanks for report, Malucooo are working to fix it

**Comment by darkjav** [comment]
@Rockerszzz 
Why close this?, really not work the wrap system...
