### ISSUE TITLE
Summon Help --  First step --

### ISSUE THREAD

**Issue by granoob** [malucooo/Otxserver-New#374]
<-?xml version="1.0" encoding="UTF-8"?>
<-monster name="Emberwing" nameDescription="a Emberwing" race="undead"  speed="500" manacost="0">
	<health now="15000" max="15000" />
	<look type="992" />
	<targetchange interval="2000" chance="20" />
	<flags>
       
		<flag summonable="1" />
		<flag attackable="1" />
		<flag hostile="0" />
		<flag illusionable="0" />
		<flag convinceable="0" />
		<flag pushable="1" />
		<flag canpushitems="1" />
		<flag canpushcreatures="1" />
		<flag staticattack="98" />
		<flag targetdistance="2" />
		<flag runonhealth="9000" />
	</flags>
	
	<attacks>
		<attack name="holy" interval="200" chance="25" skill="153"  min="-100" max="-190"/>
		<attack name="Divine Caldera" interval="500" chance="15" length="10" spread="10" target="1" min="-200" max="-500">
      			<attribute key="areaEffect" value="exevo mas san" />
    		</attack>
			<attack name="Great Fireball" interval="500" chance="16" radius="7" min="-50" max="-500">
      			<attribute key="areaEffect" value="firearea" />
    		</attack>
			<attack name="Divine Caldera" interval="2000" chance="30" target="1" radius="4" min="-100" max="-240">
			<attribute key="areaEffect" value="exevo mas san" />
		
			</attack>
			
	
			
	</attacks>
	
	<defenses armor="55" defense="95">
		<defense name="healing" interval="3000" chance="35" min="80" max="400">
			<attribute key="areaEffect" value="blueshimmer" />
		</defense>
		
	</defenses>
	<elements>
		<element firePercent="0" />
		<element earthPercent="0" />
		<element energyPercent="0" />
		<element deathPercent="0" />
		<element physicalPercent="0" />
		<element holyPercent="0" />
		<element icePercent="0" />
	</elements>
	<immunities>
		<immunity paralyze="1" />
		<immunity invisible="1" />
	</immunities>

</monster>

<-?xml version="1.0" encoding="UTF-8"?>
<-monster name="Thundergiant" nameDescription="a Thundergiant" race="undead"  speed="500" manacost="0">
	<health now="20000" max="20000" />
	<look type="994" />
	<targetchange interval="2000" chance="20" />
	<flags>
       
		<flag summonable="0" />
		<flag attackable="1" />
		<flag hostile="0" />
		<flag illusionable="0" />
		<flag convinceable="1" />
		<flag pushable="1" />
		<flag canpushitems="1" />
		<flag canpushcreatures="1" />
		<flag staticattack="98" />
		<flag targetdistance="0" />
		<flag runonhealth="9000" />
	</flags>
	
	<attacks>
		<attack name="melee" interval="200" chance="25" skill="153"  min="-100" max="-310"/>
		<attack name="Front Sweep" interval="500" chance="23" length="3" spread="3" min="-100" max="-500">
      			<attribute key="areaEffect" value="lifedrain" />
    		</attack>
		<attack name="energy" interval="2000" chance="15" range="7" length="2" min="-75" max="-705">
			<attribute key="shootEffect" value="energyball" />
			<attribute key="areaEffect" value="energy" />
		</attack>	
		
			
	</attacks>
	
	<defenses armor="55" defense="95">
		<defense name="healing" interval="3000" chance="25" min="80" max="600">
			<attribute key="areaEffect" value="blueshimmer" />
		</defense>
		<defense name="Challenge" interval="100" chance="15" >
			<attribute key="areaEffect" value="exeta res" />
		</defense>
		
	</defenses>
	<elements>
		<element firePercent="0" />
		<element earthPercent="0" />
		<element energyPercent="0" />
		<element deathPercent="0" />
		<element physicalPercent="0" />
		<element holyPercent="0" />
		<element icePercent="0" />
	</elements>
	<immunities>
		<immunity paralyze="1" />
		<immunity invisible="1" />
	</immunities>

</monster>

<-?xml version="1.0" encoding="UTF-8"?>
<-monster name="Skullfrost" nameDescription="a Skullfrost" race="undead"  speed="500" manacost="0">
	<health now="10000" max="10000" />
	<look type="991" />
	<targetchange interval="2000" chance="20" />
	<flags>
       
		<flag summonable="1" />
		<flag attackable="1" />
		<flag hostile="0" />
		<flag illusionable="0" />
		<flag convinceable="0" />
		<flag pushable="1" />
		<flag canpushitems="1" />
		<flag canpushcreatures="1" />
		<flag staticattack="98" />
		<flag targetdistance="3" />
		<flag runonhealth="9000" />
	</flags>
	
	<attacks>
		<attack name="death" interval="200" chance="25" skill="153"  min="-100" max="-280"/>
		<attack name="death" interval="500" chance="10" length="6" spread="0" target="1" min="-200" max="-500">
      			<attribute key="areaEffect" value="mortarea" />
    		</attack>
			<attack name="death" interval="500" chance="10" radius="7" min="-50" max="-500">
      			<attribute key="areaEffect" value="mortarea" />
    		</attack>
			<attack name="ice" interval="2000" chance="15" target="1" radius="7" min="-100" max="-240">
			<attribute key="areaEffect" value="icearea" />
		</attack>
			<attack name="ice" interval="2000" chance="15" radius="7" target="0" min="-60" max="-400">
			<attribute key="areaEffect" value="icetornado" />
		</attack>
			
			
	
			
	</attacks>
	
	<defenses armor="55" defense="95">
		<defense name="healing" interval="3000" chance="25" min="80" max="400">
			<attribute key="areaEffect" value="blueshimmer" />
		</defense>
		
	</defenses>
	<elements>
		<element firePercent="0" />
		<element earthPercent="0" />
		<element energyPercent="0" />
		<element deathPercent="0" />
		<element physicalPercent="0" />
		<element holyPercent="0" />
		<element icePercent="0" />
	</elements>
	<immunities>
		<immunity paralyze="1" />
		<immunity invisible="1" />
	</immunities>

</monster>

<-?xml version="1.0" encoding="UTF-8"?>
<-monster name="Grovebeast" nameDescription="Grovebeast" race="undead"  speed="500" manacost="3000">
	<health now="20000" max="20000" />
	<look type="993" />
	<targetchange interval="2000" chance="20" />
	<flags>
       
		<flag summonable="1" />
		<flag attackable="1" />
		<flag hostile="0" />
		<flag illusionable="0" />
		<flag convinceable="0" />
		<flag pushable="1" />
		<flag canpushitems="1" />
		<flag canpushcreatures="1" />
		<flag staticattack="98" />
		<flag targetdistance="0" />
		<flag runonhealth="9000" />
	</flags>
	
	<attacks>
		<attack name="melee" interval="200" chance="45" skill="153"  min="-100" max="-300"/>
		<attack name="earth" interval="1000" chance="10" target="1" spread="0" min="0" max="-800">
			<attribute key="areaEffect" value="stones" />
		</attack>
		<attack name="lifedrain" interval="2000" chance="20" target="1" range="1" min="-50" max="-200">
			<attribute key="areaEffect" value="redshimmer" />
		</attack>
		<attack name="earth" interval="2000" chance="15" length="2" spread="3" min="-250" max="-500">
			<attribute key="areaEffect" value="carniphila" />
		</attack>
			
	<attack name="Challenge" interval="500" chance="3" radius="8">
      			<attribute key="areaEffect" value="exeta res" />
    		</attack>
			
	</attacks>
	
	<defenses armor="78" defense="95">
		<defense name="healing" interval="3000" chance="16" min="80" max="600">
			<attribute key="areaEffect" value="blueshimmer" />
		</defense>
		<defense name="Challenge" interval="100" chance="15" >
			<attribute key="areaEffect" value="exeta res" />
		</defense>
		
	</defenses>
	<elements>
		<element firePercent="0" />
		<element earthPercent="0" />
		<element energyPercent="0" />
		<element deathPercent="0" />
		<element physicalPercent="0" />
		<element holyPercent="0" />
		<element icePercent="0" />
	</elements>
	<immunities>
		<immunity paralyze="1" />
		<immunity invisible="1" />
	</immunities>

</monster>
`

Now the magic

		<instant group="support" spellid="259" name="Summon Creature EK" words="utevo gran res eq" lvl="200" mana="1000"  cooldown="1080000" groupcooldown="4000" needlearn="0" script="support/pet.lua">
		<vocation name="Knight" />
		<vocation name="Elite Knight"/>
	</instant>

This part that I need help because it is incomplete, I did the script but can not put it in a way that summon, do not attack player and die in 15 minutes and disappear

Now see the script

 local combat = createCombatObject()
setCombatParam(combat, COMBAT_PARAM_TYPE, COMBAT_NONE)
setCombatParam(combat, COMBAT_PARAM_EFFECT, CONST_ME_BLOCKHIT)

local area = createCombatArea(AREA_CROSS1X1)
setCombatArea(combat, area)

local maxsummons = 1

function onCastSpell(cid, var)
doCreatureSay(cid, "My Power your Power", TALKTYPE_ORANGE_1)
	local summoncount = getCreatureSummons(cid)
	if #summoncount < 1 then
		for i = 1, maxsummons - #summoncount do
			local mid = doSummonCreature("eq", getCreaturePosition(cid))
    			if mid == false then
				return combat:execute(creature, var)
			end
			doConvinceCreature(cid, mid)
                  end
	end
	return doCombat(cid, combat, var)
end

**Comment by granoob** [comment]
fix rapido - onde ta <flag summonable="1" /> mude para <flag summonable="0" />

e onde ta <flag convinceable="0" /> muda para <flag convinceable="1" />

por fim onde ta <-?xml version="1.0" encoding="UTF-8"?>
<-monster name="Grovebeast" nameDescription="Grovebeast" race="undead" speed="500" manacost="3000">

para <?xml version="1.0" encoding="UTF-8"?>
<monster name="Grovebeast" nameDescription="Grovebeast" race="undead" speed="500" manacost="3000">

**Comment by joseamaya1** [comment]
http://imgur.com/cJBQ4eE

**Comment by granoob** [comment]
Galera ando sem tempo de pratica mais testes estou colocando a voces a pa do meu projetos para que possamos se ajudar, visando o complimento de ajuste da summon estava trabalhando nessa parte, não sei se esta completo ou se ta faltando algo assim testem ai quando eu tive mais tempo continuo as correções ou talvez os amigos do projetos

so limbrando que uso todos os recursos da 11.42, porem usando apenas o protocolo ate 11.20, tenho um source propria, mais a base inicial foi a OTX na 10.98

primeiramente vamos ao scripts

na pasta modules>scripts

`
function onRecvbyte(player, msg, byte)
	local fightMode = msg:getByte()
	local chaseMode = msg:getByte()
	local secureMode = msg:getByte() ~= 0
	local pvpMode, oldPvpMode = msg:getByte(), player:getPvpMode()
	local expertPvp = configManager.getBoolean(configKeys.EXPERT_PVP)

	player:setFightMode(fightMode)
	player:setChaseMode(chaseMode)
	if expertPvp then
		local worldType = Game.getWorldType()
		if worldType == WORLD_TYPE_NO_PVP and pvpMode == PVP_MODE_RED_FIST then
			player:setPvpMode(player:getPvpMode())
		elseif worldType == WORLD_TYPE_PVP_ENFORCED and pvpMode ~= PVP_MODE_RED_FIST then
			player:setPvpMode(PVP_MODE_RED_FIST)
		else
			player:setPvpMode(pvpMode)
		end

		-- SecureMode Formula!
		if worldType == WORLD_TYPE_NO_PVP and secureMode == false or (worldType == WORLD_TYPE_PVP_ENFORCED and secureMode == true) then
			player:setSecureMode(not secureMode)
		else
			if player:getPvpMode() == PVP_MODE_RED_FIST then
				-- force secureMode false while red fist is on!
				player:setSecureMode(false)
			else
				player:setSecureMode(secureMode)
			end

			if oldPvpMode == PVP_MODE_RED_FIST then
				player:setSecureMode(true)
			end
		end

		addPlayerEvent(Player.updateFightModes, 250, player)
	else
		player:setSecureMode(secureMode)
	end
end
`

criei com o nome de fightmodes.lua

agora em modules.xml

`<module type="recvbyte" byte="160" script="fightmodes.lua"/>`

depois adicionei na config.lua essa opçao

-- PVP-Expert Config
expertPvp = true

e depois altere o worldType = "pvp" para worldType = "no-pvp"

aguardo novidades

**Comment by joseamaya1** [comment]
Lua Script Error: [Modules Interface]
data/modules/scripts/fightmodes.lua:onRecvbyte
data/modules/scripts/fightmodes.lua:5: attempt to call method 'getPvpMode' (a nil value)

**Comment by granoob** [comment]
to mudando o script ja coloco ele de novo

**Comment by joseamaya1** [comment]
kk
:)

**Comment by marsoncschneider** [comment]
The first step is ok.

**Comment by marsoncschneider** [comment]
Now we need to create a function isPet() to edit tile.cpp line 497.
