### ISSUE TITLE
Skill modifiers are not removed/updated when item is decayed

### ISSUE THREAD

**Issue by jlcvp** [malucooo/Otxserver-New#375]
Blade of mayhem (charged and up) and like items still gives the bonus if keep equipped when the decay time's over. Same if you have a skill modifier on any decayable item.

-------
PT:
A blade of mayhem e items similares quando estão com algum modificador charged ou superior, mantêm os bonus de skills/chance de crítico, leech, etc, se acabarem e estiverem equipados. O mesmo acontece caso qualquer item com modificador de skill/atributos for decaível.

**Comment by joseluis2g** [comment]
Can you review [this ](https://github.com/malucooo/Otxserver-New/pull/376) please.

**Comment by jlcvp** [comment]
Thanks, dude.

#376 fixes this
