### ISSUE TITLE
!frags/!kills, don't work

### ISSUE THREAD

**Issue by igorlabanca** [malucooo/Otxserver-New#378]
WhatsApp 
Command! Frags, does not work the functions are all unconfigured.
Does anyone have a solution?
Thanks !

**Comment by igorlabanca** [comment]
Help plx

**Comment by granoob** [comment]
testa essse ai


`
local useFragHandler = getBooleanFromString(getConfigValue('useFragHandler'))
 
function onSay(cid, words, param, channel)
	if(not useFragHandler) then
		return false
	end
 
	local time = os.time()
	local times = {today = (time - 86400), week = (time - (7 * 86400))}
	 
	local contents, result = {day = {}, week = {}, month = {}}, db.getResult("SELECT `pd`.`date`, `pd`.`level`, `p`.`name` FROM `player_killers` pk LEFT JOIN `killers` k ON `pk`.`kill_id` = `k`.`id` LEFT JOIN `player_deaths` pd ON `k`.`death_id` = `pd`.`id` LEFT JOIN `players` p ON `pd`.`player_id` = `p`.`id` WHERE `pk`.`player_id` = " .. getPlayerGUID(cid) .. " AND `k`.`unjustified` = 1 AND `pd`.`date` >= " .. (time - (30 * 86400)) .. " ORDER BY `pd`.`date` DESC")
	if(result:getID() ~= -1) then
		repeat
			local content = {
				name = result:getDataString("name"),
				level = result:getDataInt("level"),
				date = result:getDataInt("date")
			}
			if(content.date > times.today) then
				table.insert(contents.day, content)
			elseif(content.date > times.week) then
				table.insert(contents.week, content)
			else
				table.insert(contents.month, content)
			end
		until not result:next()
		result:free()
	end
	 
	local size = {
		day = table.maxn(contents.day),
		week = table.maxn(contents.week),
		month = table.maxn(contents.month),
		dayred = getConfigValue('dailyFragsToRedSkull'),
		dayblack = getConfigValue('dailyFragsToBlackSkull'),
		weekred = getConfigValue('weeklyFragsToRedSkull'),
		weekblack = getConfigValue('weeklyFragsToBlackSkull'),
		monthred = getConfigValue('monthlyFragsToRedSkull'),
		monthblack = getConfigValue('monthlyFragsToBlackSkull')
	}

	doPlayerSendTextMessage(cid, MESSAGE_STATUS_CONSOLE_BLUE, "Day: " .. size.day .. " (red skull: " .. size.dayred .." / black skull: " .. size.dayblack .. ")")
	doPlayerSendTextMessage(cid, MESSAGE_STATUS_CONSOLE_BLUE, "Week: " .. size.week .. " (red skull: " .. size.weekred .. " / black skull: " .. size.weekblack .. ")")
	doPlayerSendTextMessage(cid, MESSAGE_STATUS_CONSOLE_BLUE, "Month: " .. size.month .. " (red skull: " .. size.monthred .. " / black skull: " .. size.monthblack .. ")")
 
	local skullEnd = getPlayerSkullEnd(cid)
	if(skullEnd > 0) then
		doPlayerSendTextMessage(cid, MESSAGE_STATUS_CONSOLE_BLUE, "Your " .. (getCreatureSkullType(cid) == SKULL_RED and "red" or "black") .. " skull will expire at " .. os.date("%d %B %Y %X", skullEnd))
	end
	return true
end
`

**Comment by igorlabanca** [comment]
data/talkactions/scripts/kills.lua:1: attempt to call global 'getConfigValue' (a nil value)

**Comment by granoob** [comment]
local time = os.time()
local times = {today = (time - 86400), week = (time - (7 * 86400))}
 
local contents, result = {day = {}, week = {}, month = {}}, db.getResult("SELECT `pd`.`date`, `pd`.`level`, `p`.`name` FROM `player_killers` pk LEFT JOIN `killers` k ON `pk`.`kill_id` = `k`.`id` LEFT JOIN `player_deaths` pd ON `k`.`death_id` = `pd`.`id` LEFT JOIN `players` p ON `pd`.`player_id` = `p`.`id` WHERE `pk`.`player_id` = " .. getPlayerGUID(cid) .. " AND `k`.`unjustified` = 1 AND `pd`.`date` >= " .. (time - (30 * 86400)) .. " ORDER BY `pd`.`date` DESC")
if(result:getID() ~= -1) then
	repeat
		local content = {
			name = result:getDataString("name"),
			level = result:getDataInt("level"),
			date = result:getDataInt("date")
		}
		if(content.date > times.today) then
			table.insert(contents.day, content)
		elseif(content.date > times.week) then
			table.insert(contents.week, content)
		else
			table.insert(contents.month, content)
		end
	until not result:next()
	result:free()
end
 
local size = {
	day = table.maxn(contents.day),
	week = table.maxn(contents.week),
	month = table.maxn(contents.month),
	dayred = getConfigValue('dailyFragsToRedSkull'),
	dayblack = getConfigValue('dailyFragsToBlackSkull'),
	weekred = getConfigValue('weeklyFragsToRedSkull'),
	weekblack = getConfigValue('weeklyFragsToBlackSkull'),
	monthred = getConfigValue('monthlyFragsToRedSkull'),
	monthblack = getConfigValue('monthlyFragsToBlackSkull')
}

doPlayerSendTextMessage(cid, MESSAGE_STATUS_CONSOLE_BLUE, "Day: " .. size.day .. " (red skull: " .. size.dayred .." / black skull: " .. size.dayblack .. ")")
doPlayerSendTextMessage(cid, MESSAGE_STATUS_CONSOLE_BLUE, "Week: " .. size.week .. " (red skull: " .. size.weekred .. " / black skull: " .. size.weekblack .. ")")
doPlayerSendTextMessage(cid, MESSAGE_STATUS_CONSOLE_BLUE, "Month: " .. size.month .. " (red skull: " .. size.monthred .. " / black skull: " .. size.monthblack .. ")")

local skullEnd = getPlayerSkullEnd(cid)
if(skullEnd > 0) then
	doPlayerSendTextMessage(cid, MESSAGE_STATUS_CONSOLE_BLUE, "Your " .. (getCreatureSkullType(cid) == SKULL_RED and "red" or "black") .. " skull will expire at " .. os.date("%d %B %Y %X", skullEnd))
end
return true
end

testa esse ai ( lua meu fraco)

**Comment by igorlabanca** [comment]
Lua Script Error: [Test Interface]
data/talkactions/scripts/kills.lua
data/talkactions/scripts/kills.lua:4: attempt to concatenate a boolean value
stack traceback:
        [C]: in function '__concat'
        data/talkactions/scripts/kills.lua:4: in main chunk
[Warning - Event::checkScript] Can not load script: scripts/kills.lua

**Comment by granoob** [comment]
me add skype newgranoob@gmail.com

**Comment by granoob** [comment]
Pronto acho que seja isso que voce quer

function onSay(cid, words, param)
	local player = Player(cid)
	local fragTime = configManager.getNumber(configKeys.FRAG_TIME)
	if fragTime <= 0 then
		player:sendTextMessage(MESSAGE_STATUS_CONSOLE_BLUE, "Voce nao tem nenhuma unjustified kill.")
		return false
	end

	local skullTime = player:getSkullTime()
	if skullTime <= 0 then
		player:sendTextMessage(MESSAGE_STATUS_CONSOLE_BLUE, "Voce nao tem nenhuma unjustified kill.")
		return false
	end

	local kills = math.ceil(skullTime / fragTime)
	local remainingSeconds = math.floor((skullTime % fragTime) / 1000)

	local hours = math.floor(remainingSeconds / 3600)
	local minutes = math.floor((remainingSeconds % 3600) / 60)
	local seconds = remainingSeconds % 60

	local message = "You have " .. kills .. " unjustified kill" .. (kills > 1 and "s" or "") .. ". A quantidade de mortes injustificadas diminuira em: "
	if hours ~= 0 then
		if hours == 1 then
			message = message .. hours .. " hora, "
		else
			message = message .. hours .. " horas, "
		end
	end

	if hours ~= 0 or minutes ~= 0 then
		if minutes == 1 then
			message = message .. minutes .. " minuto e "
		else
			message = message .. minutes .. " minutos e "
		end
	end

	if seconds == 1 then
		message = message .. seconds .. " segundo."
	else
		message = message .. seconds .. " segundos."
	end

	player:sendTextMessage(MESSAGE_STATUS_CONSOLE_BLUE, message)
	return false
end

**Comment by malucooo** [comment]
use the skullbar!
