### ISSUE TITLE
Utevo res / Dont Work in outdated client 

### ISSUE THREAD

**Issue by igorlabanca** [malucooo/Otxserver-New#379]
For those who use the outdated client (10.00) , it is debug the player to use utevo res.

@edit
Client 11.42 does not show the summon signal on the creature, only when the player exits his screen and back, then yes the summon sign appears on the creature

Thanks

**Comment by darkjav** [comment]
Confirmed, Debug only ocurred in client 10.00

**Comment by igorlabanca** [comment]
HELP

**Comment by igorlabanca** [comment]
@malucooo have one solution ?

**Comment by darkjav** [comment]
Duplicated, check: https://github.com/malucooo/Otxserver-New/issues/298

**Comment by 11229900** [comment]
alguma solução por favor :(
