### ISSUE TITLE
Tibia Update 11.43

### ISSUE THREAD

**Issue by igorlabanca** [malucooo/Otxserver-New#380]
Good Morning !!

Tibia has updated to 11.43, please update the project !!
Already tested version 11.43 the project and everything is ok!

Thanks !!

**Comment by mattyx14** [comment]
Muy bien .... OK

**Comment by darkjav** [comment]
@malucooo 
Yes, is needed update items.otb please.

**Comment by malucooo** [comment]
fixed on last commit
