### ISSUE TITLE
Error Critical, mana & life leech

### ISSUE THREAD

**Issue by granoob** [malucooo/Otxserver-New#382]
During tests in which I was going unnoticed, I found a strange thing the items with the skill life, mana, critical in the basic attack does not loose the effects nor the bonus

When releasing spells and skills the effect becomes normal

**Comment by granoob** [comment]
Tive um tempo hoje para trabalha no fix, vamos aplicar

COMBAT.CPP

procure pelo `CombatConditionFunc(caster, target, params, nullptr);`

e troque por `CombatConditionFunc(caster, target, params, &damage);`

agora procure por `void Combat::CombatConditionFunc(Creature* caster, Creature* target, const CombatParams& params, CombatDamage*)`

e troque por esse `void Combat::CombatConditionFunc(Creature* caster, Creature* target, const CombatParams& params, CombatDamage* data)`

logo abaixo " { " adicione isso : ```
 if (params.origin == ORIGIN_MELEE && data && data->primary.value == 0 && data->secondary.value == 0) {
 		return;
 	}

```

**Comment by jlcvp** [comment]
@granoob open a pull request with these changes

**Comment by igorlabanca** [comment]
Nice man !

**Comment by granoob** [comment]
@jlcvp amigo pode voce fazer la, por favo nao tem problemas...

**Comment by igorlabanca** [comment]
Testei aqui e realmente funcionou !
@granoob, tem como tu ver o sistema de !frags se consegue arrumar ?

**Comment by granoob** [comment]
o que ta acontecendo la, pois sou de um outro projeto, como iniciei o meu projeto nessa base inicial to ajudando na constribuiçao

**Comment by granoob** [comment]
o fix definitivo critical damage effect

vai em ENUMS.H

procure por : 		`
primary.type = secondary.type = COMBAT_NONE;
		primary.value = secondary.value = 0;
`

voce vera um linha descrita assim

critical = false

apague esse linha e compile e agradeça

**Comment by granoob** [comment]
FIX - final error critical ((#273))

`void Combat::CombatHealthFunc(Creature* caster, Creature* target, const CombatParams& params, CombatDamage* data)
{
	assert(data);
	CombatDamage damage = *data;
	if (g_game.combatBlockHit(damage, caster, target, params.blockedByShield, params.blockedByArmor, params.itemId != 0)) {
		return;
	}

	if ((damage.primary.value < 0 || damage.secondary.value < 0) && caster) {
		Player* targetPlayer = target->getPlayer();
		if (targetPlayer && caster->getPlayer() && targetPlayer->getSkull() != SKULL_BLACK) {
			damage.primary.value /= 2;
			damage.secondary.value /= 2;
		}
	}
		if (caster) {
			Player* casterPlayer = caster->getPlayer();
				if (casterPlayer) {
					casterPlayer->doCriticalDamage(damage);
			}
		}
		
	if (g_game.combatChangeHealth(caster, target, damage)) {
		CombatConditionFunc(caster, target, params, &damage);
		CombatDispelFunc(caster, target, params, nullptr);
	}
}`

BOM JOGO A VOCES

**Comment by puputeko** [comment]
Deu esse erro na compilação quando faz a alteração no combat.cpp 
![20960956_1488878897862923_592586915_o](https://user-images.githubusercontent.com/30515334/29479989-a7fb3866-844b-11e7-8198-211eb785393f.png)

**Comment by granoob** [comment]
pata fechar esse issue

procure em combat.cpp por

void Combat::CombatHealthFunc(Creature* caster, Creature* target, const CombatParams& params, CombatDamage* data) 

depois segue ate o o fim da  do codigo que deve acabar assim

	CombatDispelFunc(caster, target, params, nullptr);
}
}

substituir tudo o postado acima, caso vc nao consiga aguerde alguem fazer o pull request

**Comment by carmelitajter** [comment]
Eu fiz o mesmo que ele fez e apliquei oque voce disse para fazer dps do issue e deu erro tambem :/
