### ISSUE TITLE
sendTextMessage doesn't work properly at onLogin with otclient 10.98

### ISSUE THREAD

**Issue by brunojeveaux** [malucooo/Otxserver-New#383]
I realized that welcome messages doesn't appear at my screen when I log in. So I tested a few things and after some time I saw that player:sendTextMessage is not actually showing any message when I use it on creaturescripts function onLogin.

I mean, at tibia client 11.4 it works normally, but at otclient it only works when I execute addEvent(doPlayerSendTextMessage ....

**Comment by mattyx14** [comment]
This protocol is 11+ 
Protocol 10.9 no supported
