### ISSUE TITLE
Imbuing system not stack %

### ISSUE THREAD

**Issue by darkjav** [malucooo/Otxserver-New#384]
When players have 2 or more items with imbuement slot,
the % of each atribute not get stack.

Example:
Helmet wit 8% mana leech and Bow with 8% mana leech must be = 16%

But only show 8% in the window skill.

And happen with all attributes, not only mana leech.

**Comment by granoob** [comment]
na verdade mesmo que postei  a checagem eta correta, o enchated que nao deveria aparece mais porque se nos usa a mesma enchanted do mesmo tipo, seria algo muito incomun exemplo: giante sword 2 slot, e os 3 slot critical ficaria assim 30% / 150% no qual tornaria a arma super mais poderosa que a mayhem

seguindo o report, quando voce enchated 2 vezes o mesmo enchanted o mesmo ataque acontece porem ou sai 1 ou de outro e nao os 2
