### ISSUE TITLE
Decrease Frags not works

### ISSUE THREAD

**Issue by darkjav** [malucooo/Otxserver-New#386]
Example:
Player kill 12 times and get Red Skull,
each frag have 2 hours for be removed,
he wait 24 hours, then dissapear the Red skull,
now in Unjustified Points window get 0 kills.

Players wait 24 hours of more, and they not have skull, and not frags, but appear this:
![frag_window](https://user-images.githubusercontent.com/9681018/29571223-44d4e72a-871e-11e7-8bcc-e5471bd43d85.png)

If they kill again only one player, they get again red skull!
![frag_window2](https://user-images.githubusercontent.com/9681018/29572586-5c83606e-8722-11e7-8f4d-a79aad47dfe1.png)

The system are complety wrong. Not works!

Config.lua
```
worldType = "pvp"
hotkeyAimbotEnabled = true
protectionLevel = 8
pzLocked = 2 * 60 * 1000
removeChargesFromRunes = false
removeChargesFromPotions = true
removeWeaponAmmunition = true
removeWeaponCharges = false
timeToDecreaseFrags = 2 * 60 * 60 * 1000
whiteSkullTime = 5 * 60 * 1000
stairJumpExhaustion = 2 * 1000
experienceByKillingPlayers = false
expFromPlayersLevelRange = 75
dayKillsToRedSkull = 12
weekKillsToRedSkull = 15
monthKillsToRedSkull = 17
redSkullDuration = 1
blackSkullDuration = 2
orangeSkullDuration = 1
```

**Comment by igorlabanca** [comment]
After leaving redskull, how many times does he need to kill to get red skull again?

**Comment by granoob** [comment]
como descrito acima 12 morte para red skull por dia
15 por semana
17 por mes

**Comment by darkjav** [comment]
@granoob 
You not understand me, there always said that i have "You have 12 unjustified kills. The amount of unjustified kills will decrease after: 1 hour, 54 minutes and 36 seconds."

**Comment by JavEver** [comment]
@darkjav  What do you use to check the frags?

**Comment by darkjav** [comment]
@granoob 
Players wait 24 hours of more, and they not have skull, and not frags, but appear this:
![frag_window](https://user-images.githubusercontent.com/9681018/29571026-c01ae3cc-871d-11e7-989f-a3584b1b74d4.png)

If they kill again only one player, they get again red skull and 12 frags!
The system are complety wrong. Not works!
