### ISSUE TITLE
Blessings / blessing charms not working

### ISSUE THREAD

**Issue by pattyboy27** [malucooo/Otxserver-New#387]
Hi,

Blessings and blessing charms appear to not be working.

When I manually edit the database to give a character all blessings, it shows the highlighting around all of the character's item slots; but when I try and buy the blessings or use the blessing charms it *appears* to work (NPC's take gold, magic effect occurs), but makes no change to the "blessings1; blessings2; etc. player database.

**Comment by igorlabanca** [comment]
`local keywordHandler = KeywordHandler:new()
local npcHandler = NpcHandler:new(keywordHandler)
NpcSystem.parseParameters(npcHandler)
local talkState = {}

function onCreatureAppear(cid)				npcHandler:onCreatureAppear(cid)			end
function onCreatureDisappear(cid)			npcHandler:onCreatureDisappear(cid)			end
function onCreatureSay(cid, type, msg)			npcHandler:onCreatureSay(cid, type, msg)		end
function onThink()					npcHandler:onThink()					end

function creatureSayCallback(cid, type, msg)
	if(not npcHandler:isFocused(cid)) then
		return false
	end

	local talkUser = NPCHANDLER_CONVBEHAVIOR == CONVERSATION_DEFAULT and 0 or cid

-- CONFIG --	
local gold = {
p1 = 10000, -- Preço em Gold 1 ao 100
p2 = 20000, -- Preço em Gold 101 ao 150
p3 = 30000, -- Preço em Gold 151 ao 200
p4 = 50000, -- Preço em Gold 201 ao 250
p5 = 60000, -- Preço em Gold 251 ao 299
p6 = 70000 -- Preço em Gold 300 em diante
}
-- CONFIG --	
local player = Player(cid)
	if msgcontains(msg, 'valor') then
		doPlayerPopupFYI(cid, "Preço benção:\n\nLeve 1 ao 100: "..gold.p1.." gp\nLeve 101 ao 150: "..gold.p2.." gp\nLeve 151 ao 200: "..gold.p3.." gp\nLeve 201 ao 250: "..gold.p4.." gp\nLeve 251 ao 299: "..gold.p5.." gp\nLeve 300 em diante: "..gold.p6.." gp")
	end
	if msgcontains(msg, 'bless') then
		if getPlayerBlessing(cid, 5) then
			selfSay('Você já foi abençoado pelo Senhor!', cid)
		return end
		
			if getPlayerLevel(cid) >= 1 and getPlayerLevel(cid) <= 100 then
				if getPlayerMoney(cid) >= gold.p1 then
					doPlayerRemoveMoney(cid, gold.p1)
for i = 1, 8 do
			if not player:hasBlessing(i) then
				player:addBlessing(i, 1)
			end
		end
					selfSay('Parabéns {'..getPlayerName(cid)..'}, agora você tem a benção!', cid)
					doSendMagicEffect(getPlayerPosition(cid), 29)
				else
					selfSay('Nosso Deus precisa muito de dinheiro, e você não tem o suficiente! Volte quando tiver!', cid)
				end

			elseif getPlayerLevel(cid) >= 101 and getPlayerLevel(cid) <= 150 then
				if getPlayerMoney(cid) >= gold.p2 then
					doPlayerRemoveMoney(cid, gold.p2)
for i = 1, 8 do
			if not player:hasBlessing(i) then
				player:addBlessing(i, 1)
			end
		end
					selfSay('Parabéns {'..getPlayerName(cid)..'}, agora você tem a benção!', cid)
					doSendMagicEffect(getPlayerPosition(cid), 29)
				else
					selfSay('Nosso Deus precisa muito de dinheiro, e você não tem o suficiente! Volte quando tiver!', cid)
				end

			elseif getPlayerLevel(cid) >= 151 and getPlayerLevel(cid) <= 200 then
				if getPlayerMoney(cid) >= gold.p3 then
					doPlayerRemoveMoney(cid, gold.p3)
for i = 1, 8 do
			if not player:hasBlessing(i) then
				player:addBlessing(i, 1)
			end
		end
					selfSay('Parabéns {'..getPlayerName(cid)..'}, agora você tem a benção!', cid)
					doSendMagicEffect(getPlayerPosition(cid), 29)
				else
					selfSay('Nosso Deus precisa muito de dinheiro, e você não tem o suficiente! Volte quando tiver!', cid)
				end

			elseif getPlayerLevel(cid) >= 201 and getPlayerLevel(cid) <= 250 then
				if getPlayerMoney(cid) >= gold.p4 then
					doPlayerRemoveMoney(cid, gold.p4)
for i = 1, 8 do
			if not player:hasBlessing(i) then
				player:addBlessing(i, 1)
			end
		end
					selfSay('Parabéns {'..getPlayerName(cid)..'}, agora você tem a benção!', cid)
					doSendMagicEffect(getPlayerPosition(cid), 29)
				else
					selfSay('Nosso Deus precisa muito de dinheiro, e você não tem o suficiente! Volte quando tiver!', cid)
				end

			elseif getPlayerLevel(cid) >= 251 and getPlayerLevel(cid) <= 299 then
				if getPlayerMoney(cid) >= gold.p5 then
					doPlayerRemoveMoney(cid, gold.p5)
player:addBlessing(1)
for i = 1, 8 do
			if not player:hasBlessing(i) then
				player:addBlessing(i, 1)
			end
		end
					selfSay('Parabéns {'..getPlayerName(cid)..'}, agora você tem a benção!', cid)
					doSendMagicEffect(getPlayerPosition(cid), 29)
				else
					selfSay('Nosso Deus precisa muito de dinheiro, e você não tem o suficiente! Volte quando tiver!', cid)
				end

			elseif getPlayerLevel(cid) >= 300 then
				if getPlayerMoney(cid) >= gold.p6 then
					doPlayerRemoveMoney(cid, gold.p6)
for i = 1, 8 do
			if not player:hasBlessing(i) then
				player:addBlessing(i, 1)
			end
		end
					selfSay('Parabéns {'..getPlayerName(cid)..'}, agora você tem a benção!', cid)
					doSendMagicEffect(getPlayerPosition(cid), 29)
				else
					selfSay('Nosso Deus precisa muito de dinheiro, e você não tem o suficiente! Volte quando tiver!', cid)
				end				
			end
	end
return true
end

npcHandler:setCallback(CALLBACK_MESSAGE_DEFAULT, creatureSayCallback)
npcHandler:addModule(FocusModule:new())`

**Comment by joseluis2g** [comment]
please learn how to f*cking use the markdown ffs

**Comment by Olimpotibia** [comment]
yes but if you die with all blessings dont lose exp, who know where we check to fix it?

thnx

**Comment by mattyx14** [comment]
Check it:
https://github.com/malucooo/Otxserver-New/commit/dd5fe8ab0572e2ac44ba5038afeb570f624694ba
and it
https://github.com/malucooo/Otxserver-New/commit/9ccc7cc77d5b87b94a5c0157773c01a36c809927

**Comment by Olimpotibia** [comment]
Okej tomorrow with server save i go check cant do reset atm players online xDDD

gracias bro

**Comment by Olimpotibia** [comment]
same issue no loss experience/skills player when die if have blessings, with aol works 100%

Check it:
dd5fe8a
and it
9ccc7cc

withi this changes no va.

**Comment by Olimpotibia** [comment]
mattyx donde puedo mirar los blessings para reparar el expreduction o loss exp al morir con bless
