### ISSUE TITLE
Some messages classes don't work

### ISSUE THREAD

**Issue by brunojeveaux** [malucooo/Otxserver-New#388]
I tested all message classes with player:sendTextMessage, but these don't work at client 11.4:
MESSAGE_STATUS_CONSOLE_BLUE
MESSAGE_STATUS_CONSOLE_RED
MESSAGE_LOOT
MESSAGE_EVENT_ORANGE
MESSAGE_STATUS_CONSOLE_ORANGE

**Comment by Andreeyyy** [comment]
Don't work in client 10 only

**Comment by brunojeveaux** [comment]
I just tried it in client 11.42 and they're not working.

**Comment by mattyx14** [comment]
I check new speak class tomorrow

**Comment by jlcvp** [comment]
There are several message typres that are deprecated since 10.98+, a revision must be made.

**Comment by Andreeyyy** [comment]
Only "White", "Green" (party), and "Red" (Warning), work in new protocol(11.+)

**Comment by jlcvp** [comment]
we can make a compatibility layer that checks if the client is 11+ and change the text type to the best suitable for that type
