### ISSUE TITLE
Server crash bt full

### ISSUE THREAD

**Issue by darkjav** [malucooo/Otxserver-New#389]
I dont know how to reproduce, here the bt full:

> Program received signal SIGSEGV, Segmentation fault.
> [Switching to Thread 0x6665a5b2f700 (LWP 3936)]
> 0x000000000058326e in Item::getItemCount (this=0x0)
>     at /ssd/Testera_114x/source/src/item.h:689
> 689                             return count;
> (gdb) bt full
> #0  0x000000000058326e in Item::getItemCount (this=0x0)
>     at /ssd/Testera_114x/source/src/item.h:689
> No locals.
> #1  0x00000000005b1ed5 in Game::internalMoveItem (this=0xb9e780 <g_game>, fromCylinder=
>     0x6665a2ca6bf0, toCylinder=0x6664f11b4360, index=0, item=0x66658f26f190, count=1,
>     _moveItem=0x0, flags=0, actor=0x666487547320, tradeItem=0x0)
>     at /ssd/Testera_114x/source/src/game.cpp:1079
>         floorN = 0
>         retMaxCount = RETURNVALUE_NOERROR
>         m = 26212
>         moveItem = 0x6665a5b2e8f0
>         itemIndex = 32995634
>         toItem = 0x0
>         subCylinder = 0x6664f11b4360
>         ret = RETURNVALUE_NEEDEXCHANGE
>         updateItem = 0x6665a0c76208
>         fromTile = 0x6664f11b4490
>         maxQueryCount = 4045095776
> #2  0x00000000005b1b10 in Game::playerMoveItem (this=0xb9e780 <g_game>, player=
>     0x666487547320, fromPos=..., spriteId=2667, fromStackPos=6 '\006', toPos=...,
>     count=1 '\001', item=0x66658f26f190, toCylinder=0x6664f11b4360)
>     at /ssd/Testera_114x/source/src/game.cpp:1038
>         fromCylinder = 0x6665a2ca6bf0
>         playerPos = @0x666487547328: {33485, y = 31319, z = 7 '\n'}
>         mapFromPos = @0x6664f11b44a0: {33485, y = 31319, z = 7'\n'}
>         toIndex = 0 '\000'
>         ret = RETURNVALUE_NOERROR
>         toCylinderTile = 0x6664f11b4360
>         mapToPos = @0x6664f11b4370: {x = 33485, y = 31318, z = 7 '\n'}
> #3  0x00000000005afbf8 in Game::playerMoveThing (this=0xb9e780 <g_game>, playerId=268438007,
>     fromPos=..., spriteId=2667, fromStackPos=6 '\006', toPos=..., count=1 '\001')
>     at /ssd/Testera_114x/source/src/game.cpp:664
>         toCylinder = 0x6664f11b4360
>         movingCreature = 0x0
>         player = 0x666487547320
>         fromIndex = 6 '\006'
>         thing = 0x66658f26f190
> #4  0x00000000005f0eb5 in std::_Mem_fn<void (Game::*)(unsigned int, Position const&, unsigned short, unsigned char, Position const&, unsigned char)>::operator()<unsigned int&, Position&, unsigned short&, unsigned char&, Position&, unsigned char&, void> (this=0x1f77920,
>     __object=0xb9e780 <g_game>) at /usr/include/c++/4.8/functional:601
> No locals.
> #5  0x00000000005ebc37 in std::_Bind<std::_Mem_fn<void (Game::*)(unsigned int, Position const&, unsigned short, unsigned char, Position const&, unsigned char)> (Game*, unsigned int, Position, unsigned short, unsigned char, Position, unsigned char)>::__call<void, , 0ul, 1ul, 2ul, 3ul, 4ul, 5ul, 6ul>(std::tuple<>&&, std::_Index_tuple<0ul, 1ul, 2ul, 3ul, 4ul, 5ul, 6ul>) (
>     this=0x1f77920,
>     __args=<unknown type in /ssd/Testera_114x/tfs, CU 0x7639d3, DIE 0x877f9d>)
>     at /usr/include/c++/4.8/functional:1296
> No locals.
> #6  0x00000000005e4364 in std::_Bind<std::_Mem_fn<void (Game::*)(unsigned int, Position const&, unsigned short, unsigned char, Position const&, unsigned char)> (Game*, unsigned int, Position, unsigned short, unsigned char, Position, unsigned char)>::operator()<, void>() (
>     this=0x1f77920) at /usr/include/c++/4.8/functional:1355
> No locals.
> #7  0x00000000005db574 in std::_Function_handler<void (), std::_Bind<std::_Mem_fn<void (Game::*)(unsigned int, Position const&, unsigned short, unsigned char, Position const&, unsigned char)> (Game*, unsigned int, Position, unsigned short, unsigned char, Position, unsigned char)> >::_M_invoke(std::_Any_data const&) (__functor=...) at /usr/include/c++/4.8/functional:2071
> No locals.
> #8  0x00000000007e4578 in std::function<void ()>::operator()() const (this=0x1f7ce90)
>     at /usr/include/c++/4.8/functional:2471
> No locals.
> #9  0x00000000007e4462 in Task::operator() (this=0x1f7ce80)
>     at /ssd/Testera_114x/source/src/tasks.h:40
> No locals.
> #10 0x00000000007e3c5e in Dispatcher::threadMain (this=0xb9e5e0 <g_dispatcher>)
>     at /ssd/Testera_114x/source/src/tasks.cpp:60
>         task = 0x1f7ce80
>         taskLockUnique = {_M_device = 0xb9e5f8 <g_dispatcher+24>, _M_owns = false}
> #11 0x00000000007353d7 in std::_Mem_fn<void (Dispatcher::*)()>::operator()<, void>(Dispatcher*) const (this=0x1f97f98, __object=0xb9e5e0 <g_dispatcher>)
>     at /usr/include/c++/4.8/functional:601
> No locals.
> #12 0x0000000000734d53 in std::_Bind_simple<std::_Mem_fn<void (Dispatcher::*)()> (Dispatcher*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x1f97f90)
>     at /usr/include/c++/4.8/functional:1732
> No locals.
> #13 0x000000000073463d in std::_Bind_simple<std::_Mem_fn<void (Dispatcher::*)()> (Dispatcher*)>::operator()() (this=0x1f97f90) at /usr/include/c++/4.8/functional:1720
> No locals.
> #14 0x000000000073403a in std::thread::_Impl<std::_Bind_simple<std::_Mem_fn<void (Dispatcher::*)()> (Dispatcher*)> >::_M_run() (this=0x1f97f78) at /usr/include/c++/4.8/thread:115
> No locals.
> #15 0x00006665a7186a60 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
> No symbol table info available.
> #16 0x00006665a73e1184 in start_thread (arg=0x6665a5b2f700) at pthread_create.c:312
>         __res = <optimised out>
>         pd = 0x6665a5b2f700
>         now = <optimised out>
>         unwind_buf = {cancel_jmp_buf = {{jmp_buf = {112586757699328, -6140450896933856646, 1,
>                 0, 112586757700032, 112586757699328, 7350990684390120058,
>                 7350985156412136058}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0,
>               0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
>         not_first_call = <optimised out>
>         pagesize_m1 = <optimised out>
>         sp = <optimised out>
>         freesize = <optimised out>
>         __PRETTY_FUNCTION__ = "start_thread"
> #17 0x00006665a68ee37d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
> ---Type <return> to continue, or q <return> to quit---
>

**Comment by Andreeyyy** [comment]
It's a little hard to know what caused such a crash. I noticed it was in some object movement on GRAY ISLand.

**Comment by luminera** [comment]
também tenho esse problema @darkjav , pode me ajudar a resolver?

**Comment by luminera** [comment]
Can you help me? I have this problem too!

**Comment by darkjav** [comment]
@luminera You need remove this ids:
https://github.com/malucooo/Otxserver-New/commit/913d91a162da367758b47e3a68eed7129cb61769

**Comment by luminera** [comment]
How and where can I remove them? Can you help me with this?

**Comment by luminera** [comment]
And how can I crash the server with this? For me to take the test!

**Comment by darkjav** [comment]
@luminera In the RME, search each id with Ctrl + F, then remove each in the list. I dont know how to reproduce. I remove all and was solved. If you need more help: darkjav_88@hotmail.com
