### ISSUE TITLE
imbuement / New summons

### ISSUE THREAD

**Issue by karacamassa** [malucooo/Otxserver-New#390]
Items ja com skill (+ ml etc) que estão com slots para imbuement, esses items não dão +skill. e o imbuement de manaleech não funcionan tambem. estou tendo problema com summon no client 10 esta dando debug quando alguem vai criar summon, teria ja alguma soluçao para o mesmo?

E os summons novos ali, os player que o criaram levam hit do mesmo (skullfrost etc)

**Comment by darkjav** [comment]
Duplicated, check:
https://github.com/malucooo/Otxserver-New/issues/298
https://github.com/malucooo/Otxserver-New/issues/334
https://github.com/malucooo/Otxserver-New/issues/381
https://github.com/malucooo/Otxserver-New/issues/385
https://github.com/malucooo/Otxserver-New/issues/384

Please before of open a new issue, be sure that not exist in the list of issues.

**Comment by marsoncschneider** [comment]
About new summons. Now we need to make changes in source
