### ISSUE TITLE
Client 10 (versões antigas 11.30-11.32)

### ISSUE THREAD

**Issue by igorlabanca** [malucooo/Otxserver-New#391]
Galera será que alguém consegue fazer uma forma de conseguir entrar no client 10, das versões mais antigas ? 11.30-11.32 ?? sem tomar debug ?

**Comment by granoob** [comment]
rsrs eu fiz isso

**Comment by igorlabanca** [comment]
Pode me ajudar cara ?
tem muito player no meu servidor que tou perdendo por conta dos bots, não terem atualizado :l

**Comment by granoob** [comment]
posso sim, manda um contato...

**Comment by igorlabanca** [comment]
Facebook: https://www.facebook.com/igorlabanca
Wpp: 81 99861-7408
