### ISSUE TITLE
Client 11 logout when change vocation on dawnport

### ISSUE THREAD

**Issue by RichardMuller** [malucooo/Otxserver-New#395]
Em movements no arquivo vocationtrial.lua há uma linha que está assim:

changeVocation(player, fromVocation, toVocation)

Então eu mudei ela para:

changeVocation(player, 0, toVocation)

Com isso ele força a mudança de vocação como se a vocação inicial sempre fosse a de id 0(a qual não ocorre o problema). Isso foi apenas um quebra galho e funciona, mas deve haver uma maneira mais correta de corrigir esse erro.

**Comment by marsoncschneider** [comment]
Mas dai os skills nao resetam.

**Comment by marsoncschneider** [comment]
O logoff server para resetar os skills, ja que ainda nao foi implementado na source

**Comment by RichardMuller** [comment]
Ahh, entendi, vlw obrigado.
