### ISSUE TITLE
Few big warnings while compiling

### ISSUE THREAD

**Issue by drakylucas** [malucooo/Otxserver-New#398]
Hello guys, I'm having some problems while compiling this distro.
It compiles, but it also have many warnings. How to fix them?
///
Olá, estou tendo alguns problemas pra compilar essa distro. Estou tendo alguns warnings que não tinha ao compilar o TFS 1.3 original. Como corrigir esses warnings de maneira segura?

[https://pastebin.com/Zitweupg](https://pastebin.com/Zitweupg)

**Comment by Rockerszzz** [comment]
Linux/Windows? i don't get any error message compiling on Linux.

**Comment by drakylucas** [comment]
Windows 10, using visual studio 2015 community, boost 1_62_0 and TFS Libs 3.2. I don't get any of these warnings while compiling the official TFS build. Note: it's warning, not an error, I can execute the server, but it is annoying to see these warnings and, I don't know if it changes the stability of the server :p
