### ISSUE TITLE
Crash client 10.00

### ISSUE THREAD

**Issue by jeckestripador** [malucooo/Otxserver-New#399]
New sumons crash client 10.00!

**Comment by Rockerszzz** [comment]
Are you using the newest version of 10.00 client?

**Comment by mattyx14** [comment]
I try solve it tomorrow

**Comment by darkjav** [comment]
Duplicated, check: https://github.com/malucooo/Otxserver-New/issues/298

**Comment by 11229900** [comment]
a few weeks ago my server went well with the client 10 and worked well the magic utevo res without bugs and now only this bug I do not know what to do I'm lost
