### ISSUE TITLE
client 1000

### ISSUE THREAD

**Issue by GoularPink** [malucooo/Otxserver-New#401]
Oi, descartaram o client 10? Pois está dando debbug

**Comment by Andreeyyy** [comment]
Use o 10 OUTDATED, www.tibia.com

**Comment by 397821** [comment]
Aqui também da debug usando o client 10 outadated + última rev otx

**Comment by 397821** [comment]
Debug ao tentar logar

**Comment by Andreeyyy** [comment]
https://secure.tibia.com/account/?subtopic=downloadclient&step=downloadoutdated

Se usar esse e tiver tudo certo não tem erro. Utilizo aqui e é 100% revejam que estão fazendo algo errado
