### ISSUE TITLE
Debug Prey system

### ISSUE THREAD

**Issue by darkjav** [malucooo/Otxserver-New#403]
When players die and have in database table "players",
in the colums "prey_stamina_1" and "prey_stamina_2"
the values "7200",
they get debug on login.

**Comment by Eternal-Scripts** [comment]
If you edit manually can occurs debug, other way this isn't possible.

**Comment by darkjav** [comment]
@Eternal-Scripts No bro, i use the original system. Sometimes happen and others no.
