### ISSUE TITLE
X-logged player is kicked out game even if he's pz-locked

### ISSUE THREAD

**Issue by gerotib** [malucooo/Otxserver-New#417]
If character lose connection when hes pz-locked, no matter 1 or 15min, hes kicked out game after same time that he's not. It makes characters able to simply lose 15' pz and removes skull also.
There should be added expection for pz-locked characters in creature.lua, so character would be kicked out game after he loses pz, if he's still not connected.
Also players get kicked when they're become attacked by player while x-logged, i dont know if that should be like this.

**Comment by darkjav** [comment]
Confirmed.
