### ISSUE TITLE
Wand of darkenss - How to add

### ISSUE THREAD

**Issue by Olimpotibia** [malucooo/Otxserver-New#420]
items.xml

	<item id="29055" article="an" name="Wand of Darkness">
		<attribute key="description" value="Temporary magic powers enchant this staff." />
		<attribute key="weight" value="3800" />
		<attribute key="weaponType" value="wand" />
		<attribute key="range" value="4" />
		<attribute key="charges" value="250" />
		<attribute key="showcharges" value="1" />		
		<attribute key="skillcriticalchance" value="10" />
		<attribute key="skillcriticaldamage" value="50" />		
		<attribute key="decayTo" value="2401" />
		<attribute key="magiclevelpoints" value="2" />		
		<attribute key="duration" value="900" />
	</item>

Weapons.xml

	<wand id="29055" level="41" mana="20" min="80" max="100" type="energy" action="removecharge"> 
		<vocation name="Sorcerer" />
	</wand>

Movements.xml

	
	<movevent event="DeEquip" itemid="29055" slot="hand" function="onDeEquipItem" />
	<movevent event="Equip" itemid="29055" slot="hand" level="41" function="onEquipItem">
		<vocation name="Sorcerer" />
		<vocation name="Master Sorcerer" showInDescription="0" />
	</movevent>

Have fun

**Comment by Olimpotibia** [comment]
<item id="29000" article="a" name="dream blossom staff">
		<attribute key="description" value="It's a gnarly branch with a gleaming blue blossom." />
		<attribute key="weight" value="3200" />
		<attribute key="weaponType" value="wand" />
		<attribute key="shootType" value="death" />
		<attribute key="range" value="4" />
		<attribute key="magiclevelpoints" value="2" />
</item>

	<wand id="29000" level="80" mana="17" min="63" max="87" type="death"> 
		<vocation name="Sorcerer" />
		<vocation name="Druid" />
	</wand>

**Comment by Olimpotibia** [comment]
i cant open new request so here is posted sorry for bad section.

**Comment by Eternal-Scripts** [comment]
max is 77 no?

**Comment by Olimpotibia** [comment]
True!

**Comment by Olimpotibia** [comment]
@Eternal-Scripts can you help with summons, if you have time.

**Comment by malucooo** [comment]
make a pull request!
