### ISSUE TITLE
Bug lions rock

### ISSUE THREAD

**Issue by GoularPink** [malucooo/Otxserver-New#424]
Lua Script Error: [Action Interface]
data/actions/scripts/lionrock.lua:onUse
data/actions/scripts/lionrock.lua:92: attempt to index local 'reward' (a nil value)
stack traceback:
        [C]: in function '__index'
        data/actions/scripts/lionrock.lua:92: in function <data/actions/scripts/lionrock.lua:1>

When we click on fountain

**Comment by malucooo** [comment]
no have this file in data/actions/scripts/
