### ISSUE TITLE
How to open map?

### ISSUE THREAD

**Issue by EstebPain** [malucooo/Otxserver-New#425]
Hello! I'm trying to open your map (realmap.otb) with RME (map editor), but it always tells me that the client version is unsupported. What sould I do to make it work? Am I doing anything wrong? I'm using rme v3.3 from [here](https://github.com/hjnilsson/rme/releases/).
Thanks in advance!

**Comment by mrhultin** [comment]
There is a brilliant Tutorial on Tibiaking for  this purpose.
It seems to work for alot of folks, try it atleast :)

http://www.tibiaking.com/forum/forums/topic/77992-usando-rme-em-100011x/
