### ISSUE TITLE
MESSAGE_STATUS_CONSOLE_BLUE

### ISSUE THREAD

**Issue by Anon19a** [malucooo/Otxserver-New#426]
MESSAGE_STATUS_CONSOLE_BLUE not show in client 11?

**Comment by mrhultin** [comment]
I am quite confident it has been removed/reworked in Tibia 11.

For now, I've changed all mine to MESSAGE_STATUS_DEFAULT or MESSAGE_EVENT_ADVANCE

**Comment by malucooo** [comment]
great job!
