### ISSUE TITLE
STILL can't cut the spider webs with melee weapon

### ISSUE THREAD

**Issue by sn4tch0vsk** [malucooo/Otxserver-New#427]
I opened this issue before talking about this bug. The post was closed and the problem still remains.
The only item to break spider webs is fire bug.

**Comment by mattyx14** [comment]
Is required add the items on destroy on items.xml
That's a simple thing to solve

**Comment by sn4tch0vsk** [comment]
How ? Can you use magic sword as an example ?

**Comment by mattyx14** [comment]
On this datapack:
```xml
<item fromid="7538" toid="7543" article="a" name="spider web" />
```
Only change for it ... this items.xml require lite work on this functions
```xml
<item id="7538" article="a" name="spider web">
	<attribute key="destroyTo" value="7544" />
</item>
<item id="7539" article="a" name="spider web">
	<attribute key="destroyTo" value="7545" />
</item>
```

**Comment by sn4tch0vsk** [comment]
It works. Intend to change this on the items.xml ? cause it's actually like the global. Thanks man

**Comment by malucooo** [comment]
make a pull request!
