### ISSUE TITLE
Lower roshamuul stones

### ISSUE THREAD

**Issue by Rockerszzz** [malucooo/Otxserver-New#43]
Assim como os "bones" não estavam funcionando e foram corrigidos, as pedras na roshamuul lower, onde deve-se usar uma pick para quebra-las e sumonar um "Frazzlemaw" ou obter "fine gravel" que ao clicar nele vai enchendo o bucket na backpack também precisa ser implementado os scripts.

mais informações: http://www.tibiawiki.com.br/wiki/Roshamuul_(Lower_Roshamuul)_Quest

**Comment by malucooo** [comment]
não tá funcionando?
