### ISSUE TITLE
Imbuement

### ISSUE THREAD

**Issue by Anon19a** [malucooo/Otxserver-New#434]
imbuement weapons do not give the attributes
example: powerful strike(critical), powerful void(mana leech)
royal axe(7434), great axe(2415)

imbuement helmet shielding(Blockade Powerful) give: 1 magic, 4 axe, 4 shield
demon helmet(2493)

**Comment by Energex22** [comment]
I have noticed this too, seems like the imbuing isn't working 100%.... 

I have also noticed that the second imbuement slot doesn't work right, it seems to copy the first imbuement and make the second the same also..
So if you get powerful vamperisim as the first imbuement and powerful strike as the second, the second imbuement slot automatically becomes another powerful Vamperisim.

**Comment by Olimpotibia** [comment]
Hello for me says "sorry not posible" when try to imbue all items... who have same issue?

**Comment by Energex22** [comment]
Have you done the quest (talked to npc) to unlock it?

**Comment by Olimpotibia** [comment]
yes all access from npcs but says the same with god and players.... can you share your imbuement please to check? 🗡

**Comment by Olimpotibia** [comment]
https://gyazo.com/7c89ed6c88784606efb0bda72fd9bdf5

look it

**Comment by M4GO** [comment]
sorry for not open new, this error from console
Lua Script Error: [MoveEvents Interface]
data/movements/scripts/imbuement.lua:onEquip
data/modules/scripts/imbuement/imbuement.lua:646: attempt to index local 'name'
(a number value)
stack traceback:
        [C]: in function '__index'
        data/modules/scripts/imbuement/imbuement.lua:646: in function 'getImbuem
entPercent'
        data/movements/lib/movements.lua:9: in function 'onEquipWeaponImbuement'

        data/movements/scripts/imbuement.lua:2: in function <data/movements/scri
pts/imbuement.lua:1>

**Comment by Energex22** [comment]
Found a updated imbuements.lua from a different server (that i cannot get to compile)  and the second slot in now working right, but still not getting the imbuement attribute effects.

Not sure if you want this linked or not, but here it is [https://github.com/Qwizer/realmap-10x/blob/master/data/modules/scripts/imbuement/imbuement.lua](url)

**Comment by Tibiarl2** [comment]
I have the same problem and apart I get a bug in console

https://i.gyazo.com/05fe64f054fd3a11b8320d5d58d8dd7e.png
