### ISSUE TITLE
Acess cast from client 11.xx

### ISSUE THREAD

**Issue by Fmjj** [malucooo/Otxserver-New#435]
Hello my friends, how i can acess cast from client 11.xx , because if the  user pass fields is blank nothing happens.

Thanks.

**Comment by westwol** [comment]
Indeed, even if the client lets you log in, you will get "Account or password incorrect" due the php script that compare the account and password straight from the database. Therefore php login script requires work to create a cast interface.

**Comment by Olimpotibia** [comment]
true

**Comment by westwol** [comment]
![castpos](https://user-images.githubusercontent.com/17607894/30307441-cd3706ea-9743-11e7-987d-bdde6f89ff4c.png)

I ran some tests today, still figuring out how to iterate with the array of live_casts.

**Comment by tfornalewicz** [comment]
How exactly did you do it?

**Comment by westwol** [comment]
![caswt](https://user-images.githubusercontent.com/17607894/30315815-c6de381e-976a-11e7-9b2c-9abd8a6396c0.png)

At this point the cast system is functional but still missing some features such as:
- show viewers (not sure if possible due connection.cpp).
- password locked casts.

Cheers,
westwol

**Comment by tfornalewicz** [comment]
I tried casting with password but still account/login was blank and it didn't work, could you give me a hint on that :)? Or maybe it's something with database?

**Comment by Fmjj** [comment]
Good job westwol, hope the team add this feature soon.

**Comment by Eternal-Scripts** [comment]
The step of password is very simple, just change in db the password tinyint to string and use that to check with a simple query.

Show viewers use query to get the value of spectators and send that in player data ej. Name (world) replace world with spectators count.
