### ISSUE TITLE
Bugs aprensentados

### ISSUE THREAD

**Issue by brunoxxt** [malucooo/Otxserver-New#439]
Lista
- Hellgorak recebe pouco dano
- Evento Bomberman está bugado ganha o premio quem morre primeiro..
- Evento Zombie está bugado o tp está abrindo e lá dentro os zumbi não somem continuam dentro do evento os players entram e sai como vitoriosos..
- Todos os Boss da POI está dropando apenas um loot
- Bugs nos Helmets e Armors.. Não estã atribuindo os atributos de cada item no player..
- No mapa ta aparecendo alguns pisos fantasmas no world todo...

**Comment by EnzzoCaaue** [comment]
> Hellgorak recebe pouco dano
não entendi.. ele não esta recebendo pouco dano, ou você esta reclamando que ele recebe pouco dano? Se for a segunda opção, está certo e não é um bug.

**Comment by EnzzoCaaue** [comment]
O Hellgorak recebe pouco dano mesmo, não é bug.

**Comment by brunoxxt** [comment]
Então desconsidere..

**Comment by Andreeyyy** [comment]
É bug sim, posto a correção hoje ainda, basta olhar o Wiki sobre os danos

**Comment by Gustavohso** [comment]
Não sei se algum erro meu, mais o bomberman esta derrubando o ot com Segmentation fault.

**Comment by Rockerszzz** [comment]
Hellgorak não está bugado, ele é forte contra tudo, menos o ataque dos Dreadbeasts que é ataque do tipo "drown", é assim que se mata esse boss.
