### ISSUE TITLE
Áreas ausentes em Edron

### ISSUE THREAD

**Issue by NokautBR** [malucooo/otxserver-new#44]
Vampire's Crypt
https://www.tibiawiki.com.br/wiki/Vampire%27s_Crypt_(Edron)
Forgotten Tomb
https://www.tibiawiki.com.br/wiki/Forgotten_Tomb

Achei os mapas na internet, caso alguém queira adicionar ao mapa global
https://1drv.ms/u/s!AmHybA3XkDwGg4FkDv9lRfikEXISpA
ou
https://mega.nz/#!q8kiwJBQ!kG0v4i-19NvuU04iKWk0dGx5BKaFno7mYAEVMMxSgVQ
[5places_tibiaservers.net.zip](https://github.com/malucooo/otxserver-new/files/2516322/5places_tibiaservers.net.zip)

**Comment by EnzzoCaaue** [comment]
vampire's cryp tem, a forgotten tomb realmente não tem

**Comment by guifagotti** [comment]
ARRUMADO COM O PULL REQUEST #65
