### ISSUE TITLE
Imbuiment

### ISSUE THREAD

**Issue by mayconvds** [malucooo/Otxserver-New#442]
O imbuemente system nao dão as skills que deveria dar, por exemplo:

eu coloco roubo de vida ele encanta o item porém não acrescenta no banco de dados o roubo de vida.
![image](https://user-images.githubusercontent.com/20943594/30358872-97d9a572-981d-11e7-9400-2e48008b0045.png)

**Comment by Andreeyyy** [comment]
Imbuing esta com problema, temos que fazer uma vaquinha para comprar o sistema completo. Caso queira ajudar entre no grupo do whatsapp

**Comment by mayconvds** [comment]
Qual grupo do zap?

**Comment by jlcvp** [comment]
duplicate of #434
