### ISSUE TITLE
Correções a serem feitas no mapa

### ISSUE THREAD

**Issue by igordelecrode** [malucooo/Otxserver-New#448]
Alguns ajuste do mapa

-Gray Beach - town 28
{x = 33477, y = 31313, z = 7} esse piso precisa de pz área
{x = 33477, y = 31314, z = 7} esse piso precisa de pz área
{x = 33453, y = 31345, z = 7} esse piso precisa de pz área
{x = 33479, y = 31315, z = 7} retirar item id 1429 desse piso para ficar igual global
{x = 33446, y = 31273, z = 14} retirar item id 1429 desse piso para ficar igual global
{x = 33511, y = 31324, z = 8} retirar item id 1429 desse piso para ficar igual global
{x = 33436, y = 31247, z = 11} retirar item id 1429 desse piso para ficar igual global
{x = 33559, y = 31280, z = 11} retirar item id 1429 desse piso para ficar igual global
{x = 33646, y = 31261, z = 11} retirar item id 1429 desse piso para ficar igual global

-Liberty bay - town 7
{x = 32317, y = 32819, z = 6} essa área inteira precisa de pz área
{x = 32286, y = 32898, z = 5} essa área inteira precisa de pz área
{x = 32297, y = 32902, z = 5} essa área inteira precisa de pz área

- Rookgaard -town 35
{x = 32130, y = 32163, z = 9} essa hunt de dragon não existe
{x = 32113, y = 32175, z = 10} essa hunt de dragon não existe
{x = 32117, y = 32189, z = 11} essa hunt de wyrn não existe
{x = 32124, y = 32188, z = 12} essa hunt de DL não existe
{x = 32170, y = 32107, z = 9} essa hunt de lizard não existe 
{x = 32133, y = 32156, z = 10} essa hunt de banshee não existe

-Tahis - town 3

{x = 32380, y = 32239, z = 7} retirar item id 12042 desse piso para ficar igual global
{x = 32376, y = 32239, z = 7} retirar item id 12042 desse piso para ficar igual global
{x = 32378, y = 32239, z = 7} retirar item id 21584 desse piso para ficar igual global
{x = 32378, y = 32238, z = 7} retirar item id 1810 dessa parede para ficar igual global

-Rathleton/Oramond - town 33

Aqui é sobre as Catacombs, estão igual baiak cheia de portal.
{x = 33670, y = 31888, z = 5} retirar item id 1429 desse piso para ficar igual global
{x = 33667, y = 31888, z = 5} trocar o piso para o id 406 e remover item id 23056
{x = 33665, y = 31888, z = 5} trocar o piso para o id 406 e remover item id 23056
{x = 33668, y = 31887, z = 5} retirar item id 1431 desse piso para ficar igual global
{x = 33667, y = 31887, z = 5} trocar o piso para o id 406 e remover item id 23419
{x = 33666, y = 31887, z = 5} retirar item id 1431 desse piso para ficar igual global
{x = 33665, y = 31887, z = 5} trocar o piso para o id 406 e remover item id 23419
{x = 33664, y = 31887, z = 5} retirar item id 1431 desse piso para ficar igual global

a solução aqui é ou ativar o npc de votação pra escolher a hunt ou criar um scrit movement para teleportar conforme o dia para a hunt certa. ( claro vocês manjam melhor do que eu pra saber que script é necessário.) 

Outras coreções:
{x = 33460, y = 31715, z = 9} esse telerpot está com uma unique id que teleporta o cara de volta pra oramond porem ele deve ser teleportado para essa position: {x = 33626, y = 31898, z = 6}
{x = 33459, y = 31724, z = 9} essa área inteira precisa ser de anti logout
{x = 31255, y = 32604, z = 9} esse telerpot está com uma unique id que teleporta o cara de volta pra oramond porem ele deve ser teleportado para essa position: {x = 33626, y = 31898, z = 6}
{x = 31062, y = 32605, z = 9} esse telerpot está com uma unique id que teleporta o cara de volta pra oramond porem ele deve ser teleportado para essa position: {x = 33626, y = 31898, z = 6}

**Comment by granoob** [comment]
completa a informação que yalahar os mobs passa pelas grades, toda elas
]
