### ISSUE TITLE
Levers e Novas arrows/bolts

### ISSUE THREAD

**Issue by Xiolones** [malucooo/Otxserver-New#451]
Vei, depois que mudaram isso de nao passar mais emcima das alavancas..bugou uma porrada de quests..      
Quando você conjura as novas arrows/bolts                        
Se voce dropa elas no chao e pega dnv..reseta pra 1h e fica travado                        
Ou se vce tirar ela do stack e voltar tbm acontece isso

**Comment by Rockerszzz** [comment]
pode dizer quais foram as quests?

**Comment by Andreeyyy** [comment]
Alavancas foram atualizadas no tibia globa, não se pode mais passar por cima das mesmas.

**Comment by Rockerszzz** [comment]
então isso não afetou aqui, certo?
