### ISSUE TITLE
Debug with cast client 10

### ISSUE THREAD

**Issue by darkjav** [malucooo/Otxserver-New#457]
Sometimes when somebody join as spectator with client 10 in the cast of one character also with client 10, the spectator get debug and client closed.

How to reproduce:

1.- With one character activate the cast.
2.- With another client join as spectator to the cast.
3.- With the caster player go to kill monsters.
4.- If is possible you must lose life and mana.
4.- Logout with the spectator and join again or login with new spectator.
5.- You get debug with spectator.

**Comment by malucooo** [comment]
make a video to explain this... i cant reproduce this!
