### ISSUE TITLE
Debug summons client 10 and 11

### ISSUE THREAD

**Issue by darkjav** [malucooo/Otxserver-New#461]
When one player do a summon with "utevo res" or "utevo gran res eq, utevo gran res sac, utevo gran res ven, utevo gran res dru",
and if another player is out of screen range, but close, the another player get debug.

Not happen when another players are in screen range.

**Comment by westwol** [comment]
This issue is related to the spell icon.

**Comment by malucooo** [comment]
i cant reproduce... test with the client 11.47.5620 and make a video for more explainations!
