### ISSUE TITLE
Summons Heal spell only when no have fight during "X" minutes

### ISSUE THREAD

**Issue by Olimpotibia** [malucooo/Otxserver-New#462]
Summons Heal spell only when no have fight during "X" minutes, if anyone know how we can fix summons please help 💃

**Comment by EnzzoCaaue** [comment]
How to reproduce?

**Comment by granoob** [comment]
basta adicionar uma script ao mob, com hpticks

**Comment by Olimpotibia** [comment]
granoob pode ajuda?

**Comment by granoob** [comment]
@Olimpotibia fiz esse script na correria porque estava esperando o carro que vou ao hospital

--   <event type="healthchange" name="sum" script="sum.lua"/> --- essa parte em creaturescript

local config = {
	life_ative = 43750,
	life_add = 400,
	seconds_ative = 7,
}

local function Uheal(cid)
	local sun = Monster(cid)

	sun:addHealth(config.life_add)
	sun:getPosition():sendMagicEffect(CONST_ME_MAGIC_RED)
end

function onHealthChange(creature, attacker, primaryDamage, primaryType, secondaryDamage, secondaryType, origin)
	
	if attacker then
		if creature:getHealth() < config.life_ative and Game.getStorageValue(config.gStorage) < 1 then
			addEvent(Uheal, 1000 * config.seconds_ative, creature.uid)
		end
	end

	return primaryDamage, primaryType, secondaryDamage, secondaryType
end

------------------------------------------------------------------------------------------------------------------
no mob vc adiciona a isso

<script>
  <event name="sum"/>
 </script>

**Comment by malucooo** [comment]
what porra is this? make a pull request if have solution!
