### ISSUE TITLE
broadcast msg red

### ISSUE THREAD

**Issue by darkjav** [malucooo/Otxserver-New#47]
The messages of broadcast, are not appearing on the screen, only in the server log. I tested with god and gamemaster and not work. Command: /bc

**Comment by lamonato29** [comment]
broadcast command its /b

**Comment by Zainox** [comment]
yes but, is necessary in rare cases talking to players about the server out the name of god, please i like the command /bc

**Comment by Rockerszzz** [comment]
Zainox is right, the command "/bc" is very useful in the case of GOD don't want to show his name.

**Comment by Zainox** [comment]
command /bc not working
