### ISSUE TITLE
Debug

### ISSUE THREAD

**Issue by pavc93** [malucooo/Otxserver-New#472]
Sometimes random players give them debug, sometimes they can enter without problem, but also sometimes remain bug forever. This is the error:

Às vezes, os jogadores aleatórios dão-lhes o debug, às vezes eles podem entrar sem problema, mas também às vezes permanecem bug para sempre. Aqui está o error.

A veces aleatoriamente a un jugador le da debug, a veces pueden entrar sin problema, pero también a veces siguen siendo bug para siempre. Este es el error.

`Debug Assertion 1135 Control.cpp 1556
Wed Sep 20 20:47:47 2017
Graphic Engine: DirectX9 (2)
Operating System: Windows 10 in MEX
Processor: Intel CORE I3 M
Video Card: Intel (R) HD GR
Last Packet Types: 028 232 238 238 238 233 236 232 238 238
Last Packet: 023 074 000 000 016 050 000 003 015 021 013 128 003 169 252 003
Player Position: [32365,32242,7]
Player Name: Antenas (OT)
Player Action: 050 048 057 046 050 051 057 046 049 050 051 046 049 056 049 058 055 049 055 050
Player.cpp 354: exception occurred, reason:
Network.cpp 951: exception occurred, reason:
Control.cpp 1561: exception occurred (Type = 28) (MainWindow = 03D8CCF8), reason:
Control.cpp 1556: unknown packet type during game (Type = 28)`

**Comment by Olimpotibia** [comment]
11.47?

**Comment by pavc93** [comment]
sim com o cliente 10

**Comment by malucooo** [comment]
use the client 11.47.5620
