### ISSUE TITLE
Debug When trying to join the server.

### ISSUE THREAD

**Issue by Hawkke** [malucooo/Otxserver-New#473]
I cant join my otserver, Im using tibia version 11.32.
When putting my acc & password i can log in with my character but my client instantly crashes.
I get this debug when trying to join again.
It Happens with every character
![crash](https://user-images.githubusercontent.com/32209562/30766963-4eb4d080-9fbe-11e7-8e7a-814787b99dc2.png)

And when using the latest client(I think) i cant even log in, i get this msg.
![3](https://user-images.githubusercontent.com/32209562/30767498-94684ce8-9fc2-11e7-8db9-95b692d7b07e.png)

Any help please will be welcome 
Thanks

**Comment by malucooo** [comment]
use the client 11.47.5620 or equivalent client 10.
