### ISSUE TITLE
Monsters causing poison condition at first hit

### ISSUE THREAD

**Issue by gerotib** [malucooo/Otxserver-New#475]
Poison monsters like snake should cause poison condition only when they break our shield/ armor, not immediately when they touch player. Theres one [commit](https://github.com/otland/forgottenserver/commit/1294ad54f40929a57ad95a7d23cbfbd884a940ec) in original tfs i found, but it probably should be a bit changed.

**Comment by malucooo** [comment]
fixed at last commit
