### ISSUE TITLE
RESOLVER ERRO DA ID DA "diamond arrow"

### ISSUE THREAD

**Issue by brunoxxt** [malucooo/Otxserver-New#476]
ERRO na diamond arrow o id das spells não está a mesma do items.xml a id certa pra colocar no items.xml é 29056 vlw!!

**Comment by brunoxxt** [comment]
<item id="29056" article="a" name="diamond arrow">
		<attribute key="weight" value="80" />
		<attribute key="slotType" value="ammo" />
		<attribute key="attack" value="37" />
		<attribute key="decayTo" value="0" />
		<attribute key="duration" value="3600" />
		<attribute key="showduration" value="1" />
		<attribute key="weaponType" value="ammunition" />
		<attribute key="ammoType" value="arrow" />
		<attribute key="shootType" value="crystallinearrow" />
		<attribute key="maxHitChance" value="100" />

**Comment by malucooo** [comment]
fixed at last commit
