### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by Zhaturos** [malucooo/Otxserver-New#478]
1.In Service of Yalahar - Mission 6, when you have the charged ghost charm and go to talk with palimuth
"hi, mission" he don't say nothing .

2.World Coins and World coin, when you use that item no give to you nothing, can't use , in old version of the server can ---- FIXED

3. Summons no follow to you, no teleporting, old version of the server can --- FIXED

**Comment by Fmjj** [comment]
Reroll functions not workin?  GameStore.OfferTypes.OFFER_TYPE_PREYBONUS

I can buy but not adding reroll bonus.

**Comment by Fmjj** [comment]
summons still damage player.

Items.xml need a fix 

Intentional edited attack?

```
<item id="25911" article="a" name="axe of mayhem (overcharged)">
		<attribute key="weight" value="5000" />
		<attribute key="defense" value="70" />
		<attribute key="attack" value="95" />
		<attribute key="description" value="This weapon is over charged." />
		<attribute key="skillAxe" value="1" />
		<attribute key="weaponType" value="axe" />
		<attribute key="skillcriticalchance" value="20" />
		<attribute key="skillcriticaldamage" value="30" />
		<attribute key="decayTo" value="25881" />
		<attribute key="transformDeEquipTo" value="26241" />
		<attribute key="duration" value="54000" />
		<attribute key="showduration" value="1" />
```
