### ISSUE TITLE
Debug

### ISSUE THREAD

**Issue by EnzzoCaaue** [malucooo/Otxserver-New#481]
`Debug Assertion 1100 Control.cpp 1530
Mon Sep 25 17:05:37 2017
Graphic Engine: DirectX9 (2)
Operating System: Windows 7 Business Edition 64 Bit in BRA
Processor: Intel CORE I3-2
Video Card: NVIDIA GeForce GT 220
Last Packet Types: 001 156 161 160 120 121 121 120 120 120
Last Packet: 023 013 000 000 016 050 000 003 015 021 013 128 003 169 252 003
Player Position: [95,117,7]
Player Name: ADM Suporte (OTXServer-Global)
Player Action: 048 046 048 046 048 046 048 058 055 049 055 050
Player.cpp 344: exception occurred, reason:
Network.cpp 873: exception occurred, reason:
Control.cpp 1535: exception occurred (Type = 1) (MainWindow = 038E3838), reason:
Control.cpp 1530: unknown packet type during game (Type = 1)`

**Comment by mattyx14** [comment]
try to use client 10 which is equivalent to 11.47

**Comment by EnzzoCaaue** [comment]
That was the client I tried to log in.

**Comment by Olimpotibia** [comment]
same here some players have this bug offline training

https://i.gyazo.com/53e4add0ca027a34f73a45356af6edab.png

**Comment by malucooo** [comment]
use the client 11.47.5620 and respective version of client 10...
