### ISSUE TITLE
problem opening map wit rme rme

### ISSUE THREAD

**Issue by Felipe1993** [malucooo/Otxserver-New#484]
im asking becausei want to help

**Comment by EnzzoCaaue** [comment]
as you can see on README.md, its otx3.

**Comment by Felipe1993** [comment]
i cnt open the mp with the rme could you give me the sprites? i put them at 10.98 path but wont load map and if i put at 10100 the rme never loads

**Comment by granoob** [comment]
vamos ao primeiro passo, é facil abrir o mapa primeiro entre no tibiaking e baixe
[http://www.tibiaking.com/forum/forums/topic/77992-usando-rme-em-100011x/](url)

depois de aberto vai em import mapa, na parte vai pergunta se vc deseja carregar completo ou renderizar click e sim

depois preciona ctrl+g

coloque uma condenada já existem exemplo templo de thaism bom uso
