### ISSUE TITLE
Use map file UNCOMPRESSED in git

### ISSUE THREAD

**Issue by jlcvp** [malucooo/Otxserver-New#485]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use http://www.tibiaking.com/ or https://otland.net for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Using a zip file is very very expensive when making updates in the map. When editing and uploading the otbm directly, git only sends the changed bytes of the map. This should dramatically reduce upload times when using a slow connection.Buy any item in store and try throw outside of your house.

### Expected behaviour
Reduce the time upload and make easier the upload of large files.

### Actual behaviour
Missing feature

**Comment by malucooo** [comment]
i gonna make a test...

**Comment by golicar** [comment]
The uncompressed map file's size is above the limit allowed by Github, making it impossible to upload. I don't think there's a solution to this problem.

**Comment by joao-albach** [comment]
https://git-lfs.github.com/

maybe this will help?
