### ISSUE TITLE
Produtos Store

### ISSUE THREAD

**Issue by mudroock** [malucooo/Otxserver-New#487]
Alguns produtos da store não funcionam como deveriam

**XP BOOST**
Você só pode comprar 5x esse produto por dia, e a cada vez o preço será mais caro: 1º voucher = 30 Tibia Coins, 2º voucher = 45 Tibia Coins, 3º voucher = 90 Tibia Coins, 4º voucher = 180 Tibia Coins, 5º voucher = 360 Tibia Coins.

**Permanent Prey Slot**
Pode ser comprado na store quantas vezes quiser.

**Gold Pouch**
Pode ser arrastada pra fora da storebox.

**Comment by malucooo** [comment]
gold pouch é pra arrastar ou não?

**Comment by mudroock** [comment]
@malucooo não, ela é um item fixo que não pode ser dropado ou arrastado da backpack.

**Comment by Eternal-Scripts** [comment]
XP Boost
Storage de os.time e outra pra armazenar quantas vezes comprou (e uma tabela de preços)

Prey
Tem função já no modules pra verificar se tem prey slot comprado

Gold Pouch
No onMoveItem taca condição de nunca mover o Gold Pouch

**Comment by Eternal-Scripts** [comment]
Fix dd11e27f3aeab9053f47a29b523caef331b01f22
