### ISSUE TITLE
Wrong rune prices and weights

### ISSUE THREAD

**Issue by guzm9zzang** [malucooo/Otxserver-New#489]
**OTX Server Runes**

NAME							PRICE	WEIGHT
Animate Dead Rune				375		1.00
Avalanche Rune					25		0.25
Chameleon Rune					210		0.70
Convince Creature Rune			        80	        1.00
Cure Poison Rune 				        65		0.50
Destroy Field Rune				        15		0.35
Disintegrate Rune				        26		0.30
Energy Bomb Rune				        162		0.50
Energy Field Rune				        38		0.30
Energy Wall Rune				        85		0.25
Explosion Rune					31		0.35
Fire Bomb Rune					55		0.50
Fire Field Rune					28		0.20
Fire Wall Rune					        61		0.30
Fireball Rune					        30		0.20
Great Fireball Rune				        45		0.52
Heavy Magic Missile Rune		        12		0.21
Holy Missile Rune				        16		0.42
Icicle Rune						30		0.20
Intense Healing Rune 			        95		0.50
Light Magic Missile Rune		        4		0.21
Magic Wall Rune					55		0.20
Paralyse Rune 					        500		0.50
Poison Bomb Rune				        85		0.50
Poison Field Rune				        21		0.30
Poison Wall Rune				        52		0.25
Soulfire Rune					        46		0.50
Stalagmite Rune					12		0.21
Stone Shower Rune				        37		0.52
Sudden Death Rune				50		0.35
Thunderstorm Rune				37		0.52
Ultimate Healing Rune			        175		0.60 
Wild Growth Rune				        160		0.50	

 **Real Tibia Runes**
according to tibia.wikia.com

NAME							PRICE	WEIGHT
Animate Dead Rune				375		2.10
Avalanche Rune					45		0.52
Chameleon Rune					210		2.10
Convince Creature Rune			        80		2.10
Cure Poison Rune 				        65		2.10
Destroy Field Rune				        15		0.70
Disintegrate Rune				        26		0.70
Energy Bomb Rune				        162		1.05
Energy Field Rune				        38		0.70
Energy Wall Rune				        85		0.52
Explosion Rune					31		0.35
Fire Bomb Rune				        117		1.05
Fire Field Rune				        28		0.70
Fire Wall Rune					        61		0.52
Fireball Rune					        30		0.42
Great Fireball Rune				        45		0.52
Heavy Magic Missile Rune		        12		0.21
Holy Missile Rune				        16		0.42
Icicle Rune					        30		0.42
Intense Healing Rune 			        95		2.10
Light Magic Missile Rune		        4		0.21
Magic Wall Rune				        116		0.70
Paralyse Rune 					        700		2.10
Poison Bomb Rune				        85		1.05
Poison Field Rune				        21		0.70
Poison Wall Rune				        52		0.52
Soulfire Rune					        46		0.70
Stalagmite Rune				        12		0.21
Stone Shower Rune				        37		0.52
Sudden Death Rune			        108		0.70
Thunderstorm Rune			        37		0.52
Ultimate Healing Rune			        175		2.10
Wild Growth Rune				        160		1.05

**Comment by malucooo** [comment]
make a pull request plz!
