### ISSUE TITLE
bug  walking over stairs ...using otclient (char get invisible when go downstairs

### ISSUE THREAD

**Issue by Felipe1993** [malucooo/Otxserver-New#492]
Well im using otclient version 10.99 to connect to the server the bug consists in
if you re walking and go downstairs your chracter get instntly invisible and you you have to re-change your outfit

**Comment by mattyx14** [comment]
this work with 11.47 or equival to 10.00(aka 11)

**Comment by Felipe1993** [comment]
it's because the server doesn't support  otc porotc doesn't support te server?

**Comment by Felipe1993** [comment]
i forget to dd that for this i changes in definitions.h client min max to 10.99 and in config.lua did the same
