### ISSUE TITLE
Login with client 11.47 and 10.0

### ISSUE THREAD

**Issue by EnzzoCaaue** [malucooo/Otxserver-New#495]
I still having problems with logging in with client 11.47 and 10.0

https://puu.sh/xLg3b/3bf1705ec9.png
https://puu.sh/xLg54/78b51298a5.png

**Comment by malucooo** [comment]
use the client 11.47.5620 and respective client 10 outdated!

**Comment by EnzzoCaaue** [comment]
@malucooo i dont have the 11.47.5620... where can i download it?
