### ISSUE TITLE
Free Account

### ISSUE THREAD

**Issue by guzm9zzang** [malucooo/Otxserver-New#499]
free account can travel by bote and fly.

**Comment by sn4tch0vsk** [comment]
I have fixed all the ways of travel with the correct prices, but apparently someone messed around again.

**Comment by guzm9zzang** [comment]
travel to every destination being premium its free it never cost

**Comment by sn4tch0vsk** [comment]
Transportation
All premium player can use the Tibian transport system. There are ships and magic carpets available for a comfortable journey. For a **SMALL FEE** our captains will bring you to all cities and even to some remote islands. Premium Time will surely save you some long and tiresome marches!

**Comment by guzm9zzang** [comment]
Yeah i know that im talking about the server, its free

**Comment by Eternal-Scripts** [comment]
Simple my friend, just put in callback this
if player:getPremiumDays() == 0 then return false end

**Comment by guzm9zzang** [comment]
thanks bro, you guys should fix that too

**Comment by sn4tch0vsk** [comment]
I pulled a request already, just waiting to be approved.
