### ISSUE TITLE
Vulnerabilidade Stacks

### ISSUE THREAD

**Issue by tonireinbold** [malucooo/Otxserver-New#503]
Stacar muitos itens no chão está causando queda no servidor.

O rapaz compra 999999999x de label que ficam estacadas.... ai o cidadão move qualque label dessa stack para outro SQM, o servidor trava e depois cai.

:-*

**Comment by Eternal-Scripts** [comment]
Solução básica do satanás, em data/events/scripts/player.lua procure onMoveItem e faça um código do satan lá

**Comment by malucooo** [comment]
tava sem limites na source =]~
