### ISSUE TITLE
Novos Summons

### ISSUE THREAD

**Issue by tonireinbold** [malucooo/Otxserver-New#505]
Os novos summons estão recebendo XP ao matar bixos....
sendo que o correto é somente o player receber XP
:-)

**Comment by Eternal-Scripts** [comment]
Confirmado, caso desejem alterar é só procurar gainExp /= 2; no creature.cpp em onGainExperience.

**Comment by GoularPink** [comment]
Alterar o que?

**Comment by Xiolonesz** [comment]
Também não entendi oque alterar nessa linha

**Comment by Andreeyyy** [comment]
Caminho dado, basta adicionar o código e remover a linha.
