### ISSUE TITLE
Remove unnecessary levers

### ISSUE THREAD

**Issue by sn4tch0vsk** [malucooo/Otxserver-New#507]
These 2 levers can be removed because the correct ones are in the right spots of the quest.
1 on Giant Spider and the other one on Bonelord. I have checked.

![untitled](https://user-images.githubusercontent.com/27328490/31060802-6161a638-a6ce-11e7-85c5-ce6b234e11fb.jpg)

**Comment by tonireinbold** [comment]
updated your item.otbm?

**Comment by EnzzoCaaue** [comment]
@tonireinbold what does item.otbm has to do with this ?

**Comment by sn4tch0vsk** [comment]
@tonireinbold ??

**Comment by darkjav** [comment]
@tonireinbold You are wrong...

**Comment by malucooo** [comment]
in next update of map, its gonna be removed
