### ISSUE TITLE
Wrath of the Emperor Quest

### ISSUE THREAD

**Issue by RickSanchez19** [malucooo/Otxserver-New#513]
![advyf3bio](https://user-images.githubusercontent.com/32493536/31139758-eb5fe248-a848-11e7-82d5-e7ba3fc956ec.jpg)
Na terceira missão, o The Kepper não aparece depois de usar o flask of plant poison. Acontece como na imagem, aparece uma mancha azul, como se ele fosse aparecer, mas nada acontece.

**Comment by EnzzoCaaue** [comment]
o monstro não existe, por isso ele não nasce.
