### ISSUE TITLE
Wrath of the Emperor - Missão 08

### ISSUE THREAD

**Issue by RickSanchez19** [malucooo/Otxserver-New#515]
![asdijbdi](https://user-images.githubusercontent.com/32493536/31156195-477f5abe-a889-11e7-8a2e-2ca3f50848e8.jpg)
Na missão 8, mesmo falando com o Npc e recebendo o update no quest log eu não posso atravessar a porta e prosseguir com a quest

**Comment by Olimpotibia** [comment]
door id vce precisa poner door magic no door gate exp
