### ISSUE TITLE
Compilando no Ubuntu

### ISSUE THREAD

**Issue by Xiolonesz** [malucooo/Otxserver-New#516]
Ao compilar no ubuntu seguindo o tutorial, não carrega os modules de monsters na distro. A compilacao é feita normal, porem na distro buga. https://prntscr.com/gt0m0l

**Comment by malucooo** [comment]
isso é o case sensitive do linux.... manda a lista completa dos arquivos pra eu arrumar aqui =/

**Comment by methemia** [comment]
usa estos, recién los acomode, no te dará error :) 
use these, it will not give you error :)

https://www.mediafire.com/file/ojsegk6oikba02s/monster.rar

**Comment by higorbruto** [comment]
Também tem outro problema, erick, consigo compilar deboa, mas na hora de executar, ele não encontre varios arquivos que sim existem... estranho... posso anexar alguns prints

**Comment by EnzzoCaaue** [comment]
@brahminhodark anexa os prints pra eu dar uma olhada.

**Comment by brahminhodark** [comment]
Vou anexar, aguenta ai. To upando pro servidor e compilando, uns 2min. Por que eu já tinha até excluido

**Comment by brahminhodark** [comment]
![screenshot_3](https://user-images.githubusercontent.com/21095867/31191769-a0430150-a915-11e7-9371-28cca1a7bcef.png)
Pronto, da uma olhada ai. Se eu executo no meu pc (Windows) nada dá erro. Ai eu mando pro meu servidor linux, dá essa caralhada ai.

**Comment by EnzzoCaaue** [comment]
é o mesmo erro do op. aqui nao deu erro nenhum, mas como o malucooo ja disse, o linux é case-sentivie.

**Comment by brahminhodark** [comment]
Ah não tinha visto o post todo, my bad. Pra resolver no caso só tirar as letras maiusculas?

**Comment by EnzzoCaaue** [comment]
sim, só renomear com lowercase.
