### ISSUE TITLE
Fury Gate message

### ISSUE THREAD

**Issue by sn4tch0vsk** [malucooo/Otxserver-New#517]
Every time when you log in, you get the message: **"Fury Gate is on Venore Today."**

![untitled](https://user-images.githubusercontent.com/27328490/31167321-8eb890b8-a8a6-11e7-8a67-cf13790ec943.jpg)

**Comment by EnzzoCaaue** [comment]
If you want to disable, check this 
https://github.com/malucooo/Otxserver-New/blob/master/data/creaturescripts/scripts/others/login.lua
from line 184 to 203.

**Comment by sn4tch0vsk** [comment]
Thanks @EnzzoCaaue
