### ISSUE TITLE
Server crash by imbuiements get percent

### ISSUE THREAD

**Issue by Olimpotibia** [malucooo/Otxserver-New#518]
Server crash by imbuiements get percent error on player.lua and imbuement.lua

https://gyazo.com/5b740b55cc6ba93f701dd72287f47d25

**Comment by malucooo** [comment]
fixed at last commit

**Comment by Olimpotibia** [comment]
show me the commit please

**Comment by EnzzoCaaue** [comment]
[930740a](https://github.com/malucooo/Otxserver-New/commit/930740a2986a07c863b08cc2fb4e98d83c7efa08)
