### ISSUE TITLE
Wrath emperor mission 10

### ISSUE THREAD

**Issue by brunoxxt** [malucooo/Otxserver-New#519]
Essa missao ta bugada porque vc pega a wand e vai nas piramides de crystal para matar o boss e usar a wand no sulphur que eles dropa quando morre... e os bixos estão sumindo sem deixar nada para usar a wand e da quest log todos os 4 bosses estão desse jeito!!

**Comment by malucooo** [comment]
pura maluquice de qm te falou isso
