### ISSUE TITLE
Problema com levers

### ISSUE THREAD

**Issue by Kensoulz** [malucooo/Otxserver-New#523]
Estou usando um client 11.42 para conseguir conectar no servidor e estou encontrando o seguinte problema com as levers:

https://imgur.com/a/HfFej

Desde que, não consigo achar um client 11.47/48 que logue no servidor (todos ficam "estabilishing connection" com a barra vermelha e posição na fila), não consigo verificar se há um conflito com a versão ou algo do tipo.

PS: lever id "1946" funciona e aparece normalmente, quando puxada e mudada para a 1945, ela some; esta não tem função de "use" e só da pra dar look e ver que ela está ali.

**Comment by EnzzoCaaue** [comment]
[11.47.5620](http://www.mediafire.com/file/zlmbajhdu1euibh/Tibia11475620.zip)

**Comment by Kensoulz** [comment]
Resolvido cara, obrigado pela ajuda aqui e no tibia king; te devo essas ♥
