### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by testdotest** [malucooo/Otxserver-New#524]
why were the events removed ? and there are still parts of codes ?

**Comment by malucooo** [comment]
no events more... we are removing the scripts too

**Comment by testdotest** [comment]
data/movements/scripts/lmsjoin.lua
data/movements/scripts/lmsleave.lua
data/creaturescripts/scripts/battlefield.lua
data/talkactions/scripts/guild_outfit.lua (Line 64)
data/actions/scripts/ctf.lua
