### ISSUE TITLE
Pets atacando dentro da PZ zone

### ISSUE THREAD

**Issue by Xiolonesz** [malucooo/Otxserver-New#528]
Os pets (summons level 200+) atacam de dentro da PZ os monstros ou players fora da PZ.
APENAS NA CONDIÇÃO DE ESTAR AO LADO.
Exemplo: 

Tile
 [ 0, 0, 0] <- battle zone
 [ 1, 3, 0] <- battle zone
 [ 2, 0', 0'] <- pz zone (depot por exemplo)

0 = sqm vazio
0' = sqm vazio (pvpzone)
1 = monstro ou player
2 = pet
3 = player

**Comment by Andreeyyy** [comment]
Uma screen ajuda a entender melhor seu problema

**Comment by Eternal-Scripts** [comment]
Fix 1aa1c7e9df163fa7112f9060a2607916561a451c
