### ISSUE TITLE
debug new mounts and outfits

### ISSUE THREAD

**Issue by darkjav** [malucooo/Otxserver-New#53]
When i try change my outfit or mount to any new, the client crash. Only happen with the latest changes on outfits.xml and mounts.xml

**Comment by Zainox** [comment]
is because no have the items.otbm with have mounts

**Comment by darkjav** [comment]
@Zainox
I use the last update of items.otbm 10.0, that @malucooo upload, and not work.

With you work fine?

**Comment by Zainox** [comment]
@darkjav Negative, no work, this items.otbm no hace the sprite.

**Comment by ruivo26** [comment]
Hello @darkjav , for the mounts and outfits, please download the following client and put the SPR / DAT in your folder.
http://www.mediafire.com/file/5726ojwykb66s8h/God+of+global+10.99.rar

**Comment by Rockerszzz** [comment]
The news outifits/mounts works perfectly for me, but i do not tested after Malucooo posted the new protocol to 10.00

**Comment by Rockerszzz** [comment]
you have to use the new client 10.00 or copy his .spr and .dat archives for the client 10.98/10.99

**Comment by darkjav** [comment]
@Rockerszzz 
I use client 10.00, but where you download the 10.00? Maybe i have another version of this.

And i tested before that malucoo upload the new items.otb, and not work with both.

**Comment by malucooo** [comment]
fixed!
