### ISSUE TITLE
Talkactions configuração 

### ISSUE THREAD

**Issue by Xiolonesz** [malucooo/Otxserver-New#531]
Mesmo após mudar as funções pelas talkactions, não estão funcionando.

function onSay(player, words, param)
	if not player:getGroup():getAccess() then
		return true
	end

	if player:getAccountType() < ACCOUNT_TYPE_GOD then 
		return false
	end

Essa linha não funciona pra configurar, logo o comando fica inutil .
	if player:getAccountType() >= ACCOUNT_TYPE_GOD then 
	if player:getAccountType() == ACCOUNT_TYPE_GOD then

**Comment by Xiolonesz** [comment]
Consegui fazer a correção alterando essa parte : 
	if playerAccountType == ACCOUNT_TYPE_GOD then
		return false
	end

**Comment by Andreeyyy** [comment]
Verifique corretamente a configuração da account acess
