### ISSUE TITLE
Erro gold pouch

### ISSUE THREAD

**Issue by Xiolonesz** [malucooo/Otxserver-New#534]
![bug](https://user-images.githubusercontent.com/31714466/31260074-d4bde0be-aa21-11e7-879e-c090a8720f42.png)

Apareceu esse bug na distro depois do commit arrumando a gold pouch no player.lua em events.

**Comment by mudroock** [comment]
Bug, invalido! 
Certifique de que está fazendo tudo corretamente.

**Comment by Xiolonesz** [comment]
É bug na .DB?
