### ISSUE TITLE
[Duvida] Funcionamento das Houses

### ISSUE THREAD

**Issue by robsongabriel** [malucooo/Otxserver-New#538]
Alguem poderia me informar como está funcionando o pagamento das casas?
Ele retira do Banco, da backpack ou do depot?

Tenho a compra das casas através do Gesior. Mas depois de uma semana (periodo definido no config.lua) eles perdem a casa mesmo possuindo quantidade absurda de dinheiro no banco. Confirmei também se tinha acabado a Premium, mas ainda possuiam alguns dias.

**Comment by GuiValladao** [comment]
Tem um sistema no servidor que se voce ficar sem logar voce perde a casa depois de x dias
