### ISSUE TITLE
Utito tempo san BUG

### ISSUE THREAD

**Issue by Zainox** [malucooo/Otxserver-New#54]
My players have been thoroughly testing the spells, and it turns out that there is an error with the "utito tempo san" it is assumed that the use of magic paralyzes you and does not let you do support spells, as it does not currently stop you and it is possible to cure you While you use this magic So please test, to see if you can fix it, I have no idea how to do it, just notify so that they know that this bug

**Comment by johnnybarroso** [comment]
Solved. Please test for me.
