### ISSUE TITLE
Imbuement não funcionando!

### ISSUE THREAD

**Issue by joaovitor86** [malucooo/Otxserver-New#555]
Olá, fiz os testes e só funciona os itens de gold token, se você faz o imbuement de um item (exemplo emerald sword) e coloca crítico, não funciona, a arma usada não muda o status do char e tbm não dá crítico.

**Comment by malucooo** [comment]
se tiver alguma dica de como ajeitar isso... fique a vontade!

**Comment by jhonnyrs** [comment]
outro problema é quando o item gasta as 20H, as vezes ele não deixa mais imbuir, dando erro de falta de items ou erro de imbuement data, contact administrador.

**Comment by nycholassousa** [comment]
Falta adicionar os movements pro imbuement, no momento que equipa, o o OTX tem os movements, mas não cheguei a testar.

**Comment by joaovitor86** [comment]
Então, eu fiz as alterações pra os movements, coloquei lá para mana leech, hp leech e critico, mas não rola...

**Comment by Andreeyyy** [comment]
O sistema esta bem incompleto, aconselho compra-lo do @Eternal-Scripts

**Comment by joaovitor86** [comment]
kkkkkkkkkkkkkkkkkkkkkkkkk já tenho o meu pronto e funcionando... logo logo vou disponibilizar de graça :)

**Comment by Andreeyyy** [comment]
Beleza então amigo, quem postou a dúvida foi você. Dei apenas uma sugestão rápida o para solução do seu problema. Mais ok sr programador, aguardamos anciosamente sua contribuição. Grande abraço. Issue fechado
