### ISSUE TITLE
Guilds Houses Sem Depots

### ISSUE THREAD

**Issue by brunoxxt** [malucooo/Otxserver-New#558]
Não sei se no global todas guilds houses tem depot .. no otx ta faltando em boa parte delas..

**Comment by Eternal-Scripts** [comment]
@Andreeyyy levanta seu cu obeso e vai trabalhar.

**Comment by Andreeyyy** [comment]
O igor que cuida do mapa agora. Mais em todo caso, algo simples de resolver.
