### ISSUE TITLE
11.48 Client crashes when any container is opened

### ISSUE THREAD

**Issue by lukasag** [malucooo/Otxserver-New#561]
Opening any containers causes the client to crash.

**Console output:**
<character name> has logged out.

**Client Error Report Window:**
Character: xxxxxx
EngineID: 1
HardwareID: 63735b9775f6744bbbbc595c1ba134c09d369e97
OperatingSystem: Windows 10
Position: [32349,32222,8]
ProductName: Tibia Client
Server: OTXServer-Global
Timestamp: 1507777518
Version: 11.48.5753

**Client Logs:**
[ 20:04:17,226 ] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State)
[ 20:04:18,624 ] BattlEye: "Initialized (v1.243)"
[ 20:04:18,624 ] BattlEye: "Restarting client is necessary, service isn't running properly"
[ 20:04:18,624 ] BattlEye: "Restarting client is necessary, update required"
[ 20:04:18,648 ] Connection to gameserver  QUrl("tcp://127.0.0.1:7172")  requested (Charakter "xxxxxx" )
[ 20:04:18,648 ] Socket state changed  QAbstractSocket::HostLookupState
[ 20:04:18,648 ] Socket state changed  QAbstractSocket::ConnectingState
[ 20:04:18,661 ] Socket state changed  QAbstractSocket::ConnectedState
[ 20:04:18,661 ] Connected to Gameserver  "127.0.0.1" "OTXServer-Global"
[ 20:04:19,649 ] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State)
[ 20:04:19,687 ] News query failed: "Failed to get account. Try again!"
[ 20:05:29,184 ] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State)
[ 20:05:29,418 ] Asset loading complete
[ 20:05:29,739 ] QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State)

**Comment by Eternal-Scripts** [comment]
Invalid, here i can open normally.

**Comment by lukasag** [comment]
It is impossible that you could not replicate the issue, I just tested in two different machines, after downloading it and setting everything up from scratch. Client 11.48 crashes when opening any container. Test it again as I did and if everything is working please describe the exact steps:

1. Downloaded Test Build
2. Import DB
3. Change db in config.lua
4. Add login.php to the web server
5. Launch the client from the IP Changer
6. Logins normally with god account previously that comes with the database
7. Opens a container and client crashes

**Comment by Eternal-Scripts** [comment]
Maybe the player_items have an invalid item, reset this table info and try again.
