### ISSUE TITLE
Bless - NPC com erro ou não e uma dica !

### ISSUE THREAD

**Issue by granoob** [malucooo/Otxserver-New#562]
Galera não sei se esta com problema, hoje vim por ventura testar esse projeto me deparei com um seguinte problema
quando os jogadores vão compra a bless pelo NPC, ele retorna erro de modulos, e o servidor tinha sido removido o comando !bless

a minha duvida é o seguinte, realmente os NPC esta com problema mesmo ?
e o comando !bless foi desativado porque não funcionava ?

então resolvi a futuca no projeto ate descobrir a causa do problemas que me deparei com os NPC e ativei o comando !bless (segue o codigo abaixo para quem teve o mesmo problema)

https://pastebin.com/54Ffmnrh

agora, quem tive o npc funcionando por so me da uma dia se realmente estar pois vou quebrar a cabeça a toa (rsrsrs)

pelo que entendi o modulos do npcs para adicionar a bless ainda esta no método antigo e por isso ele não adiciona

**Comment by Eternal-Scripts** [comment]
Poderia postar o erro como também dizer qual NPC ocorreu o erro?

**Comment by granoob** [comment]
@Eternal-Scripts 

veja ai o erro

![image](https://user-images.githubusercontent.com/28423307/31496643-96b2125c-af32-11e7-8747-7b819b4a1dab.png)
