### ISSUE TITLE
Ultimo boss da WOTE (Mutated Zalamon)

### ISSUE THREAD

**Issue by brahminhodark** [malucooo/Otxserver-New#563]
O ultimo boss não aparece, tentei arrumar e não consegui. Não tem erro na distro, uso linux em meu servidor, mas não é problema de case sensitive creio eu.

**Comment by Fmjj** [comment]
Boa tarde, pelo que vi ele não ta adicionado na monsters.xml

vá até monster.xml e adicione:

`	<monster name="Mutated Zalamon" file="Bosses/mutated zalamon.xml" />`

**Comment by brahminhodark** [comment]
Fmjj, eu já tinha tentando e não foi. Mas mesmo assim vou tentar denovo, por que no meu já está.

**Comment by Fmjj** [comment]
Veja o caso sensitive Brah, o meu é linux também o erro fica no B da pasta Bosses.
**B**osses/mutated zalamon.xml tente colocar minusculo e de um reload no monsters.

**Comment by brahminhodark** [comment]
Não é esse, já está arrumado. Deu certo agora, eu tinha escrito errado. Estava assim:

`<monster name="Mutated Zalamon" file="Bosses/mutated zalamonn.xml" />`

Com dois "N" ali, deu certo já, obrigado.
