### ISSUE TITLE
Monster missing , weapon wrong status

### ISSUE THREAD

**Issue by Fmjj** [malucooo/Otxserver-New#567]
- The ferumbras quest is impossible to finish because is mising the monster ferumbras mortal shell.
-raids monsters with no reward loot.
fix: add this on raid script  `monster:setReward(true)`

-wrong status: You see an obsidian truncheon (Atk:60, Def:40).

-Otherworld and ferumbras boss with no loot.
-If u change sex u lose the outfits and addons.

Obsidian eu arrumei só não sei como fazer o pull request, o monstro da ferumbras esta faltando mesmo, alguém possui o mesmo?

**Comment by Xiolonesz** [comment]
monster:setReward(true)
Isso adiciona dentro do script de cada raid?

`<?xml version="1.0" encoding="utf-8"?>
<raid>
        monster:setReward(true)
    	<announce delay="1000" type="event" message="Amazons are converging north of Carlin." />
	<areaspawn delay="20000" fromx="32339" fromy="31658" fromz="7" tox="32366" toy="31636" toz="7">
		<monster name="Amazon" amount="40" />
	</areaspawn>
        <announce delay="40000" type="event" message="Amazon attack north of Carlin!" />
	<areaspawn delay="40000" fromx="32339" fromy="31658" fromz="7" tox="32366" toy="31636" toz="7">
		<monster name="Amazon" amount="30" />
	</areaspawn>
</raid>` Assim ?

**Comment by malucooo** [comment]
fixed at last commits
