### ISSUE TITLE
Anti-Idle

### ISSUE THREAD

**Issue by Xiolonesz** [malucooo/Otxserver-New#568]
O sistema de anti-afk (se estiver com battle), exemplo trainers, não funciona. Já tentei até adicionar scripts por fora e não funfa se o player estiver com battle e deixar afk nos trainers.

**Comment by Andreeyyy** [comment]
Problema confirmado, o jogador pode deixar o personagem atacando o monstro pelo tempo que quiser.

**Comment by malucooo** [comment]
fixed at last commit
