### ISSUE TITLE
Errors in console, players cant login

### ISSUE THREAD

**Issue by darkjav** [malucooo/Otxserver-New#573]
I use last commit, downloaded few minutes ago.

When server run, i get alot errors like:
```
[Error - Raids::loadFromXml] Failed to load raid: Terramite
[Error - Raid::loadFromXml] Failed to load data/raids/ankrahmun/nomad.xml: File was not found
[Error - Raids::loadFromXml] Failed to load raid: Nomad
[Error - Raid::loadFromXml] Failed to load data/raids/ankrahmun/scarab.xml: File was not found
[Error - Raids::loadFromXml] Failed to load raid: Scarab
[Error - Raid::loadFromXml] Failed to load data/raids/ankrahmun/cobra.xml: File was not found
[Error - Raids::loadFromXml] Failed to load raid: Cobra
[Error - Raid::loadFromXml] Failed to load data/raids/ankrahmun/bonebeast.xml: File was not found
[Error - Raids::loadFromXml] Failed to load raid: Bonebeast
[Error - Raid::loadFromXml] Failed to load data/raids/ankrahmun/gargoyle.xml: File was not found
[Error - Raids::loadFromXml] Failed to load raid: Gargoyle
[Warning - Event::loadScript] Can not load script. data/raids/scripts/ghazbaran.lua
cannot open data/raids/scripts/ghazbaran.lua: No such file or directory
Error: [ScriptEvent::configureRaidEvent] Can not load raid script.
[Error - Raid::loadFromXml] In file (data/raids/svargrond/ghazbaran.xml), eventNode: script
>> Fury Gate hoje esta em kazordoon.
>> Loaded 890 npcs and spawned 37125 monsters.
>> Loaded 23 towns with 1039 houses in total.
>> Loaded all modules, server starting up...
> Warning: OTX3 has been executed as root user, please consider running it as a normal user.
>> Testera 10.00 - 11.48 Server Online!

Tester Player Paladin has logged in.
[Error - Monsters::loadMonster] Failed to load data/monster/Crustaceans/crab.xml: File was not found
[Error - Monsters::loadMonster] Failed to load data/monster/Giants/behemoth.xml: File was not found
[Error - Monsters::loadMonster] Failed to load data/monster/Pharaohs/thalas.xml: File was not found
[Error - Monsters::loadMonster] Failed to load data/monster/Sorcerers/witch.xml: File was not found
[Error - Monsters::loadMonster] Failed to load data/monster/Pharaohs/rahemos.xml: File was not found
[Error - Monsters::loadMonster] Failed to load data/monster/Bio-Elementals/carniphila.xml: File was not found
[Error - Monsters::loadMonster] Failed to load data/monster/Dragons/dragonling.xml: File was not found
[Error - Monsters::loadMonster] Failed to load data/monster/Dwarves/dwarf.xml: File was not found
Tester Player Paladin has logged out.
```
And players when login, they get debug and client closed.

**Comment by robsongabriel** [comment]
**[Error - Raids::loadFromXml]**
The problem is just the name of the folders... Change the name of the files and folders to all lowercase.

**[Error - Monsters::loadMonster]**
Same problem, but you can not do the same correction, because it will give error in other monsters.

Move file **crab.xml** in data/monster/crustaceans/ to data/monster/Crustaceans/
Move file **behemoth.xml** in data/monster/giants/ to data/monster/Giants/

Same thing for others:
[..] Pharaohs/thalas.xml
[..] Sorcerers/witch.xml
[..] Pharaohs/rahemos.xml
[..] Bio-Elementals/carniphila.xml
[..] Dragons/dragonling.xml
[..] Dwarves/dwarf.xml

If possible create a Pull Request so they correct this.

**Comment by darkjav** [comment]
@robsongabriel Maybe you not understand me. the problem is with alot monsters,
not only:
[..] Pharaohs/thalas.xml
[..] Sorcerers/witch.xml
[..] Pharaohs/rahemos.xml
[..] Bio-Elementals/carniphila.xml
[..] Dragons/dragonling.xml
[..] Dwarves/dwarf.xml

I can't copy all these lines, then i only put here some lines, for the example.
And what about the client crash?

**Comment by westwol** [comment]
Then you are just like a leecher out there, despite of not contribuing anything with the community you are demanding for something to be fixed.

**Comment by 397821** [comment]
#577 first fix for monsters

**Comment by robsongabriel** [comment]
@westwol I just tried to help him you son of a bitch motherfucker _|_
