### ISSUE TITLE
Lion's Rock Quest não ativa a fonte no final da quest! E dá o item errado.

### ISSUE THREAD

**Issue by brahminhodark** [malucooo/Otxserver-New#576]
Quando você pega o 'Translation Scroll' na verdade vem o 'Mysterious Scroll' item de montaria de loot do Ferumbras Mortal Shell. Está errado, tem que trocar o papel que pega. E no fim da quest a fonte não spawna.

**Comment by brahminhodark** [comment]
A montaria que digo, é a Rift Runner. Estranhei quando vi um player do meu OT andando com ela, e descobri o bug. Alguém confundiu os dois itens, já que o Translation Scroll tem a mesma aparência do Mysterious Scroll.

**Comment by Eternal-Scripts** [comment]
Fix 1e2179a250d4ddd89eb4b037f66b7d7ac7439d1a
