### ISSUE TITLE
Update Problem 11.48

### ISSUE THREAD

**Issue by exson23** [malucooo/Otxserver-New#579]
hello good night before everything thanks for all the work you do, I'd like to know why this is happening in my case after the major update without running the exe the player goes into a tutorial and crashes.
I don't get any information anywhere.
![sin titulo](https://user-images.githubusercontent.com/32805871/31580734-dba1649e-b126-11e7-922c-c0ad516f6eda.png)
![sin titulo2](https://user-images.githubusercontent.com/32805871/31580738-0acb52ac-b127-11e7-9d69-fe8c14cb4667.png)

**Comment by brunoxxt** [comment]
emove the tutorial in login.php true, false and put false false

**Comment by exson23** [comment]
"tutorial" => (($dbRet["lastlogin"]>0) ? false:true) here?

Sent from Mail for Windows 10

**Comment by brunoxxt** [comment]
"tutorial" => (($dbRet["lastlogin"]>0) ? false:true) < Change "False"

**Comment by exson23** [comment]
thank you @brunoxxt
