### ISSUE TITLE
Store items can be thrown out.

### ISSUE THREAD

**Issue by danielouz** [malucooo/Otxserver-New#580]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use http://www.tibiaking.com/ or https://otland.net for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Buy any item in store and try throw outside of your house.

### Expected behaviour
You can't do this.

### Actual behaviour
He's throwing out of house.

**Comment by Andreeyyy** [comment]
Confirmed !

**Comment by Andreeyyy** [comment]
If you buy an item that comes in parcel, and empty, leaving the parcel inside the store, you can place items in the

**Comment by Aerwix** [comment]
As a solution:
Remove the counters from 300 and put all items in a max count of 100, this will avoid the script to create parcels.
