### ISSUE TITLE
Haste acumulando

### ISSUE THREAD

**Issue by Xiolonesz** [malucooo/Otxserver-New#588]
Utani hur + utani gran hur esta acumulando a speed

**Comment by Andreeyyy** [comment]
Confirmado, não só raste mais qualquer magia de speed acumula 
@malucooo

**Comment by malucooo** [comment]
fixed at last commit

**Comment by Xiolonesz** [comment]
Não está fixado, foi alterado pra combat:addCondition(condition) e esse comando é invalido, depois foi retornado pra combat:setCondition(condition) como estava antes, continua acumulando o speed!
