### ISSUE TITLE
Talkactions não configuravel

### ISSUE THREAD

**Issue by Xiolonesz** [malucooo/Otxserver-New#589]
player:getAccountType() >= ACCOUNT_TYPE_GAMEMASTER then
playerAccountType == ACCOUNT_TYPE_GOD then

Essas funcoes não estão funcionando para usar nos talkactions e configurar os cargos de quem pode usar os comandos..

**Comment by malucooo** [comment]
tenta summonar uma criatura usando o comando /m com um player.... caso sumone vc está usando outra datapack, se não sumonar ai sim ta usando a nossa...

**Comment by Xiolonesz** [comment]
Estou usando a de voces malucoo, o problema é que as funcoes de troca de acessos não estão funcionando como deveria..

**Comment by Xiolonesz** [comment]
Esta indo apelas pelo 	local player = Player(cid)
	if not player:getGroup():getAccess() then
		return true
	end

E acess 0 = player acess 1 = qqr cargo
