### ISSUE TITLE
In-game store Tibia Coins not working by default

### ISSUE THREAD

**Issue by pattyboy27** [malucooo/Otxserver-New#594]
Hi,

Unsure if anyone else had these issues with in-game store but here is my feedback:
1) The DATABASE.sql file doesn't create a column in 'accounts' called 'coins'
2) tibiacoins.lua exists within data/actions/scripts/other but is not referred to in actions.xml

To get the store working, I needed to create the coins column; and add tibiacoins.lua for itemid's 24774 & 16101; then it works perfectly

Thanks for a great server :) hope this helps

**Comment by jlcvp** [comment]
1. The *coins* column is created by the migration subsystem ([./data/migrations/21.lua](https://github.com/malucooo/Otxserver-New/blob/master/data/migrations/21.lua))

2. It's unsafe to have the tibia coin item in-game. Each server owner must address this.
