### ISSUE TITLE
Vials

### ISSUE THREAD

**Issue by Xiolonesz** [malucooo/Otxserver-New#597]
Tentei fazer as correções nos vials e não deram certo, procurei nos arquivos e não encontrei nada referente aos vials com ID : 2006 
Vial of blood, water, urine, oil, etc..
Os nomes de todos ficam apenas, vial of unknown.

**Comment by Eternal-Scripts** [comment]
Vial trabalha com subtype, portanto não há nada inválido.

**Comment by Xiolonesz** [comment]
E como corrige Eternal? Porque esta como unknown
