### ISSUE TITLE
Using the newest commit, using the appveyor compile (newest commit) and Tibia 11.49 client will debug anytime I open a container.

### ISSUE THREAD

**Issue by H0ltman** [malucooo/Otxserver-New#600]
lanceholtman@gmail.com

No console errors, only client crashes.

**Comment by malucooo** [comment]
update ur tools... here are all ok!

**Comment by H0ltman** [comment]
Thanks for the tip. I am following the guide in the wiki... should I do
anything different than what it says? I get this now, but the program won't
run...
[image: Inline image 1]

I just installed all this according to the wiki on your github


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
