### ISSUE TITLE
Composite Hornbow sem Imbuing Slots

### ISSUE THREAD

**Issue by brahminhodark** [malucooo/Otxserver-New#601]
O Composite Hornbow está sem os slots de imbui.

![screenshot_14](https://user-images.githubusercontent.com/21095867/31868930-f5f30eda-b782-11e7-9ce9-a4d55c2cb6c7.png)

**Comment by mattyx14** [comment]
Ítems.xml ando imbuild.lua requiere update

**Comment by brunoxxt** [comment]
Não é bug é apenas colocar os slots dos imbue no items.xml e adicionar as armas no moviments para funcionar!!

**Comment by malucooo** [comment]
Preguiça detectada

**Comment by brahminhodark** [comment]
Preguiça detectada por que? Nem todo mundo sabe mexer com essas coisas rapaz, eu trabalho das 5:40 as 17:00 e faço curso das 18:00 até as 23:00 todo dia não tenho tempo de ficar pesquisando essas coisas não, eu reporto pra ajudar, é cada uma que meu amigo kk
