### ISSUE TITLE
Frag problem

### ISSUE THREAD

**Issue by esbuma** [malucooo/Otxserver-New#62]
Having some problem with frags.
The skulltime and playerskull stay at 0 until the player get redskull.
And after a player who is redskull use the the skull remover, he go back to red skull after one kill.
Here is a more pratical way of whats is the issue:
In my config.lua kills to red skulls are set up to 8
Until 7 kill, if i go to the player table in the database..the skull time is 0.
When the player get 8 kills, he get red skull. Just them the player skulltime in the database get a number.
The problem with these...things like !kills dont show your frags.

The skull remove problem.
A player who is red skull(8 kills) use the skull remove and his skulls is removed(the player skulltime in data base and the skull is set to 0 when u use the item)
Afther that players kill someone he go back to redskull. But he only got 1 kill

**Comment by darkjav** [comment]
Yes, bug confirmed, we are trying solved here:
https://otland.net/conversations/otx-malucoo.358141/#message-524112

If somebody have a idea, tell us.

**Comment by malucooo** [comment]
skull remover is pay to win...
