### ISSUE TITLE
[Warning : Yasir] NpcSystem

### ISSUE THREAD

**Issue by Mesosot** [malucooo/Otxserver-New#626]
[Warning : Yasir] NpcSystem:    Parameter(s) missing for item:               <!--rhino horn carving   nil     nil
[Warning : Yasir] NpcSystem:    Parameter(s) missing for item:      <!--scale of gelidrazah     nil     10000
[Warning : Yasir] NpcSystem:    Parameter(s) missing for item:      <!--small energy ball       nil     250
[Warning : Yasir] NpcSystem:    Parameter(s) missing for item:      <!--solid rage      nil     nil
[Warning : Yasir] NpcSystem:    Parameter(s) missing for item:      <!--strange proto matter    nil     300
[Warning : Yasir] NpcSystem:    Parameter(s) missing for item:       <!--tarnished rhino figurine       nil     320
[Warning : Yasir] NpcSystem:    Parameter(s) missing for item:      <!--tooth of tazhadur       nil     10000

**Comment by marcomoa** [comment]
O error confirma, os itens que estão "comentados" é por que não existem em items.xml.
