### ISSUE TITLE
DemonHelmet Quest

### ISSUE THREAD

**Issue by Gahznt** [malucooo/Otxserver-New#629]
Quest demon helmet não possui lever(alavanca)..Bueiro de rookgaard está sem ponte pra passagem!
Não é possível fazer o addon Mage full (a addon2(hat) até dá), porem o cajado não é possível pois não dá pra falar com a NPC ' Lynda ' em Thais.

**Comment by igordelecrode** [comment]
Atualize seu datapack inteiro e não somente o mapa! Todas as levers estão funcionando, inclusive as de rookgaard que acionam a ponte e as da quest demon helment que citou.
