### ISSUE TITLE
Have to wait 10 seconds before skinning demon

### ISSUE THREAD

**Issue by newacc12** [malucooo/Otxserver-New#63]
When you kill a demon you have to wait 10 seconds before being able to skin it. To solve this I added to line above to these three files:

data\actions\scripts\other\skinning.lua
data\actions\scripts\tools\skinning.lua
data\actions\scripts\skinning.lua

[5995] = {value = 25000, newItem = 5906, after = 2917}

I don't know if it's the best solution but works for me.

**Comment by malucooo** [comment]
make a pull request
