### ISSUE TITLE
Regeneration HP, Mana & Soul Points inside Houses

### ISSUE THREAD

**Issue by Olimpotibia** [malucooo/Otxserver-New#633]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use http://www.tibiaking.com/ or https://otland.net for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. When open Daily Reward you can select a bonus to improve your hp/mana/soul points regeneration inside houses.

### Expected behaviour
Open daily reward and select the bonus

### Actual behaviour
Missing daily reward system and the bonuses

**Comment by Eternal-Scripts** [comment]
Please, show us how this work with a reference, thanks.

**Comment by mattyx14** [comment]
Eternal ... that works in relation to the reward system on the first day gives you the reward of regenerating faster within certain areas mainly in depots and tem  .

**Comment by mattyx14** [comment]
And on the third day it gives you the ability to regenerate stamina and even soul and that regeneration multiplies as you accumulate rewards

**Comment by jlcvp** [comment]
Any documentation on this system?

**Comment by jlcvp** [comment]
found it! - @Eternal-Scripts a good system for us to work on

https://www.tibiawiki.com.br/wiki/Recompensas_Di%C3%A1rias
http://tibia.wikia.com/wiki/Daily_Reward_System
