### ISSUE TITLE
Shovel spot

### ISSUE THREAD

**Issue by Xiolonesz** [malucooo/Otxserver-New#634]
Shovels não abrem spots nas areias de ankrahmun.
Shovel id = 2554
Spot sand id = 9059 with action id 1345
Exemplo : 33161, 32598, 7 (coordanada de um spot)

A shovel apenas sumona os scarabs e cria scarab coin, porém não abre o hole que deveria para dar acesso a cave! 
Isso em todos os spots em areias.

**Comment by GuiValladao** [comment]
Muda a actionid do local pra 100, vai funcionar
