### ISSUE TITLE
Quest bug addon's 

### ISSUE THREAD

**Issue by hscmapos** [malucooo/Otxserver-New#635]
A Marina (Sereia de Meriana) não responde quando pergunta-se sobre a Mermaid Comb (tanto utilizando a palavra "comb" quanto a "mermaid comb" ou até "mermaid". Na mesma ilha encontra-se o NPC Morgan que faz as espadas das outfits knight e warrior (addons), porém ao pedir para fazer a knight's sword, utilizando a palavra "knight's sword" e em seguida "forge" o mesmo não responde e fica parado.

**Comment by malucooo** [comment]
make the correction and send a pull request!

**Comment by EnzzoCaaue** [comment]
Morgan is fully working. You should check any tibia wikia to know how to talk to him.
