### ISSUE TITLE
Shared exp voc3

### ISSUE THREAD

**Issue by Olimpotibia** [malucooo/Otxserver-New#637]
Tested with 1 rotworm and 4 voc (party all + Stamina Green)
4 different vocations 80% + 20%

15:42 Party Ek gained 1995 experience points.
15:42 Party Ms gained 1995 experience points.
15:42 Party Rp gained 1995 experience points.
15:42 Party Ed gained 1995 experience points.

(1400x2)/4= Y x 1.5=1050

 

Tested with 1 rotworm and 3 voc (party all + Stamina Green)
3 different vocations 40% + 20%

15:46 Party Ek gained 1102 experience points.
15:46 Party Ms gained 1102 experience points.
15:46 Party Ed gained 1102 experience points.

(1400x1.6)/3= Y x 1.5=1120

 

Tested with 1 rotworm and 2 voc (party all + Stamina Green)
Activating shared experience: 20% (for all combinations) plus

2 different vocations 10% + 20%
15:48 Party Ms gained 1365 experience points.
15:48 Party Ed gained 1365 experience points.

(1400x1.3)/2= Y x 1.5=1365 

 

Tested with 1 rotworm Alone (Stamina Green)
15:49 Party Ms gained 2100 experience points
(1400x1)/= Y x 1.5=2100 
rotworm 40*35x=1400xp

All tests with levels 9.

check here: 
http://tibia.wikia.com/g00/wiki/Party?i10c.encReferrer=aHR0cHM6Ly93d3cuZ29vZ2xlLmVzLw%3D%3D

**Comment by malucooo** [comment]
make a correction and send a pull request!
