### ISSUE TITLE
Alavancas sumiram

### ISSUE THREAD

**Issue by FlexLewis** [malucooo/Otxserver-New#639]
Alavancas de farmine sumiram! 

![lever](https://user-images.githubusercontent.com/28009621/32527021-6e964090-c413-11e7-80d3-4df3e39e8716.jpg)

**Comment by binho12378** [comment]
Só no seu amigo, aqui ta normal, talvez você tenha alterado alguma coisa em actions, ou sem querer deletou no RME, confere ai.
