### ISSUE TITLE
Missing Items

### ISSUE THREAD

**Issue by Nazgul001** [malucooo/Otxserver-New#643]
I was cheking items.xml and items.otbm and there wasn't items like this:

Lloyd Boss
<item id="27615" chance="5000" />

An Observer Eye
<item id="27585" countmax="1" chance="50320" />

And others...

Every boss on hall of hope are with wrong items id

**Comment by Eternal-Scripts** [comment]
Register for us, search about item editor, thanks.

**Comment by Nazgul001** [comment]
> 		<item id="27622" article="a" name="Part of a Rune (One)">
> 		<attribute key="description" value="Part one of a rune, maybe someone can tell you about this." />
> 		<attribute key="weight" value="850" />
> 	</item>
> 		<item id="27623" article="a" name="Part of a Rune (Two)">
> 		<attribute key="description" value="Part one of a rune, maybe someone can tell you about this." />
> 		<attribute key="weight" value="850" />
> 	</item>
> 		<item id="27624" article="a" name="Part of a Rune (Three)">
> 		<attribute key="description" value="Part one of a rune, maybe someone can tell you about this." />
> 		<attribute key="weight" value="850" />
> 	</item>
> 		<item id="27625" article="a" name="Part of a Rune (Four)">
> 		<attribute key="description" value="Part one of a rune, maybe someone can tell you about this." />
> 		<attribute key="weight" value="850" />
> 	</item>
> 		<item id="27626" article="a" name="Part of a Rune (Five)">
> 		<attribute key="description" value="Part one of a rune, maybe someone can tell you about this." />
> 		<attribute key="weight" value="850" />
> 	</item>
> 		<item id="27627" article="a" name="Part of a Rune (Six)">
> 		<attribute key="description" value="Part one of a rune, maybe someone can tell you about this." />
> 		<attribute key="weight" value="850" />
> 	</item>
> 		<item id="27628" article="a" name="Astral Shaper Rune">
> 		<attribute key="description" value="Just use the rune and Stone Rhino will be yours." />
> 		<attribute key="weight" value="850" />
> 	</item>
> 	<item id="26341" article="a" name="Menacing Egg">
> 		<attribute key="description" value="It is of foreboding, reddish colour and pulses steadily. You have the feeling that something dangerous is moving inside." />
> 		<attribute key="weight" value="850" />
> 	</item>
> 		<item id="26340" article="a" name="Crackling Egg">
> 		<attribute key="description" value="It is of unnerving, greenish colour and pulses steadily. It seems that something is moving inside." />
> 		<attribute key="weight" value="850" />
> 	</item>
> 		<item id="27715" article="a" name="Death Portal">
> 		<attribute key="description" value="" />
> 	</item>
> 		<item id="27719" article="a" name="Energy Portal">
> 		<attribute key="description" value="" />
> 	</item>
> 		<item id="27718" article="a" name="Earth Portal">
> 		<attribute key="description" value="" />
> 	</item>
> 		<item id="27726" article="a" name="Ice Portal">
> 		<attribute key="description" value="" />
> 	</item>
> 		<item id="27722" article="a" name="Fire Portal">
> 		<attribute key="description" value="" />
> 	</item>
> 		<item id="27724" article="a" name="Holy Portal">
> 		<attribute key="description" value="" />
> 	</item>
> 		<item id="16003" article="a" name="CM Token">
> 		<attribute key="description" value="It was a gift from a community manager." />
> 		<attribute key="weight" value="1000" />
> 	</item>
> 	<item id="27610" article="a" name="bones of Zorvorax">
> 		<attribute key="weight" value="800" />
> 	</item>
> 	<item id="27636" article="a" name="Golden Talon">
> 	<attribute key="weight" value="650" />
> 	</item>

I'm adding this to items.xml, but do you guys have some program to open the spr o dat to help me with this thx

**Comment by malucooo** [comment]
update items.xml and make a pull request!
