### ISSUE TITLE
Rift carpets / void carpets not being saved as house items

### ISSUE THREAD

**Issue by Olimpotibia** [malucooo/Otxserver-New#644]
https://github.com/otland/forgottenserver/issues/2021

add it when you can cjaker

**Comment by Eternal-Scripts** [comment]
Isn't a good solution because he use uint16_t (2 bytes) when you can use boolean (1 byte) in attribute.
This works fine anyway.

**Comment by Olimpotibia** [comment]
rift carpets not saved when player loss house and items sends to depot all, except carpets and rest of new decorations items from Store. need fix

**Comment by malucooo** [comment]
update items.xml and make a pull request...
