### ISSUE TITLE
Client Error with Spell Summons +200

### ISSUE THREAD

**Issue by Nazgul001** [malucooo/Otxserver-New#645]
> Debug Assertion 1133 Creatures.cpp 1712
> Thu Nov 09 16:28:11 2017
> Graphic Engine: DirectX9 (2)
> Operating System: Windows 10 in ESP
> Processor: Intel CORE I3-4
> Video Card: Intel (R) HD GR
> Last Packet Types: 164 143 161 161 162 152 099 233 238 238
> Last Packet: 023 006 000 000 016 050 000 003 015 021 013 128 003 169 252 003
> Player Position: [32397,32147,6]
> Player Name: Daika Liam (Tibia)
> Player Action: 049 050 055 046 048 046 048 046 049 058 055 049 055 050
> Player.cpp 354: exception occurred, reason:
> Network.cpp 951: exception occurred, reason:
> Control.cpp 1561: exception occurred (Type = 164) (MainWindow = 041B4740), reason:
> Communication.cpp 3972: exception occurred, reason:
> Creatures.cpp 1712: assertion failed (Spell = 194) (Delay = 1315000), reason:
> Spell < SPELL_BEYONDLAST

Got this error on  client version 10.100

**Comment by malucooo** [comment]
wrong client
