### ISSUE TITLE
Tile that can't trow area runes or fields over it: itemid 22158

### ISSUE THREAD

**Issue by kito2** [malucooo/Otxserver-New#646]
Tile that can't trow area runes or fields over it: itemid 22158

![image](https://user-images.githubusercontent.com/21250744/32641662-013e9294-c5ae-11e7-9e80-b125b9fb7c5c.png)

The red rectangle marks as the item that block proyectiles, and you can walk over it.

I have found several bugs like this, and it can be solved by using an OTB editor.

Could someone upload it please?

**Comment by Olimpotibia** [comment]
has mirado con el objectbuilder de cambiarlo?

**Comment by kito2** [comment]
No, intentare verlo.

**Comment by kito2** [comment]
Tried to use object builder, but it compiles tibia.spr and tibia.dat, can't create items.otb updated with it.

**Comment by kito2** [comment]
Here are more tiles: 

13:00 Your current position is: Position(33616, 32455, 7)
12:59 Your current position is: Position(33612, 32450, 7)
12:59 Your current position is: Position(33612, 32452, 7)
12:59 Your current position is: Position(33608, 32452, 7)
12:59 Your current position is: Position(33608, 32450, 7)
12:59 Your current position is: Position(33616, 32452, 7)
12:57 Your current position is: Position(33652, 32452, 7)

Can someone upload item.otb editor?

**Comment by mattyx14** [comment]
Deja reviso con builder y otb editor para ver si es problema de ítems y si es así generare uno nuevo

**Comment by kito2** [comment]
@mattyx14 podrias enseñarme como lo haces con object builder? No he podido hacerlo.

**Comment by mattyx14** [comment]
Ocupas agregar byte nuevos para que pueda leer .dat

**Comment by kito2** [comment]
Como haces eso?

**Comment by mattyx14** [comment]
he creado un items.otb pero la estructura es muy diferente debo preguntar a maluco si ha agregado alguna flag extra el 29002 corresponde al butterfly ring en esta version de items y en la mia es la 28600

**Comment by mattyx14** [comment]
![image](https://user-images.githubusercontent.com/2807739/32959538-8762780c-cb87-11e7-9694-5a3b689a66a5.png)

**Comment by kito2** [comment]
Da lo mismo, ya aprendi a generar un items.otb y corregi los mios. Thanks!
