### ISSUE TITLE
Mana shield no work

### ISSUE THREAD

**Issue by andre-sant** [malucooo/Otxserver-New#647]
Please in last upadate mana shield no working

**Comment by mattyx14** [comment]
for my work ... try use all datapack how are here

**Comment by andre-sant** [comment]
I used all files of site and no work mana shield again

**Comment by mattyx14** [comment]
o check it

**Comment by andre-sant** [comment]
i cast utamo vita, or use energy ring and this active icone on my buff's, but the damage decrease my life not mana

**Comment by mattyx14** [comment]
listo

**Comment by binho12378** [comment]
Sorry to bother, but the bug continues. :weary:

**Comment by mattyx14** [comment]
I try solve it. you can fully describe how the fault is completely
