### ISSUE TITLE
Consider to modify the potions to turn into empty flasks.

### ISSUE THREAD

**Issue by newacc12** [malucooo/Otxserver-New#65]
When using potions (health, mana potion etc) the potion just disappear.  Would be nice to have it turn into a empty flask like RL Tibia so players can make the belt addon for summoner: http://tibia.wikia.com/wiki/Summoner_Outfits_Quest/Spoiler

To make this you can comment out the lines below from this file: data\actions\scripts\other\potions.lua

if not parent:isTile() and (parent:addItem(potion.emptyId, 1) or topParent:addItem(potion.emptyId, 1)) then
 			item:remove(1)
			return true
		end

**Comment by malucooo** [comment]
make a pull request
