### ISSUE TITLE
Erro ao logar

### ISSUE THREAD

**Issue by Tekadon58** [malucooo/Otxserver-New#651]
![image](https://user-images.githubusercontent.com/23642470/32733188-5aa33378-c86d-11e7-920f-e2b38bd311ee.png)

**Comment by Nazgul001** [comment]
Did you try to update client version on src/definitions.h

static constexpr auto CLIENT_VERSION_MIN = 1100;
static constexpr auto CLIENT_VERSION_MAX = 1149;
static constexpr auto CLIENT_VERSION_STR = "11.49";
