### ISSUE TITLE
New Crash with Trade channel

### ISSUE THREAD

**Issue by darkjav** [malucooo/Otxserver-New#654]
Hi, today i had a issue with players that trade items using WPE Pro,
when they use it, the server only get "pause", but not get crash, console still there without errors,

Then i make forced closed for open it again.

I cant get bt full because server get pause and not crashed.

Here a video from player:
https://youtu.be/kkip1M81ABo

**Comment by mattyx14** [comment]
¿Amigo usas el último código? Para partir de ahí

**Comment by Eternal-Scripts** [comment]
Try reproduce that in our otx repository with last commit. I will put unconfirmed you have only 24 hours to do it.
