### ISSUE TITLE
Schema or gesior bug!?

### ISSUE THREAD

**Issue by EnzzoCaaue** [malucooo/Otxserver-New#655]
I don't know if it's a schema bug or a server bug but whenever I try to create an account it does not save the account in database.

![Image of account being created](https://i.imgur.com/OciUGTs.png)
![Image of trying to login](https://i.imgur.com/FDm45w6.png)

**Comment by EnzzoCaaue** [comment]
Here is the account table at my database:
![Table accounts in database](https://i.imgur.com/mfRauOV.png)

**Comment by Olimpotibia** [comment]
IF you use debian, please check your permissions (https://otland.net/threads/simple-ftp-tutorial-debian-ubuntu.103502/) if not delete all and start again.

**Comment by EnzzoCaaue** [comment]
I'm using ubuntu and all permissions are ok.
Already tried to delete everything (even apache) and start again but no sucess.

**Comment by Olimpotibia** [comment]
well your website is bugged or all is bugged for me all works perfect

**Comment by EnzzoCaaue** [comment]
LoL. I'll delete and download everything again right now. If you are right should work fine. brb.

**Comment by Llaw7** [comment]
Just go for your account database on your sql and edit then with default values for columns that haven't any set. I had to do it with my MyAAC, and now it's working fine (i had to edit a lot of DBs and set default values until it fully worked).
And yes Gesior has the same problem.
If it still doesn't work, it's unrelated to the problem that i had.

**Comment by EnzzoCaaue** [comment]
@Llaw7 I don't think this is the problem. I tried to create account using sql queries and ran successfully. Thinking about being gesior's problem now.

**Comment by markovicz** [comment]
@EnzzoCaaue Yes it's a Gesior bug, but just because our .sql isn't properly done, it miss a lot of default values (new columns on our dbs), so the non-updated query from Gesior will fail to pass.

**Comment by Llaw7** [comment]
@EnzzoCaaue Yes it's a Gesior bug, but it's caused because our databases got updated without default values set into the new columns, so when Gesior send its query without a value passed on those parameters it will fail.

**Comment by EnzzoCaaue** [comment]
Thanks @Llaw7. I'll try again later. Working on other things rn.

**Comment by malucooo** [comment]
can't reproduce this...

**Comment by EnzzoCaaue** [comment]
LOL
gotta be kidding.
