### ISSUE TITLE
Missing map part

### ISSUE THREAD

**Issue by EnzzoCaaue** [malucooo/Otxserver-New#662]
Missing first dragon's room from 20 years of tibia quest

**Comment by malucooo** [comment]
ins't a issue... go track and make a pull request!

**Comment by EnzzoCaaue** [comment]
How am I supposed to track if you don't share with us map tracker ?

**Comment by vankk** [comment]
That is an issue. That part is missing and last time that I checked in this repository description it was saying _"Full Global"_

**In this case we have two people's type:**
- Who already tracked but doesn't want share;
- who have the tracker but doesn't want share.
