### ISSUE TITLE
Map - missing UID and AID (Explorer Society Quest)

### ISSUE THREAD

**Issue by OBUCHpl** [malucooo/Otxserver-New#664]
I found 2 places where UID and/or AID is missing and both are needed to make Explorer Society Quest correctly work. I already have made some progress to fix this quest (github.com/malucooo/Otxserver-New/pull/663 - Uzgod, Angus), but for some reason I'm unable to edit and upload map now. So, if anyone can help.. changes that are needed:
- chest in Dwacatra (x=32598 y=31934 z=15): add AID=2000, UID=3001, contents itemID=4845
- sharp icicles in Folda (x=32133 y=31688 z=9): add UID=3000
Thanks

**Comment by guinomall** [comment]
I edited and added it on the map here, just did not try it

http://www.mediafire.com/file/16mr3ujo7aooesd/world.zip

**Comment by OBUCHpl** [comment]
@guinomall - archive 'realmap.rar' (inside 'world.zip') is broken

**Comment by malucooo** [comment]
make a pull request...
