### ISSUE TITLE
Yalahar Green Djinn quarter NPC

### ISSUE THREAD

**Issue by newacc12** [malucooo/Otxserver-New#67]
On green djinn quarter in Yalahar we can find this NPC. I believe this is wrong since this is the green djinn npc. It should be an Efreet instead. I don't know to fix maps so I am just posting the screenshots.

![image](https://cloud.githubusercontent.com/assets/20234557/25363636/b303c15e-2921-11e7-9da9-e8577d457761.png)

![image](https://cloud.githubusercontent.com/assets/20234557/25363638/b8aab4fa-2921-11e7-8fce-0ade643f9e70.png)

**Comment by malucooo** [comment]
we need remove this npc or put here?

**Comment by newacc12** [comment]
Remove. This is the green djinn quarter hunting ground and shouldn't have this NPC as far as I know. Maybe it's an efreet monsters instead of this npc

**Comment by malucooo** [comment]
fixed on last commit
