### ISSUE TITLE
Erro site

### ISSUE THREAD

**Issue by ThiagoMA** [malucooo/Otxserver-New#686]
Fatal error: Uncaught Error: Class 'ConfigLUA' not found in C:\xampp\htdocs\system\load.init.php:42 Stack trace: #0 C:\xampp\htdocs\index.php(18): include_once() #1 {main} thrown in C:\xampp\htdocs\system\load.init.php on line 42

**Comment by EnzzoCaaue** [comment]
Can't reproduce. 

unconfirmed

**Comment by Olimpotibia** [comment]
This is an error in your web page, if you downloaded it from a forum contact the owner but do not report as a bug since it has nothing to do with the OTX.

**Comment by Eternal-Scripts** [comment]
Please, open issue in the repository of website, not here.
