### ISSUE TITLE
Erro ao conectar no jogo

### ISSUE THREAD

**Issue by Tekadon58** [malucooo/Otxserver-New#690]
Estou tentando me conectar e fica dando este problema no cliente 
![image](https://user-images.githubusercontent.com/23642470/33186297-280dd1f0-d067-11e7-8071-3691382e7864.png)

Como uso o cliente em linux o terminal fala o que está acontecendo : 
![image](https://user-images.githubusercontent.com/23642470/33186303-3f9c3424-d067-11e7-83f7-e4b4482a2496.png)

**Comment by Tekadon58** [comment]
estou tentando me conectar o ip é : 127.0.0.1

**Comment by Tekadon58** [comment]
![image](https://user-images.githubusercontent.com/23642470/33186321-6b7cb744-d067-11e7-8283-77963e3010b8.png)

**Comment by Tekadon58** [comment]
criei um no no ip e o problema continua

**Comment by EnzzoCaaue** [comment]
Troca seu login.php

**Comment by Tekadon58** [comment]
já troquei já tentei fz de tudo mais continua assim

**Comment by EnzzoCaaue** [comment]
Ele passa da tela de seleção de character?

**Comment by EnzzoCaaue** [comment]
Se sim, é o client. Troca a RSA do client q é gg.

**Comment by Tekadon58** [comment]
Ele loga no cliente aparece o personagem para selecionar, porem quando clica fica carregando aquela barra vermelha e só fica nisso.

**Comment by Tekadon58** [comment]
Já fiz a modificação do cliente para ele funcionar com meu IP e modifiquei a chave RSA do cliente com o nodepad++

**Comment by Olimpotibia** [comment]
It is not a bug, it is that you do not know how to connect, look for tutorial and do not report false bugs.

**Comment by Tekadon58** [comment]
O problema é o cliente estou utilizando agora um cliente 11.46.

O correto seria deixar um cliente na versão que está funcionando disponível para download e não coloca para baixar diretamente no site da CipSoft, ate porque a Cip sempre atualiza o cliente então quando acaba de lançar uma versão vai a cip e a atualiza e quem tem o cliente nn pode logar acontecendo esse problema ai o erro não foi meu e sim porque a CipSoft mantem sempre seu cliente atualizado e este repositório não acompanha as atualizações !

**Comment by Tekadon58** [comment]
Agora estou usando um cliente puro 11.49 e ainda assim nn consigo logar.

![image](https://user-images.githubusercontent.com/23642470/33212921-e58b277c-d103-11e7-8494-e152343e1a0d.png)
