### ISSUE TITLE
No levers on Farmine

### ISSUE THREAD

**Issue by joao-albach** [malucooo/Otxserver-New#697]
I'm testing the datapack in a little i run with my friends and we noticed that there's no levers in the farmine elevators, so we cannot explore zao :(

**Comment by joao-albach** [comment]
and we cannot open the map on rme, it says unsuported client, no matter what we do :/

**Comment by vankk** [comment]
I can confirm this issue ![bug issue](http://prntscr.com/hf4k2q)

**Comment by joao-albach** [comment]
If you look you see a lever, but you cannot click it :(

**Comment by fignacio** [comment]
A month or so ago I've asked malucoo for this and he said that I should download the capernia global with missions..

But this problems affects the whole of Zao (you can't explore it) if you don't turn the lever.. (first mission with Ongulf)

**Comment by joao-albach** [comment]
The problem is, it's not only farmine, it's every single lever with the id 1945 :) and tibia quests are like 90% based on levers, so... It's a huge issue. 1945 it's the lever turned to the left, 1946 that is the lever pointing right works fine for some reason

**Comment by joao-albach** [comment]
Nevermind it, my client wasn't up to date...

**Comment by malucooo** [comment]
![image](https://user-images.githubusercontent.com/17693030/33360764-5c98a89c-d4bc-11e7-90c2-b496ea118468.png)
use correct client!!!
