### ISSUE TITLE
Afflicted Outfit

### ISSUE THREAD

**Issue by MichelFigueira** [malucooo/Otxserver-New#704]
Olá colegas,

Hoje recebi um report sobre o Afflicted Outfit Addons.

Fiz alguns testes e identifiquei que o Addon está entregando perfeitamente quando uso os 5 cloths...
Mas quando uso o Plague Mask e o Plague Bell para os addons nao acontece nada.

Minha solucao rapida foi adicionar as linhas abaixo em actions/scripts/addons/addons.lua:
`[13926] = {female = 431, male = 430, addon = 1, effect = CONST_ME_GIANTICE, achievement = 'Beak Doctor'},`
`[13925] = {female = 431, male = 430, addon = 2, effect = CONST_ME_GIANTICE, achievement = 'Beak Doctor'}`

Porem acredito ser a forma errada de resolver o problema, porque já existe um arquivo destinado somente para o Afflicted.

Tentei analisar e ver se encontrava o erro, mas nao obtive sucesso.
Se alguem se interessar e querer resolver o problema para os demais o arquivo é afflictedoutfit.lua em Actions. Nao vou efetuar um pull request porque a forma que eu fiz nao é a correta, mas resolveu minha urgencia.

Obrigado!

**Comment by OBUCHpl** [comment]
It is problem with incorrect storage value (it should test for storages from 12000 to 12005 if they are == 1 instead of test storage 12005 >= 6)
check my pull request
https://github.com/malucooo/Otxserver-New/pull/705
