### ISSUE TITLE
Bosses Ferumbras Ascendant Quest

### ISSUE THREAD

**Issue by robsongabriel** [malucooo/Otxserver-New#707]
When the players are killing the bosses of Ferumbras ascendant quest does not allow opening loot for any player.

For everyone it displays the message: _You are not the owner._

I have all the files updated and no modifications...
Does anyone know why? If you can explain how, I make the changes and create a request.

**Comment by MichelFigueira** [comment]
Not work... The problem is with players and not with server admin.

**Comment by MichelFigueira** [comment]
@Eternal-Scripts Eu vi que voce efetuou uma alteracao referente ao admin. Mas realmente eu também tenho esse problema de alguns jogadores matar X boss e avisar que nao é owner

**Comment by Eternal-Scripts** [comment]
Certo, vou reabrir o Issue. Esse problema foi testado com a base do OTX sem
modificações?

Em 30/11/2017 14:59, "MichelFigueira" <notifications@github.com> escreveu:

**Comment by MichelFigueira** [comment]
Sim, sempre estou testando em uma base limpa sem modificacoes ou mods, com todos os arquivos atualizados.

**Comment by MichelFigueira** [comment]
Eu vou fazer um novo teste agora a noite e te retorno.
Porque me parece que se eu sumono através do /M nao ocorre esse problema. Está acontecendo somente quando o boss é chamado pelo creaturescripts :s

**Comment by joao-albach** [comment]
Estava tentando corrigir a furyosa que não aparace no fury gates, e com ela ocorre o mesmo problema, ninguém consegue abrir o corpo quando ela morre, ninguém o owner do corpo. Mas o Mad Mage por exemplo, funciona normal.

**Comment by MichelFigueira** [comment]
@Eternal-Scripts Fiz alguns testes e confirmei minha teoria... O problema é apenas quando o boss é chamado via creaturescripts...

Eu fiz o seguinte teste:
- Loguei 5 personagens e fui matar um boss do Ferumbras ascendant.
- Quando terminei de matar, tentei abrir o corpo e a mensagem apareceu: _You are not the owner._
- Loguei o admin e sumonei através do _/m_ o mesmo boss para o personagem matar. Conseguiu abrir normal o corpo, incluso apareceu a mensagem de reward chest.

https://imgur.com/a/nSo6e
