### ISSUE TITLE
XP Issue

### ISSUE THREAD

**Issue by FlexLewis** [malucooo/Otxserver-New#71]
Even if I change xp rate in config.lua and desativate xp stage, I get this msg at console:

Lua Script Error: [Event Interface]
data/events/scripts/player.lua:Player@onGainExperience
data/events/scripts/player.lua:466: attempt to index global 'config' (a nil value)
stack traceback:
        [C]: in function '__index'
        data/events/scripts/player.lua:466: in function <data/events/scripts/player.lua:438>

Lua Script Error: [Event Interface]
data/events/scripts/player.lua:Player@onGainExperience
data/events/scripts/player.lua:466: attempt to index global 'config' (a nil value)
stack traceback:
        [C]: in function '__index'
        data/events/scripts/player.lua:466: in function <data/events/scripts/player.lua:438>

XP rate continues 1 even changes :(

Anybody can help me?

**Comment by malucooo** [comment]
if u dont go to use stages put this on stages.xml
<?xml version="1.0" encoding="UTF-8"?>
<stages>
	<config enabled="1" />
	<stage minlevel="1" multiplier="HERE YOUR RATE" />
</stages>

**Comment by malucooo** [comment]
if u dont go ues stages replace all code on yout stage.xml for this:
`<?xml version="1.0" encoding="UTF-8"?>
<stages>
	<config enabled="1" />
	<stage minlevel="1" multiplier="HERE YOUR RATE" />
</stages>
`
