### ISSUE TITLE
Kegs are only 1 use and some dont work

### ISSUE THREAD

**Issue by Wizjusz** [malucooo/Otxserver-New#710]
The kegs are bugged all of them I assume + some manas missing from store!

**Comment by Wizjusz** [comment]
great mana keg charged me super spirit potion and only all have 1 charge XD + description of items are bugged likke all wraps etc

**Comment by icemirow** [comment]
Good afternoon, actually we have 2 bugs, in the kegs and in the cask:

-> First: even the char having capacity, it does not let you buy the keg:

http://prntscr.com/hhdwzq
http://prntscr.com/hhdxl7

And if you do with GOD / ADM / GM - it does at most 100 units

-> Second: you buying the cask of 1000x units, it comes only with 1 remainder:

http://prntscr.com/hhdymr
http://prntscr.com/hhe01m
http://prntscr.com/hhe06t

**Comment by malucooo** [comment]
@marsoncschneider look this!

**Comment by marsoncschneider** [comment]
will take a look now
