### ISSUE TITLE
Bug dreamer challenge quest

### ISSUE THREAD

**Issue by Dagst** [malucooo/Otxserver-New#711]
Tem um erro nessa quest, no script em \actions\scripts\quests\dreamer challenge\**stoneTeleport.lua**

Quando clica na alavanca era pra a fonte "ligar", porém não funciona. 

[<a href="https://imgbb.com/"><img src="https://image.ibb.co/igyVQG/dreammer.png" alt="dreammer" border="0"></a><br /><a target='_blank' href='https://pt-br.imgbb.com/'>picture hosting</a><br />](url)

**Comment by OBUCHpl** [comment]
I suppose it's a problem with "item.itemid == 1946 (or 1945)" or something like this, but I'm unable to check this now, sorry

**Comment by joao-albach** [comment]
I had a problem with 1945 before, but i've solved it by updating my client to 11.49

**Comment by Eternal-Scripts** [comment]
Can you upload your client 11.49 for us?

**Comment by joao-albach** [comment]
@Eternal-Scripts https://www.mediafire.com/file/229qsai8923gw38/Tibia.zip

**Comment by Eternal-Scripts** [comment]
Amigo, você citou que seu Cliente é 11.49, a versão é 11.40 da qual eu baixei...

**Comment by joao-albach** [comment]
só o .exe :) por algum motivo com o .exe da 49 ele não conecta no gameserver

**Comment by Dagst** [comment]
o problema não é no item 1945.

**Comment by MichelFigueira** [comment]
@Eternal-Scripts Fiz alguns testes e comparei com o global. Está 100% funcional a quest apenas com algumas diferencas do Global:

- Os Stones Tile ID 426 das Action 8034 onde vai os items, no global permite andar por cima.
- A fence (ID1543) nao fica na posicao 32877, 32270, 14, e sim nas posicoes 32877, 32269, 14 e 32877, 32271, 14.
- No momento que voce ativa a alavanca a Dried Well se ativa, alterando dos IDS 3729, 3730, 3731 e 3732 para 3733, 3734, 3735 e 3736.
- O portal só deve aparecer depois de jogar water no Tile da posicao 32878, 32270, 14 e com o Dried Well Ativo.

Comparei com os videos: https://youtu.be/LDk6K5dJF7Q?t=14m30s e https://youtu.be/CsKfPlcLEuQ?t=14m51s

Video da forma que está: https://vimeo.com/246111123

Testes efetuados em uma base sem alteracoes com a versao 11.49.5884

**Comment by OBUCHpl** [comment]
Probably fixed #733

**Comment by malucooo** [comment]
fixed or not?
