### ISSUE TITLE
Bug ao abrir reward shrine

### ISSUE THREAD

**Issue by tataboy67** [malucooo/Otxserver-New#712]
por mais que eu tente abrir o reward shrine ele n esta funcionando, sabe oq pode ser?

**Comment by marcomoa** [comment]
Reward Shrine ainda não possui script.

**Comment by marcomoa** [comment]
Infelizmente não.

**Comment by Eternal-Scripts** [comment]
**2.5 -> Ao abrir um issue, obrigatoriamente você deve seguir a estrutura na aba "Write"**
