### ISSUE TITLE
LOGIN tibia 11

### ISSUE THREAD

**Issue by DamianDEB** [malucooo/Otxserver-New#715]
hiho i have  big problem i download client from tibia.com and from forum tibiaking client.exe with local ip 
on login.php i set server name and ip 127.0.0.1 download gesior acc GesiorMonteiro-master
i try to login see character click login to game and have waiting list like a refused

**Comment by icemirow** [comment]
hi damian, try this..

https://github.com/malucooo/Otxserver-New
https://github.com/slawkens/myaac - site

which version of the client did you download?

Cya

**Comment by Eternal-Scripts** [comment]
**2.5 -> Ao abrir um issue, obrigatoriamente você deve seguir a estrutura na aba "Write"**
