### ISSUE TITLE
Issues List - Marco Oliveira

### ISSUE THREAD

**Issue by marcomoa** [malucooo/Otxserver-New#717]
- [ ] - Gold Pouch pode ser comprada quantas vezes quiser na store.
- [ ] - Bug ao comprar os dois rerrol do preysistem com wpe crasha o servidor.
- [ ] - Quest [The Explorer Society](https://www.tibiawiki.com.br/The_Explorer_Society_Quest) não existe em quests.xml
- [ ] - Alguns bosses ainda não foram registrados no monsters.xml
- [ ] - Revisar danos dos monstros da feyrist.

**Comment by marcomoa** [comment]
Adicionei alguns dos bosses que não estavam registrados, mas provavelmente ainda existem muitos outros com o mesmo problema.

**Comment by vankk** [comment]
Could you tell me something Marcos? What are your criteria to balance the loot chances?

**Comment by igordelecrode** [comment]
Issue fechado, leia as regras e abra novamente https://github.com/malucooo/Otxserver-New/blob/master/README.md
