### ISSUE TITLE
Erro encontrado "prey system"

### ISSUE THREAD

**Issue by tataboy67** [malucooo/Otxserver-New#721]
pelo menos aqui no meu servidor, ao usar o prey system, vai funcionar normalmente... sq logo em seguida vc quiser trocar para outro monstro , esta como 0 de gold e esta deslogando o char, bugando o servidor todo !

**Comment by granoob** [comment]
realizei os teste,em 10 conta diferente e aqui não teve nenhum erro esta 100% a não o bonus de loot aparece o logserver mais o bônus sei-la, acho que não esta certo
