### ISSUE TITLE
ao abrir o servidor me deparei com 1 erro:

### ISSUE THREAD

**Issue by tataboy67** [malucooo/Otxserver-New#728]
nao possui dicer3.lua :/ como eu faço para adicionar esse dicer?

**Comment by tataboy67** [comment]
estou precisando desse cassino e acusou esse erro :/

**Comment by Schiffers** [comment]
cara vc não leu o readme sobre postar um issue ? D: se tem esse erro verifique se tem o tal dicer na pasta de npcs etc, se não tiver vc pode tentar esse:
https://otland.net/threads/visual-gambler-npc-tfs-1-x.238812/#post-2309564
