### ISSUE TITLE
membros da party não se atacam !

### ISSUE THREAD

**Issue by tataboy67** [malucooo/Otxserver-New#732]
aqui no meu servidor membros da party não conseguem se atacar... eu por mais que eu tente atacar, com pvp ativado ou não, não funciona.
eu nao consigo atacar mas a sd vai gastando :/
(cliente 10.00)
(aqui foi testado com apenas modificações no mapa)
podemos ver 2 chars teste:
![image](https://user-images.githubusercontent.com/34138503/33713870-0763f9fc-db34-11e7-93b0-bcb4aef70664.png)
aceitamos pt e tentei atacar sd, gastou 1 de sd, porem a sd nem chegou a atingir ele:
![image](https://user-images.githubusercontent.com/34138503/33713913-3867e496-db34-11e7-9bea-a818dba31c5b.png)
tentei com pvp ativado:
![image](https://user-images.githubusercontent.com/34138503/33713965-6c78e500-db34-11e7-937b-42b1c5c0d8c4.png)
mesma situaçao, a sd gasta, porem n atinge o inimigo...

**Comment by vankk** [comment]
Isso é proposital.

**Comment by Eternal-Scripts** [comment]
Foda-se
