### ISSUE TITLE
BUG - imbuement Bow test

### ISSUE THREAD

**Issue by granoob** [malucooo/Otxserver-New#734]
Aparentemente nos teste realizado agora pouco usando o projeto original, os bows e provelmente crossbow o tempo das imbuement não acabar fica somente em 20h

-- testei agora todos os bow e crossbow e realmente o tempo do imbuing não passa
-- adição no bug, parece que não funciona de zera o tempo com qualquer ataque distance
vale para todos os items

**Comment by Eternal-Scripts** [comment]
Foda-se
