### ISSUE TITLE
Ubuntu 16.04 compile errors

### ISSUE THREAD

**Issue by jerryb1988** [malucooo/Otxserver-New#739]
Followed Ubuntu compile guide from wiki, getting this:

jerry@B250M-DS3H:~/Otxserver-New/build$ make
[  1%] Generating CXX prefix source cotire/tfs_CXX_prefix.cxx
[  2%] Generating CXX prefix header cotire/tfs_CXX_prefix.hxx
[  3%] Building CXX precompiled header cotire/tfs_CXX_prefix.hxx.pch
Scanning dependencies of target tfs
[  4%] Building CXX object CMakeFiles/tfs.dir/src/otpch.cpp.o
[  5%] Building CXX object CMakeFiles/tfs.dir/src/account.cpp.o
[  7%] Building CXX object CMakeFiles/tfs.dir/src/actions.cpp.o
In file included from /home/jerry/Otxserver-New/src/actions.cpp:26:
In file included from /home/jerry/Otxserver-New/src/game.h:30:
In file included from /home/jerry/Otxserver-New/src/player.h:28:
/home/jerry/Otxserver-New/src/vocation.h:106:30: error: field 'gainHealthTicks'
      is uninitialized when used here [-Werror,-Wuninitialized]
                uint32_t gainHealthTicks = gainHealthTicks;
                                           ^
/home/jerry/Otxserver-New/src/vocation.h:29:12: note: during field
      initialization in this constructor
                explicit Vocation(uint16_t id) : id(id) {}
                         ^
/home/jerry/Otxserver-New/src/vocation.h:107:31: error: field 'gainHealthAmount'
      is uninitialized when used here [-Werror,-Wuninitialized]
                uint32_t gainHealthAmount = gainHealthAmount;
                                            ^
/home/jerry/Otxserver-New/src/vocation.h:29:12: note: during field
      initialization in this constructor
                explicit Vocation(uint16_t id) : id(id) {}
                         ^
/home/jerry/Otxserver-New/src/vocation.h:108:28: error: field 'gainManaTicks' is
      uninitialized when used here [-Werror,-Wuninitialized]
                uint32_t gainManaTicks = gainManaTicks;
                                         ^
/home/jerry/Otxserver-New/src/vocation.h:29:12: note: during field
      initialization in this constructor
                explicit Vocation(uint16_t id) : id(id) {}
                         ^
/home/jerry/Otxserver-New/src/vocation.h:109:29: error: field 'gainManaAmount'
      is uninitialized when used here [-Werror,-Wuninitialized]
                uint32_t gainManaAmount = gainManaAmount;
                                          ^
/home/jerry/Otxserver-New/src/vocation.h:29:12: note: during field
      initialization in this constructor
                explicit Vocation(uint16_t id) : id(id) {}
                         ^
/home/jerry/Otxserver-New/src/vocation.h:110:22: error: field 'gainCap' is
      uninitialized when used here [-Werror,-Wuninitialized]
                uint32_t gainCap = gainCap;
                                   ^
/home/jerry/Otxserver-New/src/vocation.h:29:12: note: during field
      initialization in this constructor
                explicit Vocation(uint16_t id) : id(id) {}
                         ^
/home/jerry/Otxserver-New/src/vocation.h:111:23: error: field 'gainMana' is
      uninitialized when used here [-Werror,-Wuninitialized]
                uint32_t gainMana = gainMana;
                                    ^
/home/jerry/Otxserver-New/src/vocation.h:29:12: note: during field
      initialization in this constructor
                explicit Vocation(uint16_t id) : id(id) {}
                         ^
/home/jerry/Otxserver-New/src/vocation.h:112:21: error: field 'gainHP' is
      uninitialized when used here [-Werror,-Wuninitialized]
                uint32_t gainHP = gainHP;
                                  ^
/home/jerry/Otxserver-New/src/vocation.h:29:12: note: during field
      initialization in this constructor
                explicit Vocation(uint16_t id) : id(id) {}
                         ^
/home/jerry/Otxserver-New/src/vocation.h:114:26: error: field 'attackSpeed' is
      uninitialized when used here [-Werror,-Wuninitialized]
                uint32_t attackSpeed = attackSpeed;
                                       ^
/home/jerry/Otxserver-New/src/vocation.h:29:12: note: during field
      initialization in this constructor
                explicit Vocation(uint16_t id) : id(id) {}
                         ^
/home/jerry/Otxserver-New/src/vocation.h:115:24: error: field 'baseSpeed' is
      uninitialized when used here [-Werror,-Wuninitialized]
                uint32_t baseSpeed = baseSpeed;
                                     ^
/home/jerry/Otxserver-New/src/vocation.h:29:12: note: during field
      initialization in this constructor
                explicit Vocation(uint16_t id) : id(id) {}
                         ^
/home/jerry/Otxserver-New/src/vocation.h:118:28: error: field 'gainSoulTicks' is
      uninitialized when used here [-Werror,-Wuninitialized]
                uint16_t gainSoulTicks = gainSoulTicks;
                                         ^
/home/jerry/Otxserver-New/src/vocation.h:29:12: note: during field
      initialization in this constructor
                explicit Vocation(uint16_t id) : id(id) {}
                         ^
/home/jerry/Otxserver-New/src/vocation.h:120:21: error: field 'soulMax' is
      uninitialized when used here [-Werror,-Wuninitialized]
                uint8_t soulMax = soulMax;
                                  ^
/home/jerry/Otxserver-New/src/vocation.h:29:12: note: during field
      initialization in this constructor
                explicit Vocation(uint16_t id) : id(id) {}
                         ^
/home/jerry/Otxserver-New/src/vocation.h:121:22: error: field 'clientId' is
      uninitialized when used here [-Werror,-Wuninitialized]
                uint8_t clientId = clientId;
                                   ^
/home/jerry/Otxserver-New/src/vocation.h:29:12: note: during field
      initialization in this constructor
                explicit Vocation(uint16_t id) : id(id) {}
                         ^
12 errors generated.
CMakeFiles/tfs.dir/build.make:126: recipe for target 'CMakeFiles/tfs.dir/src/actions.cpp.o' failed
make[2]: *** [CMakeFiles/tfs.dir/src/actions.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/tfs.dir/all' failed
make[1]: *** [CMakeFiles/tfs.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by mattyx14** [comment]
enter to :
CMakeLists.txt

and remove:
-Werror
