### ISSUE TITLE
Reward System Boss bug

### ISSUE THREAD

**Issue by GoularPink** [malucooo/Otxserver-New#743]
### Steps to reproduce (include any configuration/script required to reproduce)
1. **Vai a algum local que dê pra ver alguém derrotando um boss, utilizando a ferramenta level spy do MageBot.**
2. **Após o boss ser morto você poderá ganhar loot e se não ganhar loot aparecerá uma mensagem de nothing.**

### Expected behaviour
1- **Se um player usar level spy, ou só observar algum boss sendo derrotado, ele não deve ganhar nenhum loot e também não deve receber mensagem alguma sobre o loot. (não estando em party)**

### Actual behaviour
1- **Se o player estiver usando um level spy e estiver vendo outros derrotando algum boss, ele também vai ter a possibilidade de ganhar loot (só observando no level spy). (não estando em party)**

Acho que é a função **creature:getDamageMap()** está capturando damage dos andares acima e abaixo.

**Comment by Eternal-Scripts** [comment]
Finalmente alguém entendeu como usar ISSUES :D

**Comment by malucooo** [comment]
e agora josé?

**Comment by MichelFigueira** [comment]
Fiz um teste basico e já deu para simular o bug.

Segue video do teste: https://vimeo.com/247180221

**Comment by malucooo** [comment]
Se tomar hit ele entende que participou do combate acaba ganhando reward

**Comment by MichelFigueira** [comment]
@malucooo lol nao é esse o problema... Se voce quiser crio um novo video, com o primeiro personagem já na area dos demons... Sem nem passar pelo boss do andar abaixo... Vai dar a mesma coisa... Sem nem enchergar o boss em nenhum momento ele ganha o loot.

**Comment by GoularPink** [comment]
@malucooo  fechou isso por que? ta bugado, só chegar no andar em cima de algum boss diário e deixar lá 24h afk que vai ficar rico em qualquer ot, não entendi por que fechou esse issue.
