### ISSUE TITLE
Loot dos bosses em geral está com problemas

### ISSUE THREAD

**Issue by joao-albach** [malucooo/Otxserver-New#744]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use http://www.tibiaking.com/ or https://otland.net for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Matar algum boss da quest do ferumbras ou a furyosa por exemplo
2. Tentar abrir o corpo

### Expected behaviour
Receber a recompensa do boss

### Actual behaviour
Fala que o corpo não pertence a player, não importa quem mate.

### Environment
Como muita gente esta tendo esse problema, creio que não precisa fazer nenhuma modificação

**Comment by MichelFigueira** [comment]
Mesma questao da Issue 707: https://github.com/malucooo/Otxserver-New/issues/707

Tem infos do meu teste lá se precisarem

**Comment by malucooo** [comment]
nomes dos boss plz!

**Comment by MichelFigueira** [comment]
@malucooo Testei com o Tarbaz

**Comment by Thierryvil** [comment]
Substitua `doCreateItem` por `Game.createItem`

**Comment by costa55** [comment]
o problema ocorre pelo fator de ta com a tag: <flag rewardboss="1" />
e talvez tenha que registrar no scripts de recompense que nao deve estar

eu mudei <flag rewardboss="0" /> ai funcionou normal

**Comment by malucooo** [comment]
@Thierryvil substituir onde?

**Comment by malucooo** [comment]
@costa55 se tirar a tag o monstro sai do sistema...

**Comment by Thierryvil** [comment]
@malucooo em todo o lugar que tiver `doCreateItem`

**Comment by malucooo** [comment]
fixed in last commits
