### ISSUE TITLE
Prey Columns

### ISSUE THREAD

**Issue by Aerwix** [malucooo/Otxserver-New#746]
New players only need 2 prey colums unlocked and 1 locked. (Like as Tibia Rl).

If someone could help me please

Probably this issue must be converted into Pull request.

If you have any doubt maybe i can explain it better.

Greetings

### Steps to reproduce (include any configuration/script required to reproduce)
1. Create a new player
2. Do Rookgard stuff
3. Go Mainland

### Expected behaviour
Player only with 2 Prey columns  and 1 locked 

### Actual behaviour
Player with 3 prey colums unlocked.

### Environment
Linux (Already compiled and donwloaded the code too many times and still has the same).

**Comment by icemirow** [comment]
Yes, it happened to me too.

**Comment by malucooo** [comment]
Isn't a issue...
