### ISSUE TITLE
NPCs Missing

### ISSUE THREAD

**Issue by blackz13** [malucooo/otxserver-new#75]
[Error - Npc::loadFromXml] Failed to load data/npc/Owin.xml: File was not found
[Error - Npc::loadFromXml] Failed to load data/npc/Maeryn.xml: File was not found

I am affraid to delete them because i don't know him, and i don't know what they do, u have it?

**Comment by favasconcelos** [comment]
Both are NPCS from Grimvale.

- https://tibia.fandom.com/wiki/Owin
- https://tibia.fandom.com/wiki/Maeryn

The second one (Maeryn) is part of https://tibia.fandom.com/wiki/Grimvale_Quest
