### ISSUE TITLE
compilação windows com erro

### ISSUE THREAD

**Issue by costa55** [malucooo/Otxserver-New#750]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use http://www.tibiaking.com/ or https://otland.net for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Ao abrir o visual studio, diz que o projeto esta com falha
2. essa falha estava para versão windows
3. não foi testado em linux

### Expected behaviour
1. ao abrir o theforgottenserver.vcxproj usando o editor, vi que estava faltando linha

### Actual behaviour
1. fiz um reparos simples

### Environment

1. fiz as correções e conseguir compilar sem problemas , segui o link do paste bin com a correção
2. para aplica a correção basta abrir o theforgottenserver.vcxproj pelo notepad ++, apague tudo e coloque o que esta no pastebin
3. https://pastebin.com/P3haKsPU , espero que tenha ajudado

**Comment by malucooo** [comment]
Aqui compila normal
