### ISSUE TITLE
Critical Imbuiment

### ISSUE THREAD

**Issue by Nicholasz23** [malucooo/Otxserver-New#755]
### Before creating an issue, please ensure:
- [ ] This is a bug in the software that resides in this repository, and not a
      support matter (use http://www.tibiaking.com/ or https://otland.net for support)
- [ ] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Make critical imbuiment on a weapon
2. Equip weapon
3. Try exori or some spell

### Expected behaviour
all creatures get caught by the critical

### Actual behaviour
Sometimes critical does not catch on all creatures

https://i.imgur.com/WINDcOw.png

### Environment

**Comment by malucooo** [comment]
its = the tibia global system
