### ISSUE TITLE
Bug the ancient tomb quest

### ISSUE THREAD

**Issue by Dagst** [malucooo/Otxserver-New#756]
Ao usar os instrumentos
data\actions\scripts\quests\theancienttombs\AncientRuinsTombInstruments.lua

Seria preciso seguir uma ordem para liberar a porta, porém utilizando qualquer item a porta é liberada.

**Comment by Eternal-Scripts** [comment]
Não aprende mesmo né, triste.

**Comment by Dagst** [comment]
Ensina velho, não é mais fácil?

**Comment by joseluis2g** [comment]
Hes talking about the way how to do the issue you t4rd. But thats also difficult to understand.

**Comment by Dagst** [comment]
Tô vendo issue aberto com menos detalhes, mas é baba ovo e não fecha, não reporto mais, simples assim, só tentei ajudar.

**Comment by joseluis2g** [comment]
Do the fxck you want bro. No one cares. Eternal had lot of closed issues all for the same reason. Use the issue format and do not be a kid. Or do the fxck you want.  I dont care.

**Comment by Dagst** [comment]
Long to be crazy, took as pain? You just have to be fair to everyone. But it's not me, I have no server.

**Comment by joseluis2g** [comment]
Wtf did you said?

**Comment by Eternal-Scripts** [comment]
Então, independente do motivo é bom ler as regras, custa nada tirar 1
minuto da sua vida pra uma leitura básica. Se você não gostou então nem
baixe o repositório e não atrapalhe.
Os issues que estão abertos foram antes das regras atualizarem, portanto
falta de atenção sua.
Regars Cjaker.

Em 21/12/2017 18:29, "Joseluis González" <notifications@github.com>
escreveu:

**Comment by Dagst** [comment]
Infelizmente existe alguns amadores aqui. A maneira de falar com as pessoas é muito importante para que tudo funcione bem. Não vejo esse tipo de tratamento no repositório do TFS, inclusive sou contribuidor lá. Você não fala com um iniciante na área. Apenas sou novo no github, mas trabalho com servidores a muitos anos. Eu só reportei porque pensei que era preciso criar um issue e depois o pull request. Mas eu encerro aqui minha participação e conversa sobre qualquer tema relacionado ao repositório. Desculpe qualquer coisa.

**Comment by joseluis2g** [comment]
Good bye son

**Comment by Eternal-Scripts** [comment]
Pode até não ser iniciante na área, mas é burro em leitura, então não muda nada.
Mesmo sendo contribuidor lá, creio eu que tenha habilidades para resolver um problema de nível baixo como esse, mas ao meu ver é mentira. Fica a critério de cada um acreditar se você é ou não.
Whatever, não adianta discutir, encerra sua participação também no tfs, pois sua ignorância em ler é bem preocupante.
