### ISSUE TITLE
Bosses show up in Prey system

### ISSUE THREAD

**Issue by H0ltman** [malucooo/Otxserver-New#759]
### Before creating an issue, please ensure:
- [X] This is a bug in the software that resides in this repository, and not a
      support matter (use http://www.tibiaking.com/ or https://otland.net for support)
- [X] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. open prey dialog
2. reroll
3. hover over monsters (some will be bosses) 
4. IF NOT reroll again and repeat

### Expected behaviour
Bosses shouldn't come up in Prey system

### Actual behaviour
Bosses show up in Prey dialog

### Environment
Not dependent on environment.

**Comment by mattyx14** [comment]
For a bosses remove from the map ... booses onli created only on raids o r special events

**Comment by H0ltman** [comment]
I don't understand. Please respond in your native language so that I can translate it with google.

**Comment by mattyx14** [comment]
So that a boss does not appear in the pre and must be removed from the map and only be generated by an event or raid

**Comment by H0ltman** [comment]
Ok, thanks. Does it make sense to have it on the map then? I haven't made any changes. This is the map from the repo.
