### ISSUE TITLE
Transform Gold bug

### ISSUE THREAD

**Issue by Nicholasz23** [malucooo/Otxserver-New#762]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use http://www.tibiaking.com/ or https://otland.net for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)

1. Create a bag and create crystal coin until you fill the bag.
https://i.imgur.com/Q3LwVQW.png

2. Use in crystal coin, with intent to turn it into platinum coin.
https://i.imgur.com/OBTZDyN.gifv

### Expected behaviour
When giving use in the crystal coin that is inside the bag, 100 coin platinum fall to the ground.

### Actual behaviour
When giving use in the crystal coin, the money disappears.

### Environment

**Comment by H0ltman** [comment]
Confirmed. This is an issue.

**Comment by Nicholasz23** [comment]
O bug tambem ocorre quando o dinheiro esta no chao e sua backpack esta cheia.

**Comment by joseluis2g** [comment]
Can you translate it please. I can also help.

**Comment by H0ltman** [comment]
> The bug also occurs when money is on the floor and your backpack is full.
-Nicholasz23 (translated to english)

**Comment by H0ltman** [comment]
"When using a crystal coin inside a bag, if the bag is full the money disappears rather than falling on the ground."

**Comment by joseluis2g** [comment]
What about reverting this commit https://github.com/malucooo/Otxserver-New/commit/724a04032daa441175bcb8c0e4ede09fe7dd3d86

**Comment by H0ltman** [comment]
That works, Jose. Thanks a lot. 

Any downside?

**Comment by joao-albach** [comment]
From time to time, my tibia crashes when I click on the platinum coin and it's suposed to turn into gold :/

**Comment by Blingx** [comment]
Would it be a good idea to make the gold that would drop transfer to the bank instead?
