### ISSUE TITLE
Players do not gain soul

### ISSUE THREAD

**Issue by H0ltman** [malucooo/Otxserver-New#763]
### Before creating an issue, please ensure:
- [X] This is a bug in the software that resides in this repository, and not a
      support matter (use http://www.tibiaking.com/ or https://otland.net for support)
- [X] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Make a character, it will have zero soul. 
2. Hunt monsters, your soul should go up.
3. It will not.

### Expected behaviour
Players should gain soul.

### Actual behaviour
Players never gain soul.

### Environment
N/A

**Comment by icemirow** [comment]
have a screenshot? because I tested here and the soul points go up yes, if you kill the bixo that gives you more XP you have to level ..

**Comment by H0ltman** [comment]
I'll be damned. This is totally my mistake. 

Thanks Icemirow.

**Comment by icemirow** [comment]
hahahahah no problem, 

close issue!

**Comment by Schiffers** [comment]
so close that issue

**Comment by H0ltman** [comment]
Just saw it at the bottom of the screen, I looked forever. 

Thanks guys
