### ISSUE TITLE
 The Ice Islands Quest  - The contactmen (Erro no código :) )

### ISSUE THREAD

**Issue by joao-albach** [malucooo/Otxserver-New#764]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use http://www.tibiaking.com/ or https://otland.net for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Começe a quest
2. Termine a missão 'The Secret of Helheim'
3. Quando for falar com o Lurik não tem como aceitar a missão falando yes

### Expected behaviour

Deveria dar um update no quest log e ele falar que espera o seu retorno com o memory crystal

### Actual behaviour

Nada acontece, pois o Lurik.lua esta com erro na linha 73, o if e else if estão na ordem errada, é só trocar, mas não manjo dos paranauê no git então melhor do que não fazer nada resolvi reportar

**Comment by GoularPink** [comment]
Posta aí o error que da por favor?

**Comment by OBUCHpl** [comment]
sorry, that is my bad.. so #776

**Comment by malucooo** [comment]
fixed at last commit
