### ISSUE TITLE
Faltando cave Krailos

### ISSUE THREAD

**Issue by GoularPink** [malucooo/Otxserver-New#768]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use http://www.tibiaking.com/ or https://otland.net for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Ir até alguma dessas posições.
Position: 33528, 31675, 7
Position: 33549, 31662, 7

### Expected behaviour
Ter duas caves novas da cidade de Krailos

### Actual behaviour
Faltam caves nessas posições.

**Comment by igordelecrode** [comment]
Obrigado por ter encontrado essas caves que faltam no mapa, irei adicionar-las em breve junto a outras novidades!

Continue esse trabalho de encontrar coisas que faltam no mapa ou erros, assim posso repor de um forma mais rápida com mais colaborações!

**Comment by GoularPink** [comment]
adicionou?
