### ISSUE TITLE
Erro no mapa, asuras palace

### ISSUE THREAD

**Issue by joao-albach** [malucooo/Otxserver-New#769]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use http://www.tibiaking.com/ or https://otland.net for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Ir até a coordenada 32950, 32671, 5
![image](https://user-images.githubusercontent.com/5909121/34439757-52c1264e-ec97-11e7-82bf-4fb6a31996a5.png)
2. Coloquei o infernal bolt no andar de baixo
3. Parece que esta faltando um quadrado ali  haha

### Expected behaviour
Não conseguir ver o andar de baixo

### Actual behaviour
É possível ver o andar de baixo

**Comment by igordelecrode** [comment]
Sera reparado em breve.
