### ISSUE TITLE
Bag of Apple Slices 

### ISSUE THREAD

**Issue by GoularPink** [malucooo/Otxserver-New#770]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use http://www.tibiaking.com/ or https://otland.net for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Tenta usar a Bag of Apple Slices em uma Incredibly Old Witch transformada em Donkey. 
2. Tenta usar a Bag of Apple Slices em um monstro transformado em Donkey. 
3. Não irá funcionar

### Expected behaviour

1- Usar a Bag of Apple Slices na bruxa enquanto ela estiver transformada em Donkey e domar o Donkey se der sorte.

### Actual behaviour

1- Não da pra usar o item na bruxa ou em nenhum monstro enquanto estão transformados.

**Comment by malucooo** [comment]
fixed at last commit
