### ISSUE TITLE
Desert Quest wrong reward

### ISSUE THREAD

**Issue by sn4tch0vsk** [malucooo/Otxserver-New#772]
10 crystal coins instead 100 platinum.

![untitled-1](https://user-images.githubusercontent.com/27328490/34457996-66760520-ed77-11e7-8245-ae58c53acff1.jpg)

**Comment by OBUCHpl** [comment]
![desert todo](https://user-images.githubusercontent.com/33429155/34500140-b7f982c0-f009-11e7-8cd3-ea9ce913d39e.PNG)
@igordelecrode ?

**Comment by EnzzoCaaue** [comment]
@OBUCHpl should be 100 planitum instead of 10 crystal.

**Comment by OBUCHpl** [comment]
Yup, I know, it was information for @igordelecrode because as far as I know he is responsible for map editing, I just wanted to show him how it looks in RME (especially coordinates), simply to make it easier to fix ;)

**Comment by sn4tch0vsk** [comment]
Sooner I will open a new issue with all the quests bugs that I find.

I'll put the bug and how should be. Guess will be better to handle instead open new issue for each quest bug.

@OBUCHpl thanks to report him about this one.

**Comment by malucooo** [comment]
we are making many fixes in map and gonna make upload in 1 times, because the limit of github file transfer
