### ISSUE TITLE
Donkey mount

### ISSUE THREAD

**Issue by GoularPink** [malucooo/Otxserver-New#778]
Esse commit ficou quase bom: 
https://github.com/malucooo/Otxserver-New/commit/19907ce7f68420584de5e1d52728c6d65ec8c31a

Porém ainda está errado, pois só está dando pra usar no monstro chamado Donkey, era pra dar pra usar em qualquer monstro ou npc transformado em Donkey, mesmo que tenham outro nome mas estando com o looktype era pra funcionar.
  
**_erros:_**
if mount.type ~= target.type
			or (mount.lookType and mount.lookType ~= target:getOutfit().lookType)
			or (**mount.name and mount.name ~= targetName**) then

**if action.run then
elseif action.destroyObject then**

action.run e destroyObject nao existe

**Comment by Eternal-Scripts** [comment]
Organize o seu issue com a nossa estrutura.

**Comment by GoularPink** [comment]
@Eternal-Scripts  Organizar tudo aquilo pra ser fechado e desaparecer o issue é chato... Se pelo menos deixassem como no forgotten

Explicação rápida: 

Só ta dando pra usar no monstro Donkey
Era pra dar pra usar em qualquer monstro transformado em Donkey, exemplo: Um Bear transformado em Donkey, era pra funcionar.
