### ISSUE TITLE
Third prey slot takes 760 hours to reroll

### ISSUE THREAD

**Issue by H0ltman** [malucooo/Otxserver-New#779]
Third prey reroll slot takes 760 hours to reroll.

### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use http://www.tibiaking.com/ or https://otland.net for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Open prey dialog
2. Look at time for reroll on third slot
3. The reroll time for the third slot is 760 hours, not 20

### Expected behaviour
Should take 20 hours for all slots.

### Actual behaviour
Two slots are 20 hours, third is 760 hours

**Comment by joao-albach** [comment]
And for some reason, when you reroll it fixes to time, but if you relog the time is set to 760h again

**Comment by jlcvp** [comment]
looks like a index error, Lua arrays are 1-based, C/C++ (clients) are 0-based. I'll investigate

**Comment by H0ltman** [comment]
Why is this issue closed? (all issues for that matter)
