### ISSUE TITLE
Donkey Mount

### ISSUE THREAD

**Issue by GoularPink** [malucooo/Otxserver-New#780]
### Before creating an issue, please ensure:
- [ ] This is a bug in the software that resides in this repository, and not a
      support matter (use http://www.tibiaking.com/ or https://otland.net for support)
- [ ] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Tenta usar o item em um monstro transformado em Donkey
2. Não da pra usar

### Expected behaviour

1- Usar o bag of~ em algum monstro ou npc com o looktype Donkey e domar a criatura, ou falhar.

### Actual behaviour

1- Só da pra usar o item no próprio monstro Donkey e não da pra usar em monstros transformados pela bruxinha

**Comment by icemirow** [comment]
testei aqui e tá funcionando normal
