### ISSUE TITLE
Crash client when try open containers

### ISSUE THREAD

**Issue by Armed7979** [malucooo/Otxserver-New#781]
### Before creating an issue, please ensure:
- [ ] This is a bug in the software that resides in this repository, and not a
      support matter (use http://www.tibiaking.com/ or https://otland.net for support)
- [X ] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1.   Download Otxserver-New
2.   Download Client Tibia 11.49.5813
3.   Download IP Changer 11.40
4.   Install ZAC ACC in website 
5.   Configure and import .SQL to MySQL
6.   Configure config.lua
7.   Login in OTS
8.   All is works but when I try open backpack/deposit (containers), client have crash
9.   In consol I just logged out.
10. I try clear table player_items but this is not work.

### Expected behaviour

Open containers( backpack etc.)
### Actual behaviour

Crash client when i try open containers (backpack)
### Environment
Debian 8
Otxserver latest
Client Tibia 11.49.5813
IP Changer 11.40

Client error:
Character: Armed
EngineID: 1
HardwareID: c2563913cfddaa1d0c2e20851fc6df080daef3c8
OperatingSystem: Windows 7
Position: [33014,32060,7]
ProductName: Tibia Client
Server: OTXServer-Global
Timestamp: 1515248266
Version: 11.49.5884

**Comment by Schiffers** [comment]
empty backpacks or backpacks that you create some item and it was throwed into the backpack ?
should be problem with otb, you try with client 10, the outdated?

**Comment by Armed7979** [comment]
This is clear OTS, i dont create anything. I only install OTS and have problem.

**Comment by Schiffers** [comment]
try use the client 10 to see if it happens, almost sure that is a wrong byte in somewhere

**Comment by Schiffers** [comment]
also, the container should have a name in items.xml else ofc it will crash the client

**Comment by H0ltman** [comment]
Reinstall your client.

**Comment by malucooo** [comment]
Reinstall client
