### ISSUE TITLE
<QUESTS BUGS OR MISSING>

### ISSUE THREAD

**Issue by sn4tch0vsk** [malucooo/Otxserver-New#782]
Guys, I'm testing all the possibles quests, one by one, with all the details, paths, talks etc.. to check if has any bug, ex: if is missing something, incomplete or unable to start etc...

This is based at the most updated version, so, if any of these quests was already solved, please, let me know so I can test again and make 100% sure. I hope this can help to improve a lot more the OT.

I will keep updating this post with more bugs daily.

------------------------------------------------------------------------------------------------------------------

**Spike Tasks Quest -** 

NPC Gnommander don't start the tasks missions. NPC Gnomilly said that you already has the outfit and don't start the Upper Spike Tasks (level 25-49), instead, he ask you to go down and talk to NPC Gnombold to make the Middle Spike (50-79)

source: http://tibia.wikia.com/wiki/Spike_Tasks_Quest

----------------------------------------------------------------------

**The Tainted Souls Quest -**

You can't combine Antlers with Star Herb and holy water to obtain a Sacred Antler Talisman and proceed with the quest.

source: http://tibia.wikia.com/wiki/Spike_Tasks_Quest

----------------------------------------------------------------------

**Hot Cuisine Quest -**

The Quest is OK, but the vials and mugs have problems.

Ex: Vial of Beer, vial of milk, vial of wine or mugs of something etc... all they are appearing with wrong name like VIAL OF UNKNOWN OR MUG OF UNKNOWN, making a little bit confuse. When you trade with some NPCs, they just show the name MUG or VIAL, making a huge problem to guess what is it.

source:http://tibia.wikia.com/wiki/Hot_Cuisine_Quest

----------------------------------------------------------------------

**The Scatterbrained Sorcerer Quest -**

NPC Eclesius script isn't complete. Doesn't matter your level, you can't start the quest. He'll always says "Who are you? What do you want? You seem too experienced to become my assistant. Please leave."

source: http://tibia.wikia.com/wiki/The_Scatterbrained_Sorcerer_Quest

----------------------------------------------------------------------

**Scale Armor Quest -** 

2 chests is giving the same reward (scale armor). The correct one is inside the well already.
The wrong one (Position: 32353, 32128, 8) must be deleted.

----------------------------------------------------------------------

**Minotaur Leather Quest -**

Missing a chest on the raft south of Thais containing 01 minotaur leather

Position: 32302, 32415, 7

----------------------------------------------------------------------

**Troll Sabotage Quest -** 

NPC Jerom has wrong script, so, can't start the quest.

source:http://tibia.wikia.com/wiki/Troll_Sabotage_Quest

----------------------------------------------------------------------

**Tower Defence Quest-**

NPC Bunny Bonecrusher has wrong script, can't start the quest.

source:http://tibia.wikia.com/wiki/Tower_Defence_Quest

----------------------------------------------------------------------

**Kingdom of Kormarak Quest-**

The dead human body containing the reward next to the coffin is missing.

"Open the Dead Human near the Wooden Coffin to find a Brass Armor, a Brass Helmet, a Hatchet and 13 Throwing Stars."

Position: 32552, 32200, 11

source:http://tibia.wikia.com/wiki/Kingdom_of_Kormarak_Quest

----------------------------------------------------------------------

**Pilgrimage of Ashes Quest-**

Not working. Guide NPCs isn't working to start this quest.

source:http://tibia.wikia.com/wiki/Pilgrimage_of_Ashes_Quest

----------------------------------------------------------------------

**Venore Daily Tasks Quest-**

NPC Norman The Foreman script isn't correct, can't start the jobs.

source:http://tibia.wikia.com/wiki/Venore_Daily_Tasks_Quest

----------------------------------------------------------------------

**Steal From Thieves Quest-**

NPC Ahmet wrong script, can't start the quest.

Missing the hidden box containing Ahmet's stolen property (Position: 33131, 32661, 7).

source:http://tibia.wikia.com/wiki/Steal_From_Thieves_Quest

----------------------------------------------------------------------

**Rottin Wood and the Married Men Quest-**

Mission 3: Bushwhacking- After set the traps on the ground, the passing merchants don't appear, making the quest incomplete.

source:http://tibia.wikia.com/wiki/Rottin_Wood_and_the_Married_Men_Quest

---------------------------------------------------------------------

**Blood Herb Quest-**

Wyda don't trade Blood herb for a witchesbroom. Also, she don't get bored, making the possibility to trade the blood herb for a torn teddy.

source:http://tibia.wikia.com/wiki/Blood_Herb_Quest

---------------------------------------------------------------------

**Nomads Land Quest**

Needs Aritos Task Quest complete

source:http://tibia.wikia.com/wiki/Nomads_Land_Quest

--------------------------------------------------------------------

**Aritos Task Quest-**

NPC Arito has wrong script, can't iniciate the quest.

source:http://tibia.wikia.com/wiki/Arito%27s_Task_Quest

----------------------------------------------------------------------

**The Desert Dungeon Quest**

Chest is giving 10 crystal coins instead 100 platinum.

21:00 You see a chest.
It weighs 121.00 oz.
Item ID: 1740, Action ID: 2000, Unique ID: 9158
Position: 32668, 32069, 8

---------------------------------------------------------------------

**Jack to the Future Quest**

Needs Sea of Light Quest complete.

source:http://tibia.wikia.com/wiki/Jack_to_the_Future_Quest

---------------------------------------------------------------------

**Sea of Light Quest-**

Mission 2 - Can't obtain a rare crystal using a pick from the large crystal in Lost Mines.

23:16 You see a large crystal.
Item ID: 8634, Action ID: 4224
Position: 33031, 31758, 8

source:http://tibia.wikia.com/wiki/Sea_of_Light_Quest

----------------------------------------------------------------------

**Mintwallin Cyclops Quest-**

The chests in the last room are there, but just empty. Need add the rewards.

source:http://tibia.wikia.com/wiki/Mintwallin_Cyclops_Quest

----------------------------------------------------------------------

**Dragon Tower Quest-**

Missing especific type and number of monsters in each floor.

The monsters are as follows:

First floor : 3 Elf Scouts and 1 Elf
Second floor : 4 Elf Scouts and 2 Elf Arcanists
Third floor : 2 Dragons 
Fourth floor : 6 Elf Scouts and 3 Elf Arcanists
Fifth floor: 3 Elf Scout and 2 Elf Arcanists

Source:http://tibia.wikia.com/wiki/Dragon_Tower_Quest

----------------------------------------------------------------------

**Draconia Quest-**

Missing a lot of dead human and skeleton bodies around the maze.

Key 3001 - Missing the skeleton body containing the key (Position: 32794, 31572, 7). The rest of the quest is complete.

source: http://tibia.wikia.com/wiki/Draconia_Quest?file=Draconia_Quest_Key_3001.png

---------------------------------------------------------------------

**Shamam Treasure Quest-**

A skeleton and a chest is giving the same reward (3 blank runes). The correct one is the skeleton, please remove the chest.

Chest location: Position: 33120, 31885, 9

source:http://tibia.wikia.com/wiki/Shaman_Treasure_Quest

----------------------------------------------------------------------

**To Appease the Mighty Quest-**

NPC Kazzan can't start the quest.

source:http://tibia.wikia.com/wiki/To_Appease_the_Mighty_Quest

----------------------------------------------------------------------

**Research and Development Quest-**

Needs Sea of Light Quest completed

source:http://tibia.wikia.com/wiki/Research_and_Development_Quest

----------------------------------------------------------------------

**Panpipe Quest-**

Hollow rock (Position: 32652, 32107, 7) should be able to give key 4055 after use it.

Reward chest is empty (Position: 32644, 32131, 8). Need add the rewards: Quest box containing a Bag with 1 Power Ring, Panpipes and 2 Small Amethysts

source:http://tibia.wikia.com/wiki/Panpipe_Quest

----------------------------------------------------------------------

**Elvenbane Quest-**

Add poison fields on all over the ground at the 2nd floor of the tower (Position: 32590, 31645, 6)

source:http://tibia.wikia.com/wiki/Elvenbane_Quest

----------------------------------------------------------------------

**Goblin Merchant Quest-**

NPC Rafzan can't start the quest.

source:http://tibia.wikia.com/wiki/Goblin_Merchant_Quest

---------------------------------------------------------------------

**Into The Bone Pit Quest-**

Missing lots of carcass of animals and skeleton bodies at the place.

The action ID of the quest is in there, but when we use the shovel to dig up the humanoid, nothing happens, stucking the rest of the quest.
00:23 You see dirt.
Item ID: 103, Action ID: 4205
Position: 32408, 32107, 10

source:http://tibia.wikia.com/wiki/Into_The_Bone_Pit_Quest

----------------------------------------------------------------------

**Power Bolts Quest-**

Missing a skeleton body in position (Position: 32817, 32283, 8) containing the rest of the reward (02 handed sword, 06 throwing stars, talon).

Missing a pile of dead human, creatures and animals bodies on the upper-left corner.

source:http://tibia.wikia.com/wiki/Power_Bolts_Quest

----------------------------------------------------------------------
  
**Triangle Tower Quest**  

Add 01 demon skeleton on third floor
Add 01 witch on the Final floor

source:http://tibia.wikia.com/wiki/Triangle_Tower_Quest

---------------------------------------------------------------------

**Top of the City Quest**

NPC Iriana has wrong script, making unable to start the quest.

source:http://tibia.wikia.com/wiki/Top_of_the_City_Quest

--------------------------------------------------------------------

**Waterskin of Mead Quest**

The room with the barrels, there's no reward. Just need add the reward (a bag containing Berserk Potion, 82gp, Waterskin of Mead)

20:13 You see a barrel (Vol:25).
Item ID: 1774
Position: 32214, 31060, 10

source:http://tibia.wikia.com/wiki/Waterskin_of_Mead_Quest

--------------------------------------------------------------------

**The Great Dragon Hunt Quest**

There's no quest, should be build from the beginning.

source:http://tibia.wikia.com/wiki/The_Great_Dragon_Hunt_Quest

--------------------------------------------------------------------

**The Repenters Quest**

NPC Ashari has wrong script. Can't start the quest.

source:http://tibia.wikia.com/wiki/The_Repenters_Quest

--------------------------------------------------------------------

**Rest in Hallowed Ground Quest**

Unable to use the vial of holy water on graves, making the quest incomplete.

source:http://tibia.wikia.com/wiki/Rest_in_Hallowed_Ground_Quest

--------------------------------------------------------------------

**The White Raven Monastery Quest**

NPC Costello script seems ok, but we can proceed with the quest after use the correct words (Hi - Fugio).

source:http://tibia.wikia.com/wiki/The_White_Raven_Monastery_Quest

--------------------------------------------------------------------

**Hidden Threats Quest**

Missing the new path in this position (Position: 33056, 32012, 11) that leads to the teleport.
Can't find  Corym Ratter or Corym Servant

source:http://tibia.wikia.com/wiki/Hidden_Threats_Quest

--------------------------------------------------------------------

**To Blind the Enemy Quest**

NPC Eroth wrong script. Can't start the mission

source:http://tibia.wikia.com/wiki/To_Blind_the_Enemy_Quest

-------------------------------------------------------------------

**The Isle of Evil Quest**

NPC Rapanaio wrong script. Can't start the mission.

source:http://tibia.wikia.com/wiki/The_Isle_of_Evil_Quest

-------------------------------------------------------------------

**Naginata Quest**

Missing 02 Dragon Lords in the last room of the quest (Position: 32347, 32069, 12)

source:http://tibia.wikia.com/wiki/Naginata_Quest

-------------------------------------------------------------------

**The Paradox Tower Quest**

NPC Oldrak can't start the mission.

source:http://tibia.wikia.com/wiki/The_Paradox_Tower_Quest#Mission_2:_Talk_with_Riddler_.231

--------------------------------------------------------------------

**Mad Mage Room Quest**

00:21 You see a closed door.
Item ID: 1213
Position: 32578, 32197, 15

This door needs a action ID to be opened only using the key 3666.

00:24 You see a silver key (Key:3666).
It weighs 1.00 oz.
Item ID: 2088, Action ID: 3666
Position: 32394, 32137, 14

source:http://tibia.wikia.com/wiki/Mad_Mage_Room_Quest

---------------------------------------------------------------------

**Machinery of War Quest**

NPC Baxter can't start the quest.

source:http://tibia.wikia.com/wiki/Machinery_of_War_Quest

---------------------------------------------------------------------

**The Hidden City of Beregar Quest**

19:29 You see a chest (Vol:15).
It weighs 120.00 oz.
Item ID: 1740
Position: 32549, 31437, 14

This chest should contain a crystal of focus (item id 9941)

THE ROYAL RESCUE MISSION
There's a lot of bugs in this specific mission, a lot of monsters respawn missing.

source:http://tibia.wikia.com/wiki/The_Hidden_City_of_Beregar_Quest

-----------------------------------------------------------------------

**Treasure Hunt Quest**

NPC Wyrdin can't start the quest.

source:http://tibia.wikia.com/wiki/Treasure_Hunt_Quest

-----------------------------------------------------------------------

**Darashia Dragon Quest**

Missing dragon corpse containing the reward (life ring) (Position: 33233, 32280, 12)

source:http://tibia.wikia.com/wiki/Darashia_Dragon_Quest

----------------------------------------------------------------------

**Realm of Dreams Quest**

19:01 You see a gate of expertise for level 240.
Item ID: 10780, Action ID: 1240
Position: 32826, 31496, 7

Change the door level from 240 to 40.

source:http://tibia.wikia.com/wiki/Realm_of_Dreams_Quest

-------------------------------------------------------------------

**Deeper Fibula Quest**

Remove this teleport:
20:06 You see a magic forcefield.
Item ID: 1387
Position: 32278, 32386, 10

source:http://tibia.wikia.com/wiki/Deeper_Fibula_Quest

-------------------------------------------------------------------

**Secret Service Quest**

Mission 2 - Operation Green Claw
21:57 You see a gate of expertise for level 30.
Item ID: 5103, Action ID: 1030
Position: 32872, 31957, 11

This door must be a sealed door only available to complete Mission 2.

source:http://tibia.wikia.com/wiki/Secret_Service_Quest#Mission_2_-_Operation_Green_Claw

---------------------------------------------------------------------

**The Hunt for the Sea Serpent Quest**

Not possible use baits on the crane.
No teleport to the top of mast to use the telescope.
A bunch of teleports just to skip the quest and go straight under the sea.

source:http://tibia.wikia.com/wiki/The_Hunt_for_the_Sea_Serpent_Quest

----------------------------------------------------------------------

**The Gravedigger of Drefia Quest**

Vol.2, Ch.4: Ashes To Ashes / Cinder Sparks / A Taste Of Ashes
Can't use the chalk on the purple flame to get the shadow ashes. 
Can't continue the quest after here.

02:50 You see a strange fire.
Item ID: 21430, Action ID: 4637
Decays to: 21431
Position: 32983, 32376, 11

source:http://tibia.wikia.com/wiki/The_Gravedigger_of_Drefia_Quest

----------------------------------------------------------------------

**Blood Brothers Quest**

NPC Julius can't start the quest.

source:http://tibia.wikia.com/wiki/Blood_Brothers_Quest

---------------------------------------------------------------------

**Comment by fignacio** [comment]
Wow really good, also I would like to point out the mission to access Zao is impossible to do due to bad action on the levers!

New frontier quest - Mission 1

**Comment by sn4tch0vsk** [comment]
Really good @fignacio 
Later, I will check more quest and update the list =) All for the best of the sever

**Comment by OBUCHpl** [comment]
@fignacio #783

**Comment by malucooo** [comment]
Great job!

**Comment by fignacio** [comment]
I'm gonna check it out @OBUCHpl but looks pretty well made, I'll be back in a few hours once I get to test it! thanks for it!

Also to OP excellent job, it's a pity I don't know ANYTHING about lua or any programming language to help the developers to solve this issues I would really like to learn that!

**Comment by jlcvp** [comment]
Nice job @sn4tch0vsk I'll try to format a TO-DO list to keep it up-to-date within this topic
