### ISSUE TITLE
Using blessed wooden stake on demon drops dust on floor

### ISSUE THREAD

**Issue by H0ltman** [malucooo/Otxserver-New#784]
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use http://www.tibiaking.com/ or https://otland.net for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. kill demon
2. use blessed wooden stake on corpse
3. If dust is generated it will be on floor

### Expected behaviour
Should be in backpack

### Actual behaviour
It drops on floor

**Comment by joao-albach** [comment]
Are you using the latest version? Mine goes to the backpack as it should

**Comment by H0ltman** [comment]
Mustve been fixed since then. Thanks.

**Comment by OBUCHpl** [comment]
#747 ;)
