### ISSUE TITLE
file paths not found error with monsters and raids

### ISSUE THREAD

**Issue by Tatuy** [malucooo/Otxserver-New#786]
You have to adjust the uppercase and lowercase of some directories of monsters and raids since linux is sensitive to this. Thank you.

**Comment by Tatuy** [comment]
I just corrected all the routes, can you give me access as a collaborator to update it?

**Comment by OBUCHpl** [comment]
Which ones? Marco fixed 'glires' yesterday, are there more issues?  If u want to post an update you can always make a pull request.

**Comment by jlcvp** [comment]
@Tatuy You can open a pull request so we can merge your changes

**Comment by malucooo** [comment]
@Tatuy You can open a pull request so we can merge your changes2
