### ISSUE TITLE
Utito tempo

### ISSUE THREAD

**Issue by GoularPink** [malucooo/Otxserver-New#789]
Quando usa utito tempo + Berserk Potion só ta ficando o skill do utito tempo, não ta somando os skill.

Berserk Potion > Durante 10 minutos, aumenta em 5 pontos de seu skill de Melee (fist, sword, axe ou club), porém diminui em 10 pontos o seu skill de shielding.

Utito tempo > Aumenta seu melee skill (fist fighting, axe fighting, club fighting e sword fighting) em 35% por 10 segundos. A magia irá apenas aumentar o skill para o tipo de arma que você está usando, ou irá aumenta seu fist skill se você não estiver usando nenhuma.

**Comment by newacc12** [comment]
Os skills nao somam de acordo com: http://tibia.wikia.com/wiki/Berserk_Potion
