### ISSUE TITLE
Exevo frigo hur

### ISSUE THREAD

**Issue by Zainox** [malucooo/Otxserver-New#79]
The spell exevo frigo hur have a little error, the spawm attack sqm is much little, the original spell have 1 sqm more, please check this...

**Comment by johnnybarroso** [comment]
Hello Zainox,

I checked this is spell and i not found problem in using in the monsters.

The SQM is equals to tibia global for kill monster.
See bellow spell test
Image test: https://goo.gl/QoqqrM

Check the font to compare SQM.
Font: http://tibia.wikia.com/wiki/File:Ice_wave1.gif

**Comment by malucooo** [comment]
no have bugs!
