### ISSUE TITLE
Binary and zipped files are making this repo HUGE to clone

### ISSUE THREAD

**Issue by jlcvp** [malucooo/Otxserver-New#795]
## English
Git is essencially made to register and control file changes from one commit to another at every file. These are called the **"deltas"** between every commits. These zip files are a real pain to git VCS as it basically saves a COPY OF EVERY VERSION THAT HAS EVER BEEN IN THERE. 

At this time, we have 245MB of source files, and 1.8GB of git history.

My suggestion is to MOVE the clients to another repository and UNZIP the map file and work with it unzipped. It's better for git and for network as it'll only upload the changes in the file. 
 
**tl;dr**: When we zip a file, it scrambles the data in the file A LOT and generates a bloat in the git history. It's better to use unzipped files

-------------------------------------------------------------------------------------
## Português
O Git é, essencialmente, feito para registrar e controlar mudanças nos arquivos de um commit para o outro PARA CADA ARQUIVO. Essas mudanças são chamadas "deltas" entre cada commit. Esses arquivos ZIP são realmente ruins pra o sistema do git, pois ele basicamente salva UMA CÓPIA DE CADA VERSÃO QUE JÁ EXISTIU AQUI.

No momento, temos 245mb em sources, e 1.8GB de histórico do git.

Minha sugestão é MOVER os clients pra outro repositório e DEZIPAR o arquivo de mapa e trabalhar nele no formato otbm mesmo. É melhor pra o git e para a rede, pois ele vai fazer upload apenas das mudanças no mapa.

**Resumo**: Quando zipamos um arquivo, ele embaralha MUITO os dados no arquivo e gera uma bolha no histórico do git. É melhor trabalhar com arquivos DEZIPADOS

**Comment by joao-albach** [comment]
Eu sugeriria deixar os clients e bots e essas coisas que não são do otx em uma pasta do google drive ou mega. Já o mapa não muita solução pois o git não aceita arquivos do tamanho dele descompactado.
