### ISSUE TITLE
faltando mapa e quest

### ISSUE THREAD

**Issue by GoularPink** [malucooo/Otxserver-New#799]
ta faltando o mapa e a quest 

https://tibiawiki.com.br/wiki/Treasure_Hunt_Quest

**Comment by costa55** [comment]
qual o mapa vc disse pq se foi esse ele tem sim....
![image](https://user-images.githubusercontent.com/34360730/35202730-799493d8-ff0b-11e7-9c93-4e04c5009bf1.png)
por que se foi esse tem, esta como desativado, nao tem respawn nem npc os tp tb nao ta funcionando facil de resolver

veja mais esse detalhe
![image](https://user-images.githubusercontent.com/34360730/35202794-d4393816-ff0b-11e7-851a-e13a90cb9728.png)
para acha basta dar goto nesse npc  Captain Waverider

**Comment by malucooo** [comment]
Gitlab.com/malucooo/otxserver-global/

**Comment by jlcvp** [comment]
the repository was moved, please reopen this issue or any further issues there

https://gitlab.com/malucooo/Otxserver-Global
