### ISSUE TITLE
The Images in Store Is Off

### ISSUE THREAD

**Issue by gigantescu** [malucooo/otxserver-new#8]
![image](https://user-images.githubusercontent.com/22483547/40508826-df6b6592-5f6e-11e8-99cb-6a240f626f09.png)

> -- Misc.
allowChangeOutfit = true
freePremium = true
kickIdlePlayerAfterMinutes = 15
idleWarningTime = 10 * 60 * 1000
idleKickTime = 15 * 60 * 1000
maxMessageBuffer = 4
emoteSpells = false
classicEquipmentSlots = false
allowWalkthrough = true
coinPacketSize = 1
coinImagesURL = "http://127.0.0.1/images/store/"
classicAttackSpeed = false

**Comment by milkersky** [comment]
Have the same :/

**Comment by erimyth** [comment]
coinImagesURL = "http://127.0.0.1/store/"
