### ISSUE TITLE
Experience bug

### ISSUE THREAD

**Issue by thecamarada** [malucooo/Otxserver-New#80]
I've just downloaded server, overwrited database configuration and IP server in config.lua.

After create the character, on kill monsters the experience was always 1x (even in config.lua set to 5x and stages was active). You can set expRate to 10000x and will always give 1x  experience.

The console shows an error in **data/events/scripts/player.lua**, at line 466. 

`-- Apply Extra Experience
	if self:getStorageValue(config.storage) >= os.time() then
		exp = exp * config.rate
	end`

Probably config has a null value.

**Comment by esbuma** [comment]
You need to got to your player.xml locate in \data\events\scripts 
in line 466 chenge
if self:getStorageValue(config.storage) >= os.time() then
		exp = exp * config.rate
	end

to
if self:getStorageValue(61398) >= os.time() then
		exp = exp * config.rate
	end
------------------------
 config.rate <<<change to the number you set up in the file                                                                                    \data\actions\scripts\other\exp.lua

**Comment by thecamarada** [comment]
But this kind of issue must be revised in the master source. It's not a good deal to the individual developer fix in his own project. Many people will download the Otxserver-new and will not be able to use.

**Comment by esbuma** [comment]
I`m giving you how to fix...not say that dont need to change in the source.

And the source is not going to be perfect...you always have to chenge things in your individual project

**Comment by thecamarada** [comment]
Oh ok, i see. I did not mean to be rude. Also, Malucooo already posted a fix, based on your answer.

By the way, thanks for your comment!

**Comment by malucooo** [comment]
fixed!
