### ISSUE TITLE
Vocation None -> Others (Sorc/Druid/Pala/Kina)

### ISSUE THREAD

**Issue by waldirtaj** [malucooo/Otxserver-New#800]
I can use my char with none vacation without problems but when I try to go to the main and re-log the server crash (after my char got a vocation)

And when I create a character on the site and choose for example Sorcerer he create as "no vocation"

Im using this compiled distro, by the way

https://ci.appveyor.com/project/malucooo/otxserver-new

**Comment by waldirtaj** [comment]
Im using this compiled distro, by the way

https://ci.appveyor.com/project/malucooo/otxserver-new

**Comment by flaviiojr** [comment]
Confirm !

**Comment by malucooo** [comment]
Man the project as moved... go to issues in this link: http://www.gitlab.com/malucooo/otxserver-global/
