### ISSUE TITLE
cannot use most of god commands

### ISSUE THREAD

**Issue by omarkane** [malucooo/Otxserver-New#801]
Hello, my problem is that i cannot use alot of god commands like /i, /m, /s etc...
i can use some of them like /b, /r
i searched for solution to this problem but i didn't find
i have all my talkactions folder complete and i have tried to replace them with another folder but this also didn't succeed
can you please tell me a solution?

**Comment by jlcvp** [comment]
are you sure you're running our latest version server? it's located at 

https://gitlab.com/malucooo/Otxserver-Global


be sure you're using our sample database too, there's a CM account already configured
