### ISSUE TITLE
Client crash

### ISSUE THREAD

**Issue by thecamarada** [malucooo/Otxserver-New#82]
No changes on the server, just IP and Database. The first time the character logs in, the client crashes. After the second time, no crashs on login.

But there is another issue, the client also crashs on open the outfit window.

(Tested in original client **10.97**, **10.98**, **10.99**, using ipchanger). 

On crash, there is no reports on server console.

**Comment by esbuma** [comment]
You crash beacuse on opening outfit window..because some outfits only work on 10.00 and some on 11....you need to use the 10.00 and disable the Pharaoh Outfit(as far I know only wornks on client 11)...so you wont  crash on outfit window

**Comment by thecamarada** [comment]
My advice is to disable the Pharaoh Outfit, so everyone who download this server will not encounter a client crash.

Thanks for your reply!

**Comment by darkjav** [comment]
You not need disabled Pharaoh Outfit, you only neeed download the last tibia 10.00 oficial and use the .spr and .dat in the client 10.99 or 10.00 old
