### ISSUE TITLE
Critical damage accumulates.

### ISSUE THREAD

**Issue by Tetee11** [malucooo/Otxserver-New#83]
This happens every time you equip the weapon.

![critical](https://cloud.githubusercontent.com/assets/26393750/25538918/45b1fa4e-2c0a-11e7-89c8-c385112f56d9.PNG)

**Comment by jlcvp** [comment]
There are some **OnDeEquip** movements missing on **movements.xml** , so, it only calculates the increase of critical, never the decrease. 

Adding all the respective DeEquip movements on movements.xml should solve the problem.

**Comment by Tetee11** [comment]
When you cast a spell without critical weapon and with critical stats of 0% sometimes you see a critical hit. I think this is not problem with `onDeEquip` or `onEquip`. 

When you equip the critical weapon for first time after you logged in you see the duplicte stats of the weapon.
![critical2](https://cloud.githubusercontent.com/assets/26393750/25543568/a2351faa-2c1c-11e7-9445-aaca914d6276.PNG)

This are the stats after equip a `You see a chopper of mayhem (overcharged) (Atk:53, Def:35, axe fighting +1, critical hit chance +20%, critical hit damage +30%)  for first time. This happens with every critical weapon.`

**Comment by darkjav** [comment]
Im sure that is problem of onDeEquip and onEquip

**Comment by lamonato29** [comment]
bro, the problem is of onDeEquip...
We are sure about that..
But i have the problem with casting spell without any critical weapon and i see some critical hits too!

**Comment by jlcvp** [comment]
@lamonato29 even with 0% critical in the skills window?

**Comment by lamonato29** [comment]
Yes bro..
Em 29/04/2017 16:25, "João Leonardo Pereira" <notifications@github.com>
escreveu:

**Comment by Rockerszzz** [comment]
#87
