### ISSUE TITLE
Variable "config.killAllBeforeCut" empty ?!

### ISSUE THREAD

**Issue by luanluciano93** [malucooo/Otxserver-New#84]
Is not this variable necessary? "config.killAllBeforeCut"

**Comment by malucooo** [comment]
where u have found this?

**Comment by luanluciano93** [comment]
https://github.com/malucooo/Otxserver-New/blob/1a8e857b5f92702289fe494cf2c6c3673f14a76f/data/actions/scripts/quests/demon%20oak/demonOak.lua#L80

And in this same script ...

https://github.com/malucooo/Otxserver-New/blob/1a8e857b5f92702289fe494cf2c6c3673f14a76f/data/actions/scripts/quests/demon%20oak/demonOak.lua#L17

**Comment by luanluciano93** [comment]
?
