### ISSUE TITLE
Bug Character

### ISSUE THREAD

**Issue by lamonato29** [malucooo/Otxserver-New#85]
Direto acontece isso, o char trava em um SQM, mas mostra que ele está em outro..
é meio dificil explicar então vou postar a imagem..
![bug](https://cloud.githubusercontent.com/assets/26177550/25567000/d1cd51fc-2dba-11e7-9c32-dcd2e41c7093.png)

**Comment by lamonato29** [comment]
Qualquer magia que eu usar apartir dai, vai aparecer no sqm q ta "utani hur", alem do char ficar tracado.. Para destravar tenho que ficar clicando do lado com o botao direito..

**Comment by darkjav** [comment]
Send mini mapa for that we can fix, or send position with command: /pos

**Comment by lamonato29** [comment]
Bro, it doesnt happens only in one sqm, only in one position.. But can happen in anywhere.. Srry for my bad english..

**Comment by jlcvp** [comment]
notei isso uma vez enquando usava bot, talvez seja alguma falta de sincronia entre o client e um pacote de entrada. Destrava dando USE em algum lugar com mais de 1 sqm de distância.

**Comment by malucooo** [comment]
fail on inject dll of ur bot... i'm not make bots =/

**Comment by malucooo** [comment]
i can't roproduce this!

**Comment by malucooo** [comment]
reproduce*

**Comment by darkjav** [comment]
Is sure that is problem of the bot, @lamonato29 what bot you use?

**Comment by lamonato29** [comment]
srry about that ;D im using bbot
