### ISSUE TITLE
Bug creating guild

### ISSUE THREAD

**Issue by ZeroCast** [malucooo/Otxserver-New#86]
![png1](https://cloud.githubusercontent.com/assets/28275684/25596871/16eae976-2e91-11e7-8122-b73eb2d34437.png)
![png2](https://cloud.githubusercontent.com/assets/28275684/25596873/16ec8b00-2e91-11e7-93ae-368860e95575.png)
![png3](https://cloud.githubusercontent.com/assets/28275684/25596872/16ec9276-2e91-11e7-81ea-cba6cd0c378c.png)

When creating a guild, send that error. Is there any solution

**Comment by Rockerszzz** [comment]
website problem, not related to the server.

**Comment by malucooo** [comment]
ur site... ur problems... only distro problems here or scripts!
