### ISSUE TITLE
client dbug

### ISSUE THREAD

**Issue by cinmsa12** [malucooo/Otxserver-New#89]
blade of carving (overcharged) itemID = 25962;26270 
Removing the id 26270 does not cause debug, error in this sprite?

<attribute key="transformEquipTo" value="26270" />

When you remove the "item" from the hand, the client closes and you can not open that backpack. 

other bug
all items overcharged add 2 skill onEquip but only remove 1 onDeEquip. duplique movement? example id 26256 blade of remedy (overcharged) (sword fighting +1)

**Comment by Rockerszzz** [comment]
works fine for me, please make sure your files are up to date with github files.

**Comment by cinmsa12** [comment]
I am using the tibia1000 client and the files downloaded here without modifications

**Comment by darkjav** [comment]
Where you download the client 10.00?? Try downloading the last oficial client 10.00 and use the .spr and .dat in you client.

**Comment by cinmsa12** [comment]
The client link is in this server post
http://www.mediafire.com/file/571cbbt9cy2y30t/tibia1000.rar

**Comment by cinmsa12** [comment]
solved! i download other client in tibia-clients.com; although it does not show the bright effect, it does not give dbug. that is enough for me. And the skill bug is still there but it is easy to solve in movements. You can close the topic thanks.If I find another bug I will post it

**Comment by darkjav** [comment]
@cinmsa12 Ok good, if the skill bug still there, open another issue for explain us what happen.
