### ISSUE TITLE
Cannot compile.

### ISSUE THREAD

**Issue by Dzanar** [malucooo/otxserver-new#93]
In Ubuntu Bionic cannot compile from sources.

I have installed the following packages "$ sudo apt-get install git cmake build-essential liblua5.2-dev libgmp3-dev libmysqlclient-dev libboost-system-dev libboost-iostreams-dev libpugixml-dev libcrypto++-dev" 

The Forgotten server from the master sources compile without any error. 

When i run cmake .. command the output is:

`damian@MacBook-Damian:~/otxserver-new/src$ cmake ..
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- cotire 1.7.6 loaded.
-- Performing Test COMPILER_KNOWS_CXX11
-- Performing Test COMPILER_KNOWS_CXX11 - Success
-- Performing Test COMPILER_KNOWS_STDLIB
-- Performing Test COMPILER_KNOWS_STDLIB - Failed
-- Found GMP: /usr/include/x86_64-linux-gnu
-- Found PugiXML: /usr/include
-- MySQL Include dir: /usr/include/mysql  library dir: /usr/lib/x86_64-linux-gnu
-- MySQL client libraries: /usr/lib/x86_64-linux-gnu/libmysqlclient.so
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Could NOT find LuaJIT (missing: LUA_INCLUDE_DIR)
-- Found Lua: /usr/lib/x86_64-linux-gnu/libluajit-5.1.so;/usr/lib/x86_64-linux-gnu/libm.so (found version "")
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   system
--   iostreams
--   regex
-- CXX target tfs cotired without unity build.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/damian/otxserver-new/src
`

The error is :

`[100%] Linking CXX executable tfs
CMakeFiles/tfs.dir/combat.cpp.o: In function `ValueCallback::getMinMaxValues(Player*, CombatDamage&, bool) const':
combat.cpp:(.text+0x3361): undefined reference to `lua_pcallk'
CMakeFiles/tfs.dir/combat.cpp.o: In function `TargetCallback::onTargetCombat(Creature*, Creature*) const':
combat.cpp:(.text+0x3787): undefined reference to `lua_pcallk'
CMakeFiles/tfs.dir/configmanager.cpp.o: In function `(anonymous namespace)::getGlobalString(lua_State*, char const*, char const*)':
configmanager.cpp:(.text+0x37): undefined reference to `lua_getglobal'
configmanager.cpp:(.text+0x96): undefined reference to `lua_rawlen'
CMakeFiles/tfs.dir/configmanager.cpp.o: In function `(anonymous namespace)::getGlobalNumber(lua_State*, char const*, int)':
configmanager.cpp:(.text+0x1a4): undefined reference to `lua_getglobal'
CMakeFiles/tfs.dir/configmanager.cpp.o: In function `(anonymous namespace)::getGlobalBoolean(lua_State*, char const*, bool)':
configmanager.cpp:(.text+0x22e): undefined reference to `lua_getglobal'
configmanager.cpp:(.text+0x281): undefined reference to `lua_rawlen'
CMakeFiles/tfs.dir/configmanager.cpp.o: In function `(anonymous namespace)::getGlobalFloat(lua_State*, char const*, float)':
configmanager.cpp:(.text+0x39e): undefined reference to `lua_getglobal'
CMakeFiles/tfs.dir/configmanager.cpp.o: In function `ConfigManager::load()':
configmanager.cpp:(.text+0x4b3): undefined reference to `lua_pcallk'
CMakeFiles/tfs.dir/databasemanager.cpp.o: In function `DatabaseManager::updateDatabase()':
databasemanager.cpp:(.text+0xb38): undefined reference to `lua_setglobal'
databasemanager.cpp:(.text+0xb96): undefined reference to `lua_setglobal'
databasemanager.cpp:(.text+0xbf4): undefined reference to `lua_setglobal'
databasemanager.cpp:(.text+0xcc5): undefined reference to `lua_pcallk'
databasemanager.cpp:(.text+0xd96): undefined reference to `lua_getglobal'
databasemanager.cpp:(.text+0xdc0): undefined reference to `lua_pcallk'
CMakeFiles/tfs.dir/luascript.cpp.o: In function `LuaScriptInterface::protectedCall(lua_State*, int, int)':
luascript.cpp:(.text+0x1378): undefined reference to `lua_pcallk'
CMakeFiles/tfs.dir/luascript.cpp.o: In function `LuaScriptInterface::getEvent(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
luascript.cpp:(.text+0x15f1): undefined reference to `lua_getglobal'
luascript.cpp:(.text+0x16a4): undefined reference to `lua_setglobal'
CMakeFiles/tfs.dir/luascript.cpp.o: In function `LuaScriptInterface::getMetaEvent(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
luascript.cpp:(.text+0x1833): undefined reference to `lua_getglobal'
CMakeFiles/tfs.dir/luascript.cpp.o: In function `LuaScriptInterface::getStackTrace(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
luascript.cpp:(.text+0x1c5c): undefined reference to `lua_getglobal'
luascript.cpp:(.text+0x1d58): undefined reference to `lua_callk'
CMakeFiles/tfs.dir/luascript.cpp.o: In function `LuaScriptInterface::registerFunctions()':
luascript.cpp:(.text+0x4c47): undefined reference to `lua_setglobal'
luascript.cpp:(.text+0x4c80): undefined reference to `lua_setglobal'
luascript.cpp:(.text+0x4cb9): undefined reference to `lua_setglobal'
luascript.cpp:(.text+0x4cf2): undefined reference to `lua_setglobal'
luascript.cpp:(.text+0x4d2b): undefined reference to `lua_setglobal'
CMakeFiles/tfs.dir/luascript.cpp.o:luascript.cpp:(.text+0x4d64): more undefined references to `lua_setglobal' follow
CMakeFiles/tfs.dir/luascript.cpp.o: In function `LuaScriptInterface::registerClass(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int (*)(lua_State*))':
luascript.cpp:(.text+0x5d41d): undefined reference to `lua_getglobal'
CMakeFiles/tfs.dir/luascript.cpp.o: In function `LuaScriptInterface::registerTable(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
luascript.cpp:(.text+0x5d820): undefined reference to `lua_setglobal'
CMakeFiles/tfs.dir/luascript.cpp.o: In function `LuaScriptInterface::registerMethod(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int (*)(lua_State*))':
luascript.cpp:(.text+0x5d85e): undefined reference to `lua_getglobal'
CMakeFiles/tfs.dir/luascript.cpp.o: In function `LuaScriptInterface::registerGlobalMethod(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int (*)(lua_State*))':
luascript.cpp:(.text+0x5d99c): undefined reference to `lua_setglobal'
CMakeFiles/tfs.dir/luascript.cpp.o: In function `LuaScriptInterface::registerVariable(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, double)':
luascript.cpp:(.text+0x5d9db): undefined reference to `lua_getglobal'
CMakeFiles/tfs.dir/luascript.cpp.o: In function `LuaScriptInterface::registerGlobalVariable(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, double)':
luascript.cpp:(.text+0x5da76): undefined reference to `lua_setglobal'
CMakeFiles/tfs.dir/luascript.cpp.o: In function `LuaScriptInterface::registerGlobalBoolean(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)':
luascript.cpp:(.text+0x5dac7): undefined reference to `lua_setglobal'
CMakeFiles/tfs.dir/luascript.cpp.o: In function `LuaScriptInterface::luaAddEvent(lua_State*)':
luascript.cpp:(.text+0x60d27): undefined reference to `lua_getglobal'
luascript.cpp:(.text+0x60d5a): undefined reference to `lua_getglobal'
luascript.cpp:(.text+0x60dca): undefined reference to `lua_callk'
CMakeFiles/tfs.dir/npc.cpp.o: In function `NpcScriptInterface::registerFunctions()':
npc.cpp:(.text+0x2959): undefined reference to `lua_setglobal'
npc.cpp:(.text+0x298c): undefined reference to `lua_setglobal'
npc.cpp:(.text+0x29bf): undefined reference to `lua_setglobal'
npc.cpp:(.text+0x29f2): undefined reference to `lua_setglobal'
npc.cpp:(.text+0x2a25): undefined reference to `lua_setglobal'
CMakeFiles/tfs.dir/npc.cpp.o:npc.cpp:(.text+0x2a58): more undefined references to `lua_setglobal' follow
collect2: error: ld returned 1 exit status
CMakeFiles/tfs.dir/build.make:2276: recipe for target 'tfs' failed
make[2]: *** [tfs] Error 1
CMakeFiles/Makefile2:99: recipe for target 'CMakeFiles/tfs.dir/all' failed
make[1]: *** [CMakeFiles/tfs.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
damian@MacBook-Damian:~/otxserver-new/src$
`

**Comment by favasconcelos** [comment]
As far as I could read, the problem is related to the lua installation. All the error from the build are related to that. The CMAKE script also could not found the lua ENV. Have you done any changes to the make script?

```
Could NOT find LuaJIT (missing: LUA_INCLUDE_DIR) -- Found Lua: /usr/lib/x86_64-linux-gnu/libluajit-5.1.so
```

**Comment by ivenspontes** [comment]
cmake .. -DLUA_INCLUDE_DIR=/usr/include/luajit-2.1

works here
