### ISSUE TITLE
Imbuing

### ISSUE THREAD

**Issue by atsbruno** [malucooo/otxserver-new#94]
Estou tentando colocar o Imbuing em uma versão 10.98, só que o único problema, na horá de abrir o ImbuementWindow, ele da um erro de packet não conhecido, que é o 238 ou 0xEE.

Analisando o código, é justamente nesse momento:

```
self:sendResource("bank", self:getBankBalance())
self:sendResource("inventory", self:getMoney())
```

A função:

```
function Player.sendResource(self, resourceType, value)
	local typeByte = 0
	if (resourceType == "bank") then
		typeByte = 0x00
	elseif (resourceType == "inventory") then
		typeByte = 0x01
	elseif (resourceType == "prey") then
		typeByte = 0x0A
	end

	local msg = NetworkMessage()
	msg:addByte(0xEE)
	msg:addByte(typeByte)
	msg:addU64(value)
	msg:sendToPlayer(self)
end
```

Alguém poderia me ajudar a dizer, se o byte enviado neste caso, muda na versão 10.98-10.99?
Eu não sei como fazer para saber qual/quais bytes o client espera :(

Obrigado pela atenção desde já.

**Comment by malucooo** [comment]
github.com/mattyx14/otxserver/
