### ISSUE TITLE
BroadCast not work?

### ISSUE THREAD

**Issue by sirakx** [malucooo/Otxserver-New#97]
Estoy probando unos eventos en el servidor y mira que el broadcast message no aparece enmedio de la pantalla de color rojo Game.broadcastMessage("mensaje") solo aparece en el server log.

alguna solución? o es debido al cliente? o por error o compatibilidad lo quitaron de los sources?

**Comment by darkjav** [comment]
You already fixed here?
https://github.com/malucooo/Otxserver-New/commit/0255e40644d918cd441daba5b87404f7ea32d934

**Comment by sirakx** [comment]
fue una solución rápida pero la cuestión es por que no funciona si se hace con sendTextMessage

player:sendTextMessage(MESSAGE_STATUS_WARNING, "msg")
