### ISSUE TITLE
Sistema de Promotion Não funciona

### ISSUE THREAD

**Issue by Zebutops** [malucooo/otxserver-new#99]
O sistema de promotion não funciona, acredito estar relacionado ao sistema de premium account do servidor, que mesmo que o player tenha X dias de premmy o no Ctrl + G (Account Status) o player ainda aparece como Free Account e ao comprar a promotion nos NPC King / Queen ele paga o dinheiro sai, o npc fala congrations, porem nada acontece....

**Comment by favasconcelos** [comment]
Como está a variável, freePremium no seu config.lua?

**Comment by Zebutops** [comment]
favasconcelos consegui resolver ajustando o config.lua com o loguin.php que estava divergente...

**Comment by favasconcelos** [comment]
Se possível, descreve aqui a correção! :+1:
